const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, PageBreak, AlignmentType } = require("docx");
const { IQS, F, p, pRuns, h1, h2, h3, bullet, box, tabla, tablaTiempos, numberingConfig, seg, punto } = require("./lib_iqs");

const children = [];

// ---------- Portada ----------
children.push(
 new Paragraph({ spacing: { before: 1900, after: 200 }, alignment: AlignmentType.CENTER,
 children: [new TextRun({ text: "Bloque 1", size: 40, bold: true, color: IQS.greenDark, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 },
 children: [new TextRun({ text: "Introducción a la mecatrónica y panorama 2026 de la robótica", size: 44, bold: true, color: IQS.navy, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
 children: [new TextRun({ text: "82514, Mecatrónica y Robótica · IQS Universitat Ramon Llull", size: 24, color: IQS.grey, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
 children: [new TextRun({ text: "Apuntes del profesor con citas de fuente · Sesiones S1–S4 (9, 10, 16 y 17 de septiembre de 2026) · 4 horas", size: 22, color: IQS.grey, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER,
 children: [new TextRun({ text: "Ediciones citadas: De Silva et al. (2016), Mechatronics: Fundamentals and Applications, CRC Press · Corke (2023), Robotics, Vision and Control, 3.ª ed. Python, Springer · Lynch y Park (2017), Modern Robotics, Cambridge", size: 18, italics: true, color: IQS.grey, font: F })] }),
 new Paragraph({ children: [new PageBreak()] })
);

children.push(h1("Objetivos de aprendizaje y convenciones de estos apuntes"));
children.push(bullet("Definir la mecatrónica como disciplina de diseño integrado multidominio, enumerar los componentes de un sistema mecatrónico típico y clasificar ejemplos reales."));
children.push(bullet("Explicar los tres problemas del diseño no acoplado, el concepto de índice de diseño y la formulación del Cociente de Diseño Mecatrónico (MDQ)."));
children.push(bullet("Situar los hitos históricos de la robótica industrial con fechas y protagonistas, y enunciar la definición operativa de robot: percibir, planificar, actuar."));
children.push(bullet("Describir el panorama actual del sector (Physical AI, modelos VLA, humanoides) y articular las cuestiones éticas asociadas."));
children.push(box("Cómo leer las citas", "Cada afirmación relevante lleva su fuente y página en formato (Autor, año, p. X). Las páginas corresponden a las ediciones de la carpeta de bibliografía: De Silva et al. (2016), el capítulo 1 ocupa las pp. 1-13, Corke (2023), capítulo 1, pp. 1-19, y Lynch y Park (2017). Las comillas «» marcan traducción casi literal del original en inglés. El guion de cada clase lista los puntos que deben tratarse explícitamente en cada segmento, con remisión al apartado de teoría correspondiente; no es una transcripción."));

// ============================================================ S1
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Sesión S1 (mié 9 sep, 1 h), Qué es la mecatrónica"));

children.push(h2("Guion de la clase"));
children.push(seg("0–10 min", "Presentación de la asignatura"));
children.push(punto("Presentarse: trayectoria propia y por qué esta asignatura."));
children.push(punto("Recorrer la guía docente en pantalla: los 8 bloques y su lógica (fundamentos → percepción → software → IA), fechas clave del calendario (festivos del 11 y 24 de septiembre, seminario en S41–S42, defensa del proyecto en S43)."));
children.push(punto("Evaluación: pesos vigentes de la guía, cuestionarios de cierre de bloque, proyecto integrador por equipos (formación en S5–S7)."));
children.push(punto("Política de IA generativa: se permite como asistente de estudio y de código; uso declarado en cada entrega; toda entrega es defendible oralmente."));
children.push(punto("Bibliografía: mostrar los tres libros troncales y decir para qué sirve cada uno (De Silva: diseño mecatrónico; Corke: robótica aplicada en Python; Lynch y Park: fundamentos matemáticos)."));
children.push(seg("10–15 min", "Pregunta de arranque"));
children.push(punto("Formular: «¿qué objetos de vuestro día a día son mecatrónicos?» y anotar la lista en la pizarra sin corregir nada todavía."));
children.push(punto("Anunciar que al final de la clase revisaremos la lista con la definición en la mano."));
children.push(seg("15–35 min", "Teoría: definición y dominios (apdos. 1.1 y 1.2)"));
children.push(punto("Enunciar y escribir la definición completa: aplicación sinérgica de mecánica, electrónica, control e informática con enfoque de diseño integrado (De Silva et al., 2016, p. 1)."));
children.push(punto("Desglosar las dos palabras clave: «sinérgica» (los subsistemas se optimizan juntos) e «integrado» (las interacciones dinámicas entran desde la primera fase)."));
children.push(punto("Definir sistema de dominio mixto o multidominio y enumerar los cuatro dominios físicos: eléctrico, mecánico, fluídico y térmico (De Silva et al., 2016, p. 1)."));
children.push(punto("Desarrollar el ejemplo del ABS con sus cuatro dominios y la conclusión: solo el diseño conjunto lo hace «óptimo» (De Silva et al., 2016, p. 1)."));
children.push(punto("Dato histórico del término: Yaskawa 1969, marca 1972, derechos liberados 1982 (De Silva et al., 2016, p. 10); subrayar que nació en la industria japonesa."));
children.push(punto("Dibujar el diagrama de dominios (fig. 1.2 del libro) y mapear cada órbita a un bloque del curso."));
children.push(seg("35–50 min", "Teoría: componentes y ejemplos (apdo. 1.3)"));
children.push(punto("Dictar la lista de los ocho componentes de un sistema mecatrónico (De Silva et al., 2016, p. 2) y decir en voz alta que es el índice de la asignatura."));
children.push(punto("Ejemplo HDD (fig. 1.1 del libro, p. 2): identificar sobre el esquema platos, husillo, brazo, actuador y lazo de seguimiento; lanzar la pregunta de las resonancias (anticipa B5)."));
children.push(punto("Ejemplo servomotor (p. 2): las tres capas (mecánica, eléctrica, control) y la idea de sistema anidado: un dispositivo mecatrónico dentro de otro."));
children.push(punto("Barrido de áreas de aplicación (pp. 11-12): un ejemplo por sector, terminando en el Mars Exploration Rover."));
children.push(seg("50–60 min", "Cierre y discusión"));
children.push(punto("Volver a la lista de la pizarra: clasificar cada objeto como electromecánico o mecatrónico usando la definición."));
children.push(punto("Idea fuerza de cierre: la mecatrónica es una metodología de diseño, no una lista de componentes."));
children.push(punto("Encargar lectura: De Silva et al. (2016), cap. 1, pp. 1-10, para S2."));

children.push(h2("1.1. Definición de mecatrónica"));
children.push(p("La mecatrónica se define como la «aplicación sinérgica de la mecánica, la electrónica, la ingeniería de control y la ingeniería informática» (mechanics, electronics, controls, and computer engineering) al desarrollo de productos y sistemas electromecánicos, «mediante un enfoque de diseño integrado» (De Silva et al., 2016, p. 1). Las dos palabras que soportan el peso de la definición son «sinérgica» e «integrado»: no basta con que un producto contenga piezas mecánicas y electrónica, eso lo cumple cualquier electrodoméstico desde hace un siglo; lo distintivo es que los subsistemas se conciben, modelan y optimizan conjuntamente, incorporando sus interacciones dinámicas desde la primera fase del diseño."));
children.push(p("La disciplina es «particularmente aplicable a los sistemas de dominio mixto o multidominio» (mixed-domain or multidomain systems): aquellos que incorporan varios dominios físicos, «eléctrico, mecánico, fluídico y térmico», de manera integrada (De Silva et al., 2016, p. 1). El ejemplo canónico del libro es el sistema de frenos antibloqueo: el ABS de un automóvil «puede involucrar mecánica, electrónica, hidráulica y transferencia de calor», y «puede diseñarse de manera óptima como un producto mecatrónico» (De Silva et al., 2016, p. 1), es decir, como un único problema de diseño, no como cuatro problemas independientes acoplados a posteriori."));
children.push(p("El término tiene partida de nacimiento: en 1969 Yaskawa Electric (Japón) fue la primera empresa en acuñar la palabra «mechatronics», obtuvo el registro de la marca en 1972 y liberó los derechos en 1982 (De Silva et al., 2016, p. 10). Vale la pena contar el contexto completo que da el libro: los sistemas electromecánicos, automóvil, máquina de escribir eléctrica, aeronave, ascensor, existían desde comienzos del siglo XX, pero no eran mecatrónicos por carecer de enfoque integrado; los avances que hicieron posible la mecatrónica fueron la ingeniería de control, que despegó «en gran medida a inicios de la década de 1950», y la computación digital impulsada por los circuitos integrados y los microprocesadores «a partir de finales de la década de 1960» (De Silva et al., 2016, p. 10)."));
children.push(box("Idea fuerza para el aula", "Un sistema electromecánico diseñado por partes funciona; un sistema mecatrónico diseñado de forma integrada funciona mejor, disipa menos energía y es más fiable (síntesis de De Silva et al., 2016, pp. 1-5). La mecatrónica es, ante todo, una metodología de diseño."));

children.push(h2("1.2. Los dominios y su mapa sobre el curso"));
children.push(p("La figura 1.2 del libro (De Silva et al., 2016, p. 2) representa el sistema mecatrónico como la confluencia de los campos tradicionales de la ingeniería mecánica, la ingeniería eléctrica y electrónica, la ingeniería de control y la ingeniería informática, rodeada de los elementos de trabajo de la disciplina: modelado y análisis, diseño integrado, sensores y transductores, actuadores, controladores, componentes estructurales, electrónica analógica y digital, procesamiento de señal, dispositivos hidráulicos y neumáticos, dispositivos térmicos, fuentes de energía y software. Conviene dibujarla en la pizarra y anotar sobre cada elemento el bloque del curso que lo desarrolla: modelado en B4-B5, sensores y actuadores en B3, controladores en B5, procesamiento de la información sensorial en B6, software en B7 y el diseño integrado como hilo del proyecto."));
children.push(p("Un matiz que el libro subraya y que conviene verbalizar: cada aspecto o problema dentro de un sistema mecatrónico puede tener a su vez carácter multidominio, y el estudio de la disciplina debe cubrir «todas las etapas de modelado, diseño, desarrollo, integración, instrumentación, control, prueba, operación y mantenimiento» del sistema (De Silva et al., 2016, pp. 1-2). La ingeniería mecatrónica no es una fase: acompaña el ciclo de vida completo del producto."));

children.push(h2("1.3. Componentes de un sistema mecatrónico y ejemplos canónicos"));
children.push(p("«Un sistema mecatrónico típico consiste en un esqueleto mecánico, actuadores, sensores, controladores, dispositivos de acondicionamiento/modificación de señal, hardware y software de computador/digital, dispositivos de interfaz y fuentes de alimentación» (De Silva et al., 2016, p. 2). Esta lista es, casi literalmente, el índice de la asignatura, y decirlo en voz alta el primer día da a los estudiantes el mapa del semestre: el bloque 3 cubre sensores y actuadores; el bloque 4, el esqueleto y su movimiento; el bloque 5, el modelado y los controladores; el bloque 6, el procesamiento de la información sensorial; el bloque 7, el software y las interfaces."));
children.push(pRuns([
 { text: "El disco duro. ", bold: true },
 { text: "La figura 1.1 del libro (De Silva et al., 2016, p. 2) presenta una unidad HDD con sus pistas, brazo, rotor del brazo, circuito de control, motor de husillo, cabezal lector, disco y marco de montaje, como ejemplo de dispositivo con «estructuras mecánicas microminiatura, actuadores y sensores» integrados. Es un objeto cotidiano que condensa la disciplina: los platos giran a régimen constante, el cabezal vuela a nanómetros de la superficie y el lazo de control sigue pistas con precisión submicrométrica. Pregunta para el aula: ¿por qué el servo del brazo no puede diseñarse sin conocer la mecánica del brazo? Las resonancias estructurales y la masa móvil acoplan ambos problemas, exactamente el argumento contra el diseño no acoplado que formalizaremos en S2." },
]));
children.push(pRuns([
 { text: "El servomotor. ", bold: true },
 { text: "El libro lo describe como un motor con realimentación sensorial para la generación precisa de movimientos complejos, y detalla sus componentes mecánicos (rotor, estátor, rodamientos, encoder óptico, carcasa), eléctricos (bobinados de campo y rotor, circuitos de transmisión de potencia y conmutación) y electrónicos de sensado (De Silva et al., 2016, p. 2). Es el «átomo» de la robótica: un robot industrial de seis ejes son seis servomotores coordinados sobre un esqueleto, y a la vez el servomotor es, él solo, un sistema mecatrónico completo: la estructura anidada de la que habla el apartado 1.2." },
]));
children.push(pRuns([
 { text: "Áreas de aplicación. ", bold: true },
 { text: "El barrido del libro (De Silva et al., 2016, pp. 11-12) da un ejemplo por sector: en transporte terrestre, despliegue de airbags, ABS, control de crucero, suspensiones activas y los sistemas inteligentes de autopista (IVHS); en transporte aéreo, simuladores de vuelo, sistemas de control de vuelo y mecanismos de tren de aterrizaje; en fabricación, robots de soldadura, pintura, ensamblado e inspección, vehículos guiados (AGV), máquinas CNC y micromecanizado; en medicina, robótica de exploración, cirugía, rehabilitación y telemedicina; en el hogar y la oficina, desde aspiradoras robóticas hasta máquinas multifunción; en ingeniería civil, grúas y excavadoras; y en el espacio, robots móviles como el Mars Exploration Rover de la NASA, calificados de «sistemas fundamentalmente mecatrónicos» (De Silva et al., 2016, p. 12). La conclusión del capítulo: las fronteras tradicionales entre disciplinas de ingeniería serán cada vez más difusas (De Silva et al., 2016, pp. 12-13)." },
]));

// ============================================================ S2
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Sesión S2 (jue 10 sep, 1 h), El proceso de diseño mecatrónico"));

children.push(h2("Guion de la clase"));
children.push(seg("0–5 min", "Recuperación de S1"));
children.push(punto("Dos preguntas orales: (1) la definición de mecatrónica con sus dos palabras clave; (2) tres componentes de un sistema mecatrónico de la lista de la p. 2."));
children.push(seg("5–20 min", "Teoría: modelado y diseño (apdo. 2.1)"));
children.push(punto("Definir modelo: «una representación de un sistema real» (De Silva et al., 2016, p. 3), y por qué el diseño necesita modelos: predecir antes de construir."));
children.push(punto("Dibujar el bucle modelo-diseño de la fig. 1.3 (p. 3) en la pizarra: objetivos → modelo → predicción → decisiones → refinamiento, y recorrerlo dos veces con un ejemplo (accionamiento de un eje)."));
children.push(punto("Presentar la energía como hilo unificador con sus dos razones (p. 4): los puertos de potencia enlazan dominios (v·i = ω·τ, ec. 1.1, p. 6) y la disipación mínima es objetivo de diseño."));
children.push(punto("Advertencia contra el sobredimensionamiento: factores de seguridad excesivos y especificaciones de peor caso no dan diseños óptimos ni más económicos (De Silva et al., 2016, p. 4)."));
children.push(punto("Anunciar cómo esto estructura el proyecto integrador (modelo → control → percepción)."));
children.push(seg("20–40 min", "Teoría: diseño acoplado y MDQ (apdos. 2.2 y 2.3)"));
children.push(punto("Describir el enfoque secuencial tradicional (mecánica → electrónica → computador → controlador) y definir diseño no acoplado (De Silva et al., 2016, p. 5)."));
children.push(punto("Enunciar los tres problemas de la p. 5, uno a uno, con un ejemplo propio para cada uno (motor de catálogo con inercia real; sobredimensionamiento; variable oculta tras integrar)."));
children.push(punto("Definir índice de diseño (p. 6) y presentar la función de coste J (ec. 1.2, p. 6): qué significa cada término, sin manipularla."));
children.push(punto("Presentar el MDQ como cociente (ec. 1.4, p. 7), su lectura («cuánto se acerca el conjunto al ideal de cada dominio») y su generalización a fiabilidad, mantenibilidad, eficiencia, coste, tamaño, facilidad de control e inteligencia (p. 7)."));
children.push(punto("Esbozar la optimización con algoritmos genéticos: cromosoma = diseño, gen = decisión, alelos = opciones, aptitud = MDQ (p. 7); y la variante jerárquica tipo de actuador → motor concreto (p. 8)."));
children.push(seg("40–52 min", "Caso práctico en parejas"));
children.push(punto("Enunciado: «diseñad el accionamiento de una cinta transportadora: motor, reductora y control de velocidad»."));
children.push(punto("Fase 1 (5 min): que lo planteen secuencialmente y anoten qué decide cada fase."));
children.push(punto("Fase 2 (5 min): identificar qué decisiones deberían tomarse de forma acoplada y qué índice de diseño usarían (par disponible, eficiencia, coste, precisión de velocidad)."));
children.push(punto("Puesta en común (2-3 parejas): conectar cada observación con los tres problemas de la p. 5."));
children.push(seg("52–60 min", "Cierre: evolución de diseño e instrumentación (apdo. 2.4)"));
children.push(punto("Resumir las cinco etapas de la evolución de diseño (pp. 8-9) y su idea germinal: la monitorización de salud puede detectar debilidades de diseño, no solo averías."));
children.push(punto("Instrumentación como parte integral del diseño y la limitación práctica del caso del transporte guiado (p. 10): casi siempre se diseña con restricciones heredadas."));
children.push(punto("Anunciar S3 (historia y definición de robot) y recordar la lectura de Corke cap. 1, pp. 1-9."));

children.push(h2("2.1. Modelado y diseño: un bucle iterativo con la energía como hilo"));
children.push(p("«Un modelo es una representación de un sistema real» (De Silva et al., 2016, p. 3). En ingeniería mecatrónica, modelado y diseño «pueden avanzar de la mano de manera iterativa» (p. 3): los objetivos y especificaciones alimentan un modelo; el modelo permite predecir el desempeño; la predicción informa las decisiones de diseño; y el diseño resultante refina el modelo, cerrando el ciclo que la figura 1.3 del libro representa gráficamente (De Silva et al., 2016, p. 3). Este bucle estructura el proyecto integrador de la asignatura: los equipos construirán un modelo cinemático (B4), lo usarán para diseñar control (B5) y lo refinarán con percepción y navegación (B6-B7)."));
children.push(p("La energía es el hilo unificador del diseño integrado por dos razones (De Silva et al., 2016, p. 4). Primera: existen puertos de energía y potencia que enlazan la dinámica eléctrica con la mecánica, lo que permite formulaciones híbridas multidominio; en el modelo de acoplamiento ideal, la potencia eléctrica que entra iguala a la mecánica que sale, v·i = ω·τ (ec. 1.1; De Silva et al., 2016, p. 6), con la corriente i y el par τ como variables «de paso» y la tensión v y la velocidad angular ω como variables «de puerto». Segunda: un diseño óptimo persigue mínima disipación de energía, porque mayor disipación implica menor eficiencia y más problemas térmicos, de ruido, vibración, desgaste e impacto ambiental (p. 4). De ahí la advertencia del libro contra los factores de seguridad excesivos y las especificaciones de «peor caso» (worst-case): no producen diseños óptimos ni, muchas veces, los más económicos (De Silva et al., 2016, p. 4)."));

children.push(h2("2.2. El diseño no acoplado y sus tres problemas"));
children.push(p("El enfoque tradicional para diseñar un sistema multidominio es secuencial: primero los componentes mecánicos y estructurales; después la selección e interconexión de los componentes eléctricos y electrónicos; luego el computador y su interfaz; y por último el controlador. En este esquema cada subsistema se diseña por separado manteniendo constantes sus interacciones con los demás: es el diseño no acoplado (uncoupled design) (De Silva et al., 2016, p. 5)."));
children.push(p("El libro enumera tres problemas estructurales de ese enfoque, que conviene dictar casi literalmente (De Silva et al., 2016, p. 5): (1) «cuando dos componentes diseñados independientemente se interconectan, las características y condiciones de operación originales de ambos cambian debido a la carga o las interacciones dinámicas»; (2) «el acoplamiento perfecto de dos componentes diseñados y desarrollados independientemente es prácticamente imposible», de modo que un componente quedará «considerablemente subutilizado o sobrecargado en el sistema interconectado, siendo ambas condiciones ineficientes e indeseables»; y (3) «algunas de las variables externas de los componentes se volverán internas y ocultas debido a la interconexión», generando problemas potenciales «que no pueden monitorizarse explícitamente mediante sensado ni controlarse directamente». Tres ejemplos propios para el aula: el motor que en catálogo daba su par nominal deja de darlo arrastrando la inercia real de la transmisión (problema 1); la reductora sobredimensionada «por si acaso» que encarece y ralentiza el conjunto (problema 2); la tensión intermedia de un bus DC-DC que tras integrar el convertidor en el módulo ya no es accesible para diagnóstico (problema 3)."));

children.push(h2("2.3. Índice de diseño y Cociente de Diseño Mecatrónico (MDQ)"));
children.push(p("El marco formal parte de un sistema electromecánico modelado como dos subsistemas unidos por un transformador de energía ideal (fig. 1.4; De Silva et al., 2016, pp. 5-6). Si el subsistema mecánico se diseña tratando al eléctrico como fuente fija de energía, y viceversa, cada uno alcanza por separado un óptimo aislado: el índice de diseño Iue para el eléctrico e Ium para el mecánico, donde «el índice de diseño es una medida del grado en que el diseño particular satisface las especificaciones de diseño (objetivos de diseño)» (De Silva et al., 2016, p. 6). Al interconectar ambos subsistemas aparecen interacciones dinámicas y los objetivos se satisfacen a niveles inferiores, dados por los índices reales Ie e Im (p. 6)."));
children.push(p("«Un diseño verdaderamente mecatrónico intentará llevar Ie e Im tan cerca como sea posible de Iue e Ium, respectivamente», lo que puede lograrse «minimizando la función de coste cuadrática» J = αe·(Iue − Ie)² + αm·(Ium − Im)² (ec. 1.2; De Silva et al., 2016, p. 6), sujeta a la restricción [Ie, Im] = D(p) (ec. 1.3, p. 6), donde D representa la transformación del proceso de diseño y p la información de diseño disponible. El libro advierte que D es «compleja y típicamente no analítica», y que la minimización de J es en la práctica «un esquema iterativo, basado en conocimiento y no analítico» (De Silva et al., 2016, p. 7)."));
children.push(p("La formulación alternativa es la maximización del Cociente de Diseño Mecatrónico, concepto introducido por De Silva en 2003: MDQ = (αe·Ie² + αm·Im²) / (αe·Iue² + αm·Ium²) (ec. 1.4; De Silva et al., 2016, p. 7), un cociente entre el desempeño alcanzado y el ideal, ponderado por dominio. Aunque la ecuación se formula para dos categorías, «el MDQ puede generalizarse para tres o más», con índices que pueden representar «fiabilidad, mantenibilidad, eficiencia, relación coste-eficacia, potencia», tamaño y geometría, facilidad de control e inteligencia (De Silva et al., 2016, pp. 7-8). Importante para el examen: se pide interpretar estas expresiones (qué mide cada término, por qué es un cociente), no manipularlas."));
children.push(p("Para explorar el espacio de diseños, el libro propone algoritmos genéticos: una población de cromosomas donde cada cromosoma representa un diseño completo, cada gen un elemento de información del diseño (un componente, una estructura de conexión, un parámetro o atributo), los alelos son los valores posibles de cada gen (las opciones disponibles), y la función de aptitud es el propio MDQ, de modo que el problema se convierte en maximizar MDQ(p1, …, pm) (ec. 1.5; De Silva et al., 2016, pp. 7-8). La optimización puede además organizarse jerárquicamente: una capa superior optimiza el tipo de actuador, hidráulico, DC, de inducción, paso a paso, con un MDQ apropiado, y una capa inferior la selección del motor concreto dentro del catálogo disponible (De Silva et al., 2016, p. 8)."));

children.push(h2("2.4. Evolución de diseño e instrumentación integrada"));
children.push(p("La «evolución de diseño» extiende el mantenimiento predictivo al diseño mismo: igual que un sistema de monitorización de salud de máquina detecta componentes defectuosos, «el mismo sistema debería poder identificar regiones (sitios) de debilidad de diseño» (De Silva et al., 2016, p. 8). El marco tiene cinco etapas (De Silva et al., 2016, pp. 8-9): (1) desarrollar un modelo del sistema existente; (2) establecer, mediante el sistema de monitorización y un sistema experto, qué aspectos o segmentos pueden modificarse o mejorarse, los «sitios modificables» (modifiable sites); (3) formular una función de desempeño que represente la bondad del diseño: el MDQ; (4) hacer evolucionar el modelo con un método de optimización (por ejemplo, programación genética) maximizando esa función; (5) implementar en el sistema real los cambios de diseño del modelo evolucionado. La figura 1.5 (p. 9) representa la arquitectura completa: sistema real, monitorización, sistema experto, modelo, optimizador y función de desempeño realimentando mejoras."));
children.push(p("Por último, la instrumentación, sensores, actuadores, interfaces, controladores, «debe tratarse como un aspecto integral del diseño», no como una fase posterior (De Silva et al., 2016, pp. 9-10). El libro reconoce, no obstante, una limitación práctica del ideal mecatrónico: exigiría poder modificar concurrentemente todo el sistema, incluido el proceso, y eso rara vez es posible cuando el proceso ya existe. Su ejemplo es un sistema de transporte con vehículos guiados (automated vehicle guideway system) en el que deben sustituirse algunos vagones: no es práctico modificar la infraestructura para acomodar un diseño de vagón «óptimo», de modo que aunque los vagones nuevos se instrumenten de forma mecatrónica, el sistema global no operará óptimamente (De Silva et al., 2016, p. 10). Lección para el proyecto: casi siempre se diseña con restricciones heredadas."));

// ============================================================ S3
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Sesión S3 (mié 16 sep, 1 h), Historia y definición de robot"));

children.push(h2("Guion de la clase"));
children.push(seg("0–5 min", "Recuperación de S2"));
children.push(punto("Pregunta oral: los tres problemas del diseño no acoplado (p. 5); pedir un ejemplo concreto de al menos uno."));
children.push(seg("5–25 min", "Teoría: historia (apdo. 3.1)"));
children.push(punto("Abrir con la idea de Corke: la palabra «robot» significa cosas distintas para cada persona y la ciencia ficción ha moldeado las expectativas por delante de la ingeniería (Corke, 2023, pp. 1-2)."));
children.push(punto("Autómatas: pato de Vaucanson (1739), mecanismo de levas, un único programa fijo (Corke, 2023, p. 2)."));
children.push(punto("Telar de Jacquard (1801): reprogramable con tarjetas perforadas; citar la frase de los «rasgos distintivos de un robot moderno» (Corke, 2023, p. 2) y la línea Babbage → Lovelace."));
children.push(punto("R.U.R. (1920): Čapek, «roboti», raíz checa de servidumbre; el molde narrativo de la rebelión (Corke, 2023, p. 2); Asimov y las Tres Leyes como exploración de la moralidad humano-robot."));
children.push(punto("Devol: patente solicitada en 1954 y concedida en 1961, «Programmed Article Transfer», tambor magnético, concepto «Unimation» (Corke, 2023, p. 2)."));
children.push(punto("Unimation Inc.: Devol y Engelberger se conocen en un cóctel en 1956; primera empresa de robótica, Danbury, Connecticut (Corke, 2023, p. 3)."));
children.push(punto("Primer Unimate en 1961 en una planta de fundición a presión de General Motors en Nueva Jersey (Corke, 2023, p. 2); licencia a Kawasaki en 1968: primer robot industrial japonés (Corke, 2023, p. 3)."));
children.push(punto("Anécdota Engelberger: The Tonight Show, 1966; su segunda carrera en robots de servicio hospitalario con HelpMate (Corke, 2023, p. 4)."));
children.push(seg("25–40 min", "Teoría: definición de robot y sensores (apdos. 3.2 y 3.3)"));
children.push(punto("Citar a Engelberger: «no puedo definir un robot, pero sé reconocer uno cuando lo veo» (Corke, 2023, p. 8)."));
children.push(punto("Enunciar y escribir la definición: «máquina orientada a objetivos que puede percibir, planificar y actuar» (Corke, 2023, p. 8); avisar de que es pregunta literal de examen."));
children.push(punto("Mapear la tríada sobre el curso: percibir = B3/B6, planificar = B7, actuar = B3/B4/B5."));
children.push(punto("Definir sensores propioceptivos con sus tres ejemplos (ángulos articulares, revoluciones de rueda, corriente de motor) y exteroceptivos con los suyos (choque, GPS, brújula, tiempo de vuelo) (Corke, 2023, pp. 8-9)."));
children.push(punto("Adelantar la conexión con B6: propiocepción → odometría; exterocepción → corrección de la deriva."));
children.push(seg("40–55 min", "Teoría y discusión: telerobots y autonomía (apdo. 3.4)"));
children.push(punto("Telerobots: Tesla y su «teleautomaton» (1898); Goertz en Argonne, brazos líder-seguidor con realimentación de fuerza para material radiactivo (Corke, 2023, p. 7)."));
children.push(punto("Precisar: los «robots» que exploraron el Titanic eran ROV; la cirugía robótica actual es teleoperada, no autónoma (Corke, 2023, p. 7)."));
children.push(punto("Definir control alternado (traded) y compartido (shared) con sus ejemplos (Corke, 2023, pp. 7-8) y el caso de los rovers marcianos: autonomía local por latencia, objetivos desde la Tierra (Corke, 2023, p. 7)."));
children.push(punto("Discusión (8 min): situar dron FPV, taxi autónomo y el brazo del laboratorio en el espectro; dejar abierta la pregunta de si un robot industrial que ni percibe ni planifica es «robot»."));
children.push(seg("55–60 min", "Cierre"));
children.push(punto("Recapitular las tres fechas que hay que saber: 1920 (la palabra), 1961 (primer Unimate en GM), 1968 (Kawasaki)."));
children.push(punto("Encargar para S4: traer un ejemplo de robot «moderno» visto en prensa reciente."));

children.push(h2("3.1. De los autómatas a Unimation"));
children.push(p("La prehistoria de la robótica son los autómatas del siglo XVIII. El pato de Vaucanson (1739) batía las alas, comía grano y defecaba, pero funcionaba con un mecanismo de levas y ejecutaba «un único programa» fijo (Corke, 2023, p. 2). El salto conceptual llega con el telar de Jacquard (1801), una máquina reprogramable cuyo patrón de tejido se codificaba en tarjetas perforadas: «esta máquina tiene muchos de los rasgos distintivos de un robot moderno: realizaba una tarea física y era reprogramable» (Corke, 2023, p. 2). El libro traza además la línea que conecta esa idea con Babbage y la mecanización del cálculo y, a través de él, con Ada Lovelace y el primer algoritmo (Corke, 2023, p. 2): la historia de la robótica y la de la computación comparten raíz."));
children.push(p("La palabra «robot» nace en el teatro: la obra checa de ciencia ficción R.U.R., Rossum's Universal Robots, de Karel Čapek, publicada en 1920 y estrenada en 1921, con el término «roboti» sugerido por su hermano Josef, emparentado en checo con «servidumbre» (Corke, 2023, p. 2). Los robots de la obra son personas artificiales que acaban rebelándose, el molde de buena parte de la ciencia ficción posterior. Isaac Asimov exploró después la interacción humano-robot y su moralidad en su serie de relatos y novelas (1950-1985), cuyos robots llevan «cerebros positrónicos» que codifican las Tres Leyes de la Robótica (Corke, 2023, p. 4). Merece un minuto de aula: gran parte de lo que los estudiantes esperan de un robot viene de la ficción, no de la ingeniería (Corke, 2023, pp. 1-2)."));
children.push(p("La robótica industrial real comienza con una patente: George C. Devol solicitó en 1954, concedida en 1961, la patente estadounidense 2.988.237, «Programmed Article Transfer», que describía un brazo de coordenadas polares sobre raíl cuyas secuencias de movimiento se almacenaban como patrones magnéticos en un tambor giratorio, introduciendo el concepto de «Universal Automation», contraído en «Unimation» (Corke, 2023, p. 2). Devol y Joseph Engelberger se conocieron en un cóctel en 1956 y fundaron Unimation Inc. en Danbury, Connecticut: la primera empresa de robótica del mundo (Corke, 2023, p. 3). El primer robot Unimate entró en servicio en 1961 en una planta de fundición a presión de General Motors en Nueva Jersey (Corke, 2023, p. 2). En 1968 Unimation licenció su tecnología a Kawasaki Heavy Industries, que produjo el primer robot industrial japonés (Corke, 2023, p. 3), el punto de partida del liderazgo japonés del sector, que enlaza con el nacimiento del término «mecatrónica» en Yaskawa un año después (De Silva et al., 2016, p. 10). Desde entonces se han fabricado millones de manipuladores para soldadura, pintura, carga y descarga de máquinas, montaje, clasificación, empaquetado y paletizado (Corke, 2023, p. 4)."));
children.push(box("Anécdota para el aula", "En 1966 Engelberger presentó un Unimate en The Tonight Show: sirvió una cerveza, metió un putt de golf y dirigió la banda del programa (Corke, 2023, p. 4). Conocido como «el Padre de la Robótica», dedicó su etapa posterior a los robots de servicio: fundó Transitions Research Corporation, luego HelpMate Robotics, pionera en robots de reparto hospitalario (Corke, 2023, p. 4)."));

children.push(h2("3.2. La definición de robot"));
children.push(p("«No puedo definir un robot, pero sé reconocer uno cuando lo veo», bromeaba Engelberger (citado en Corke, 2023, p. 8). La definición operativa que adopta el libro, y esta asignatura, es: un robot es «una máquina orientada a objetivos que puede percibir, planificar y actuar» (a goal oriented machine that can sense, plan, and act) (Corke, 2023, p. 8). Un robot percibe su entorno y usa esa información, junto con un objetivo, para planificar una acción y ejecutarla: mover la herramienta de un manipulador para asir una pieza, o conducir un vehículo móvil hasta su destino (Corke, 2023, p. 8). La tríada organiza literalmente el resto del curso, percibir es el bloque 6 (con los sensores del 3), planificar el 7, actuar los bloques 3, 4 y 5, y conviene decirlo de forma explícita."));

children.push(h2("3.3. Sensores propioceptivos y exteroceptivos"));
children.push(p("Primera clasificación técnica del curso (Corke, 2023, p. 8): los sensores propioceptivos miden «el estado del propio robot»: el ángulo de las articulaciones de un brazo, el número de revoluciones de las ruedas de un móvil o la corriente que consume un motor eléctrico. Los sensores exteroceptivos miden «el estado del mundo con respecto al robot»: desde el simple sensor de choque de una aspiradora robótica hasta un receptor GPS, una brújula que mide el vector del campo magnético terrestre, o los sensores activos que emiten pulsos acústicos, ópticos o de radio y miden la distancia por el tiempo de vuelo de la señal reflejada (Corke, 2023, p. 8). La distinción reaparecerá dos veces: en el catálogo de sensores del bloque 3 y en la fusión sensorial del bloque 6, donde la propiocepción proporciona odometría y la exterocepción corrige su deriva acumulada."));

children.push(h2("3.4. Telerobots y grados de autonomía"));
children.push(p("Entre la teleoperación pura y la autonomía plena hay un espectro, y su historia empieza antes que la de los robots industriales: el primer telerobot documentado es el barco radiocontrolado que Nikola Tesla demostró en 1898 y llamó «teleautomaton» (Corke, 2023, p. 7). El origen técnico moderno está en el Proyecto Manhattan: para manipular material radiactivo, Ray Goertz desarrolló en el Argonne National Laboratory los brazos maestro-esclavo (hoy líder-seguidor) en los que el operador, mirando a través de ventanas de vidrio plomado o por televisión, movía el brazo líder cuyo movimiento reproducía el seguidor, con las fuerzas percibidas por éste realimentadas al líder (Corke, 2023, p. 7). Sus herederos directos: los vehículos operados remotamente (ROV) que exploraron el pecio del Titanic y los robots quirúrgicos actuales, que son teleoperados, no autónomos (Corke, 2023, p. 7), una precisión que sorprende a muchos estudiantes."));
children.push(p("El libro formaliza dos modos híbridos de reparto del control (Corke, 2023, pp. 7-8): en el control alternado (traded control), «la función de control pasa de un lado a otro entre el humano y el computador», como el piloto que conecta y desconecta el piloto automático; en el control compartido (shared control), ambos ejercen el control simultáneamente, como un coche que mantiene el carril mientras el conductor gestiona la velocidad. Los rovers marcianos ocupan el punto intermedio del espectro: navegan autónomamente en lo local, pero reciben objetivos de alto nivel de operadores en la Tierra, porque la latencia de comunicación de varios minutos exige que las decisiones inmediatas se tomen a bordo (Corke, 2023, p. 7). Pregunta de discusión con recorrido: el brazo del laboratorio ejecutando un programa ni percibe ni planifica, ¿lo cubre la definición de la p. 8? La definición es una vara de medir, no una frontera nítida."));

// ============================================================ S4
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Sesión S4 (jue 17 sep, 1 h), Panorama 2026 y lanzamiento del seminario"));

children.push(h2("Guion de la clase"));
children.push(seg("0–5 min", "Recuperación de S3"));
children.push(punto("Preguntar la definición de robot (literal, p. 8 de Corke) y un ejemplo de sensor propioceptivo y otro exteroceptivo."));
children.push(seg("5–25 min", "Teoría: el momento actual (apdo. 4.1)"));
children.push(punto("Plantear la tesis de la sesión: los fundamentos del curso no caducan, pero desde 2023 hay un cambio de paradigma en cómo se programa el comportamiento."));
children.push(punto("Definir modelo visión-lenguaje-acción (VLA): red entrenada con demostraciones robóticas que produce acciones motoras a partir de imágenes e instrucciones en lenguaje natural; citar π0 (Black et al., 2024, arXiv:2410.24164) y GR00T N1 como modelo fundacional abierto para humanoides (NVIDIA, 2025, arXiv:2503.14734)."));
children.push(punto("Mostrar 2-3 vídeos cortos (humanoide en almacén; demo VLA de manipulación); tras cada vídeo, preguntar: ¿qué parte es percepción, cuál planificación, cuál actuación?"));
children.push(punto("Conectar con los rasgos ya vistos: un VLA no elimina los lazos de control (B5) ni la cinemática (B4); genera las consignas que esos lazos ejecutan."));
children.push(punto("Mensaje profesional: el mercado pide fundamentos + Python + ROS 2 + criterio sobre cuándo la IA aporta valor; el bloque 8 desarrolla esto técnicamente."));
children.push(seg("25–35 min", "Debate de ética (apdo. 4.2)"));
children.push(punto("Proyectar dos afirmaciones y votar a mano alzada antes y después de discutir: «los robots destruyen más empleo del que crean» y «preferiría ser operado por un cirujano asistido por robot»."));
children.push(punto("Aportar los datos y argumentos de Corke (2023, pp. 11-12): automatización como condición de viabilidad industrial; entornos peligrosos; el contraste de los conductores humanos que matan a más de un millón de personas al año frente a la incomodidad social con el coche autónomo; la pregunta de la culpa."));
children.push(punto("Cerrar con la posición del libro: los roboticistas no deben decidir solos estas cuestiones, pero tampoco ignorarlas (Corke, 2023, p. 12)."));
children.push(seg("35–50 min", "Lanzamiento del seminario de artículos"));
children.push(punto("Reglas: parejas; artículo de los últimos 12-18 meses; temas (VLA y robot learning, SLAM, humanoides, manipulación, percepción, HRI, seguridad); fuentes (arXiv cs.RO, ICRA, IROS, RSS, CoRL, Science Robotics, T-RO, RA-L)."));
children.push(punto("Fechas: validación del artículo por el profesor antes del 30 de septiembre; presentaciones en S41-S42 (16-17 de diciembre); 10 minutos + 5 de preguntas."));
children.push(punto("Rúbrica: claridad 30%, comprensión técnica 40%, análisis crítico 20%, gestión de preguntas 10%; IA generativa permitida con declaración; defensa oral individual."));
children.push(punto("Guion que debe cubrir cada presentación: problema, método, resultados, limitaciones, conexión con los bloques del curso."));
children.push(seg("50–60 min", "Cuestionario de seguimiento del bloque 1"));
children.push(punto("8-10 preguntas tipo test (Moodle/Kahoot) sobre S1-S4; entra: definición de mecatrónica (p. 1), componentes (p. 2), los tres problemas (p. 5), lectura del MDQ (p. 7), fechas clave (1920/1961/1968), definición de robot (p. 8) y tipos de sensores (p. 8)."));

children.push(h2("4.1. El momento «Physical AI»: por qué 2026 no es 2016"));
children.push(p("La robótica vive desde 2023 su transformación más profunda desde la llegada del microprocesador: la aplicación de modelos fundacionales, la tecnología de los grandes modelos de lenguaje, al control de robots físicos. Los modelos visión-lenguaje-acción (VLA) se entrenan con grandes volúmenes de demostraciones robóticas y datos visuales, y aprenden a producir directamente acciones motoras a partir de observaciones de cámara e instrucciones en lenguaje natural. Las referencias que hay que conocer en 2026: π0 (pi-zero), presentado por Physical Intelligence como «modelo de flujo visión-lenguaje-acción para control general de robots» (Black et al., 2024, arXiv:2410.24164); GR00T N1, «un modelo fundacional abierto para robots humanoides generalistas» (NVIDIA, 2025, arXiv:2503.14734); y Gemini Robotics, la línea equivalente de Google DeepMind. La industria agrupa esta ola bajo la etiqueta «Physical AI» o IA encarnada, y los humanoides han pasado de curiosidad de laboratorio a producto con pilotos industriales en logística y fabricación."));
children.push(p("Para el aula, el mensaje tiene dos mitades. Primera: nada de lo que estudiaremos caduca. Un VLA no deroga la cinemática (B4) ni los lazos de control (B5): genera consignas que esos lazos ejecutan, sobre percepción (B6) y middleware (B7) que siguen siendo los de siempre. Segunda: el perfil profesional que el mercado demanda combina esos fundamentos con software moderno, Python, ROS 2, y con criterio para evaluar cuándo el aprendizaje aporta valor frente a la ingeniería clásica. El bloque 8 desarrolla los VLA con detalle técnico, y el seminario de artículos mantendrá la asignatura pegada a la frontera durante todo el semestre."));

children.push(h2("4.2. Consideraciones éticas"));
children.push(p("Corke dedica la sección 1.5 de su capítulo introductorio a la ética (Corke, 2023, pp. 11-12), y conviene traerla al aula el mismo día que hablamos del presente del sector. La preocupación más citada es el empleo: la IA ya realiza tareas de manejo de información, análisis de imágenes, decisiones, redacción automática, y se teme que los robots invadan pronto las tareas físicas, aunque su destreza, fiabilidad, velocidad y coste aún lo limitan (Corke, 2023, p. 11). Los contraargumentos que el propio libro presenta: hay trabajos que las personas no deberían hacer, en entornos insalubres o peligrosos, y trabajos poco cualificados donde escasea la mano de obra, como la recolección de fruta, las alternativas son subir salarios, importar el producto o automatizar; y la automatización robótica ha sido crítica para mantener la viabilidad económica de la industria del automóvil en países de salarios altos: sin robots, esas industrias no existirían ni emplearían a nadie (Corke, 2023, pp. 11-12)."));
children.push(p("El caso de los coches autónomos añade la dimensión de la responsabilidad: los conductores humanos matan a más de un millón de personas al año y, sin embargo, la incomodidad social ante el coche autónomo es mayor que ante el conductor humano; surge la pregunta de a quién culpar cuando el robot se equivoca (Corke, 2023, p. 12). Cuestiones análogas aparecen en cirugía robótica, cuidado de mayores, ¿pérdida de contacto humano?, y educación infantil, además del debate sobre las armas autónomas (Corke, 2023, p. 12). La posición del libro, que hago mía ante los estudiantes: son cuestiones éticas profundas que «no deben ni pueden decidirse solo por los roboticistas, pero tampoco deben ser ignoradas por ellos»; participar en el debate social es parte de la profesión (Corke, 2023, p. 12)."));

children.push(h2("4.3. Organización del seminario de artículos"));
children.push(p("El seminario es la pieza de la asignatura que se renueva sola cada año y la que conecta a los estudiantes con la literatura primaria. Las reglas completas, formato por parejas, ventana de publicación de 12-18 meses, temas, fuentes recomendadas, calendario con validación antes del 30 de septiembre y presentaciones en S41-S42, rúbrica con sus pesos y política de IA, están detalladas en el guion de la sesión, y deben quedar publicadas en el campus virtual el mismo día. Criterio de validación de artículos que aplico: venue reconocida o arXiv con tracción demostrable, resultados experimentales (no solo posición), y extensión abordable para una presentación de diez minutos. Conexión con la evaluación: la presentación puntúa en «trabajos y presentaciones», y las preguntas del público cuentan para la participación de quien las hace."));

// ============================================================ Guía de discusiones
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Guía de conducción de las discusiones de este bloque"));

children.push(h2("Método general: cómo se conduce una discusión en este curso"));
children.push(p("Conviene empezar por la objeción que uno se hace a sí mismo cuando llega a la clase con el temario justo: los diez minutos de discusión del cierre de S1 o los diez del debate de ética de S4 no son tiempo restado a la teoría, son el único instrumento que tenemos para ver, en tiempo real, si lo que acabamos de dictar se ha convertido en criterio o se ha quedado en frase memorizada. Un estudiante de máster puede repetir sin error que la mecatrónica es la «aplicación sinérgica de la mecánica, la electrónica, la ingeniería de control y la ingeniería informática» con enfoque de diseño integrado (De Silva et al., 2016, p. 1) y ser incapaz de decidir si su lavadora es mecatrónica. La discusión es, en el sentido técnico del término, evaluación formativa: no puntúa, pero informa una decisión docente inmediata, repetir el argumento, cambiar el ejemplo o seguir adelante, y lo hace con una latencia que ningún cuestionario alcanza. Tiene además una consecuencia sobre la evaluación real de la asignatura, y merece decirse en voz alta el primer día: la participación cuenta, y las preguntas que se hacen en clase cuentan para quien las hace."));
children.push(p("La técnica más rentable y la que más cuesta sostener es el silencio. Después de formular una pregunta abierta hay que callar y contar diez segundos mirando al grupo, sin reformular, sin añadir un ejemplo y sin rebajar la pregunta. Diez segundos de silencio son eternos para quien está de pie delante de treinta personas y perfectamente normales para quien está pensando la respuesta; la asimetría de esa percepción es la causa del error más frecuente en el aula, que consiste en que el profesor rellene su propio silencio. El coste es acumulativo: si uno se contesta dos veces el primer día, la clase aprende en veinte minutos que no hace falta contestar, y ese aprendizaje no se revierte en todo el semestre. Ayudan tres trucos mecánicos: contar mentalmente hasta diez, apoyarse en la pizarra escribiendo la propia pregunta mientras se espera, da algo que hacer con las manos, y no reformular nunca, porque reformular obliga al que ya había empezado a construir una respuesta a empezar de cero y suele producir más silencio, no menos."));
children.push(p("Hay que distinguir con nitidez los dos tipos de pregunta que usan los guiones de estas sesiones, porque confundirlos arruina las dos. La pregunta cerrada de recuperación es la de los tramos de cinco minutos que abren S2, S3 y S4: los tres problemas del diseño no acoplado (De Silva et al., 2016, p. 5), la definición literal de robot (Corke, 2023, p. 8), un sensor propioceptivo y otro exteroceptivo. Tiene una respuesta correcta, se dirige por nombre, se corrige en segundos y su función no es discutir nada, sino forzar recuperación activa de la memoria, que es lo que consolida. La pregunta abierta de discusión admite varias respuestas defendibles, se lanza al grupo entero y su valor está en el razonamiento, no en el resultado. La prueba para saber cuál se tiene entre manos es sencilla: si uno sabe de antemano la respuesta exacta que quiere oír, la pregunta es cerrada, y no sirve para abrir discusión, porque la clase percibe en seguida que se busca una palabra concreta y calla esperando que el profesor la diga. El error simétrico también existe: tratar como abierta una pregunta que tiene respuesta única en el libro deja al aula con la impresión de que las fechas de Unimate son opinables."));
children.push(p("La votación a mano alzada es el instrumento más eficaz para hacer visible lo que de otro modo no se ve, que es el cambio de opinión. El guion de S4 ya la prescribe explícitamente para las dos afirmaciones del debate de ética, y la mecánica conviene respetarla al detalle: enunciar la afirmación en forma binaria, pedir que voten todos a la vez a una señal, para que nadie mire la mano del vecino antes de levantar la suya, contar en voz alta y escribir el número en la pizarra sin comentarlo. Después se discute. Al terminar se vota otra vez y se escribe el segundo número al lado del primero. El resultado no importa; lo que importa es el delta, porque hace tangible que un argumento ha movido votos y, sobre todo, porque legitima públicamente el hecho de cambiar de opinión ante un dato, que es una competencia profesional y no una debilidad. La misma mecánica sirve para calibrar clasificaciones, el espectro de autonomía de S3 y S5, con la variante de votar con los dedos entre varias opciones numeradas. Si el delta sale nulo, no es un fracaso: se comenta en voz alta y se pregunta qué haría falta para mover un voto, que es una pregunta excelente."));
children.push(p("Los dos problemas de reparto de la palabra tienen soluciones distintas. Con el estudiante que monopoliza, hay uno por grupo, es casi siempre bueno y sus intervenciones son casi siempre correctas, la maniobra no es cortarle, que lo desactiva para el resto del semestre, sino cerrar su turno con una síntesis que le reconozca la aportación y redirigir de forma explícita: se agradece, se resume en una frase lo que ha dicho, y se pide expresamente la voz de alguien que no haya hablado todavía. Conviene anunciar al principio del curso la regla de las dos intervenciones antes de repetir, porque anunciada no ofende a nadie y aplicada sin anunciar parece personal; y ayuda desplazarse físicamente hacia el lado opuesto del aula, porque la atención del grupo sigue al profesor. Con el estudiante que no habla nunca, la pregunta abierta lanzada en frío es contraproducente: lo expone y confirma su decisión de no participar. Lo que funciona es invertir el orden y darle una respuesta ya construida antes de pedírsela: un minuto de trabajo en parejas sobre la pregunta, y después una pregunta dirigida por su nombre pero formulada en plural, qué habéis dicho en la pareja, de modo que lo que expone es un producto compartido y no una opinión personal expuesta a juicio. De aquí se sigue la herramienta más rentable del primer día de clase, que es aprenderse los nombres: sin nombres no hay pregunta dirigida, y sin pregunta dirigida el aula se reduce a los cuatro de siempre."));
children.push(p("Queda el trato de la respuesta errónea y el cierre, que son el mismo problema: cómo ejerce el profesor su autoridad sobre el contenido sin desactivar la participación. Una respuesta equivocada no se corrige en seco, y menos la primera de la sesión, porque el precio de un corte limpio lo paga toda la clase en forma de silencio. La secuencia que funciona tiene tres movimientos: pedir el razonamiento, cómo has llegado ahí, devolver el asunto al grupo, alguien lo ve de otra manera, y sólo al final cerrar nombrando la fuente y la página. Con frecuencia el propio estudiante encuentra el error al explicarse en voz alta, y entonces el aprendizaje es mayor y el coste social nulo. Hay que distinguir, eso sí, el error factual del juicio discutible: que el primer Unimate entró en servicio en 1961 en una planta de fundición a presión de General Motors en Nueva Jersey (Corke, 2023, p. 2) no se explora, se corrige en cinco segundos y con la página; que un móvil sea o no mecatrónico sí se explora. Y toda discusión se cierra con una posición del profesor, aunque sea de segundo orden: la fórmula es separar en dos frases lo que queda decidido por la fuente de lo que queda legítimamente abierto, y escribir en la pizarra la idea fuerza. Lo que no hay que decir nunca al cerrar es que cada uno tiene su opinión y todas son igual de válidas: es falso en una asignatura que se apoya en fuentes con página, anula el trabajo de los diez minutos anteriores y enseña justo lo contrario de lo que se pretendía enseñar."));
children.push(box("La regla de los diez segundos", "Formular la pregunta, callar y contar diez. No reformular, no dar un ejemplo, no contestarse. Si a los diez segundos no hay nadie, no se rebaja la pregunta: se pasa a la maniobra de rescate prevista para esa discusión, minuto en parejas, votación a mano alzada o pregunta dirigida por nombre, que es distinta en cada una y está descrita en los apartados siguientes."));

children.push(h2("La discusión de cierre de S1 (50–60 min): electromecánico o mecatrónico"));
children.push(h3("Objetivo"));
children.push(p("Lo que debe quedar aprendido es que la definición del apartado 1.1 es un test aplicable y no una frase para el examen: que «sinérgica» e «integrado» sirven para decidir sobre un objeto concreto (De Silva et al., 2016, p. 1). Y hay un segundo aprendizaje, menos evidente y más valioso, que sólo se produce en la discusión y no en la exposición: buena parte de la lista de la pizarra no se puede clasificar mirando el objeto, porque la diferencia entre electromecánico y mecatrónico no está en los componentes sino en cómo se tomaron las decisiones de diseño, y eso desde fuera no se ve. La teoría afirma que la mecatrónica es una metodología de diseño; la discusión es lo que convierte esa afirmación en una experiencia incómoda, que es como se aprende. Nótese la diferencia de función respecto al ejemplo del ABS que ya se ha explicado en el tramo de teoría (De Silva et al., 2016, p. 1): el ABS lo resuelve el libro, la lavadora del estudiante no la resuelve nadie."));
children.push(h3("Formato y tiempos"));
children.push(p("El guion asigna al cierre el tramo de 50 a 60 minutos, y hay que repartirlo así. De 50 a 51, recuperar la lista que quedó escrita en la pizarra en el tramo de 10 a 15 minutos y leerla en voz alta entera, sin comentar ninguna entrada: leerla ya produce risas y correcciones espontáneas, y eso es participación gratuita. De 51 a 53, dos minutos de trabajo en parejas con una instrucción muy concreta: marcar cada objeto de la lista con M de mecatrónico, E de electromecánico o una interrogación. De 53 a 58, cinco minutos de barrido en común, y aquí la decisión importante es no recorrer la lista completa: se eligen cinco o seis objetos, empezando por uno fácil y terminando por uno imposible. De 58 a 60, cierre con la idea fuerza y encargo de la lectura de De Silva et al. (2016), capítulo 1, pp. 1-10, para S2. La tentación de estirar la discusión hasta el timbre hay que resistirla: el encargo de lectura dicho con prisa y de espaldas mientras la clase recoge no se hace."));
children.push(h3("Pregunta de apertura"));
children.push(p("Formulada literalmente, y después de haber escrito en la pizarra las dos palabras clave: «Con la definición en la mano, diseño sinérgico e integrado y no simplemente mecánica más electrónica: de esta lista, ¿cuáles son mecatrónicos y cuáles son solamente electromecánicos? Empezad por uno del que estéis seguros y marcad otro que os parezca dudoso.» Pedir un caso seguro y un caso dudoso, y no sólo la clasificación, es lo que hace hablar: dar un ejemplo dudoso no compromete a nadie y abre la puerta al que no quiere equivocarse en público."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "«El móvil es mecatrónico». ", bold: true },
 { text: "Sale siempre y es la que hay que devolver a la clase, no resolver. La pregunta de vuelta es qué parte concreta del móvil se ha diseñado acoplando mecánica y control, y el recorrido termina casi solo en el módulo de cámara con estabilización óptica y en el motor del vibrador: el teléfono es, en conjunto, un sistema electrónico que contiene subsistemas mecatrónicos. Es la ocasión de introducir la idea de sistema anidado que la teoría ya ha presentado con el servomotor, un dispositivo mecatrónico completo dentro de otro (De Silva et al., 2016, p. 2), y por eso vale la pena gastar en ella un minuto entero." },
]));
children.push(pRuns([
 { text: "«La lavadora es mecatrónica». ", bold: true },
 { text: "Es la respuesta que más rendimiento da y la que conviene desarrollar. En lugar de aceptarla o negarla, se pide a la clase qué lavadora: la de temporizador de leva de los años setenta ejecuta un programa fijo y no es mecatrónica; la que mide el desequilibrio de la carga y ajusta el perfil de centrifugado sí lo es, y el mismo tambor y el mismo motor están en las dos. Ese contraste reproduce exactamente el argumento histórico del libro, según el cual los sistemas electromecánicos existían desde comienzos del siglo XX, automóvil, máquina de escribir eléctrica, aeronave, ascensor, pero no eran mecatrónicos por carecer de enfoque integrado (De Silva et al., 2016, p. 10). Si alguien ha puesto el ascensor en la lista, se aprovecha por la misma vía." },
]));
children.push(pRuns([
 { text: "«El coche», «el ABS». ", bold: true },
 { text: "Es la respuesta del libro y hay que aceptarla rápido, sin gastar tiempo, porque ya se ha explicado (De Silva et al., 2016, p. 1). Lo productivo es devolverla partida: el ABS sí, y el limpiaparabrisas con sensor de lluvia, ¿también? La respuesta obliga a mirar si hay lazo cerrado y diseño conjunto o simplemente un sensor añadido a un mecanismo preexistente." },
]));
children.push(pRuns([
 { text: "«Todo lo que lleva un microcontrolador es mecatrónico». ", bold: true },
 { text: "Es la respuesta errónea previsible y la más útil de la sesión, porque el error es sustantivo. No se corrige en seco: se pide a la clase un contraejemplo, y aparecen en seguida, un mando a distancia, un reloj digital, un termostato que no mueve nada. Sólo después se cierra nombrando el criterio: lo que hace mecatrónico a un sistema no es la presencia del microprocesador, sino que las decisiones de los distintos dominios físicos se hayan tomado juntas y considerando sus interacciones dinámicas desde la primera fase (De Silva et al., 2016, p. 1)." },
]));
children.push(h3("Desvíos frecuentes y cómo reconducir"));
children.push(p("El desvío más habitual es la deriva al modelo comercial: la discusión pasa de si un teléfono es mecatrónico a qué teléfono tiene mejor estabilizador. Se reconduce sin cortar a nadie diciendo en voz alta que el modelo no interesa y que lo que interesa es qué decisión de diseño lo hace mecatrónico, y volviendo a nombrar el objeto genérico. El segundo desvío previsible es la pregunta de si la inteligencia artificial cuenta como dominio, que en septiembre de 2026 la hace alguien en la primera clase: se anota literalmente en un rincón de la pizarra como pregunta pendiente y se remite a S4, donde está el apartado del momento «Physical AI»; anotarla en vez de despacharla enseña que las preguntas no se pierden. El tercero es la deriva a si mecatrónica y robótica son lo mismo, que se resuelve señalando el diagrama de dominios ya dibujado (De Silva et al., 2016, p. 2) y prometiendo la definición de robot para S3 (Corke, 2023, p. 8). Y hay un cuarto desvío que no es un desvío, sino la mejor objeción posible: el estudiante purista que sostiene que entonces nada es mecatrónico, porque en la práctica nunca se diseña todo a la vez. A ése no se le reconduce, se le da la razón parcialmente y se le paga con la propia limitación que el libro admite en el caso del sistema de transporte con vehículos guiados, donde el ideal mecatrónico no es alcanzable porque la infraestructura ya existe (De Silva et al., 2016, p. 10)."));
children.push(h3("Si la clase no habla"));
children.push(p("Es el primer día, no se conocen entre ellos y no conocen al profesor, de modo que el silencio aquí es lo normal y no hay que interpretarlo como desinterés. La maniobra de rescate no es insistir con la pregunta abierta sino reducirla a una votación binaria sobre un único objeto, el más doméstico de la lista: manos arriba los que digan mecatrónico, manos arriba los que digan electromecánico. Con el recuento escrito en la pizarra hay dos bandos visibles, y entonces se pide una razón a alguien de la mayoría y otra a alguien de la minoría, por nombre si ya se dispone de la lista de clase. Si tampoco así arranca, se hace el primer objeto en voz alta razonando uno mismo delante de ellos, se hace el segundo a medias y se pide el tercero: modelar el razonamiento en voz alta es más eficaz que exigirlo, y sólo cuesta dos minutos."));
children.push(h3("Cierre"));
children.push(p("Hay que terminar con la idea fuerza que ya fija el guion, dicha tal cual: la mecatrónica es una metodología de diseño, no una lista de componentes. Y conviene añadir el corolario que la discusión ha demostrado y la exposición no podía demostrar: por eso la mitad de esta lista no puede clasificarse mirando el objeto, haría falta ver el expediente de diseño. Con eso, la clase se va con una definición que ha usado, no sólo oído. Lo que no conviene decir es que casi toda la lista es mecatrónica, para dejar buen sabor: es falso y desactiva el criterio recién construido. Tampoco conviene cerrar con que el asunto es discutible y ahí lo dejamos, porque es exactamente la impresión de que todo vale. Y no conviene prometer que en el examen habrá que clasificar objetos concretos, porque no es cierto: lo que se pide es la definición y su aplicación razonada."));

children.push(h2("La discusión de S3 (47–55 min): telerobots, autonomía y el brazo del laboratorio"));
children.push(h3("Objetivo"));
children.push(p("El objetivo es doble. Primero, que el espectro de autonomía deje de ser una lista de etiquetas, teleoperación, control alternado, control compartido, autonomía supervisada (Corke, 2023, pp. 7-8), y se convierta en un instrumento con el que situar objetos reales, incluidos los casos límite. Segundo, y es el objetivo de fondo, que la definición operativa de robot se experimente como vara de medir y no como frontera: la definición de Corke exige percibir, planificar y actuar (Corke, 2023, p. 8), y el brazo industrial del laboratorio, que es el robot con el que van a hacer prácticas todo el semestre, no percibe ni planifica. La teoría del apartado 3.4 enuncia esa tensión en una frase; la discusión es lo que la hace sentir, y sin sentirla la frase no significa nada. Es importante saber qué no se persigue: no se persigue llegar a un veredicto sobre el brazo, sino que la clase descubra que la pregunta útil no es de sí o no."));
children.push(h3("Formato y tiempos"));
children.push(p("El guion asigna el tramo de 40 a 55 minutos a teoría y discusión sobre telerobots y autonomía, con ocho minutos de discusión. El reparto que funciona es este. De 40 a 47, la exposición del apartado 3.4: Tesla y su teleautomaton de 1898, los brazos líder-seguidor de Goertz en Argonne, la precisión de que los vehículos del Titanic eran ROV y que la cirugía robótica actual es teleoperada, los dos modos híbridos de reparto de control y el caso de los rovers marcianos (Corke, 2023, pp. 7-8). En el minuto 47 se dibuja en la pizarra un eje horizontal con teleoperación a la izquierda y autonomía plena a la derecha, se enuncia la pregunta y se callan diez segundos. De 48 a 52, situar los tres casos sobre el eje. De 52 a 55, la pregunta incómoda sobre el brazo del laboratorio y el cierre. A las 55 hay que haber terminado, porque el tramo final de la sesión tiene contenido propio: las tres fechas que hay que saber, 1920, 1961 y 1968, y el encargo para S4."));
children.push(h3("Preguntas de apertura"));
children.push(p("La primera, literal: «Vamos a colocar tres cosas en este eje: un dron FPV pilotado por radio, un taxi autónomo y el brazo del laboratorio ejecutando su programa. ¿Dónde va cada uno y, sobre todo, por qué? En cada caso quiero que me digáis quién percibe, quién planifica y quién pone el objetivo.» Obligar a desglosar la tríada en cada caso es lo que impide que la discusión se convierta en un intercambio de intuiciones. La segunda pregunta, la incómoda, se reserva para el minuto 52 y también conviene formularla literalmente: «Corke define un robot como una máquina orientada a objetivos que puede percibir, planificar y actuar, y lo hemos escrito hace veinte minutos. El brazo del laboratorio no percibe y no planifica: repite. ¿Es un robot?»"));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "«El dron FPV es teleoperación pura». ", bold: true },
 { text: "Se acepta rápido porque es correcta en lo esencial, y después se refina con una pregunta devuelta a la clase: ¿quién controla la actitud del dron? El controlador de vuelo estabiliza mientras el piloto manda consignas, de modo que humano y computador controlan simultáneamente, que es precisamente la definición de control compartido y el mismo caso que el coche que mantiene el carril mientras el conductor gestiona la velocidad (Corke, 2023, pp. 7-8). Es la respuesta que más conviene desarrollar, porque de ella se sigue la idea que la sesión necesita: el escalón no es una propiedad de la máquina, sino del reparto de control en una tarea y un modo concretos." },
]));
children.push(pRuns([
 { text: "«El taxi autónomo es autonomía plena». ", bold: true },
 { text: "Se acepta y se matiza, sin corregir de frente. El objetivo de alto nivel lo pone el pasajero, exactamente igual que los operadores en la Tierra fijan objetivos de alto nivel al rover marciano mientras éste navega de forma autónoma en lo local porque la latencia de varios minutos lo exige (Corke, 2023, p. 7). Autonomía supervisada no es un escalón inferior al ideal, es la categoría correcta, y el supuesto que hay que desmontar es que autonomía signifique ausencia de humanos en el bucle." },
]));
children.push(pRuns([
 { text: "«El brazo no es un robot» y «el brazo sí es un robot». ", bold: true },
 { text: "Las dos aparecerán, y no hay que zanjar ninguna: hay que pedir a cada bando su criterio. Al bando del no se le pregunta qué le falta, y la respuesta es percepción y planificación. Al bando del sí se le pregunta con qué criterio, y aquí está la mejor jugada disponible de toda la sesión: el argumento de la reprogramabilidad ya está en el libro y en la propia historia que se ha contado veinte minutos antes, porque del telar de Jacquard de 1801 dice Corke que «tiene muchos de los rasgos distintivos de un robot moderno: realizaba una tarea física y era reprogramable» (Corke, 2023, p. 2). Con eso, el bando del sí queda legitimado por la fuente y no por la benevolencia del profesor, y la discusión se sostiene sin arbitraje." },
]));
children.push(pRuns([
 { text: "«Los robots quirúrgicos son autónomos». ", bold: true },
 { text: "Es la creencia extendida que hay que corregir, y se corrige con la fuente y sin ironía: la cirugía robótica actual es teleoperada, no autónoma, y es descendiente directa de los brazos líder-seguidor de Goertz, igual que los ROV que exploraron el Titanic (Corke, 2023, p. 7). Es la corrección con más valor de la sesión porque desmonta una idea que casi todos traen de los medios, y conviene dejarla dicha con claridad porque volverá en S5, donde el robot quirúrgico es una de las fichas de la actividad en equipos." },
]));
children.push(h3("Desvíos frecuentes y cómo reconducir"));
children.push(p("El desvío más previsible es el salto a los niveles SAE de conducción autónoma, que alguien conoce y quiere aportar. No es un error y no se corta: se reconoce que es el vocabulario de un sector concreto, se anota la correspondencia aproximada en un margen de la pizarra y se vuelve al eje del libro, diciendo explícitamente que en la asignatura usamos el espectro de Corke. El segundo desvío es el más peligroso por lo atractivo: los accidentes de coches autónomos y la cuestión de quién es responsable. Es material de S4, donde está tratado con la fuente en la mano (Corke, 2023, p. 12), y hay que aparcarlo prometiéndolo por su nombre y para el jueves; si se deja correr se come los ocho minutos y la sesión pierde su cierre. El tercero es la pregunta de qué pasa si el robot lleva un modelo de lenguaje dentro, que se remite a S4 y al bloque 8. Y hay un cuarto, menor pero recurrente, que es la discusión terminológica sobre maestro-esclavo frente a líder-seguidor: se zanja en una frase diciendo que el libro recoge ambas denominaciones y usa hoy la segunda (Corke, 2023, p. 7), y se sigue."));
children.push(h3("Si la clase no habla"));
children.push(p("La maniobra de rescate aquí no es el eje, que exige construir un argumento, sino la pregunta incómoda convertida en votación: quién dice que el brazo del laboratorio es un robot, quién dice que no. Se cuentan las manos y se escriben los dos números en la pizarra. Una división visible obliga a que alguien defienda su bando, sobre todo si el reparto está cerca del empate, y basta con preguntar a alguien de cada lado por qué ha levantado la mano, lo cual es mucho más fácil de contestar que una pregunta abierta. Si el grupo sigue frío, se recurre al minuto en parejas sobre una sola cuestión, qué le falta al brazo para cumplir la definición, y después a la pregunta dirigida por nombre en plural, preguntando qué han dicho en la pareja. Conviene tener localizados de antemano a dos estudiantes que ya hayan hablado en S1 o S2: en la tercera sesión eso ya se sabe."));
children.push(h3("Cierre"));
children.push(p("Se cierra con la frase que ya está en el apartado 3.4 y que conviene decir exactamente así: la definición es una vara de medir, no una frontera nítida. Y con el corolario práctico, que es lo que se llevan de utilidad para el resto del curso y para el seminario de artículos: cuando lean un artículo o una hoja de catálogo, la pregunta útil no es si aquello es un robot, sino qué percibe, qué planifica y quién le pone el objetivo. Lo que no conviene decir es que la definición de Corke está mal o es insuficiente: es materia literal de examen, se ha dictado en la misma sesión y desautorizarla el mismo día desorienta al grupo sin ganancia alguna. Tampoco conviene dictar sentencia diciendo que el brazo del laboratorio no es un robot, porque durante las prácticas de todo el semestre se le va a llamar robot con toda naturalidad. La formulación que resuelve las dos cosas es que es un robot en el uso industrial de la palabra y un caso incompleto medido con la definición del libro, y que ambas afirmaciones son verdaderas a la vez."));

children.push(h2("El debate de ética de S4 (25–35 min): el más delicado del bloque"));
children.push(h3("Objetivo"));
children.push(p("Lo que debe quedar aprendido no es una conclusión ética, que no nos corresponde imponer, sino la capacidad de sostener un argumento con datos y de encontrar el punto débil del propio: concretamente, que sepan defender y refutar la tesis del empleo con los argumentos que el libro pone sobre la mesa (Corke, 2023, pp. 11-12). Y hay un objetivo de actitud profesional que es tan importante como el anterior: que salgan convencidos de que esto forma parte del trabajo del ingeniero y no es un apéndice de relleno, porque es exactamente lo que sostiene el propio Corke. La diferencia con la teoría es aquí más marcada que en ninguna otra discusión del bloque: el apartado 4.2 entrega los argumentos ya ordenados y enfrentados, de modo que leerlo produce la sensación de que la cuestión está resuelta; el debate obliga a defender una posición, a recibir el contraargumento y a comprobar que la sensación de resolución era falsa."));
children.push(h3("Formato y tiempos"));
children.push(p("Son diez minutos exactos, del 25 al 35, y con tan poco margen el reparto tiene que estar decidido de antemano. De 25 a 26 se proyectan las dos afirmaciones que fija el guion y se vota a mano alzada cada una, con el recuento escrito en la pizarra y sin comentar nada. De 26 a 27, un minuto de trabajo en parejas con asignación cruzada: cada pareja prepara el mejor argumento para la posición contraria a la que ha votado. Esa asignación cruzada es la maniobra clave de todo el debate, porque separa a la persona de la posición y desactiva de entrada el enfrentamiento personal, que es el riesgo real de estos diez minutos. De 27 a 32, cinco minutos de intervenciones alternando bandos, con el profesor anotando en dos columnas y sin valorar ninguna. De 32 a 33, el profesor aporta los datos y argumentos del libro que no hayan salido. De 33 a 34, segunda votación y anotación del delta junto al primer recuento. De 34 a 35, cierre con la posición del libro. Después viene el lanzamiento del seminario, que necesita sus quince minutos íntegros, de modo que aquí no hay margen para estirar."));
children.push(h3("Preguntas de apertura"));
children.push(p("Las dos afirmaciones se enuncian tal como están en el guion, en forma de sentencia y no de pregunta, porque una sentencia se vota y una pregunta abre matices que aquí no caben. Literalmente: «Primera afirmación: los robots destruyen más empleo del que crean. Segunda afirmación: preferiría ser operado por un cirujano asistido por robot. No quiero matices todavía, quiero manos: votad las dos, y luego os voy a pedir que defendáis lo contrario de lo que acabáis de votar.» Anunciar la asignación cruzada antes de votar tiene una ventaja adicional: reduce el voto estratégico y hace que el recuento inicial sea más sincero, porque votar ya no compromete a defender nada."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "«Destruyen empleo, se ve en la industria del automóvil». ", bold: true },
 { text: "Es la intervención más frecuente y no hay que refutarla: hay que pedir el dato y después oponerle el argumento del propio libro, que es contraintuitivo y por eso mueve votos. La automatización robótica ha sido crítica para mantener la viabilidad económica de la industria del automóvil en países de salarios altos, y sin robots esas industrias no existirían ni emplearían a nadie (Corke, 2023, pp. 11-12). Conviene decirlo con la fuente delante, porque el argumento suena a defensa interesada del sector y con la cita deja de sonar así." },
]));
children.push(pRuns([
 { text: "«Crean empleo distinto y más cualificado». ", bold: true },
 { text: "Es la respuesta cómoda del alumno de ingeniería y hay que devolverla a la clase con la pregunta difícil: quién paga la transición del que pierde el suyo. Y hay que reconocer en voz alta que el libro no responde a eso, porque es exactamente ahí donde empieza la política pública. Reconocer el límite de la fuente es lo que impide que el debate suene a folleto corporativo, y da credibilidad a todo lo demás." },
]));
children.push(pRuns([
 { text: "«Hay trabajos que nadie debería hacer». ", bold: true },
 { text: "Es literalmente el argumento del libro y hay que reforzarlo con su caso concreto: los trabajos en entornos insalubres o peligrosos, y los poco cualificados donde escasea la mano de obra, como la recolección de fruta, cuyas alternativas reales son subir salarios, importar el producto o automatizar (Corke, 2023, pp. 11-12). El valor pedagógico de esas tres alternativas es que ninguna es gratis, y ver eso es más útil que cualquier conclusión." },
]));
children.push(pRuns([
 { text: "«Yo prefiero un cirujano humano, no me fío de una máquina». ", bold: true },
 { text: "Aquí no se corrige la opinión, que es legítima, sino el supuesto que la sostiene: la cirugía robótica es teleoperada y el cirujano está a los mandos (Corke, 2023, p. 7), como ya se vio en S3. La pregunta no es humano contra máquina, sino humano con instrumento. Es el dato que más votos cambia en la segunda votación, y por eso conviene reservarlo para el minuto 32 y no adelantarlo: si se dice al principio, la segunda afirmación deja de dar juego." },
]));
children.push(p("Aparecerán también, casi con seguridad, las armas autónomas y el cuidado de mayores con su pregunta sobre la pérdida de contacto humano. Ambas están en el libro (Corke, 2023, p. 12) y se pueden acoger nombrándolas en una frase, pero no hay que abrirlas: cada una se come sola los diez minutos y ninguna se cierra bien con prisa. La fórmula que funciona es decir que están en el texto, que el libro las pone al mismo nivel, y que quien quiera puede llevarlas al seminario de artículos."));
children.push(h3("Cómo mantener la neutralidad sin parecer evasivo"));
children.push(p("La neutralidad que hay que sostener es sobre las conclusiones, no sobre el método ni sobre los hechos, y esa distinción es la que evita parecer evasivo. No digo qué hay que votar, pero sí digo que un argumento que ignora que los conductores humanos matan a más de un millón de personas al año está incompleto (Corke, 2023, p. 12). La pregunta directa, y usted qué opina, la hacen siempre, y la respuesta escurridiza de que no me corresponde suena a cobardía y desactiva el debate justo cuando estaba funcionando. Recomiendo contestar en dos tiempos. Primero, declarar la posición que sí es del profesor y además es la del libro, y declararla sin rodeos: estas cuestiones no pueden decidirse sólo por los roboticistas, pero tampoco pueden ser ignoradas por ellos (Corke, 2023, p. 12). Segundo, prometer la opinión personal para el final del debate y darla entonces, en una frase, marcándola explícitamente como opinión personal que no forma parte de la evaluación. El orden importa: en cuanto la clase sabe qué piensa el profesor, la mitad se alinea por deferencia y la otra mitad calla por prudencia, y los cinco minutos de intervenciones se vacían."));
children.push(h3("El estudiante con una posición extrema"));
children.push(p("Aparece en dos versiones simétricas, el tecnooptimismo absoluto, todo se automatizará y será mejor, y el rechazo total, la robótica destruye la sociedad, y las dos se manejan con la misma técnica. Lo primero que hay que tener claro es que ninguna se silencia ni se ridiculiza: el coste de silenciar a uno es que callen diez, y en un grupo de máster ese coste se paga durante todo el semestre. La secuencia es de tres pasos. Se reformula su posición en su versión más fuerte y se le pide confirmación de que se ha entendido bien, lo que le quita la necesidad de subir el tono, que casi siempre es lo que buscaba. Se le pide después la condición de falsación: qué dato le haría cambiar de opinión. Una posición que no admite ningún dato deja de ser un argumento, y la clase lo ve sin que el profesor tenga que decirlo, que es infinitamente mejor que decirlo. Y se devuelve el asunto al grupo en lugar de responderlo uno mismo, porque un profesor debatiendo con un estudiante convierte a los otros veintinueve en espectadores. Sólo hay un caso en que se corta, y es cuando la intervención roza lo ofensivo hacia un colectivo: se corta por la forma y no por el contenido, se recuerda la norma de respeto del aula en una frase, se ofrece continuar en el despacho y se sigue con el debate. Merece mención aparte el estudiante que aporta experiencia personal directa, un familiar cuyo puesto se automatizó: eso no es una posición extrema, es un dato, y merece un reconocimiento explícito antes de seguir adelante."));
children.push(h3("El límite con la política de partido"));
children.push(p("El debate tiene una salida lateral que conviene cerrar antes de que se abra. Empleo, automatización y regulación conectan de forma inmediata con programas electorales, y basta una alusión a un partido o a un gobierno concreto para que la discusión cambie de naturaleza: se pasa de argumentar a identificarse, y en el momento en que eso ocurre nadie cambia de opinión y el dato deja de tener efecto, con lo cual la segunda votación pierde todo su sentido. La regla que aplico y que anuncio al empezar es que se discuten políticas y no partidos: se puede defender que hay que regular el ritmo de despliegue de una tecnología, y no se puede decir quién lo propone. Cuando aparece, que aparecerá, la reconducción no es un reproche sino una traducción: se toma la intervención, se le quita la etiqueta partidista y se devuelve al aula convertida en el argumento que contenía. Hay dos razones para ser estricto con esto. La primera es la asimetría de autoridad: cualquier posición partidista del profesor pesa en el aula más de lo que debería, y eso vale también para los guiños. La segunda es práctica y muy real en un máster: con estudiantes internacionales en la sala, las referencias partidistas locales excluyen directamente a una parte del grupo de una conversación en la que queremos que participen todos."));
children.push(h3("Si la clase no habla"));
children.push(p("En este debate el silencio no significa falta de ideas, significa prudencia: nadie quiere quedar como el insensible que defiende despedir gente ni como el ludita que rechaza la tecnología que ha venido a estudiar. La maniobra correcta es despersonalizar, y la asignación cruzada del minuto en parejas ya lo hace, pero hay que insistir en la fórmula en voz alta: no defiendes tu opinión, defiendes la posición que te ha tocado. Si el silencio persiste, se pide por nombre a una pareja que lea su argumento del papel, porque leer protege mucho más que hablar y da un primer turno sin coste. El tercer recurso, si el grupo sigue trabado, consiste en que el profesor enuncie él mismo el argumento más flojo de uno de los bandos y pida a la clase que lo mejore: mejorar un argumento ajeno y malo es una tarea fácil, no compromete a nadie y produce inmediatamente material para las dos columnas de la pizarra."));
children.push(h3("Cierre"));
children.push(p("Se cierra con la posición del libro, casi literalmente y sin adornos: son cuestiones éticas profundas que no deben ni pueden decidirse sólo por los roboticistas, pero que tampoco deben ser ignoradas por ellos, y participar en el debate social es parte de la profesión (Corke, 2023, p. 12). Antes de eso conviene señalar físicamente el delta de votos escrito en la pizarra y nombrarlo: esto es lo que han hecho unos argumentos en diez minutos, y es la razón por la que este rato no era relleno. Lo que no conviene decir bajo ningún concepto es que cada uno tiene su opinión y todas son respetables, porque es el mensaje contrario al del libro y anula el trabajo hecho: el libro no dice que todas las posiciones valgan igual, dice que la decisión no es sólo de los ingenieros. Tampoco conviene cerrar con una broma sobre Terminator o sobre la rebelión de las máquinas, por tentador que resulte para bajar la tensión: devuelve el asunto a la ficción de la que hemos intentado sacarlo durante toda la sesión anterior (Corke, 2023, pp. 1-2). Y no conviene tranquilizar al grupo diciendo que esto no entra en el examen, porque sí entra en la forma que importa: entran la posición del libro y los argumentos de las páginas 11 y 12, y decirlo mantiene el debate dentro de la asignatura en lugar de convertirlo en una charla simpática de media hora."));

// Bibliografía
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Bibliografía citada en este bloque"));
children.push(bullet("Mechatronics: Fundamentals and Applications. CRC Press, 2016. Capítulo 1 (pp. 1-13): definición (p. 1), componentes y ejemplos (p. 2), modelado (p. 3), energía (p. 4), diseño no acoplado (p. 5), índice de diseño y ec. 1.2 (p. 6), MDQ y GA (pp. 7-8), evolución de diseño (pp. 8-9), instrumentación e historia (p. 10), aplicaciones (pp. 11-12).", "De Silva, C. W., Khoshnoud, F., Li, M. y Halgamuge, S. K. (eds.). "));
children.push(bullet("Robotics, Vision and Control: Fundamental Algorithms in Python. 3.ª ed., Springer, 2023. Capítulo 1 (pp. 1-19): historia (pp. 2-4), tipos de robots (pp. 4-7), definición y sensores (p. 8), visión robótica (pp. 9-10), ética (pp. 11-12).", "Corke, P. "));
children.push(bullet("Modern Robotics: Mechanics, Planning, and Control. Cambridge University Press, 2017. Capítulo 1 como lectura complementaria de contexto; se cita formalmente a partir del bloque 2.", "Lynch, K. M. y Park, F. C. "));
children.push(bullet("π0: A Vision-Language-Action Flow Model for General Robot Control. arXiv:2410.24164, 2024.", "Black, K. et al. (Physical Intelligence). "));
children.push(bullet("GR00T N1: An Open Foundation Model for Generalist Humanoid Robots. arXiv:2503.14734, 2025.", "NVIDIA. "));

const doc = new Document({
 numbering: numberingConfig,
 styles: { default: { document: { run: { font: F, size: 22 } } } },
 sections: [{ properties: { page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } }, children }],
});
Packer.toBuffer(doc).then(buf => { fs.writeFileSync("Apuntes_B1_Introduccion_Mecatronica.docx", buf); console.log("OK B1 v2"); });
