const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, PageBreak, AlignmentType } = require("docx");
const { IQS, F, p, pRuns, h1, h2, h3, bullet, box, tabla, tablaTiempos, numberingConfig, seg, punto } = require("./lib_iqs");

const children = [];

// ---------- Portada ----------
children.push(
 new Paragraph({ spacing: { before: 1900, after: 200 }, alignment: AlignmentType.CENTER,
 children: [new TextRun({ text: "Bloque 2", size: 40, bold: true, color: IQS.greenDark, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 },
 children: [new TextRun({ text: "Tipología de robots, cobots y humanoides. Seguridad y normativa", size: 44, bold: true, color: IQS.navy, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
 children: [new TextRun({ text: "82514, Mecatrónica y Robótica · IQS Universitat Ramon Llull", size: 24, color: IQS.grey, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
 children: [new TextRun({ text: "Apuntes del profesor con citas de fuente · Sesiones S5–S7 (18, 23 y 25 de septiembre de 2026) · 5 horas", size: 22, color: IQS.grey, font: F })] }),
 new Paragraph({ alignment: AlignmentType.CENTER,
 children: [new TextRun({ text: "Ediciones citadas: Corke (2023), Robotics, Vision and Control, 3.ª ed. Python, Springer · Lynch y Park (2017), Modern Robotics, Cambridge · normas ISO 10218:2025, ISO/TS 15066:2016 e ISO 12100:2010", size: 18, italics: true, color: IQS.grey, font: F })] }),
 new Paragraph({ children: [new PageBreak()] })
);

children.push(h1("Objetivos de aprendizaje y convenciones"));
children.push(bullet("Clasificar cualquier robot según las taxonomías de movilidad y función, y describir las configuraciones de manipuladores con los conceptos formales de configuración, grados de libertad, espacio de configuraciones, espacio de tareas y espacio de trabajo."));
children.push(bullet("Comparar las arquitecturas de locomoción de robots móviles, explicar la restricción no holonómica y distinguir AGV de AMR."));
children.push(bullet("Explicar la arquitectura de la ISO 10218:2025 (fabricante frente a integrador), los cuatro métodos de operación colaborativa y los pasos del análisis de riesgos."));
children.push(box("Cómo leer las citas", "Formato (Autor, año, p. X) sobre las ediciones de la carpeta de bibliografía: Corke (2023), cap. 1, pp. 1-19; cap. 4, pp. 127-160; cap. 7, pp. 251-290, y Lynch y Park (2017), cap. 2, pp. 11-40. Las normas se citan por su designación y, cuando procede, por cláusula; los datos de mercado o de actualidad sin página se apoyan en las fuentes sectoriales listadas en la bibliografía final. Las comillas «» marcan traducción casi literal. El guion de cada clase lista los puntos a tratar explícitamente en cada segmento; no es una transcripción."));

// ============================================================ S5
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Sesión S5 (vie 18 sep, 2 h), Taxonomía y configuraciones"));

children.push(h2("Guion de la clase"));
children.push(seg("0–10 min", "Repaso del cuestionario B1"));
children.push(punto("Comentar los dos o tres errores más frecuentes del cuestionario de S4 (típicamente: confundir la fórmula del MDQ con la función de coste J, y las fechas de Unimate/Kawasaki)."));
children.push(punto("Presentar el mapa del bloque: hoy clasificamos robots; el miércoles, los móviles; el viernes 25, seguridad."));
children.push(seg("10–35 min", "Teoría: las dos taxonomías (apdo. 5.1)"));
children.push(punto("Distinguir robots fijos de «primera generación» y robots móviles por tierra, aire y agua (Corke, 2023, p. 4)."));
children.push(punto("Enumerar la taxonomía funcional con la definición de cada clase: fabricación, servicio, campo (Corke, 2023, pp. 4-5) y humanoides como categoría transversal, «son a la vez robots móviles y robots de servicio» (Corke, 2023, p. 5)."));
children.push(punto("Leer la definición de robot de fabricación (Corke, 2023, p. 6) y extraer su lógica económica: piezas presentadas de forma ordenada → velocidad y precisión máximas."));
children.push(punto("Seguridad por exclusión (jaula) frente a cobots que «operan a baja velocidad y se detienen ante una obstrucción» (Corke, 2023, p. 6); anticipar que S7 convierte esta diferencia en normativa."));
children.push(punto("Los dos retos de campo y servicio (Corke, 2023, p. 7): entorno complejo, desordenado y cambiante; y operar con seguridad entre personas, construir la «escalera de intimidad física» (entre personas → con personas dentro → dentro de personas)."));
children.push(punto("Dinámica: proyectar 6-8 fotos de robots reales y que la clase los clasifique en ambas taxonomías antes de dar la respuesta."));
children.push(seg("35–65 min", "Teoría: configuraciones de manipuladores (apdo. 5.2)"));
children.push(punto("Definir formalmente configuración, grados de libertad y espacio de configuraciones leyendo la Definición 2.1 (Lynch y Park, 2017, p. 12); ilustrar con la puerta (1 gdl) y la moneda sobre la mesa (3 gdl) (Lynch y Park, 2017, pp. 11-12)."));
children.push(punto("Articulaciones: rotativas (R) y prismáticas (P) como las relevantes en robótica; de tornillo, cilíndricas y esféricas «son raras» (Corke, 2023, p. 255)."));
children.push(punto("Presentar el manipulador serie: articulaciones en cadena, cada una soporta y mueve todas las exteriores (Corke, 2023, p. 254); con N articulaciones hay N+1 eslabones (Corke, 2023, p. 260)."));
children.push(punto("Recorrer las configuraciones con la fig. 7.2 (Corke, 2023, p. 255): brazo articulado de 6 gdl de propósito general (los Mitsubishi y ABB del laboratorio), SCARA de 4 gdl para ensamblado electrónico, pórtico (gantry) con prismáticas x-y-z y gran volumen de trabajo, y manipulador paralelo con los motores en la base."));
children.push(punto("SCARA: rígido en vertical y flexible en el plano horizontal, ventaja para tareas planas como el montaje de placas (Corke, 2023, p. 254); su tercera articulación es prismática (Corke, 2023, p. 260)."));
children.push(punto("Hito: PUMA 560 (1978), «el primer robot industrial moderno», diseño antropomórfico, motores eléctricos y muñeca esférica (Corke, 2023, p. 261); vocabulario antropomórfico cintura-hombro-codo-muñeca ↔ articulaciones 0, 1, 2 y 3-5 (Corke, 2023, p. 261)."));
children.push(punto("Definir espacio de tareas (donde la tarea se expresa naturalmente; lo decide la tarea) y espacio de trabajo (configuraciones alcanzables por el efector; lo decide la estructura) (Lynch y Park, 2017, pp. 32-33)."));
children.push(punto("Repetibilidad frente a exactitud: la repetibilidad es la dispersión al volver a un punto programado y es la cifra que dan los catálogos de los fabricantes; la exactitud, el error respecto a una pose absoluta, suele ser peor y es la relevante en programación fuera de línea (basado en hojas de datos de fabricantes; sin cita de libro)."));
children.push(seg("65–75 min", "Descanso"));
children.push(punto("Pausa."));
children.push(seg("75–95 min", "Teoría: espectro de autonomía (apdo. 5.3)"));
children.push(punto("Recuperar de S3 los cuatro escalones y formalizarlos: teleoperación, control alternado, control compartido (Corke, 2023, pp. 7-8) y autonomía supervisada con el ejemplo del rover y la latencia (Corke, 2023, p. 7)."));
children.push(punto("Insistir en la precisión de S3: cirugía robótica y ROV son teleoperación (Corke, 2023, p. 7)."));
children.push(punto("Preguntas de calibración a mano alzada: dron FPV, taxi autónomo, brazo del laboratorio."));
children.push(seg("95–115 min", "Actividad en equipos: fichas de clasificación"));
children.push(punto("Repartir 6 fichas por equipo (robot industrial articulado, cobot, AMR de almacén, humanoide, robot quirúrgico, dron de inspección)."));
children.push(punto("Para cada ficha el equipo anota: taxonomía por movilidad y por función, configuración cinemática si aplica (con gdl), y posición en el espectro de autonomía."));
children.push(punto("Puesta en común: un portavoz por equipo defiende la ficha más discutida; corregir con las definiciones citadas."));
children.push(seg("115–120 min", "Cierre"));
children.push(punto("Abrir la formación de equipos del proyecto integrador (cierre definitivo en S7)."));
children.push(punto("Encargar lectura para S6: Corke (2023), cap. 4, pp. 139-146 (vehículos diferenciales y omnidireccionales)."));

children.push(h2("5.1. Dos taxonomías complementarias"));
children.push(p("La primera clasificación es por movilidad. Los robots de «primera generación» estaban fijos en su emplazamiento, mientras que los robots móviles se desplazan por el mundo: mediante ruedas o patas en tierra, alas fijas o múltiples rotores en el aire, o desplazándose por o bajo la superficie del agua (Corke, 2023, p. 4). La segunda clasificación es funcional (Corke, 2023, pp. 4-5): los robots de fabricación (manufacturing robots) operan en fábricas y son los descendientes tecnológicos de los primeros robots de Unimation; los robots de servicio prestan servicios a personas, limpieza, cuidado personal, rehabilitación médica, o recoger y entregar objetos; los robots de campo (field robots) trabajan a la intemperie en tareas como monitorización ambiental, agricultura, minería, construcción y silvicultura; y los robots humanoides tienen la forma física de un ser humano y «son a la vez robots móviles y robots de servicio» (Corke, 2023, p. 5), las categorías no son excluyentes, y conviene decirlo antes de que los estudiantes intenten encajar cada robot en una sola casilla."));
children.push(p("La definición de robot de fabricación encierra la lógica económica del sector: es «típicamente un manipulador de tipo brazo sobre una base fija» que «realiza tareas repetitivas dentro de una célula de trabajo local», donde «las piezas se presentan al robot de forma ordenada, lo que maximiza la ventaja de la alta velocidad y precisión del robot» (Corke, 2023, p. 6). Esa velocidad y precisión implican peligro: los robots rápidos se hacen seguros excluyendo a las personas de su espacio de trabajo, típicamente situando el robot dentro de una jaula (Corke, 2023, p. 6). Los robots colaborativos invierten el planteamiento: «son seguros para el ser humano: operan a baja velocidad y se detienen cuando encuentran una obstrucción» (Corke, 2023, p. 6). La diferencia, que en S7 convertiremos en categorías normativas, es también una decisión de diseño mecatrónico: el cobot sustituye vallado por sensórica, limitación de esfuerzos y control."));
children.push(p("Los robots de campo y de servicio afrontan dos retos que el robot enjaulado no tiene (Corke, 2023, p. 7): primero, operar y moverse en un entorno complejo, desordenado y cambiante, el ejemplo del libro es el robot de reparto hospitalario abriéndose paso entre personas y carritos, y el rover planetario sin mapa local preciso; segundo, operar con seguridad en presencia de personas: el robot de reparto circula entre ellas, el coche robótico las lleva dentro y el dispositivo quirúrgico opera dentro de ellas (Corke, 2023, p. 7). Esta «escalera de intimidad física» explica por qué la percepción (bloque 6) y la seguridad (S7) dominan la agenda de la robótica moderna."));

children.push(h2("5.2. Configuraciones de manipuladores y conceptos formales"));
children.push(p("Antes de clasificar brazos conviene fijar el vocabulario formal, que tomaremos de Lynch y Park y reutilizaremos durante todo el bloque 4. «La configuración de un robot es una especificación completa de la posición de cada punto del robot. El número mínimo n de coordenadas de valor real necesarias para representar la configuración es el número de grados de libertad (gdl) del robot. El espacio n-dimensional que contiene todas las configuraciones posibles del robot se llama espacio de configuraciones (C-space)» (Definición 2.1; Lynch y Park, 2017, p. 12). Los ejemplos introductorios del libro son útiles en el aula: una puerta tiene un grado de libertad (su ángulo de bisagra) y una moneda sobre una mesa tiene tres (dos coordenadas de posición y una de orientación); el número de gdl es «el menor número de coordenadas de valor real» necesarias, y variables discretas como cara/cruz no cuentan (Lynch y Park, 2017, pp. 11-12)."));
children.push(p("Un manipulador serie es una cadena de eslabones rígidos conectados por articulaciones actuadas; las articulaciones relevantes en robótica son las rotativas (revolute) y las prismáticas (lineales), mientras que otros tipos, de tornillo, cilíndricas de 2 gdl o esféricas de 3 gdl, «son raras en robótica» (Corke, 2023, p. 255). En los manipuladores serie «las articulaciones están conectadas en serie» y «cada articulación tiene que soportar y mover todas las articulaciones situadas entre ella y el efector final» (Corke, 2023, p. 254); un manipulador serie con N articulaciones tiene N+1 eslabones, siendo el eslabón 0 la base (Corke, 2023, p. 260). En contraste, «un manipulador de eslabones paralelos tiene todos los motores en la base» conectados al efector por varias cadenas cerradas (Corke, 2023, p. 254), de ahí su poca inercia móvil y su velocidad."));
children.push(p("Sobre ese vocabulario, el catálogo de configuraciones que presenta la figura 7.2 del libro (Corke, 2023, p. 255): (a) el manipulador industrial de propósito general de 6 gdl, «lo más común es el brazo manipulador de seis grados de libertad que comprende una serie de eslabones rígidos y seis articulaciones rotativas actuadas» (Corke, 2023, p. 254), la configuración de los Mitsubishi y ABB del laboratorio y la que usaremos en el bloque 4; (b) el SCARA (Selective Compliance Assembly Robot Arm), de 4 gdl, «rígido en la dirección vertical y flexible en el plano horizontal, lo que es ventajoso para tareas planas como el ensamblado de placas de circuito electrónico» (Corke, 2023, p. 254), con tercera articulación prismática (Corke, 2023, p. 260); (c) el robot pórtico (gantry), que se mueve sobre raíles elevados con articulaciones prismáticas en x, y y z, «lo que le da un volumen de trabajo muy grande» (Corke, 2023, pp. 254 y 260); y (d) el manipulador paralelo, cuyo efector está accionado por seis eslabones paralelos en el ejemplo del libro (Corke, 2023, p. 255)."));
children.push(box("Hito histórico para el aula", "El PUMA 560, lanzado en 1978, «fue el primer robot industrial moderno», con «diseño antropomórfico, motores eléctricos y una muñeca esférica: el arquetipo de todo lo que siguió» (Corke, 2023, p. 261). De él heredamos también el vocabulario antropomórfico: cintura, hombro, codo y muñeca corresponden a las articulaciones 0, 1, 2 y 3-5 (Corke, 2023, p. 261). Hay un PUMA en el Smithsonian; el Stanford Arm, con su tercera articulación prismática, también (Corke, 2023, pp. 260-261)."));
children.push(p("Dos conceptos más cierran el aparato formal (Lynch y Park, 2017, pp. 32-33): el espacio de tareas es «un espacio en el que la tarea del robot puede expresarse de forma natural», si la tarea es dibujar con un bolígrafo sobre papel, el plano R², y su definición «la decide la tarea, independientemente del robot»; el espacio de trabajo es «una especificación de las configuraciones que el efector final del robot puede alcanzar», y su definición «la decide principalmente la estructura del robot, independientemente de la tarea». Ambos se refieren al efector, no al robot completo. Añadimos la distinción práctica de catálogo, que no procede de estos libros sino de las hojas de datos de los fabricantes: la repetibilidad, dispersión al volver a un mismo punto programado, la cifra que anuncia el catálogo, y la exactitud, error respecto a una pose absoluta ordenada, generalmente peor y crítica cuando se programa fuera de línea."));

children.push(h2("5.3. El espectro de autonomía"));
children.push(p("Formalizamos lo apuntado en S3 como un espectro de cuatro escalones. En un extremo, la teleoperación pura: el humano controla y el telerobot ejecuta, como en los ROV que exploraron el Titanic o en la cirugía robótica actual (Corke, 2023, p. 7). Los dos escalones intermedios son el control alternado (traded control), en el que «la función de control pasa de un lado a otro entre el humano y el computador», el piloto que conecta el piloto automático, y el control compartido (shared control), en el que ambos controlan simultáneamente, el coche que mantiene el carril mientras el conductor gestiona la velocidad, (Corke, 2023, pp. 7-8). En el extremo de autonomía supervisada están los rovers marcianos: navegan de forma autónoma en lo local porque la latencia de comunicación de varios minutos lo exige, mientras los operadores en la Tierra fijan objetivos de alto nivel (Corke, 2023, p. 7). El caso incómodo que conviene provocar en el aula: el brazo industrial ejecutando un programa no percibe ni planifica; medido con la definición de robot de Corke (2023, p. 8), es más «automatización programable» que robot, y esa tensión es productiva, no un defecto de la definición."));

// ============================================================ S6
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Sesión S6 (mié 23 sep, 1 h), Robots móviles"));

children.push(h2("Guion de la clase"));
children.push(seg("0–5 min", "Recuperación de S5"));
children.push(punto("Pedir a dos estudiantes que dibujen en la pizarra un SCARA y un articulado de 6 gdl con sus espacios de trabajo; corregir con la fig. 7.2 (Corke, 2023, p. 255)."));
children.push(seg("5–25 min", "Teoría: locomoción con ruedas (apdo. 6.1)"));
children.push(punto("Partir de la observación de Corke: el vehículo tipo coche tiene ruedas directrices «mecánicamente complejas»; la tracción diferencial es la alternativa simple (Corke, 2023, p. 140)."));
children.push(punto("Tracción diferencial: dos ruedas motrices independientes, modelo uniciclo (Corke, 2023, p. 142); puede girar sobre sí misma pero no desplazarse lateralmente (Corke, 2023, p. 154)."));
children.push(punto("Dirección Ackermann (Corke, 2023, p. 132): geometría del coche; radio de giro mínimo; introducir la restricción no holonómica con la fig. 4.26: «el coche no puede moverse directamente del círculo a la estrella» (Corke, 2023, p. 153)."));
children.push(punto("Formalizar restricción no holonómica: restricción de velocidad no integrable que «reduce la dimensión de las velocidades factibles pero no la del C-space alcanzable» (Lynch y Park, 2017, p. 32); vehículo subactuado que debe maniobrar (Corke, 2023, p. 154)."));
children.push(punto("Ruedas omnidireccionales: los dos tipos de rueda con rodillos (una rueda que puede rodar lateralmente y otra que puede impulsarse lateralmente; Corke, 2023, p. 144) y el ejemplo del KUKA youBot con cuatro ruedas mecanum (Corke, 2023, p. 145): holonómico en el plano."));
children.push(punto("Orugas / skid-steer: como el diferencial, subactuado; «puede girar sobre el sitio pero no moverse lateralmente» (Corke, 2023, p. 154); añadir el coste práctico: el giro por deslizamiento degrada la odometría (experiencia de laboratorio; sin cita de libro)."));
children.push(seg("25–40 min", "Teoría: AGV frente a AMR; aire (apdos. 6.2 y 6.3)"));
children.push(punto("Definir AGV (sigue infraestructura física: filoguiado, banda magnética, balizas; ruta fija; se detiene ante obstáculos) y AMR (navega con mapa propio construido por SLAM, planifica y rodea; el vehículo se adapta al entorno), distinción de práctica industrial, apoyada en las fuentes sectoriales de la bibliografía."));
children.push(punto("Subrayar la lectura mecatrónica: mismo chasis y sensores, distinto software; la diferencia es el stack de navegación que veremos con Nav2 en B7."));
children.push(punto("Multirrotores: notación del cuadrirrotor con sus cuatro rotores y vectores de empuje (Corke, 2023, p. 147); ventajas (vuelo estacionario, simplicidad mecánica) frente a ala fija (cobertura de área)."));
children.push(punto("Patas: ganan al terreno discontinuo a costa de equilibrio y consumo; su viabilidad reciente debe tanto a actuadores y baterías como al aprendizaje por refuerzo aplicado a locomoción (se desarrolla en B8)."));
children.push(seg("40–55 min", "Ejercicio guiado: selección de plataforma"));
children.push(punto("Tres escenarios: intralogística de almacén, reparto interno hospitalario, monitorización de viñedo."));
children.push(punto("Cada pareja elige plataforma (locomoción + sensórica + grado de autonomía) y justifica con los conceptos de la sesión (holonomía, terreno, entorno con personas)."));
children.push(punto("Puesta en común: exigir que cada justificación nombre al menos una restricción (p. ej., «no holonómico → pasillos estrechos requieren maniobra»)."));
children.push(seg("55–60 min", "Cierre"));
children.push(punto("Anunciar S7 (2 h de seguridad y normativa) y recordar el cierre de equipos del proyecto."));
children.push(punto("Lectura opcional: Corke (2023), cap. 4, pp. 147-155 (cuadrirrotor y discusión de holonomía)."));

children.push(h2("6.1. Locomoción con ruedas y la restricción no holonómica"));
children.push(p("El punto de partida del capítulo de vehículos de Corke es una observación de diseño: «un vehículo tipo coche tiene ruedas directrices que son mecánicamente complejas», y la alternativa simple es la dirección diferencial (Corke, 2023, p. 140). El vehículo de tracción diferencial lleva dos ruedas motrices accionadas independientemente (más apoyos pasivos), y su cinemática se captura con el modelo de uniciclo (Corke, 2023, p. 142): girando ambas ruedas a la misma velocidad avanza, y con velocidades opuestas gira sobre su propio eje. Es la arquitectura de la mayoría de las plataformas móviles de interior y la que modelaremos en el bloque 4 por ser la más simple."));
children.push(p("El vehículo tipo coche usa la geometría de dirección de Ackermann (Corke, 2023, p. 132), que le da estabilidad a velocidad y un radio de giro mínimo, pero introduce la restricción característica de los coches: «el coche no puede moverse directamente del círculo a la estrella debido a la restricción no holonómica» (Corke, 2023, p. 153, fig. 4.26), no existe movimiento lateral puro. La formalización es de Lynch y Park: una restricción de velocidad no integrable se llama restricción no holonómica, y «reduce la dimensión de las velocidades factibles del sistema pero no reduce la dimensión del C-space alcanzable» (Lynch y Park, 2017, p. 32): el coche puede alcanzar cualquier configuración, pero a veces solo por un camino indirecto, la maniobra. Corke añade la conexión con la actuación: «un vehículo de dirección diferencial o por deslizamiento, como un tanque, también está subactuado: tiene solo dos actuadores… puede girar sobre el sitio pero no puede moverse lateralmente»; esa necesidad de maniobrar «es la firma clara de un sistema subactuado» (Corke, 2023, p. 154). Esta restricción condicionará la planificación de trayectorias en el bloque 7."));
children.push(p("La locomoción omnidireccional elimina la restricción a costa de mecánica: existen dos tipos de rueda con rodillos periféricos, una que permite a la rueda rodar lateralmente y otra que le permite impulsarse lateralmente (Corke, 2023, p. 144); la rueda mecanum descompone la velocidad en la componente de giro de la rueda y la de rodadura de los rodillos (Corke, 2023, pp. 144-145, ec. 4.14). Con cuatro ruedas mecanum, como el KUKA youBot del libro (Corke, 2023, p. 145), la plataforma es holonómica en el plano: puede trasladarse en cualquier dirección mientras rota. El precio: sensibilidad al estado del suelo y menor capacidad de carga por rueda, de nuevo un compromiso de diseño mecatrónico, no una solución universalmente superior."));

children.push(h2("6.2. AGV frente a AMR"));
children.push(p("La distinción práctica más relevante hoy en intralogística no está en la mecánica sino en el software. El AGV (Automated Guided Vehicle) sigue una infraestructura física instalada para él, filoguiado, banda magnética, balizas reflectantes, recorre rutas fijas y ante un obstáculo se detiene: el entorno se adapta al vehículo. El AMR (Autonomous Mobile Robot) construye y mantiene un mapa del entorno mediante SLAM (bloque 6), se localiza en él, planifica rutas y rodea obstáculos (con las herramientas que veremos en el bloque 7): el vehículo se adapta al entorno. Esta caracterización es de práctica industrial, los libros de la asignatura no usan la pareja AGV/AMR, y se apoya en las fuentes sectoriales listadas en la bibliografía. La lectura mecatrónica que quiero que los estudiantes se lleven: el chasis (tracción diferencial) y el sensor principal (LiDAR) pueden ser idénticos en ambos; treinta años de progreso en percepción y planificación separan uno de otro, y son exactamente los contenidos de los bloques 6 y 7."));

children.push(h2("6.3. Aire, patas y agua"));
children.push(p("En el aire, la plataforma dominante en robótica es el multirrotor. La notación estándar del cuadrirrotor, cuatro rotores con sus vectores de empuje y sentidos de giro alternados, y su modelo dinámico están en Corke (2023, p. 147 y ss.); el control de actitud se consigue aplicando momentos mediante empuje diferencial de los rotores (Corke, 2023, p. 152). Sus ventajas prácticas son el vuelo estacionario y la simplicidad mecánica; el ala fija lo supera en cobertura de área y autonomía. Bajo el agua conviven los ROV teleoperados, los del Titanic de S3 (Corke, 2023, p. 7), y los AUV autónomos. En tierra, las patas ganan donde las ruedas pierden, escaleras, escombros, terreno discontinuo, a costa de equilibrio dinámico, muchas articulaciones actuadas y consumo; la viabilidad comercial reciente de cuadrúpedos y humanoides debe tanto a actuadores y baterías como al aprendizaje por refuerzo aplicado a la locomoción, que veremos en el bloque 8 con las referencias de la ola «Physical AI» citadas en el bloque 1. Todos comparten la anatomía percibir-planificar-actuar (Corke, 2023, p. 8) con sensórica adaptada al medio."));

// ============================================================ S7
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Sesión S7 (vie 25 sep, 2 h), Cobots, seguridad y normativa"));

children.push(h2("Guion de la clase"));
children.push(seg("0–10 min", "Recuperación de S6"));
children.push(punto("Preguntas orales: ¿qué es una restricción no holonómica (Lynch y Park, 2017, p. 32)? ¿En qué se diferencian AGV y AMR?"));
children.push(seg("10–40 min", "Teoría: marco normativo (apdo. 7.1)"));
children.push(punto("Presentar la ISO 10218 «Robotics, Safety requirements» y su revisión de 2025; estructura en dos partes: parte 1 dirigida al fabricante del robot, parte 2 al integrador de la aplicación."));
children.push(punto("Idea clave 1: comprar un robot «seguro» no hace segura la célula; la seguridad es una propiedad de la aplicación integrada, y la evaluación de riesgos es responsabilidad del integrador (ISO 10218-2:2025)."));
children.push(punto("Idea clave 2: «cobot» no es una categoría legal sino una aplicación colaborativa; la revisión de 2025 integró en la ISO 10218 los requisitos de operación colaborativa que estaban en la ISO/TS 15066:2016, que sigue siendo la referencia de los valores límite biomecánicos por región corporal."));
children.push(punto("Ejemplo provocador para discusión: un brazo de fuerza limitada con una herramienta cortante no constituye una aplicación colaborativa segura; un robot industrial clásico puede participar en una célula colaborativa correctamente salvaguardada."));
children.push(punto("Aclarar el papel del profesor/alumno frente a la norma: no memorizar cláusulas; entender la arquitectura y la división de responsabilidades."));
children.push(seg("40–70 min", "Teoría: métodos de operación colaborativa (apdo. 7.2)"));
children.push(punto("Presentar los cuatro métodos (ISO/TS 15066:2016, cl. 5.5): parada monitorizada de seguridad, guiado manual, monitorización de velocidad y separación, y limitación de potencia y fuerza."));
children.push(punto("Para cada método: en qué consiste, qué tecnología lo habilita y un caso de uso típico (turnos de carga; programación por demostración; célula sin vallado con escáner certificado; contacto admisible con cobot)."));
children.push(punto("Proyectar un vídeo corto por método y pedir a la clase que identifique cuál es antes de nombrarlo."));
children.push(punto("Cerrar con dos matices: los métodos se combinan en una misma célula, y la velocidad reducida tiene coste de productividad, elegir método es una decisión de diseño con el espíritu del MDQ del bloque 1 (De Silva et al., 2016, p. 7)."));
children.push(seg("70–80 min", "Descanso"));
children.push(punto("Pausa."));
children.push(seg("80–110 min", "Taller: análisis de riesgos (apdo. 7.3)"));
children.push(punto("Presentar los cinco pasos del proceso (según ISO 12100:2010 e ISO 10218-2:2025): límites de la aplicación; identificación de peligros por tarea, incluidos los modos degradados; estimación del riesgo; reducción según la jerarquía eliminar-proteger-informar; validación y documentación."));
children.push(punto("Encargo por equipos: célula con el robot ABB del laboratorio y carga/descarga manual de piezas; entregable: tabla de riesgos de seis filas (peligro, tarea, estimación, medida, método colaborativo si aplica)."));
children.push(punto("Durante el trabajo, pasar por los equipos forzando la pregunta de los modos degradados: limpieza, mantenimiento, recuperación de fallos."));
children.push(punto("Corrección en común de dos tablas: es la síntesis del bloque."));
children.push(seg("110–120 min", "Cierre del bloque"));
children.push(punto("Cuestionario de seguimiento B2 (8-10 preguntas): taxonomías (Corke pp. 4-7), Definición 2.1 (Lynch y Park p. 12), configuraciones (Corke pp. 254-255), no holonomía (Lynch y Park p. 32), partes de la ISO 10218 y los cuatro métodos colaborativos."));
children.push(punto("Cerrar equipos del proyecto integrador y publicar la asignación."));

children.push(h2("7.1. El marco normativo: ISO 10218:2025"));
children.push(p("La seguridad de los robots industriales se rige por la norma ISO 10218, «Robotics, Safety requirements», publicada en su revisión profunda en 2025 en dos partes: la ISO 10218-1:2025 establece los requisitos del robot como componente, funciones de parada de seguridad, límites de eje, modos de operación, y se dirige al fabricante; la ISO 10218-2:2025 establece los requisitos de la aplicación robótica completa, disposición de la célula, resguardos, dispositivos de protección, validación, y se dirige al integrador. Esta división de responsabilidades es el concepto más importante que un futuro ingeniero debe llevarse: comprar un robot certificado no hace segura la célula, porque la seguridad es una propiedad de la aplicación integrada, y la evaluación de riesgos de la aplicación es obligación del integrador (ISO 10218-2:2025), el papel profesional que muchos de nuestros egresados desempeñarán."));
children.push(p("La revisión de 2025 incorporó a la propia ISO 10218 los requisitos de operación colaborativa que hasta entonces vivían en la especificación técnica ISO/TS 15066:2016, «Robots and robotic devices, Collaborative robots», que sigue siendo la referencia para los valores límite biomecánicos: los umbrales de fuerza y presión admisibles en caso de contacto, tabulados por región corporal en su anexo A. De aquí se deriva el segundo mensaje clave de la sesión: «cobot» no es una categoría legal de robot, sino una propiedad de la aplicación. Un brazo de fuerza limitada equipado con una herramienta cortante no constituye una aplicación colaborativa segura, y un robot industrial clásico puede participar en una aplicación colaborativa si la célula incorpora las salvaguardas adecuadas. El robot se certifica; la aplicación se valida."));

children.push(h2("7.2. Los cuatro métodos de operación colaborativa"));
children.push(p("La ISO/TS 15066:2016 (cláusula 5.5) define cuatro métodos de operación colaborativa, hoy integrados en la ISO 10218:2025. Primero, la parada monitorizada de seguridad (safety-rated monitored stop): el robot ejecuta una parada segura supervisada cuando una persona entra en el espacio colaborativo y reanuda el movimiento cuando sale; es colaboración por turnos, la forma más simple. Segundo, el guiado manual (hand guiding): el operador mueve el robot aplicando fuerza directamente, con el robot compensando su propio peso; es la base de la programación por demostración. Tercero, la monitorización de velocidad y separación (speed and separation monitoring): el sistema vigila en tiempo real la distancia entre robot y persona y modula la velocidad, hasta detenerse, de modo que el contacto nunca llegue a producirse; requiere sensórica de seguridad certificada (escáneres láser, visión de seguridad) y habilita células sin vallado con robots rápidos. Cuarto, la limitación de potencia y fuerza (power and force limiting): se admite el contacto físico, pero fuerza, par y presión se mantienen por debajo de los umbrales biomecánicos del anexo A de la ISO/TS 15066; es el método que popularizaron los cobots con medición de par en las articulaciones, los robots que «operan a baja velocidad y se detienen cuando encuentran una obstrucción» de la descripción de Corke (2023, p. 6)."));
children.push(p("Dos matices de ingeniería que conviene explicitar. Los métodos se combinan: una célula real puede usar monitorización de velocidad y separación durante la aproximación y limitación de potencia y fuerza en la zona de entrega. Y la seguridad tiene coste de productividad: la velocidad reducida y las paradas penalizan el ritmo de la célula, de modo que elegir método colaborativo es una decisión de diseño con variables técnicas, económicas y humanas, la lógica de optimización multiobjetivo del MDQ del bloque 1 (De Silva et al., 2016, p. 7) aplicada a la seguridad."));

children.push(h2("7.3. El análisis de riesgos en cinco pasos"));
children.push(p("El proceso que exige la normativa sigue la metodología general de seguridad de máquinas de la ISO 12100:2010, particularizada para aplicaciones robóticas por la ISO 10218-2:2025. Los cinco pasos que los equipos aplicarán en el taller: (1) determinar los límites de la aplicación: espacio, tareas, quién interactúa con el sistema y cómo; (2) identificar los peligros tarea por tarea, atrapamiento, impacto, aplastamiento, peligros de la herramienta, proyección de piezas, incluyendo de forma explícita los modos degradados: limpieza, mantenimiento y recuperación de fallos, que es donde se concentran los accidentes reales; (3) estimar el riesgo de cada peligro combinando severidad del daño, exposición y probabilidad de evitación; (4) reducir el riesgo siguiendo la jerarquía obligatoria: eliminar por diseño, después proteger con resguardos y dispositivos, y solo en último lugar informar con señalización y formación; (5) validar que las medidas funcionan y documentarlo. El entregable del taller, una tabla de riesgos de seis filas sobre la célula del laboratorio, ejercita el proceso completo a escala reducida, y su corrección en común es la mejor síntesis del bloque."));
children.push(box("Conexión con el laboratorio", "En las prácticas con los robots Mitsubishi y ABB, la primera sesión incluye las normas de seguridad del aula-taller. Estos apuntes dan el marco conceptual; las normas concretas del laboratorio, ya establecidas, son de obligado cumplimiento y no se modifican en esta programación."));

// ============================================================ Guía de discusiones
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Guía de conducción de las discusiones de este bloque"));
children.push(p("El método general de conducción de discusiones, la regla de los diez segundos de silencio, la diferencia entre pregunta cerrada de recuperación y pregunta abierta de discusión, la votación a mano alzada antes y después, el trato del estudiante que monopoliza y del que no habla nunca, qué hacer con una respuesta errónea y cómo cerrar sin dejar la sensación de que todo vale, está desarrollado en los apuntes del bloque 1 y vale para todo el curso; no se repite aquí. Lo que sigue son las cuatro discusiones concretas que los guiones de S5 y S7 planifican, cada una con su objetivo, su reparto de minutos dentro del tramo que ya fija el guion, la formulación literal de la pregunta de apertura, las respuestas que van a salir y qué hacer con cada una, los desvíos previsibles, la maniobra de rescate si el grupo no habla y el cierre. Hay una diferencia de contexto respecto al bloque 1 que condiciona las cuatro: S5 y S7 son sesiones de dos horas, de modo que el cansancio es un factor real y las maniobras de rescate tienen que exigir menos energía al final que al principio."));
children.push(box("Los cinco mecanismos que se repiten", "Diez segundos de silencio tras la pregunta, sin reformular. Votación a mano alzada o con los dedos, contada en voz alta y escrita en la pizarra. Un minuto en parejas antes de pedir la voz a quien no habla. Pregunta dirigida por nombre y formulada en plural, sobre lo que se ha dicho en la pareja o en el equipo. Y cierre siempre con una posición del profesor, separando lo que queda decidido por la fuente de lo que queda legítimamente abierto."));

children.push(h2("Las preguntas de calibración a mano alzada de S5 (88–95 min)"));
children.push(h3("Objetivo"));
children.push(p("El objetivo es comprobar, con tres casos y en pocos minutos, si el espectro de cuatro escalones del apartado 5.3 se ha convertido en criterio operativo, y hacer visible la dispersión del grupo justo antes de la actividad de fichas, que es donde ese criterio se va a aplicar en serio seis veces seguidas. La diferencia con la teoría es de función y no de contenido: el apartado 5.3 ya recorre los cuatro escalones con sus citas (Corke, 2023, pp. 7-8) y ya avisa del caso incómodo del brazo industrial medido con la definición de robot (Corke, 2023, p. 8); lo que la calibración añade es el dato de en qué escalón coloca cada uno los tres casos, y sobre todo el desacuerdo público, que es lo que motiva la actividad siguiente. Conviene tener presente que los tres casos son deliberadamente los mismos que se discutieron en S3: la repetición no es descuido, permite comparar lo que la clase decía cuando las etiquetas eran informales con lo que dice ahora que están formalizadas, y merece decirse en voz alta."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 75 a 95 minutos está asignado al espectro de autonomía, y la calibración ocupa su último tercio. De 75 a 88, la exposición del apartado 5.3, terminando con los cuatro escalones escritos en la pizarra como cuatro columnas numeradas: uno, teleoperación; dos, control alternado; tres, control compartido; cuatro, autonomía supervisada. De 88 a 90, primer caso, el dron FPV: se vota con los dedos, todos a la vez a la señal, se cuenta por columnas y se pide la razón a alguien de la columna mayoritaria y a alguien de una minoritaria. De 90 a 92, el taxi autónomo con la misma mecánica. De 92 a 95, el brazo del laboratorio y el cierre en una frase que enlaza con la actividad de fichas. La votación con los dedos en lugar de manos arriba es una decisión deliberada para esta sesión concreta: con cuatro opciones obliga a elegir una, se cuenta igual de rápido y permite participar sin hablar a un grupo que lleva hora y media sentado."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con los cuatro escalones ya escritos: «Tenemos los cuatro escalones en la pizarra. Voy a nombrar tres máquinas y quiero que votéis con los dedos, todos a la vez cuando yo diga tres: un dedo si es teleoperación, dos si es control alternado, tres si es control compartido y cuatro si es autonomía supervisada. Primera máquina: un dron FPV pilotado por radio. Tres, dos, uno.» La cuenta atrás no es teatro gratuito: es lo que evita que la clase mire primero la mano del vecino, y sin ella el recuento no mide nada. Después de cada recuento, la pregunta que hay que hacer es siempre la misma: «tú has votado tres, dime en una frase por qué», y no «alguien quiere explicar su voto»."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "Dron FPV: mayoría de unos, algunos treses. ", bold: true },
 { text: "Los treses tienen razón y son la respuesta que hay que desarrollar. La estabilización de actitud la ejerce el controlador de vuelo mientras el piloto manda consignas, y eso es literalmente control compartido en el sentido del libro, donde humano y computador ejercen el control simultáneamente, igual que el coche que mantiene el carril mientras el conductor gestiona la velocidad (Corke, 2023, pp. 7-8). El rendimiento de esta respuesta es que convierte el «depende del modo de vuelo» en la idea que la sesión necesita: el escalón no lo fija la máquina, lo fija la configuración de la tarea." },
]));
children.push(pRuns([
 { text: "Taxi autónomo: mayoría de cuatros, algunos treses. ", bold: true },
 { text: "Se acepta el cuatro y se corrige el supuesto, que es que cuatro signifique ausencia de humanos. El objetivo de alto nivel lo pone el pasajero, exactamente como los operadores en la Tierra fijan objetivos al rover marciano mientras éste navega solo en lo local porque la latencia de varios minutos lo exige (Corke, 2023, p. 7). Autonomía supervisada es la categoría correcta y no un escalón por debajo de un ideal." },
]));
children.push(pRuns([
 { text: "Brazo del laboratorio: unos y cuatros a la vez. ", bold: true },
 { text: "Es el reparto habitual y es el resultado interesante, así que no hay que resolverlo por votación. Lo que hay que hacer es nombrar en voz alta la razón de cada bando: quien vota uno está pensando en el operador que programó los puntos, y quien vota cuatro está pensando en el ciclo funcionando solo por la noche. Y de ahí al punto del apartado 5.3: medido con la definición de robot (Corke, 2023, p. 8), el brazo no percibe ni planifica, y por eso el espectro de autonomía, que presupone un reparto de control entre humano y máquina durante la tarea, no tiene realmente casilla para él; es automatización programable. Esa conclusión hay que dejarla escrita en la pizarra, porque vuelve en la actividad de fichas." },
]));
children.push(pRuns([
 { text: "«El brazo es teleoperado porque lo movemos con el teach pendant». ", bold: true },
 { text: "Es la respuesta que hay que corregir, y con precisión y sin ironía, porque el razonamiento es razonable: enseñar puntos no es teleoperar, porque en la teleoperación el humano controla durante la ejecución de la tarea (Corke, 2023, p. 7). Conviene además anunciar el enlace, porque llega el viernes: mover el robot aplicándole fuerza o guiándolo tiene nombre normativo y es uno de los cuatro métodos de operación colaborativa, el guiado manual (ISO/TS 15066:2016, cl. 5.5)." },
]));
children.push(h3("Desvíos frecuentes y cómo reconducir"));
children.push(p("El desvío casi garantizado es la conversación entre aficionados al vuelo FPV sobre los modos acro, angle y GPS. Es técnicamente correcta y es justo el desvío que uno querría tener, de modo que se acoge en una frase, el escalón depende del modo, y eso es exactamente lo que quería que saliera, y se corta por tiempo, no por contenido. El segundo es el salto a los niveles SAE, igual que en S3: se reconoce como vocabulario de un sector y se vuelve al espectro del libro. El tercero es la discusión sobre si el taxi autónomo funciona o no funciona, y en qué ciudad: se reconduce diciendo que no estamos discutiendo madurez comercial sino reparto de control, que es una distinción que además les sirve para leer prensa técnica. El cuarto es la deriva a la seguridad, qué pasa si atropella a alguien, que se aparca nombrándola y remitiéndola explícitamente a S7, donde tiene su sitio y su norma. Con siete minutos de tramo, cualquiera de los cuatro desvíos consumidos hasta el final deja sin hacer la calibración del brazo, que es la que importa."));
children.push(h3("Si la clase no habla"));
children.push(p("La votación con los dedos ya está elegida precisamente para eso: obliga a participar sin exponerse a hablar, y en un grupo de dos horas a última hora de la mañana del viernes esa diferencia es decisiva. El problema real no es que no voten, es que nadie quiera justificar su voto. La maniobra es no pedir voluntarios en ningún momento y nombrar directamente a quien ya se ha comprometido con una mano visible: con el voto ya emitido, la pregunta dirigida no resulta agresiva, porque el estudiante no tiene que decidir nada delante de todos, sólo explicar algo que ya ha decidido. El segundo recurso, más suave todavía, es pedir la justificación de la posición contraria a la propia: por qué creéis que alguien votaría uno. Explicar el razonamiento ajeno es sensiblemente más fácil que defender el propio y produce el mismo contenido en la pizarra."));
children.push(h3("Cierre"));
children.push(p("La frase de cierre es que el escalón de autonomía no es una propiedad del robot sino del reparto de control en una tarea concreta, y que por eso la misma máquina cambia de escalón cuando cambia de modo. Y el enlace inmediato con lo que viene: en las fichas vais a tener que decidir esto seis veces, y quiero la razón, no la etiqueta. Lo que no conviene hacer es dar la respuesta correcta de cada caso como si estuviera en el libro. En Corke están explícitamente clasificados la cirugía robótica y los ROV como teleoperación y los rovers marcianos como autonomía con objetivos remotos (Corke, 2023, p. 7); el dron FPV, el taxi y el brazo del laboratorio son aplicaciones nuestras del criterio, y ser honesto sobre esa diferencia enseña algo sobre cómo se usa una fuente. Tampoco conviene resolver la tensión del brazo diciendo que entonces no es un robot: la formulación útil es la misma de S3, que es un robot en el uso industrial de la palabra y un caso incompleto medido con la definición."));

children.push(h2("La actividad de fichas en equipos de S5 (95–115 min) y su puesta en común"));
children.push(h3("Objetivo"));
children.push(p("Lo que debe quedar aprendido es que las cuatro clasificaciones que hemos manejado en la sesión, movilidad, función, configuración cinemática con sus grados de libertad y escalón de autonomía, son sistemas independientes y no equivalentes, y que un mismo objeto puede ocupar varias casillas a la vez sin que eso sea un problema: los humanoides «son a la vez robots móviles y robots de servicio» (Corke, 2023, p. 5). La teoría lo advierte de pasada; la actividad fuerza a comprobarlo seis veces, y lo que de verdad enseña es el desacuerdo dentro del equipo. De ahí la instrucción que hay que dar de entrada y que cambia la naturaleza de la actividad: no se pide una tabla bien rellenada, se pide que marquen la ficha en la que no se han puesto de acuerdo. Sin esa instrucción, la actividad degenera en un ejercicio de rellenar casillas y la puesta en común no tiene material."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo es de 95 a 115 minutos, veinte minutos que hay que repartir con disciplina. De 95 a 97, formar equipos de tres o cuatro por proximidad y repartir las seis fichas, robot industrial articulado, cobot, AMR de almacén, humanoide, robot quirúrgico y dron de inspección, enunciando las cuatro casillas. Conviene decir explícitamente que estos no son los equipos del proyecto integrador, que se cierran en S7, porque si no se dice la mitad del tiempo se va en negociaciones de grupo. De 97 a 108, once minutos de trabajo en equipos con el profesor circulando. La regla de circulación es no dar respuestas y hacer una sola pregunta por equipo, elegida según cómo van: al equipo que avanza rápido se le pregunta por los grados de libertad, que es la casilla difícil; al que va atascado, por la movilidad, que es la fácil, para desbloquearlo. De 108 a 113, cinco minutos de puesta en común, y aquí la decisión crítica es no repasar las seis fichas: no caben y aburren. Se pide a cada equipo únicamente la ficha que ha circulado, con un minuto por equipo, y se lleva la cuenta en la pizarra de qué fichas se repiten. De 113 a 115, cierre, apertura de la formación de equipos del proyecto y encargo de la lectura de Corke (2023), cap. 4, pp. 139-146, para S6."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, al repartir las fichas: «Cada equipo tiene seis fichas. Para cada una quiero cuatro cosas: movilidad, función, configuración cinemática con sus grados de libertad si es un manipulador, y escalón de autonomía. Tenéis once minutos. Y quiero que marquéis con un círculo la ficha en la que no os hayáis puesto de acuerdo, porque es la única que os voy a pedir.» La última frase es la que hace la actividad: convierte el desacuerdo en el entregable en lugar de en algo que hay que esconder, y garantiza que la puesta en común empiece por el punto interesante de cada equipo y no por el primero de la lista."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "El humanoide. ", bold: true },
 { text: "Es la ficha que más equipos circulan y la que hay que desarrollar. Casi todos discuten si es de servicio o de fabricación, y la respuesta del libro es que es las dos cosas a la vez, móvil y de servicio (Corke, 2023, p. 5), con los pilotos industriales en logística complicándolo un poco más. La jugada buena es devolver a la clase la casilla de la configuración: nadie sabe cuántos grados de libertad tiene un humanoide, y en el intento se ve que el catálogo de configuraciones de la figura 7.2 (Corke, 2023, p. 255) describe brazos y pórticos, no cuerpos enteros. Que el aparato formal se quede corto ante un objeto real es un aprendizaje mejor que cualquier tabla." },
]));
children.push(pRuns([
 { text: "El robot quirúrgico. ", bold: true },
 { text: "Vienen dos errores previsibles: colocarlo en autonomía alta y no saber qué configuración asignarle. El primero se corrige con la fuente, que ya se ha dado dos veces, es teleoperación (Corke, 2023, p. 7), y a la tercera conviene preguntar quién puede explicarlo, en lugar de explicarlo uno mismo. El segundo se aprovecha para el espacio de tareas: la tarea se expresa naturalmente en el interior del paciente, y esa definición «la decide la tarea, independientemente del robot», mientras la del espacio de trabajo «la decide principalmente la estructura del robot, independientemente de la tarea» (Lynch y Park, 2017, pp. 32-33). Es el mejor ejemplo de la sesión para esa pareja de conceptos." },
]));
children.push(pRuns([
 { text: "El cobot. ", bold: true },
 { text: "Aparecerá clasificado como categoría propia, en una quinta casilla inventada. Es el error productivo del día y no hay que gastarlo aquí: se reconoce, se sitúa por función donde le corresponde, es un robot de fabricación (Corke, 2023, p. 6), y se anuncia que el viernes veremos que «cobot» no es una categoría de robot sino una propiedad de la aplicación. Dejarlo abierto con ese anuncio es el mejor enganche posible para S7, y resolverlo hoy le quita a esa sesión su mejor momento." },
]));
children.push(pRuns([
 { text: "El AMR de almacén y el dron de inspección. ", bold: true },
 { text: "El AMR suele ir bien y lo que hay que exigir es precisión en la locomoción: tracción diferencial, subactuada, capaz de girar sobre el sitio pero no de desplazarse lateralmente (Corke, 2023, p. 154). No hay que exigir la distinción entre AGV y AMR, que es contenido de S6; si algún equipo la trae, se acoge y se promete para el miércoles. El dron de inspección lo clasifican unos como robot de campo y otros como de servicio, y las dos son defendibles porque la monitorización ambiental es explícitamente una tarea de robótica de campo (Corke, 2023, pp. 4-5): es una ficha para devolver a la clase, no para cerrar por decreto. Y el robot industrial articulado, que es la ficha fácil, sirve para exigir el vocabulario completo: seis grados de libertad, articulaciones rotativas, cintura, hombro, codo y muñeca correspondiendo a las articulaciones 0, 1, 2 y 3-5 (Corke, 2023, p. 261), y seguridad por exclusión mediante jaula (Corke, 2023, p. 6)." },
]));
children.push(h3("Desvíos frecuentes y cómo reconducir"));
children.push(p("El desvío más común es el equipo que convierte la ficha en una búsqueda en el móvil, encuentra un modelo comercial y copia sus especificaciones. No hace falta prohibir el móvil, que además genera un conflicto innecesario: basta pedirles que tapen la pantalla y defiendan la clasificación con las definiciones que están en la pizarra, señalando que el catálogo da el número de ejes pero no el criterio de clasificación. El segundo es el equipo que rellena las veinticuatro casillas en cuatro minutos y se calla: no han discutido nada y no tendrán ficha circulada. La maniobra es darles una séptima ficha en blanco y pedirles un objeto que rompa la taxonomía, un exoesqueleto, un ascensor moderno, un coche autónomo, que es un encargo que ningún equipo rápido rechaza. El tercero es la deriva terminológica sobre si un dron es un robot, que se resuelve remitiendo a la definición de S3 (Corke, 2023, p. 8) y siguiendo. Y el cuarto es el riesgo real de la actividad: que la puesta en común se convierta en seis monólogos y se coma el cierre de la sesión. Se previene con tres reglas dichas antes de empezar: sólo la ficha circulada, un minuto cronometrado por equipo, y prohibido repetir una ficha ya defendida, de modo que el segundo equipo que traiga el humanoide tiene que añadir algo nuevo o pasar a otra."));
children.push(h3("Si la clase no habla"));
children.push(p("En la puesta en común el silencio tiene una causa distinta a la de una discusión abierta: el equipo tiene la respuesta escrita y lo que no quiere es exponerse a que se la corrijan en público. Hay tres maniobras, en este orden. La primera es pedir el papel y leerlo en voz alta el profesor sin decir de qué equipo es, que es la versión anónima de la puesta en común y funciona muy bien con grupos nuevos, como es el caso en la quinta sesión del curso. La segunda es anunciar antes de empezar el trabajo que el portavoz no podrá ser quien más haya hablado dentro del equipo: dicho al principio, obliga a que se prepare alguien que normalmente no habla, y dicho al final es una emboscada. La tercera, para el equipo concreto que se bloquea, es bajar el nivel de la pregunta a la casilla más fácil, la movilidad, y subir desde ahí; contestar algo, aunque sea trivial, rompe el bloqueo mucho mejor que un silencio prolongado."));
children.push(h3("Cierre"));
children.push(p("Hay que terminar con la idea de que las taxonomías son herramientas de descripción y no cajones excluyentes, y que la ficha que ha costado clasificar no señala un fallo de la clase sino un rasgo del objeto: el humanoide es el caso que el propio libro presenta como perteneciente a dos categorías a la vez (Corke, 2023, p. 5). Y conviene cerrar nombrando la casilla que hemos dejado deliberadamente incómoda, el cobot, y anunciando que es la clase del viernes: eso da continuidad al bloque y crea expectativa concreta. Lo que no conviene hacer es reparto de una plantilla con las respuestas correctas de las seis fichas, ni durante la sesión ni después en el campus virtual. Convertiría una actividad de criterio en un ejercicio de corrección, y la desactivaría para el curso siguiente en cuanto la plantilla circule. Si la piden, que la pedirán, se les dan las definiciones citadas con su página y no la tabla resuelta, explicando por qué: porque la tabla resuelta no existe, y sostener eso es parte de lo que se está enseñando."));

children.push(h2("El ejemplo provocador del cobot con herramienta cortante en S7 (30–36 min)"));
children.push(h3("Objetivo"));
children.push(p("Lo que debe quedar aprendido es que la afirmación de que «cobot» no es una categoría legal sino una propiedad de la aplicación funciona en los dos sentidos, y que el criterio se sabe aplicar en ambos: un brazo de fuerza limitada puede constituir una aplicación insegura, y un robot industrial clásico puede formar parte de una célula colaborativa correctamente salvaguardada. El apartado 7.1 ya lo afirma y ya da la razón de fondo, que es la división de responsabilidades entre el fabricante del robot (ISO 10218-1:2025) y el integrador de la aplicación (ISO 10218-2:2025), y ya lo condensa en la fórmula de que el robot se certifica y la aplicación se valida. La diferencia con la teoría es que leer esa frase produce asentimiento inmediato y no produce criterio: sólo se ve si el criterio existe cuando hay que decidir sobre dos casos concretos que apuntan en direcciones opuestas, y eso es lo que hacen estos seis minutos."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 10 a 40 minutos está asignado al marco normativo, y el ejemplo provocador ocupa de 30 a 36, dejando de 36 a 40 para la última idea del guion, que es aclarar qué se le pide al alumno frente a la norma. De 30 a 31, enunciar el caso y pedir votación a mano alzada inmediata, sin discusión previa, con el recuento escrito. De 31 a 34, pedir razones empezando por la minoría, y anotar en la pizarra los factores que vayan apareciendo: energía del contacto, geometría de la herramienta, presión sobre el punto de contacto, tarea concreta, quién está cerca y cuándo. De 34 a 35, el caso simétrico, que es el que de verdad enseña, con una segunda votación rápida. De 35 a 36, cierre en una línea y enlace con el segmento siguiente, que son los cuatro métodos de operación colaborativa. Votar antes de discutir y no después es deliberado: la pregunta parece fácil, la mayoría se compromete con la respuesta intuitiva, y el valor pedagógico está justamente en que se hayan comprometido."));
children.push(h3("Preguntas de apertura"));
children.push(p("La primera, literal: «Tengo un brazo de fuerza y potencia limitadas, certificado por su fabricante. Le monto en la brida una cuchilla para cortar cinta. Trabaja a velocidad reducida y se detiene si encuentra una obstrucción. ¿Es una aplicación colaborativa segura? Sí o no, a mano alzada, y luego lo discutimos.» La segunda, en el minuto 34 y también literal: «Ahora al revés. Un robot industrial clásico, grande y rápido, de los que van en jaula. ¿Puede formar parte de una aplicación colaborativa?» El orden importa: el primer caso desmonta la confianza en la etiqueta del producto y el segundo desmonta la confianza en su ausencia, y hacen falta los dos para que el criterio quede simétrico."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "«Sí, porque es un cobot y está certificado». ", bold: true },
 { text: "Es lo que vota la mayoría al principio y es exactamente el error que la sesión tiene que deshacer, de modo que no se corrige de frente. La pregunta que lo deshace sola es qué dice el certificado del fabricante, y la respuesta es que dice que el robot cumple los requisitos aplicables al robot como componente (ISO 10218-1:2025) y no dice nada de la herramienta que le hemos montado después. Y remata otra pregunta, casi coloquial, que es la que hace caer la ficha en el aula: ¿quién ha puesto la cuchilla, el fabricante o tú? De ahí sale sin esfuerzo la conclusión de que la evaluación de riesgos de la aplicación es responsabilidad del integrador (ISO 10218-2:2025)." },
]));
children.push(pRuns([
 { text: "«No, porque una cuchilla corta aunque vaya despacio». ", bold: true },
 { text: "Es la respuesta correcta y hay que desarrollarla técnicamente para que no se quede en intuición, porque una intuición no se puede aplicar a un caso nuevo. Los valores límite biomecánicos están tabulados por región corporal en el anexo A de la ISO/TS 15066:2016, y lo están en términos de fuerza y de presión; la presión es fuerza dividida por superficie de contacto, de modo que un filo concentra en una superficie mínima cualquier fuerza que en abstracto fuera admisible. Esa frase conviene decirla despacio y escribirla, porque es el argumento y no el veredicto lo que hay que llevarse." },
]));
children.push(pRuns([
 { text: "«Depende de la velocidad» o «si va muy despacio, sí». ", bold: true },
 { text: "Se devuelve a la clase, porque contiene media verdad: reducir la velocidad reduce la energía de un impacto, pero no reduce la presión de un filo en contacto cuasiestático. Es la ocasión de adelantar en una frase lo que viene en el segmento siguiente, que la limitación de potencia y fuerza es sólo uno de los cuatro métodos de operación colaborativa (ISO/TS 15066:2016, cl. 5.5) y que aquí seguramente haya que combinarlo con monitorización de velocidad y separación, o bien eliminar el peligro por diseño, que es el primer escalón de la jerarquía de reducción del riesgo del apartado 7.3." },
]));
children.push(pRuns([
 { text: "«Un robot de jaula nunca puede ser colaborativo». ", bold: true },
 { text: "Es la respuesta mayoritaria al caso simétrico y hay que corregirla con el criterio, no con la autoridad. Puede participar en una aplicación colaborativa si la célula incorpora las salvaguardas adecuadas, típicamente monitorización de velocidad y separación con sensórica de seguridad certificada, que es precisamente lo que habilita células sin vallado con robots rápidos (apdo. 7.2). La confusión de fondo merece nombrarse, porque es instructiva: han leído la descripción de Corke, según la cual los robots colaborativos «operan a baja velocidad y se detienen cuando encuentran una obstrucción» (Corke, 2023, p. 6), como si fuera una definición legal, y es una descripción tecnológica de una familia de productos." },
]));
children.push(p("Aparecerá también el ingenioso que propone ponerle una funda a la cuchilla o retraerla cuando no corta. Hay que acogerlo con entusiasmo explícito, porque no es una salida por la tangente: es eliminar el peligro por diseño, que es el primer escalón de la jerarquía obligatoria (apdo. 7.3), y la mejor medida de protección siempre es la que hace desaparecer el peligro en lugar de gestionarlo."));
children.push(h3("Desvíos frecuentes y cómo reconducir"));
children.push(p("El primer desvío es el anecdotario de accidentes con robots, que en un grupo de máster con gente que ha estado en planta llega enseguida. No se corta, se reconduce hacia el proceso con una sola pregunta: en qué paso del análisis de riesgos se habría detectado eso. Así el anecdotario alimenta el taller de la segunda hora en lugar de sustituirlo. El segundo es la deriva al detalle normativo, con alguien pidiendo el valor exacto de fuerza admisible en el antebrazo. Se contesta con honestidad, está tabulado en el anexo A de la ISO/TS 15066:2016 y no se memoriza, y se aprovecha para decir ya la idea del guion sobre qué se le pide al alumno frente a la norma: no memorizar cláusulas, sino entender la arquitectura, la división de responsabilidades y dónde vive cada cosa. El tercero es el más peligroso profesionalmente y hay que nombrarlo como tal: la idea de que esto lo resuelve el proveedor. Es la excusa real de muchas integraciones defectuosas, y se devuelve con la división de responsabilidades (ISO 10218-2:2025), señalando que muchos de los presentes van a firmar precisamente esa evaluación. El cuarto es la deriva a marcas concretas de cobot, que se corta por neutralidad y en una frase: en clase discutimos métodos, no proveedores."));
children.push(h3("Si la clase no habla"));
children.push(p("La votación inmediata sin discusión previa está puesta justamente para eso, y funciona porque la pregunta parece fácil y contestarla no exige haber entendido la norma. Si nadie quiere justificar el voto, la maniobra es dividir el aula de forma explícita: los que habéis dicho que sí tenéis que convencerme, treinta segundos con el de al lado. Un encargo con destinatario concreto y plazo corto rompe el silencio mejor que una pregunta abierta. Y queda un segundo recurso que en este caso concreto es especialmente eficaz: hacer el gesto. Se coge un objeto con filo, unas tijeras del aula, se apoya en la palma de la mano y se presiona despacio mientras se dice en voz alta que la fuerza es la misma que aplicaría la mano abierta. La diferencia entre fuerza y presión se entiende en dos segundos y se recuerda el resto del curso. Es teatro, y es probablemente el minuto más rentable de la sesión."));
children.push(h3("Cierre"));
children.push(p("La frase de cierre es la del apartado 7.1, dicha tal cual: el robot se certifica, la aplicación se valida. Y el corolario que conviene dejar escrito, porque es el que van a usar profesionalmente: la pregunta correcta no es si algo es un cobot, sino qué método colaborativo aplica esta tarea y con qué evidencia. Lo que no conviene decir es que los cobots son seguros, ni tampoco que son peligrosos: las dos frases son igual de falsas y las dos circulan por el sector con naturalidad, de modo que decir cualquiera de ellas es reforzar precisamente el hábito que estamos intentando corregir. Y no conviene resolver el caso con la autoridad del profesor, no es seguro, y punto, antes de que haya salido del aula el argumento de la presión: el caso vale por el argumento, no por el veredicto, y si se da el veredicto primero el argumento ya no lo escucha nadie."));

children.push(h2("La corrección en común del taller de análisis de riesgos en S7 (100–110 min)"));
children.push(h3("Objetivo"));
children.push(p("Lo que debe quedar aprendido son dos cosas que ningún apartado teórico consigue transmitir por sí solo. La primera es que los peligros no están en el funcionamiento normal del ciclo sino en los modos degradados, limpieza, mantenimiento y recuperación de fallos, que es donde se concentran los accidentes reales (apdo. 7.3). La segunda es que la jerarquía de reducción del riesgo, eliminar por diseño, después proteger con resguardos y dispositivos y sólo en último lugar informar, es un orden obligatorio y no un menú de opciones. La diferencia con la teoría es empírica y llega sola: el apartado 7.3 enumera los cinco pasos y todo el mundo asiente, y luego la corrección en común muestra que casi todos los equipos han saltado el paso primero, determinar los límites de la aplicación, y han empezado directamente por listar peligros, y que la medida que aparece con más frecuencia en las filas de riesgo alto es la formación del operario. Ver eso en su propia tabla enseña el proceso mejor que oírlo enumerado."));
children.push(h3("Formato y tiempos"));
children.push(p("El taller ocupa de 80 a 110 minutos y la corrección en común son los diez últimos, con el trabajo en equipos entre el 83 y el 100 aproximadamente. De 100 a 101, elegir las dos tablas y proyectarlas o copiarlas en la pizarra. La elección no es al azar y no se hace en ese momento: durante la circulación por los equipos hay que haber localizado una tabla sólida y otra con un error instructivo, y hay que avisar a los dos equipos con antelación para que no les pille de sorpresa, porque una corrección pública por sorpresa se vive como una emboscada y desactiva al equipo para el resto del curso. De 101 a 105, la primera tabla, la sólida, recorrida fila a fila con el equipo defendiéndola. De 105 a 109, la segunda, la del error instructivo, y aquí el trabajo del profesor es no señalar el error: se pide a la clase que compare la fila equivalente en las dos tablas. De 109 a 110, cierre del taller y del bloque, y paso al cuestionario de seguimiento B2."));
children.push(h3("Preguntas de apertura"));
children.push(p("Para la primera tabla, literalmente: «Vamos a corregir dos tablas y no las he elegido por buenas ni por malas. De esta primera quiero que me digáis, fila a fila, en qué paso de los cinco estáis: si la fila describe un peligro, si estima un riesgo o si ya propone una medida. Y quiero saber en qué tarea ocurre cada peligro.» Preguntar por el paso y por la tarea, y no si la fila está bien, es lo que convierte la corrección en un ejercicio de método. Para la segunda tabla, la pregunta es de comparación y también conviene formularla literalmente: «Comparad esta fila con la fila equivalente de la tabla anterior. ¿Qué diferencia hay entre las dos medidas, y cuál de las dos está más arriba en la jerarquía?»"));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "Filas que mezclan el peligro con la medida. ", bold: true },
 { text: "Del tipo «atrapamiento: poner vallado». Es el error más frecuente y no es grave: se corrige separando las columnas en voz alta y devolviendo la pregunta que falta, que es la estimación. Conviene insistir en por qué falta: sin estimar el riesgo no se puede justificar la elección de la medida, y en una evaluación real esa justificación es precisamente lo que hay que documentar." },
]));
children.push(pRuns([
 { text: "Todas las filas describen el funcionamiento normal del ciclo. ", bold: true },
 { text: "Es el error importante de la sesión y no hay que decirlo: hay que preguntar quién entra en la célula y cuándo, y esperar los diez segundos. Alguien dirá que para cambiar la garra, o cuando se atasca una pieza, o para limpiar, y ahí están los modos degradados. Que la frase la diga un estudiante vale muchísimo más que dicha por el profesor, y este es el sitio exacto del bloque donde esa diferencia se nota, porque es la lección que se lleva a la vida profesional." },
]));
children.push(pRuns([
 { text: "«Medida: formación del operario» en una fila de riesgo alto. ", bold: true },
 { text: "Se corrige con la jerarquía y no con un juicio de valor, que además sería injusto porque la formación es una medida legítima en su sitio. Informar es el último escalón, después de eliminar por diseño y de proteger con resguardos y dispositivos, y una medida informativa sola no reduce un riesgo alto. La pregunta que hay que hacer antes de aceptar cualquier resguardo es la del primer escalón: hace falta realmente que la carga sea manual." },
]));
children.push(pRuns([
 { text: "Un método colaborativo en todas las filas. ", bold: true },
 { text: "Ocurre porque la columna existe en la plantilla y da la sensación de que hay que rellenarla. Se corrige el supuesto: la célula del laboratorio con carga y descarga manual se resuelve perfectamente con parada monitorizada de seguridad por turnos (ISO/TS 15066:2016, cl. 5.5), y hay tareas que no necesitan método colaborativo ninguno, sino que no haya nadie dentro. Y hay una confusión próxima que conviene corregir rápido y con la fuente metodológica cuando aparece: estimar el riesgo no es puntuar la severidad, es combinar severidad del daño, exposición y probabilidad de evitación (ISO 12100:2010, según el apdo. 7.3)." },
]));
children.push(h3("Desvíos frecuentes y cómo reconducir"));
children.push(p("El primer desvío es la casuística legal: y si el operario no lleva los guantes, de quién es la culpa. Se reconduce sin descalificar la pregunta, que es natural: la norma no reparte culpas, define responsabilidades de diseño y de integración, y la culpa es un asunto posterior y de otro foro. El segundo es la comparación con las normas del laboratorio del IQS, y aquí hay que ser explícito y breve en el sentido que ya fija el propio apartado: estos apuntes dan el marco conceptual, y las normas concretas del aula-taller están establecidas, son de obligado cumplimiento y no se discuten en clase. El tercero es la deriva al detalle de producto, con alguien preguntando qué escáner láser y de qué categoría. Es buena señal profesional y hay que decirlo, pero se aparca: la selección de dispositivos de protección exige niveles de integridad y arquitecturas de seguridad que esta asignatura no cubre. Y el cuarto es el equipo que quiere defender su tabla contra la corrección, que no hay que cortar en absoluto: se le pide la evidencia del paso quinto, la validación. Casi nunca la tienen, y esa es precisamente la lección que cierra el bloque."));
children.push(h3("Si la clase no habla"));
children.push(p("En el minuto cien de una sesión de dos horas el silencio es cansancio y no timidez, y hay que tratarlo como lo que es en lugar de insistir con más preguntas. Tres maniobras, en este orden. La primera es sacar al equipo a la pizarra en vez de preguntarle desde el sitio: levantarse y escribir cambia la energía del aula y despierta a los demás. La segunda es pedir que sea el equipo vecino el que revise la tabla ajena y diga una sola cosa que falta, porque revisar es mucho más fácil que producir y a estas alturas de la sesión esa diferencia decide si hay conversación o no. La tercera es reducir el alcance sin disimulo: corregir una sola fila bien hecha en lugar de arrastrar dos tablas enteras. Si el grupo está agotado, una corrección de cuatro minutos bien cerrada vale más que diez minutos de tirón, y siempre es preferible terminar antes con algo aprendido que llegar al timbre con la clase desconectada."));
children.push(h3("Cierre"));
children.push(p("La idea de cierre es la que da sentido a las dos horas y al bloque entero: la seguridad no es un componente que se compra ni una cláusula que se cita, es el resultado de un proceso documentado sobre una aplicación concreta, y el orden de la jerarquía no es negociable. Conviene terminar nombrando el papel profesional, porque en un máster eso aterriza el contenido: una parte de los presentes va a firmar evaluaciones de riesgos como integradores, y la división de responsabilidades del apartado 7.1 dejará de ser un esquema para ser su firma. Lo que no conviene decir es que la tabla corregida es la solución, porque no existe una tabla correcta única y decirlo invita a memorizar la del año pasado. Y no conviene cerrar con estadísticas de accidentes graves para dejar impresión: es un recurso fácil, se recuerda mal y desplaza la atención del proceso al miedo, que es exactamente lo contrario de lo que hace un buen análisis de riesgos."));

// Bibliografía
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Bibliografía citada en este bloque"));
children.push(bullet("Robotics, Vision and Control: Fundamental Algorithms in Python. 3.ª ed., Springer, 2023. Cap. 1: taxonomías y definiciones (pp. 4-8); cap. 4: vehículos móviles (Ackermann p. 132, diferencial pp. 140-142, omnidireccional pp. 144-146, cuadrirrotor pp. 147-152, holonomía pp. 153-155); cap. 7: manipuladores (pp. 254-255, 260-261).", "Corke, P. "));
children.push(bullet("Modern Robotics: Mechanics, Planning, and Control. Cambridge University Press, 2017. Cap. 2: Definición 2.1 de configuración, gdl y C-space (pp. 11-12); restricciones no holonómicas (p. 32); espacio de tareas y espacio de trabajo (pp. 32-33).", "Lynch, K. M. y Park, F. C. "));
children.push(bullet("ISO 10218-1:2025 e ISO 10218-2:2025, Robotics, Safety requirements (partes 1 y 2). ISO/TS 15066:2016, Robots and robotic devices, Collaborative robots (métodos colaborativos, cl. 5.5; límites biomecánicos, anexo A). ISO 12100:2010, Safety of machinery, General principles for design, Risk assessment and risk reduction.", "Normas: "));
children.push(bullet("Mechatronics: Fundamentals and Applications, CRC Press, 2016, MDQ (p. 7), citado como marco de decisión multiobjetivo.", "De Silva, C. W. et al. "));
children.push(bullet("contexto de mercado de cobots, AMR y humanoides: ABB Robotics (Key Cobot Trends Shaping 2026), informes sectoriales de automatización 2026 listados en el plan del curso. Sin paginación; usados solo para afirmaciones de contexto industrial.", "Fuentes sectoriales: "));

const doc = new Document({
 numbering: numberingConfig,
 styles: { default: { document: { run: { font: F, size: 22 } } } },
 sections: [{ properties: { page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } }, children }],
});
Packer.toBuffer(doc).then(buf => { fs.writeFileSync("Apuntes_B2_Tipologia_Seguridad.docx", buf); console.log("OK B2 v2"); });
