#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Banco de preguntas ABCD para los cuestionarios Moodle de 15 min (10 preguntas de cada banco de 12).
Genera moodle/Moodle_BX.gift (importable) y banco.json (para exámenes y docx)."""
import json, os, re

# (enunciado, [A, B, C, D], índice_correcta 0-3, retroalimentación breve)
B = {}

B[1] = [
("Según De Silva, la mecatrónica es la aplicación sinérgica de mecánica, electrónica, control e informática. ¿Qué significa aquí «sinérgica»?",
 ["Que los subsistemas se conciben y optimizan conjuntamente desde el inicio del diseño",
 "Que el producto final contiene componentes de todos los dominios",
 "Que la electrónica sustituye progresivamente a la mecánica",
 "Que cada subsistema lo diseña un especialista de ese dominio"], 0,
 "Sinergia = concebir los subsistemas juntos, no yuxtaponerlos. Un producto electromecánico no es automáticamente mecatrónico (S1)."),
("El término «mechatronics» fue acuñado en 1969 por…",
 ["Un ingeniero de Yaskawa Electric, en Japón",
 "Joseph Engelberger, fundador de Unimation",
 "El MIT, en su laboratorio de servomecanismos",
 "Karel Čapek, en la obra R.U.R."], 0,
 "Lo acuñó Yaskawa (Japón); marca registrada en 1972 y liberada en 1982 (S1)."),
("En el diseño secuencial (no acoplado), ¿cuál de estos problemas aparece al interconectar componentes diseñados por separado?",
 ["Sus condiciones de operación cambian y dejan de cumplirse las prestaciones de catálogo",
 "El coste total siempre disminuye",
 "Los componentes quedan automáticamente sobredimensionados por igual",
 "Las variables internas pasan a ser externas y más fáciles de medir"], 0,
 "La carga y las interacciones dinámicas alteran las condiciones originales; además aparecen variables ocultas (S2)."),
("El Cociente de Diseño Mecatrónico (MDQ) se define como…",
 ["Un cociente que compara el índice de diseño del conjunto interconectado con el de los subsistemas aislados",
 "La suma de los índices de diseño eléctrico y mecánico",
 "El producto de fiabilidad por eficiencia del sistema",
 "La diferencia entre coste previsto y coste real del prototipo"], 0,
 "MDQ = (αe·Ie² + αm·Im²)/(αe·Iue² + αm·Ium²): cociente, no suma (ec. 1.4, De Silva p. 7; S2)."),
("Un valor de MDQ próximo a 1 indica que…",
 ["El diseño interconectado se acerca al óptimo que cada subsistema lograría aislado",
 "El sistema es inestable y debe rediseñarse",
 "Los pesos αe y αm están mal elegidos",
 "El diseño eléctrico domina sobre el mecánico"], 0,
 "El MDQ mide cuánto se acerca el conjunto al ideal de cada dominio (S2)."),
("En el bucle de modelado y diseño, la relación v·i = ω·τ expresa que…",
 ["La potencia enlaza los dominios eléctrico y mecánico en el transformador ideal",
 "La tensión es proporcional al par en cualquier motor",
 "La corriente y la velocidad son siempre inversamente proporcionales",
 "El rendimiento del motor es del 100 % en régimen permanente"], 0,
 "La potencia eléctrica de entrada iguala la mecánica de salida: la energía es el hilo unificador (S2)."),
("La definición de robot que usa el curso (Corke) es una máquina orientada a objetivos que puede…",
 ["Percibir, planificar y actuar",
 "Programarse, calibrarse y repetir",
 "Sentir, comunicar y aprender",
 "Medir, controlar y registrar"], 0,
 "La tríada percibir-planificar-actuar organiza toda la asignatura (S3)."),
("Un sensor propioceptivo mide…",
 ["El estado del propio robot, como los ángulos articulares o las revoluciones de rueda",
 "El mundo exterior respecto al robot, como la distancia a un obstáculo",
 "Solo magnitudes eléctricas internas del controlador",
 "La posición absoluta del robot mediante balizas externas"], 0,
 "Propioceptivo = estado propio (base de la odometría); exteroceptivo = el mundo (S3)."),
("El primer robot industrial (Unimate) entró en producción en 1961 en…",
 ["Una planta de General Motors en Nueva Jersey",
 "La cadena de montaje de Toyota en Nagoya",
 "Los laboratorios Bell",
 "Una fábrica textil de Lyon"], 0,
 "Patente de Devol + Engelberger: Unimation; GM, Nueva Jersey, 1961 (S3)."),
("El telar de Jacquard (1801) es un hito de la robótica porque…",
 ["Era una máquina reprogramable: el programa estaba en tarjetas perforadas",
 "Fue el primer autómata con realimentación de fuerza",
 "Introdujo el motor eléctrico en la industria",
 "Fue el primer dispositivo teleoperado a distancia"], 0,
 "Reprogramable antes de la electrónica; influyó en Babbage y Ada Lovelace (S3)."),
("La cirugía robótica actual (tipo Da Vinci) es un ejemplo de…",
 ["Teleoperación: el cirujano controla y el robot ejecuta",
 "Autonomía supervisada con objetivos de alto nivel",
 "Control compartido entre cirujano e inteligencia artificial",
 "Robot de fabricación adaptado al quirófano"], 0,
 "Es teleoperada, no autónoma: heredera de los brazos maestro-esclavo de Goertz (S3)."),
("Un modelo VLA (visión-lenguaje-acción) se caracteriza por…",
 ["Producir acciones motoras a partir de imágenes de cámara e instrucciones en lenguaje natural",
 "Traducir planos CAD en trayectorias articulares",
 "Sustituir a los lazos de control de bajo nivel del robot",
 "Generar lenguaje natural que describe lo que ve el robot"], 0,
 "VLA: de cámara + instrucción a acciones; las consignas las ejecutan los lazos clásicos (S4/B8)."),
]

B[2] = [
("En la taxonomía funcional de Corke, los humanoides son un caso interesante porque…",
 ["Son a la vez robots móviles y de servicio: las categorías no son excluyentes",
 "No encajan en ninguna categoría y forman la quinta",
 "Son siempre robots de fabricación",
 "Solo existen como plataformas de investigación"], 0,
 "Las categorías (fabricación, servicio, campo, humanoides) se solapan (S5)."),
("La diferencia esencial entre un robot industrial clásico y un cobot es que el cobot…",
 ["Sustituye el vallado por sensórica y control que garantizan la seguridad ante el contacto",
 "Es siempre más rápido y preciso",
 "No necesita evaluación de riesgos",
 "Solo puede mover cargas inferiores a 1 kg"], 0,
 "Seguridad por diseño y control en lugar de exclusión física (S5/S7)."),
("La configuración SCARA se caracteriza por ser…",
 ["Rígida en vertical y ágil en el plano horizontal: ideal para ensamblado electrónico",
 "Un robot de cadenas cinemáticas cerradas de baja inercia",
 "La configuración con mayor espacio de trabajo esférico",
 "Un manipulador puramente cartesiano"], 0,
 "SCARA (RRP): rigidez en Z y agilidad plana (S5)."),
("El robot delta alcanza altísimas velocidades porque…",
 ["Sus cadenas cinemáticas cerradas dejan los motores en la base y mueven muy poca inercia",
 "Usa motores hidráulicos de gran potencia",
 "Su espacio de trabajo es mayor que el de un 6R",
 "No necesita reductoras"], 0,
 "Cadenas cerradas, actuadores en la base, poca masa móvil: envasado y pick and place (S5)."),
("La cifra estrella de los catálogos de robots industriales es la repetibilidad. La exactitud…",
 ["Es en general peor, y es la que importa al programar fuera de línea",
 "Es siempre igual a la repetibilidad",
 "Es mejor que la repetibilidad gracias a la calibración",
 "No está definida para robots de 6 ejes"], 0,
 "Repetibilidad ±0,01–0,05 mm; la exactitud es peor y manda en programación fuera de línea (S5)."),
("¿Cuántos grados de libertad necesita un manipulador para alcanzar una pose arbitraria (posición y orientación) en el espacio?",
 ["6", "3", "4", "8"], 0,
 "3 de posición + 3 de orientación = 6 (S5/B4)."),
("Una plataforma con dirección Ackermann (tipo coche) es «no holonómica» porque…",
 ["No puede desplazarse lateralmente: sus velocidades posibles están restringidas",
 "No puede girar sobre sí misma más de 360 grados",
 "Su odometría no acumula error",
 "Necesita un mapa para poder moverse"], 0,
 "La restricción de velocidad condiciona la planificación (aparcar en paralelo) (S6/B7)."),
("La diferencia clave entre un AGV y un AMR es que el AMR…",
 ["Navega con un mapa que construye y mantiene, y rodea obstáculos planificando",
 "Sigue una banda magnética con mayor precisión",
 "No lleva sensores a bordo",
 "Solo funciona en exteriores"], 0,
 "AGV: infraestructura física y ruta fija; AMR: SLAM + planificación, mismo hardware, distinto software (S6)."),
("En la ISO 10218:2025, la responsabilidad legal de la evaluación de riesgos de la célula recae en…",
 ["El integrador (Parte 2), que diseña y valida la aplicación completa",
 "El fabricante del robot (Parte 1)",
 "El operario que trabaja en la célula",
 "El organismo notificado que certifica el robot"], 0,
 "Parte 1 = robot como componente; Parte 2 = célula integrada y evaluación de riesgos (S7)."),
("El método colaborativo de «limitación de potencia y fuerza» se caracteriza por…",
 ["Admitir el contacto persona-robot manteniendo fuerza y presión bajo umbrales biomecánicos",
 "Detener el robot cuando una persona entra en la célula",
 "Modular la velocidad según la distancia a la persona",
 "Permitir mover el robot con la mano para programarlo"], 0,
 "Es el método de los cobots con par medido; los umbrales vienen de la ISO/TS 15066 (S7)."),
("La ISO/TS 15066 sigue siendo la referencia para…",
 ["Los límites biomecánicos de fuerza y presión por región corporal",
 "El marcado CE de máquinas completas",
 "La clasificación de robots por carga útil",
 "Los requisitos de software de los controladores"], 0,
 "La revisión 2025 de la ISO 10218 integró sus requisitos; los límites biomecánicos siguen ahí (S7)."),
("En la reducción de riesgos, la jerarquía correcta es…",
 ["Eliminar por diseño, después proteger, e informar solo en último lugar",
 "Informar primero, proteger después, rediseñar si hay presupuesto",
 "Proteger siempre con vallado antes de cualquier otra medida",
 "Formar al operario y señalizar: el diseño no se toca"], 0,
 "Jerarquía estricta de la ISO 12100: diseño, protección, información (S7)."),
]

B[3] = [
("Para Fraden, un sensor es un dispositivo que…",
 ["Recibe un estímulo y responde con una señal eléctrica",
 "Convierte cualquier energía en movimiento",
 "Amplifica señales débiles para el conversor A/D",
 "Almacena la medida en memoria digital"], 0,
 "Sensor: estímulo → señal eléctrica; transductor: energía → energía; actuador: lo opuesto (S8)."),
("Muestreas a 500 Hz una vibración de 400 Hz. ¿Qué observas?",
 ["Un alias de baja frecuencia (100 Hz) imposible de deshacer con filtrado digital posterior",
 "La señal correcta, porque 500 es mayor que 400",
 "Ruido blanco sin estructura",
 "La señal atenuada a la mitad de amplitud"], 0,
 "Nyquist exige fs ≥ 2·f. El alias aparece en |fs − f| = 100 Hz y ya no se corrige (S8)."),
("Repetibilidad y exactitud: ¿cuál es la afirmación correcta?",
 ["Un sesgo estable (buena repetibilidad, mala exactitud) puede calibrarse; una dispersión aleatoria, no",
 "Son sinónimos en las hojas de datos",
 "La exactitud siempre es mejor que la repetibilidad",
 "La repetibilidad solo se define para sensores digitales"], 0,
 "Por eso la repetibilidad es la especificación clave: el sesgo se corrige por calibración (S8)."),
("La histéresis de un sensor es…",
 ["La diferencia de salida según el estímulo llegue subiendo o bajando",
 "El tiempo que tarda en estabilizarse la lectura",
 "La deriva térmica del cero",
 "El menor incremento de estímulo detectable"], 0,
 "La salida depende del camino (ida o vuelta), una de las 8 características estáticas (S8)."),
("Los dos canales A y B en cuadratura (90°) de un encoder incremental permiten…",
 ["Conocer el sentido de giro y multiplicar por 4 la resolución de cuenta",
 "Medir la posición absoluta al arrancar",
 "Compensar la temperatura del disco",
 "Duplicar la velocidad máxima medible"], 0,
 "El desfase da el sentido; la decodificación x4 cuenta los cuatro flancos (S9)."),
("Un encoder incremental de 500 líneas con decodificación x4 tiene una resolución angular de…",
 ["0,18 grados", "0,72 grados", "1,44 grados", "0,045 grados"], 0,
 "360/(4·500) = 0,18° (S9)."),
("«Los acelerómetros miden la gravedad y el movimiento del cuerpo a la vez» (Corke). Una consecuencia práctica es que…",
 ["En reposo miden g, lo que permite estimar la inclinación",
 "En reposo su salida es exactamente cero",
 "Solo funcionan en caída libre",
 "No sirven para estimar orientación"], 0,
 "La referencia de gravedad es la base de la estimación de inclinación (S9)."),
("El bias de un acelerómetro es el gran enemigo de la navegación inercial porque…",
 ["Al integrar dos veces, el error de posición crece cuadráticamente con el tiempo",
 "Hace que el sensor se sature enseguida",
 "Aparece solo a altas velocidades de giro",
 "Impide medir la temperatura interna"], 0,
 "x_medido = s·x + b + ruido; b deriva y la doble integración lo amplifica (S9)."),
("El factor de galga expresa…",
 ["El cambio relativo de resistencia por unidad de deformación (dR/R = Se·ε)",
 "La fuerza máxima que soporta la galga",
 "La sensibilidad térmica del adhesivo",
 "La tensión de alimentación óptima del puente"], 0,
 "Se ≈ 2 en metales; hasta ±150 en silicio con fuerte sensibilidad térmica (S10)."),
("Montar 4 galgas activas en puente de Wheatstone completo sirve para…",
 ["Compensar la temperatura y cuadruplicar la sensibilidad",
 "Reducir el consumo a la cuarta parte",
 "Medir cuatro fuerzas independientes",
 "Eliminar la necesidad de amplificador"], 0,
 "La configuración completa compensa efectos térmicos comunes y suma las cuatro contribuciones (S10)."),
("La fuerza contraelectromotriz (back-EMF) de un motor DC…",
 ["Crece con la velocidad y fija la velocidad máxima alcanzable a una tensión dada",
 "Solo aparece con el rotor bloqueado",
 "Es independiente de la velocidad de giro",
 "Aumenta el par disponible a alta velocidad"], 0,
 "Vb = Km·ω se opone a la corriente; cuando iguala la tensión, el par cae a cero (S11)."),
("Con una reductora de relación G, la inercia de la carga vista desde el motor…",
 ["Se divide por G²", "Se multiplica por G", "No cambia", "Se divide por G"], 0,
 "Par ×G, velocidad ÷G, inercia reflejada ÷G², el cuadrado es la clave del dimensionado (S12)."),
]

B[4] = [
("En la notación T_AB del curso, la regla de composición T_AC = T_AB · T_BC funciona porque…",
 ["El subíndice interior repetido «se cancela» al encadenar poses relativas",
 "Las matrices de pose conmutan entre sí",
 "La inversa de T es igual a su traspuesta",
 "Los marcos son siempre coincidentes en el origen"], 0,
 "Regla mecánica de lectura de subíndices que evita los errores de orden (S13)."),
("Una matriz de rotación R pertenece a SO(3) si cumple…",
 ["R traspuesta por R igual a identidad, y determinante +1",
 "Determinante distinto de cero y traza positiva",
 "Todos sus elementos entre -1 y 1",
 "R simétrica y definida positiva"], 0,
 "Ortonormalidad + det = +1 (excluye marcos levógiros); además R inversa = R traspuesta (S13)."),
("El bloqueo de cardán (gimbal lock) ocurre cuando…",
 ["Dos ejes de la secuencia de tres ángulos se alinean y se pierde un grado de libertad de representación",
 "El robot alcanza el límite físico de una articulación",
 "El determinante de la matriz de rotación se hace cero",
 "Se usan cuaterniones no unitarios"], 0,
 "Afecta a TODAS las representaciones de tres ángulos; anécdota del Apolo 13 (S13)."),
("La ventaja decisiva de los cuaterniones unitarios frente a los ángulos de Euler es que…",
 ["No tienen singularidad de representación y componen e interpolan de forma barata",
 "Usan solo tres números en lugar de cuatro",
 "Son más intuitivos para comunicar orientaciones a humanos",
 "Evitan tener que normalizar"], 0,
 "Regla del curso: matrices para operar, ángulos para comunicar, cuaterniones para interpolar (S13)."),
("La convención de Denavit-Hartenberg describe cada eslabón con…",
 ["4 parámetros", "6 parámetros", "3 parámetros", "2 parámetros"], 0,
 "θ, d, a, α por eslabón: tabla compacta, el estándar de intercambio desde los años 60 (S14)."),
("La cinemática directa (FK) de un robot serie…",
 ["Siempre existe y es única; el problema con solución múltiple es el inverso",
 "Puede tener hasta ocho soluciones",
 "Solo existe si el robot tiene muñeca esférica",
 "Requiere métodos numéricos iterativos"], 0,
 "FK: de articulares a pose, única. La multiplicidad es de la IK (S14/S16)."),
("Un 6R industrial con muñeca esférica y offset de hombro tiene, en general, ¿cuántas soluciones de IK para una pose alcanzable?",
 ["8", "2", "4", "Infinitas"], 0,
 "lefty/righty × codo arriba/abajo × muñeca volteada o no = 8 (S16)."),
("La condición que permite resolver la IK de un 6R en forma cerrada es…",
 ["Una muñeca esférica: tres ejes que se cortan en un punto, que desacopla posición y orientación",
 "Que todos los eslabones tengan la misma longitud",
 "Que el robot no tenga reductoras",
 "Que la base esté fija al suelo"], 0,
 "El desacoplo posición/orientación estructura la solución analítica (S16)."),
("En las soluciones analíticas de IK se usa siempre atan2 en lugar de la arcotangente del cociente porque…",
 ["atan2 conserva el cuadrante del ángulo",
 "atan2 es más rápida de calcular",
 "La arcotangente no está definida en radianes",
 "atan2 devuelve siempre ángulos positivos"], 0,
 "Regla de oficio del curso: atan2(y, x), nunca atan(y/x) (S16)."),
("La columna i del jacobiano geométrico J(q) representa…",
 ["La velocidad del efector cuando solo la articulación i se mueve a velocidad unidad",
 "La fuerza que ejerce la articulación i en reposo",
 "La posición del eslabón i en el marco del mundo",
 "El error de la articulación i respecto a su consigna"], 0,
 "La lectura por columnas es la que fija la intuición física del jacobiano (S17)."),
("En una singularidad cinemática…",
 ["El efector pierde la capacidad de moverse instantáneamente en una o más direcciones",
 "El robot pierde potencia en todos los motores",
 "La cinemática directa deja de ser única",
 "El jacobiano se hace simétrico"], 0,
 "J pierde rango; cerca de ella, velocidades cartesianas modestas exigen velocidades articulares enormes (S18)."),
("La relación estática entre la fuerza F en el efector y los pares articulares es τ = J traspuesta por F. Una propiedad notable es que…",
 ["No requiere invertir el jacobiano: la estática sigue definida incluso en singularidades",
 "Solo es válida lejos de singularidades",
 "Requiere invertir el jacobiano en cada instante",
 "Solo aplica a robots planos de dos eslabones"], 0,
 "τ = Jᵀ·F no requiere invertir J: la estática no explota en singularidades (Corke, 2023, p. 325; S19)."),
]

B[5] = [
("La función de transferencia de un motor DC en velocidad es de primer orden. Al controlar posición…",
 ["Se añade un integrador: un polo en s = 0, al borde de la estabilidad",
 "El sistema pasa a ser de orden cero",
 "Aparece un cero en el origen que acelera la respuesta",
 "La constante de tiempo se duplica"], 0,
 "Θ(s)/U(s) añade 1/s a la planta de velocidad (S20)."),
("En un sistema de primer orden, en t = τ (una constante de tiempo) la respuesta al escalón ha alcanzado aproximadamente…",
 ["El 63 % del valor final", "El 37 % del valor final", "El 50 % del valor final", "El 95 % del valor final"], 0,
 "Queda e^(−1) ≈ 37 % por recorrer; establecimiento al 2 % en unas 4τ (S21)."),
("La sobreoscilación Mp de un segundo orden subamortiguado depende…",
 ["Solo del amortiguamiento ζ",
 "Solo de la frecuencia natural ωn",
 "Del producto ζ·ωn",
 "De la amplitud del escalón de entrada"], 0,
 "Mp = e^(−πζ/√(1−ζ²)); ζ = 0.5 da ≈ 16 % (S21)."),
("Un sistema lineal es estable si y solo si…",
 ["Todas las raíces del polinomio característico tienen parte real negativa",
 "Su ganancia estática es menor que 1",
 "No tiene ceros en el semiplano derecho",
 "Su respuesta en frecuencia es plana"], 0,
 "El criterio del mapa del plano s; válido también en orden superior (S21)."),
("En la ley PID aplicada a una articulación, Kp y Kd actúan como…",
 ["Un muelle y un amortiguador virtuales",
 "Un filtro paso-bajo y otro paso-alto",
 "Dos ganancias redundantes con el mismo efecto",
 "Compensadores de gravedad y de fricción"], 0,
 "Lectura física de Lynch y Park: muelle y amortiguador virtuales (S22)."),
("Un controlador PD sobre un eslabón con gravedad deja error estacionario porque…",
 ["Sostener el eslabón exige un par no nulo, y el término P solo da par si hay error",
 "El término D amplifica el ruido del encoder",
 "La gravedad hace inestable el lazo",
 "El modelo del motor es de primer orden"], 0,
 "Kp·e = m·g·r·cosθ en el reposo; el término I lo elimina (S22)."),
("El «windup» del integrador aparece cuando…",
 ["El actuador se satura y la integral del error sigue acumulándose",
 "La ganancia Kd es demasiado alta",
 "El periodo de muestreo es demasiado corto",
 "La referencia cambia lentamente"], 0,
 "Al llegar al objetivo el par «tarda en desenrollarse»: gran sobreoscilación. Remedios: integración condicional o límite del integrador (S22)."),
("En la representación de espacio de estados, el estado x es…",
 ["La memoria mínima del sistema: lo que hay que conocer hoy para predecir mañana dadas las entradas",
 "El vector de salidas medidas por los sensores",
 "El error entre referencia y salida",
 "Una variable auxiliar sin significado físico"], 0,
 "x contiene toda la información dinámica necesaria (S23)."),
("La condición de controlabilidad de Kalman exige que…",
 ["La matriz [B, AB, A²B, …] tenga rango igual al orden del sistema",
 "A sea invertible",
 "B tenga tantas columnas como estados",
 "Todos los polos sean reales"], 0,
 "Si las direcciones de empuje no llenan el espacio, hay estados inalcanzables (S23)."),
("En la ecuación del manipulador M(q)·q̈ + C(q,q̇)·q̇ + g(q) = τ, el término que suele dominar es…",
 ["La gravedad g(q), que actúa incluso con el robot parado",
 "La matriz de inercia M(q)",
 "Los términos de Coriolis",
 "La fricción viscosa"], 0,
 "Corke: g es «generalmente el término dominante»; después la fricción (S24)."),
("Los términos de Coriolis y centrífugos de la dinámica del manipulador…",
 ["Solo aparecen en movimiento y crecen con el cuadrado de la velocidad articular",
 "Actúan también con el robot parado",
 "Son independientes de la configuración",
 "Se anulan con una reductora suficientemente grande"], 0,
 "Términos con productos de velocidades articulares (S24)."),
("El control por par calculado logra, con modelo perfecto, que la dinámica del error sea…",
 ["Lineal, desacoplada e independiente de la configuración",
 "No lineal pero estable",
 "De primer orden en todos los ejes",
 "Idéntica a la del PID articular independiente"], 0,
 "Cancela la dinámica con el modelo inverso: e¨ + Kv·ė + Kp·e = 0 (S24)."),
]

B[6] = [
("En el modelo estenopeico, la proyección u = f·X/Z implica que…",
 ["Un punto de la imagen corresponde a un rayo completo del espacio: la profundidad se pierde",
 "La imagen conserva las distancias métricas de la escena",
 "Los objetos lejanos se ven más grandes",
 "La focal no influye en la imagen"], 0,
 "La división por Z es la fuente de la ambigüedad de escala (S26)."),
("Los parámetros intrínsecos de una cámara (matriz K)…",
 ["Describen la cámara y no cambian al moverla; se calibran una vez",
 "Cambian en cada instante con el movimiento",
 "Incluyen la rotación y traslación respecto al mundo",
 "Solo son necesarios en cámaras estéreo"], 0,
 "Los extrínsecos (R, t) son el estado que estima la localización (S26)."),
("En una calibración con tablero de ajedrez, el criterio de calidad habitual es…",
 ["Error de reproyección por debajo de un píxel, con vistas variadas del tablero",
 "Que el tablero aparezca siempre centrado y frontal",
 "Un mínimo de 100 imágenes",
 "Que la focal calculada coincida con la nominal"], 0,
 "Vistas solo frontales degradan la estimación de la distorsión (S26, cuaderno S25)."),
("La convolución es la operación base del procesado clásico y además…",
 ["Es la misma operación que ejecuta cada capa convolucional de una CNN",
 "Solo sirve para suavizar imágenes",
 "Es exclusiva de las imágenes en color",
 "Fue sustituida por el umbralizado"], 0,
 "Suavizado, realce y derivadas, y el puente conceptual con el aprendizaje profundo (S27)."),
("«Los bordes de la imagen no son necesariamente los bordes de los objetos» (Corke). Un ejemplo típico es…",
 ["Una sombra proyectada que produce un gradiente fuerte sin frontera física",
 "Un objeto sin textura sobre fondo uniforme",
 "Una imagen sobreexpuesta",
 "El ruido térmico del sensor"], 0,
 "El gradiente marca discontinuidades de intensidad, no de materia (S27)."),
("¿Cuándo conviene elegir procesado clásico frente a aprendizaje profundo?",
 ["Con escena controlada, exigencia de determinismo y medición metrológica",
 "Siempre que haya GPU disponible",
 "Cuando los objetos son deformables y la iluminación variable",
 "Cuando hay millones de imágenes etiquetadas"], 0,
 "Clásico: transparente, métrico, sin datos de entrenamiento; aprendido: absorbe variabilidad (S27)."),
("La creencia (belief) de un robot es…",
 ["Una distribución de probabilidad sobre su estado, condicionada a medidas y controles pasados",
 "Su mejor estimación puntual de posición",
 "El mapa que ha construido hasta el momento",
 "La covarianza del ruido del sensor"], 0,
 "El robot no conoce su estado: mantiene y refina una distribución (S28)."),
("En el ciclo del filtro de Bayes, la predicción y la corrección hacen, respectivamente…",
 ["Crecer la incertidumbre (modelo de movimiento) y reducirla (verosimilitud de la medida)",
 "Reducir la incertidumbre y aumentarla",
 "Ambas reducen la incertidumbre",
 "Ambas la dejan igual si el robot no se mueve"], 0,
 "El latido predicción-corrección es el esqueleto de Kalman, EKF y partículas (S28)."),
("El filtro de Kalman mantiene la creencia gaussiana para siempre si…",
 ["El sistema es lineal, el ruido gaussiano y la creencia inicial gaussiana",
 "El robot se mueve despacio",
 "La covarianza inicial es pequeña",
 "Las medidas llegan a frecuencia constante"], 0,
 "Basta propagar media y covarianza; casi ningún robot real es lineal → EKF (S28)."),
("El riesgo característico del EKF es que…",
 ["Con no linealidad fuerte o incertidumbre grande puede divergir sin avisar",
 "Su coste crece exponencialmente con el tiempo",
 "No admite más de tres estados",
 "Necesita conocer la pose inicial exacta"], 0,
 "La linealización es una aproximación; la gaussiana deja de describir la creencia (S28)."),
("La localización global (pose inicial desconocida) se resuelve mejor con filtro de partículas que con EKF porque…",
 ["Las partículas representan creencias multimodales y una gaussiana no",
 "Las partículas son más precisas en el seguimiento fino",
 "El EKF no admite mapas de balizas",
 "El filtro de partículas no necesita modelo de movimiento"], 0,
 "«Estoy en uno de estos cuatro pasillos idénticos» no cabe en una gaussiana (S29/S30)."),
("El SLAM es un problema «circular» porque…",
 ["Para construir el mapa hay que saber dónde está el robot, y para saberlo hace falta el mapa",
 "El robot debe recorrer trayectorias cerradas",
 "Los sensores giran 360 grados",
 "La covarianza es una matriz circular"], 0,
 "Se resuelven ambos a la vez; el cierre de bucle corrige de golpe la deriva acumulada (S31)."),
]

B[7] = [
("En ROS 2, un nodo es…",
 ["Un proceso independiente que hace una cosa y se comunica por mensajes",
 "Un fichero de configuración del robot",
 "Un hilo del programa principal",
 "Un punto del árbol de transformadas"], 0,
 "El sistema es un grafo de nodos, no un programa único (S32)."),
("ROS 2 no tiene nodo maestro central (a diferencia de ROS 1) porque…",
 ["Se apoya en DDS, un estándar industrial con descubrimiento automático",
 "Cada nodo lleva su propio maestro embebido",
 "El maestro se sustituyó por un servidor web",
 "Ya no hace falta descubrir nodos"], 0,
 "DDS aporta el transporte publicación-suscripción y el descubrimiento (S32)."),
("Para un LiDAR publicando a 40 Hz, el perfil de QoS razonable es…",
 ["Best effort: si se pierde un barrido, llega otro en 25 ms",
 "Reliable con reintentos ilimitados",
 "Transient local con historial profundo",
 "Cualquiera: el QoS no afecta a sensores"], 0,
 "Reliable para órdenes críticas (parada); best effort para flujos de sensor densos (S32)."),
("Un publicador y un suscriptor con perfiles de QoS incompatibles…",
 ["No se conectan y no aparece ningún error visible: causa clásica de «no llega nada»",
 "Se conectan degradando al perfil menor",
 "Generan una excepción en ambos nodos",
 "Funcionan solo en la misma máquina"], 0,
 "El fallo silencioso que más tiempo consume a los principiantes (S32)."),
("Una tarea de larga duración que puede querer cancelarse (navegar hasta un punto) se modela en ROS 2 como…",
 ["Acción: objetivo, retroalimentación y cancelación",
 "Topic de alta frecuencia",
 "Servicio bloqueante",
 "Parámetro dinámico"], 0,
 "Nav2 y MoveIt 2 exponen sus interfaces principales como acciones (S33)."),
("La convención REP 105 encadena los marcos como…",
 ["map → odom → base_link, con odom→base continua pero derivante y map→odom corrigiendo a saltos",
 "odom → map → base_link, con map fijo al robot",
 "base_link → map → odom, sin deriva",
 "map → base_link directamente, sin marco intermedio"], 0,
 "Por eso el robot «salta» en RViz al cerrar un bucle (S34)."),
("Inflar los obstáculos del mapa con el radio del robot sirve para…",
 ["Tratar al robot como un punto en el espacio de configuraciones",
 "Aumentar la resolución del mapa",
 "Reducir el número de celdas del costmap",
 "Evitar la localización global"], 0,
 "El truco fundacional del C-space, implementado en la capa de inflado del costmap (S35)."),
("A* garantiza el camino óptimo solo si la heurística es admisible, es decir…",
 ["Nunca sobreestima el coste restante hasta la meta",
 "Es exactamente igual al coste real",
 "Es cero en todas las celdas",
 "Crece con la distancia recorrida"], 0,
 "Con h admisible, A* es óptimo y expande menos nodos que Dijkstra (S35)."),
("RRT domina la planificación en alta dimensión porque…",
 ["El árbol crece hacia muestras aleatorias sin discretizar todo el espacio",
 "Garantiza siempre el camino más corto",
 "No necesita detectar colisiones",
 "Funciona solo en dos dimensiones"], 0,
 "«Las muestras tiran del árbol»; admite además restricciones no holonómicas (S35)."),
("En Nav2, los costmaps se organizan en capas. Las tres típicas son…",
 ["Estática (mapa), obstáculos (sensores en vivo) e inflado (margen del robot)",
 "Global, local y de emergencia",
 "LiDAR, cámara y ultrasonidos",
 "Planificación, control y recuperación"], 0,
 "Se combinan en un único mapa de coste maestro (S36)."),
("La localización que usa Nav2 (AMCL) es…",
 ["El filtro de partículas adaptativo del bloque 6, convertido en un nodo",
 "Un EKF sobre balizas artificiales",
 "GPS diferencial filtrado",
 "Odometría pura de las ruedas"], 0,
 "La teoría de MCL corriendo en producción (S36)."),
("En MoveIt 2, planificar sin planning scene es un error porque…",
 ["Se planifica «contra el aire»: sin el modelo del mundo no hay comprobación de colisiones",
 "El robot no puede recibir objetivos",
 "OMPL no arranca sin escena",
 "La cinemática inversa deja de funcionar"], 0,
 "La escena integra robot, obstáculos y objetos percibidos (percepción de B6) (S37)."),
]

B[8] = [
("Los cinco elementos de un MDP son…",
 ["Estado, acción, transición, recompensa y descuento",
 "Sensor, actuador, controlador, planta y referencia",
 "Política, valor, modelo, crítico y actor",
 "Entrada, salida, estado, ruido y ganancia"], 0,
 "El esqueleto matemático del RL (S38)."),
("La mayoría de los fracasos prácticos del RL en robótica provienen de…",
 ["Recompensas mal especificadas que el agente explota de formas imprevistas",
 "Falta de potencia de cálculo",
 "Usar un factor de descuento igual a 1",
 "Sensores demasiado precisos"], 0,
 "Diseñar la recompensa es la parte difícil (S38)."),
("El objetivo del agente de RL es maximizar…",
 ["El retorno acumulado (con descuento), no la recompensa inmediata",
 "La recompensa del siguiente paso",
 "El número de estados visitados",
 "La entropía de su política"], 0,
 "La acción buena de ahora puede pagarse mucho después: recompensa retardada (S38)."),
("La estrategia epsilon-greedy responde al dilema…",
 ["Exploración frente a explotación",
 "Sesgo frente a varianza",
 "Modelo frente a datos",
 "Precisión frente a recall"], 0,
 "Con probabilidad ε explora una acción aleatoria; si no, explota la mejor conocida (S38)."),
("En la actualización de Q-learning, el corchete r + γ·max Q(s',a') − Q(s,a) es…",
 ["El error de diferencia temporal: la sorpresa entre lo esperado y lo observado",
 "La recompensa media del episodio",
 "El gradiente de la política",
 "La varianza del retorno"], 0,
 "α decide cuánto corregir con esa sorpresa (S38)."),
("Q-learning se llama «libre de modelo» porque…",
 ["Aprende solo de transiciones observadas (s, a, r, s'), sin conocer las probabilidades de transición",
 "No necesita función de recompensa",
 "No usa ninguna estructura de datos",
 "Funciona sin explorar"], 0,
 "Basta la experiencia; el modelo del mundo no se estima (S38)."),
("El Q-learning tabular no escala a un brazo de 6 ejes porque…",
 ["El estado es continuo y de alta dimensión: no cabe en una tabla y discretizar explota combinatoriamente",
 "La tabla converge demasiado rápido",
 "Los motores no admiten acciones discretas",
 "El descuento no está definido en continuo"], 0,
 "La maldición de la dimensionalidad; la salida es aproximar con redes (S38/S39)."),
("PPO se impuso como algoritmo de referencia en robótica porque…",
 ["Limita cuánto puede cambiar la política en cada paso y tolera hiperparámetros razonables",
 "Garantiza el óptimo global",
 "No necesita simulación",
 "Funciona sin red neuronal"], 0,
 "El recorte evita saltos destructivos; robusto sin ajuste fino (S39)."),
("El RL profundo se entrena en simulación y no directamente en el robot real porque…",
 ["Necesita millones de interacciones: en el robot serían años y varios robots rotos",
 "Los simuladores son más precisos que la realidad",
 "El hardware real no puede ejecutar redes",
 "La normativa lo prohíbe"], 0,
 "Simulación paralela masiva: horas en vez de años (S39)."),
("La aleatorización de dominio (domain randomization) consiste en…",
 ["Entrenar bajo parámetros físicos variables para forzar políticas robustas que crucen la brecha sim-to-real",
 "Elegir aleatoriamente el algoritmo de RL",
 "Cambiar el robot en cada episodio real",
 "Añadir ruido solo a las recompensas"], 0,
 "Fricción, masas, retardos y apariencia variables durante el entrenamiento (S39)."),
("El fallo característico del behavior cloning es que…",
 ["Al desviarse de lo demostrado entra en estados no vistos y el error se acumula",
 "Necesita una función de recompensa muy precisa",
 "Solo aprende tareas de locomoción",
 "Requiere explorar millones de estados"], 0,
 "Deriva por errores compuestos; motiva DAgger, ACT y las diffusion policies (S39)."),
("Ante un obstáculo que puede esquivarse por la izquierda o la derecha, una red que predice «la acción media» choca. Las diffusion policies lo resuelven porque…",
 ["Generan la distribución completa de acciones en lugar de su media",
 "Eligen siempre la izquierda por convenio",
 "Predicen con mayor frecuencia de muestreo",
 "Usan una recompensa más densa"], 0,
 "La multimodalidad exige modelar la distribución, no promediarla (S39)."),
]

# ── Salidas ──
os.makedirs("moodle", exist_ok=True)

def gift_escape(t):
    for c in "~=#{}:":
        t = t.replace(c, "\\" + c)
    return t

LETRAS = "ABCD"
for b, qs in B.items():
    assert len(qs) == 12, f"B{b}: {len(qs)}"
    lineas = [f"$CATEGORY: $course$/82514/Bloque {b}", ""]
    for i, (enun, ops, corr, fb) in enumerate(qs, 1):
        assert len(ops) == 4 and 0 <= corr <= 3
        lineas.append(f"::B{b}-{i:02d}::{gift_escape(enun)} {{")
        for j, op in enumerate(ops):
            pref = "=" if j == corr else "~"
            lineas.append(f"{pref}{gift_escape(op)}")
        lineas.append(f"####{gift_escape(fb)}")
        lineas.append("}")
        lineas.append("")
    open(f"moodle/Moodle_82514_B{b}.gift.txt", "w", encoding="utf-8").write("\n".join(lineas))
    print(f"B{b}: 12 preguntas")

import json as _json
_json.dump({str(k): v for k, v in B.items()}, open("banco.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("banco.json listo (96 preguntas)")
