// ============================================================ Guía de discusiones
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Guía de conducción de las discusiones y puestas en común de este bloque"));

children.push(p("El método general de conducción está desarrollado en los apuntes del bloque 1 y aquí se aplica sin cambios: los diez segundos de silencio después de formular la pregunta, sin reformular y sin contestarse; la distinción entre la pregunta cerrada de recuperación, las de los tramos que abren S39 y S40, que se corrigen en segundos y sirven para forzar recuperación activa, y la pregunta abierta de discusión; la votación a mano alzada para hacer visible el cambio de opinión, con su recuento antes y después; el reparto de la palabra con el que monopoliza y con el que nunca habla; y la exploración de la respuesta errónea antes de corregirla nombrando la fuente. Lo que cambia respecto a los dos bloques anteriores es la naturaleza de la materia, y conviene tenerlo presente desde el primer día. En los bloques 6 y 7 las discusiones eran de criterio técnico y nacían de un resultado del taller: un error de reproyección, una tabla de longitudes de camino, un topic que no fluye. Aquí vuelven a ser, como en el bloque 1, discusiones de juicio y de frontera. Se discute qué significa un factor de descuento, qué se puede y qué no se puede aleatorizar en un simulador, qué han demostrado los modelos fundacionales y qué se les atribuye, y qué haría falta para confiarle una célula a un sistema aprendido. Son las preguntas del debate de ética de S4 con vocabulario técnico, y se conducen con las mismas cautelas: se separa el hecho del juicio, se pide la condición de falsación y el profesor no coloca su opinión en el minuto uno."));
children.push(p("Eso no significa que no haya datos: significa que los datos no zanjan solos. Los tres cuadernos del bloque están construidos precisamente para dar sustancia numérica a discusiones que de otro modo serían de impresiones, y conviene tenerlos proyectados durante las puestas en común y no sólo durante el trabajo. En 82514_S38_MDP_Q_learning.ipynb está el barrido de gamma que desmonta la interpretación ingenua del descuento y el barrido de epsilon que sorprende a todo el mundo. En 82514_S39_RL_Profundo_SimToReal.ipynb está la rejilla de masas, longitudes y retardos que hace visible la brecha de realidad y lo que la aleatorización compra y no compra. Y en 82514_S40_Imitacion_VLA.ipynb están las cuarenta demostraciones con las que se ve la deriva por errores compuestos y el choque de la media contra el obstáculo, que son los dos argumentos con los que después se leen los papers de modelos fundacionales sin necesidad de creerse nada. La regla de conducción que se sigue de todo esto, y que es la propia de este bloque, es la del etiquetado: cada afirmación que se pone en la pizarra lleva delante una etiqueta, demostrado, en curso o esperado, y ninguna se acepta sin ella. Es un hábito, no un contenido, y es lo que el seminario de S41 y S42 evalúa."));
children.push(box("La regla añadida en este bloque", "Toda afirmación sobre lo que un sistema aprendido puede hacer se acompaña de tres datos: sobre qué se midió, en qué condiciones y quién lo midió. Sin esos tres datos, la afirmación no es un resultado sino una expectativa, y se escribe en la pizarra en otra columna. La distinción no es escepticismo: es la competencia profesional que se evalúa en el seminario y la que separa evaluar un proveedor de creerle."));

children.push(h2("La discusión de gamma en S38 (12–17 min): qué hace exactamente el descuento"));
children.push(h3("Objetivo"));
children.push(p("El guion pide discutir qué hace gamma, miopía frente a visión a largo plazo, y calcular un ejemplo numérico en la pizarra. El apartado 38.1 ya enuncia las tres funciones del descuento: garantizar que la suma sea finita en tareas continuas, expresar la preferencia por recompensa temprana y actuar como perilla de diseño, con gamma cercano a cero para el agente miope y del orden de 0,99 en robótica (Sutton y Barto, 2018, cap. 3). Leído así, gamma parece un parámetro de conveniencia matemática. El objetivo de estos cinco minutos es sustituir esa idea por una cuantitativa que el estudiante pueda usar: gamma fija un horizonte efectivo del orden de 1 dividido por 1 menos gamma pasos, y ese horizonte tiene que cubrir la tarea o la recompensa es literalmente invisible desde el punto de partida. Y hay un segundo objetivo, más fino y menos esperado, que es el que hace que la discusión merezca la pena: gamma cambia sobre todo cuánto vale estar en cada sitio y mucho menos hacia dónde ir, de modo que la intuición de que un agente con gamma pequeño se comporta como un cortoplacista es cierta solo cuando hay recompensas en conflicto. Descubrir eso vacuna contra la costumbre de ajustar gamma cuando la política sale mal."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 5 a 20 minutos cubre el problema del RL y el MDP, con el retorno con descuento y el ejercicio de formulación como puntos finales. La discusión de gamma ocupa del 12 al 17, y hay que llegar a ella con el retorno ya escrito en la pizarra y sin borrarlo. El reparto: de 12 a 13, un ejemplo numérico mínimo hecho a mano, una recompensa de valor uno a diez pasos vista con gamma igual a 0,9 y con gamma igual a 0,5, es decir, unas tres décimas frente a una milésima, porque sin ese contraste la discusión no tiene objeto. De 13 a 16, tres minutos de discusión con la pregunta de apertura. De 16 a 17, la regla del horizonte efectivo escrita en la pizarra. Un aviso de gestión: la tentación de introducir aquí el problema del descuento en tareas episódicas frente a continuas hay que resistirla, porque es una discusión de teoría del RL que se come el ejercicio de formulación, que es lo que de verdad prepara la sesión siguiente."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con las dos cifras del ejemplo en la pizarra: «Con gamma igual a 0,5, una recompensa que está a quince pasos vale tres cienmilésimas: para el agente, es como si no existiera. Con gamma igual a 0,99 vale casi lo mismo que si estuviera al lado. Pregunta: si a un robot que reparte piezas en una nave le ponéis gamma igual a 0,5, ¿qué hará exactamente? No me digáis que será miope; decidme qué hará.» La formulación importa: prohibir la palabra miope obliga a describir un comportamiento, y describir un comportamiento es lo único que demuestra comprensión. Conviene tener preparada la segunda pregunta para el minuto 15, que es la que produce el hallazgo: «¿Y si en la nave sólo hay un sitio donde ganar recompensa, cambiaría la dirección en la que se mueve?»"));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«Se quedará dando vueltas cerca de donde esté». ", bold: true },
 { text: "Es la respuesta más frecuente y es correcta en el caso general, pero hay que pedirle la condición porque tal como se dice es incompleta. Se cumple si hay alguna fuente de recompensa cercana que compita con la lejana; si la única recompensa está en la meta, el agente con gamma pequeño no se queda quieto: sigue yendo a la meta, solo que valora en casi nada estar lejos de ella. Ese matiz es exactamente lo que mide el barrido de 82514_S38_MDP_Q_learning.ipynb, y conviene proyectarlo: con gamma igual a 0,5 el valor de la esquina más alejada es el valor de no llegar nunca, y sin embargo la política óptima apenas cambia en cuatro o cinco estados de setenta. Ver ese resultado es lo que convierte la discusión en aprendizaje." },
]));
children.push(pRuns([
 { text: "«Entonces gamma no importa tanto». ", bold: true },
 { text: "Es la conclusión precipitada que sigue al resultado anterior y hay que corregirla con el caso que la desmiente, no con una advertencia. La pregunta de vuelta es qué pasaría si en la nave hubiera dos recompensas, una pequeña y cercana y otra grande y lejana: ahí gamma decide, y decide de forma abrupta. Conviene formularlo como regla: gamma no cambia la política cuando no hay conflicto temporal y la cambia por completo cuando lo hay, y en una tarea real siempre lo hay, un atajo arriesgado frente a un rodeo seguro, recargar ahora o entregar primero. Y la consecuencia de diseño: el conflicto temporal se puede introducir sin querer al añadir un término a la recompensa, y entonces gamma pasa de ser irrelevante a ser crítico sin que nadie lo haya tocado." },
]));
children.push(pRuns([
 { text: "«Pues pongo gamma igual a uno y ya está». ", bold: true },
 { text: "Sale siempre y es la ocasión de dar la respuesta que importa. Con gamma igual a uno, en una tarea sin final, la suma no converge y el valor es infinito en todas partes, con lo que ninguna política es mejor que otra. Pero hay una versión más interesante del problema que el propio cuaderno muestra y que conviene contar: con gamma muy cercano a uno y sin coste por paso, todas las políticas que acaban llegando valen lo mismo y el agente no tiene ningún motivo para darse prisa. De ahí sale la relación entre gamma y el coste por paso, que es la primera lección de diseño de recompensa del curso: el descuento ya codifica cierta prisa, llegar diez pasos más tarde multiplica la recompensa por 0,95 elevado a diez, es decir, unas seis décimas, y cuando gamma se acerca a uno esa prisa desaparece y hay que ponerla explícitamente." },
]));
children.push(pRuns([
 { text: "«¿Y cómo se elige gamma en un robot de verdad?». ", bold: true },
 { text: "Es la mejor pregunta del tramo y hay que contestarla con la regla operativa, que es lo único que se llevan de utilidad: se estima cuántos pasos de decisión dura la tarea y se elige gamma de forma que 1 dividido por 1 menos gamma sea de ese orden o mayor. Con un lazo de decisión a cincuenta hercios y una tarea de diez segundos son quinientos pasos, y por eso los valores habituales en robótica están en 0,99 o por encima. Conviene añadir la comprobación honesta: si al subir gamma el aprendizaje se vuelve inestable, el problema no es gamma, es que el horizonte largo aumenta la varianza de las estimaciones, y ése es el asunto que resuelven la línea base y la ventaja de la sesión siguiente." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es tratar gamma como un mando de comportamiento, lo subo y el robot se vuelve más previsor, en lugar de como lo que es, un parámetro que define el objetivo que se está optimizando. La diferencia parece filosófica y tiene consecuencias inmediatas: quien cree lo primero ajusta gamma cuando la política sale mal, del mismo modo que en el bloque 5 se ajustaba una ganancia, y eso convierte un problema de especificación en una búsqueda a ciegas. Se desmonta con los dos resultados del barrido del cuaderno puestos uno al lado del otro, y no cuesta más de un minuto de proyector. El primero: con la recompensa concentrada en la meta, cambiar gamma de 0,5 a 0,995 cambia los setenta valores y sólo cuatro o cinco decisiones, de modo que gamma no era el mando del comportamiento. El segundo: poner el coste por paso a cero con gamma igual a 0,95 tampoco cambia casi nada la política, pero sube todos los valores, porque vagar deja de costar. Los dos juntos dicen lo mismo desde dos lados: gamma y la recompensa definen conjuntamente qué se está pidiendo, y el comportamiento es la respuesta a esa pregunta y no un efecto que se pueda dosificar. El segundo error, más benigno, es confundir el descuento con la incertidumbre sobre el futuro; se desmonta señalando que la incertidumbre ya está en la dinámica del MDP y que el descuento sigue haciendo falta incluso con dinámica determinista."));
children.push(h3("Si la clase no habla"));
children.push(p("En el minuto 12 de la primera sesión de un bloque nuevo, y con una fórmula recién escrita, el silencio es de precaución. La maniobra de rescate es aritmética y sin riesgo: se pide a mano alzada cuánto vale una recompensa de cien unidades situada a veinte pasos con gamma igual a 0,9, se recogen dos o tres cifras y se escribe la buena. Hacer una potencia en voz alta no compromete a nadie y desbloquea. La segunda maniobra es la votación de tres opciones: para un robot que reparte piezas durante una jornada, gamma igual a 0,5, a 0,9 o a 0,99, mostrando los dedos y con recuento en la pizarra; el reparto casi siempre está dividido entre las dos últimas y de ahí se pide razón a cada lado. La tercera, para grupos muy callados, consiste en invertir la pregunta: en lugar de qué hace gamma, se pregunta cuánto tiene que valer para que la meta se note desde el otro extremo de la nave. Es la misma pregunta, tiene respuesta numérica y produce la regla del horizonte efectivo sin que el profesor la enuncie."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, escrita en la pizarra y con el número al lado: gamma define un horizonte efectivo del orden de 1 dividido por 1 menos gamma pasos, y ese horizonte tiene que cubrir la tarea; con gamma igual a 0,99 son unos cien pasos y con gamma igual a 0,9 son diez. El corolario que se lleva al examen y al proyecto: gamma no es un mando de comportamiento, es parte de la definición del objetivo, y cuando la política sale mal la primera sospecha es la recompensa y no el descuento. Lo que no conviene decir es que en la práctica se deja gamma en 0,99 y no se piensa más: es lo que se hace y es exactamente la frase que impide entender el fallo el día que la tarea dure más que el horizonte. Tampoco conviene abrir aquí la discusión de los MDP de horizonte finito ni la del descuento como aproximación a la probabilidad de terminación, aunque sean discusiones legítimas: se anotan en un rincón y se remiten a la bibliografía, porque los tres minutos siguientes son el ejercicio de formulación y es el que prepara el resto del bloque."));

children.push(h2("El ejercicio de formulación del MDP en S38 (17–20 min): S, A, recompensa y el reward hacking"));
children.push(h3("Objetivo"));
children.push(p("El guion pide proponer el caso del robot móvil que debe llegar al muelle de carga sin colisionar y construir con la clase el conjunto de estados, el de acciones y la recompensa, avisando del peligro del reward hacking. Es la primera vez en el curso que se pide especificar un objetivo en lugar de resolverlo, y ahí está el objetivo de estos tres minutos: que el estudiante experimente que la parte difícil del aprendizaje por refuerzo no es el algoritmo sino la especificación. La teoría lo enuncia con la hipótesis de la recompensa, todo objetivo puede expresarse como maximización de una recompensa escalar acumulada (Sutton y Barto, 2018, cap. 3), y con la advertencia de que el agente optimiza lo que se mide y no lo que se quiso decir. Pero enunciado es una frase ingeniosa y construido en la pizarra es una experiencia incómoda, que es como se aprende: en cuanto la clase propone una recompensa razonable, el profesor encuentra en veinte segundos la manera de cobrarla sin hacer la tarea, y esa asimetría entre lo fácil que es escribir una recompensa y lo fácil que es romperla es todo el contenido. Hay además un objetivo que se cobra dos días después: quien ha visto romper una recompensa entiende sin explicación por qué la manipulación se aborda por imitación."));
children.push(h3("Formato y tiempos"));
children.push(p("Son los tres minutos que van del 17 al 20, con el tramo de política y funciones de valor empezando en punto. Con tan poco margen el reparto tiene que estar decidido: de 17 a 18, se enuncia el caso y se piden los estados y las acciones, que son fáciles y salen a coro. De 18 a 19, se pide la recompensa y se escribe la primera propuesta tal cual, sin mejorarla. De 19 a 20, el profesor la rompe y se extrae la regla. Dos avisos de conducción. El primero: hay que escribir la propuesta de la clase literalmente, con sus términos y sus signos, incluso si es evidentemente mala, porque el valor del ejercicio está en romper la propuesta de la clase y no una propuesta de laboratorio. El segundo: romperla es el papel del profesor y no hay que delegarlo en la clase, porque encontrar el agujero exige experiencia y en tres minutos nadie lo encuentra; lo que sí hay que pedir a la clase es que arregle el agujero, que es la mitad productiva."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente: «Un robot móvil tiene que llegar al muelle de carga sin chocar. Estado y acciones, rápido. Y ahora lo difícil: escribid la recompensa. Quiero números y signos, no descripciones, la recompensa es lo único que el robot va a leer.» Insistir en números y signos es lo que evita respuestas del tipo de premiar el buen comportamiento, que no se pueden romper porque no dicen nada. Y para el minuto 19, la pregunta que cierra el ejercicio: «Con vuestra recompensa, ¿cuál es la forma más barata de ganar puntos sin llegar al muelle?»"));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«Más uno al llegar, menos uno al chocar». ", bold: true },
 { text: "Es la primera propuesta y es la correcta en su estructura; el problema es otro y conviene nombrarlo porque es el que van a sufrir: con esa recompensa el robot no recibe ninguna señal hasta que llega por casualidad, y en un almacén no llega por casualidad nunca. Es el problema de la recompensa dispersa, y de aquí sale sola la tentación de las recompensas conformadas de la sesión siguiente. La pregunta que lo hace visible es cuánto tarda un robot que se mueve al azar en tropezar con el muelle, y basta con recordar que en el gridworld de setenta celdas del cuaderno hicieron falta del orden de seis mil episodios con una tabla de doscientos ochenta números." },
]));
children.push(pRuns([
 { text: "«Le doy recompensa por acercarse». ", bold: true },
 { text: "Es la propuesta que hay que provocar si no sale, porque es la que se puede romper de forma memorable. Si la recompensa premia reducir la distancia al muelle, el robot puede cobrar acercándose, alejándose y volviendo a acercarse, indefinidamente, sin entrar nunca, que es el ejemplo clásico de práctica común del que ya avisa el apartado 38.1, el robot que aprende a vibrar junto a la meta para cosechar recompensa de aproximación. Contarlo así, con el robot vibrando delante del muelle, produce la risa que garantiza que se recuerde. Y después hay que pedir el arreglo, que es la parte que enseña: premiar el progreso neto y no el movimiento, o dar la recompensa como diferencia de un potencial, que es la formulación limpia del mismo remedio." },
]));
children.push(pRuns([
 { text: "«Le pongo un castigo por cada paso para que se dé prisa». ", bold: true },
 { text: "Es una propuesta buena y hay que reconocerla como tal, porque es exactamente lo que hace el gridworld del cuaderno con su coste por paso. Y hay que llevarla al límite, que es donde está el aprendizaje: si el castigo por paso es grande y el premio por llegar pequeño, la política óptima puede ser suicidarse contra el obstáculo más cercano para terminar el episodio, si terminar deja de acumular castigo. Es el mismo fenómeno con otra cara y conviene nombrarlo así: no hay recompensas seguras, hay recompensas cuyos agujeros conocemos. La comprobación que hay que exigir siempre es aritmética: calcular el retorno de la política que se quiere y el de la política tramposa, y ver cuál es mayor." },
]));
children.push(pRuns([
 { text: "«Entonces esto es imposible de hacer bien». ", bold: true },
 { text: "Aparece al final y es la conclusión honesta, no un lamento; hay que darle la razón parcial y añadir la salida. Sí, especificar recompensas para tareas ricas es endiabladamente difícil, y ésa es precisamente la razón por la que existe la mitad del contenido de S40: cuando demostrar la tarea es más fácil que especificarla, se demuestra. Conviene decirlo aquí con todas las letras, porque convierte la frustración de tres minutos en la motivación de la sesión del viernes, y porque es la tesis que ordena el bloque: el refuerzo domina donde la recompensa es fácil de escribir, la locomoción, y la imitación domina donde es fácil de demostrar, la manipulación." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es creer que una recompensa mal diseñada se detecta leyéndola. Es el error de método que garantiza que en el proyecto nadie compruebe nada: se escribe la recompensa, se lee, parece razonable, se entrena y se pierden dos días. Se desmonta con un procedimiento y no con un discurso, y el procedimiento cabe en una frase que conviene dictar: antes de entrenar, escribir dos políticas, la que se quiere y la tramposa más obvia, y comparar sus retornos con lápiz. Si la tramposa gana o empata, la recompensa está mal y ninguna cantidad de entrenamiento lo arreglará. El apoyo empírico está en el propio cuaderno 82514_S38_MDP_Q_learning.ipynb, cuya solución del primer ejercicio muestra el efecto de quitar el coste por paso: con el descuento cerca de uno y sin coste, todas las políticas que llegan valen lo mismo y el agente no tiene motivo para darse prisa; es decir, un cambio que parecía inocuo al leerlo altera el conjunto de políticas óptimas. El segundo error, más específico, es intentar arreglar una recompensa rota añadiendo términos: se desmonta señalando que cada término nuevo añade un agujero nuevo y un peso que ajustar, y que las funciones de recompensa con decenas de términos que usa la locomoción son un logro de ingeniería y no un modelo a imitar en un proyecto de un mes."));
children.push(h3("Si la clase no habla"));
children.push(p("Con tres minutos no hay margen para maniobras, así que la de rescate tiene que ser inmediata: el profesor escribe él mismo la primera recompensa, deliberadamente mala, más uno por cada metro que se acerque, y pide sólo una cosa, cómo la haríais trampa. Pedir que rompan algo ajeno es infinitamente más fácil que pedir que construyan algo propio, y una clase de máster encuentra el agujero en veinte segundos. La segunda maniobra, si tampoco arranca, es dar dos recompensas y pedir que elijan cuál es peor a mano alzada; con el recuento en la pizarra se pide una razón. Y hay una tercera que funciona con cualquier grupo porque apela a la experiencia y no al contenido: se pregunta si alguien conoce un indicador de su trabajo o de sus estudios que se pueda cumplir sin hacer lo que se pretendía medir. Siempre hay alguien con un ejemplo, y ese ejemplo es literalmente reward hacking en un sistema humano; de ahí volver al robot es un paso natural."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, en una frase que conviene escribir: el agente optimiza lo que se mide y no lo que se quiso decir, de modo que la recompensa no se lee, se ataca. El corolario operativo es el procedimiento de las dos políticas con lápiz antes de entrenar. Y el cierre correcto del tramo es el enlace, porque este ejercicio es el que justifica el resto del bloque: la dificultad de especificar es la razón de la imitación, y en el viernes se verá que a veces enseñar es más barato que definir. Lo que no conviene hacer es dejar en la pizarra una recompensa arreglada y presentarla como la solución del caso: da la impresión falsa de que hay una recompensa correcta que se puede encontrar en tres minutos, y lo que hay que llevarse es lo contrario. Tampoco conviene contar más de un ejemplo divertido de reward hacking, por tentador que sea: los ejemplos son abundantes y muy comentables, pero cada uno cuesta un minuto y a las veinte hay que estar en las funciones de valor, que es materia literal de examen."));

children.push(h2("La discusión de sim-to-real en S39 (50–57 min): qué se puede y qué no se puede aleatorizar"));
children.push(h3("Objetivo"));
children.push(p("El guion la plantea como debate breve por parejas sobre qué parámetros aleatorizar para transferir una política de empuje de cajas con el brazo del laboratorio, recogiendo tres o cuatro respuestas. El apartado 39.3 ya explica la brecha de realidad y la aleatorización de dominio con sus dos referencias, la formulación original con aleatorización visual (Tobin et al., 2017, arXiv:1703.06907) y el caso extremo de la mano resolviendo el cubo de Rubik con aleatorización automática (OpenAI et al., 2019, arXiv:1910.07113). Lo que la discusión tiene que producir, y la exposición no puede, son tres cosas concretas. La primera es un criterio para ordenar candidatos, que no es la intuición sino cuánto cambia la dinámica que la política no observa. La segunda es la distinción entre lo que se mide y lo que se aleatoriza: masa, geometría y latencia se miden barato en el laboratorio, y medirlas permite estrechar las distribuciones en lugar de ensancharlas a ciegas. La tercera, y es la más importante y la que casi nunca se enuncia, es que la aleatorización no garantiza robustez universal: garantiza, a lo sumo, rendimiento sobre la distribución que se aleatorizó, y si el robot real cae fuera de esa familia la política no tiene ninguna razón para funcionar. Esa frase, bien entendida, es la vacuna contra la única forma de superstición que este bloque puede generar."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 50 a 60 minutos es de discusión y cierre, con el anuncio de S40 y el recordatorio logístico del seminario ocupando los últimos tres minutos. La discusión tiene siete minutos, del 50 al 57. El reparto: de 50 a 52, dos minutos en parejas con una consigna cerrada y exigente, tres parámetros ordenados, y para cada uno una frase de por qué, porque pedir una lista sin orden produce lluvia de ideas y no criterio. De 52 a 56, cuatro minutos de recogida ordenada, escribiendo los candidatos en la pizarra en dos columnas: los que se miden y los que se aleatorizan. De 56 a 57, la regla de cierre. Un aviso de gestión que decide el resultado: hay que exigir el orden. Si se aceptan listas, la discusión acaba con quince parámetros en la pizarra, todos razonables, y sin ninguna decisión, que es precisamente el vicio que la aleatorización de dominio induce en la práctica."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente: «Tenéis una política de empuje de cajas entrenada en simulación y el brazo del laboratorio delante. Sólo podéis aleatorizar tres cosas, porque cada una que añadís hace el entrenamiento más largo y la política más conservadora. ¿Cuáles tres, en orden, y por qué esas?» La restricción a tres es artificial y es la clave del formato: obliga a jerarquizar, que es lo único que se quiere enseñar. Y conviene tener preparada la segunda pregunta para el minuto 55, que es la que introduce el matiz de fondo: «De vuestros tres, ¿cuáles podríais medir en el laboratorio esta tarde con una balanza y un cronómetro?»"));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«La fricción entre la caja y la mesa». ", bold: true },
 { text: "Sale primero y es la respuesta correcta para el primer puesto; el trabajo es que digan por qué y no sólo qué. La razón es doble y conviene explicitarla: es el parámetro peor conocido, no está en ningún catálogo y cambia con el polvo, la humedad y el uso, y es el que más cambia la respuesta al empuje, es decir, la dinámica que la política no observa directamente. Ése es el criterio de ordenación que hay que dejar escrito, porque sirve para cualquier tarea: se aleatoriza primero lo que peor se conoce y más afecta a la dinámica no observada." },
]));
children.push(pRuns([
 { text: "«La masa de la caja» y «la posición inicial». ", bold: true },
 { text: "Las dos aparecen y hay que tratarlas de forma distinta, porque no son la misma clase de cosa y confundirlas es el error conceptual del tramo. La masa es un parámetro físico que cambia la dinámica y se aleatoriza por robustez; la posición inicial no cambia la dinámica en absoluto, y aleatorizarla es cobertura de estados, es decir, asegurarse de que la política ha visto la variedad de situaciones en las que tendrá que actuar. Las dos son necesarias y por razones distintas, y quien no las distingue acaba creyendo que aleatorizar la posición inicial le da robustez a la fricción. Conviene además señalar el contraste con la masa: la masa de la caja se mide con una balanza en treinta segundos, y por tanto es candidata a medirse y no a aleatorizarse a ciegas." },
]));
children.push(pRuns([
 { text: "«La latencia de la red», si alguien la nombra. ", bold: true },
 { text: "Es el candidato que hay que aportar si no sale, y sale menos de lo que debería porque es invisible. Merece el segundo puesto y hay que defenderlo con el resultado del taller, que es contundente: en la rejilla de 82514_S39_RL_Profundo_SimToReal.ipynb, un retardo de tres pasos a cincuenta hercios, sesenta milisegundos, es decir, nada en un robot con bus de campo y ciclo de autómata, se lleva por delante en torno a un tercio del rendimiento medio de una política que en su mundo de entrenamiento saca el máximo, y su peor casilla se hunde a quince pasos de los quinientos posibles. Proyectar esa rejilla es el momento más eficaz de la discusión, porque nadie espera que la latencia sea peor que la masa. Y hay una lectura adicional que el cuaderno hace explícita y que conecta con el bloque 5: la política robusta traslada la ganancia del término de velocidad al de posición, es decir, redescubre sola que las señales derivadas son las que se vuelven peligrosas cuando hay retardo en el lazo, porque realimentan información caducada." },
]));
children.push(pRuns([
 { text: "«Aleatorizamos todo y así vale para cualquier robot». ", bold: true },
 { text: "Es la respuesta que hay que desmontar y la que da sentido a los siete minutos. Tiene dos defectos y conviene separarlos. El primero es de rendimiento: aleatorizar de más produce políticas conservadoras, que sacrifican desempeño en el caso nominal para sobrevivir a casos que no van a ocurrir. El segundo es de alcance y es el más importante: la aleatorización no garantiza robustez universal, garantiza rendimiento esperado sobre la familia de mundos que se aleatorizó, tal como muestra el ejercicio 2 del cuaderno, donde la política robusta sigue siendo mejor que la especializada fuera del rango pero cae mucho, y con retardos de seis a ocho pasos las dos fracasan. La formulación correcta hay que dictarla: es un cambio de objetivo, no una propiedad mágica, se pasa de optimizar el retorno en un mundo a optimizar el retorno esperado sobre una familia de mundos." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es entender la aleatorización de dominio como un seguro: si aleatorizo suficiente, funcionará en el robot. Es un error de lógica, confundir cobertura con garantía, y es especialmente peligroso porque el discurso divulgativo lo alimenta. Se desmonta con el ejercicio 2 del propio cuaderno y no con una advertencia, porque el dato es inapelable: dentro del rango aleatorizado la política aguanta en toda la rejilla de masas y longitudes; fuera del rango se degrada de forma clara; y con un retardo mayor del que vio en entrenamiento fracasa igual que la especializada. Es decir, la aleatorización no crea robustez, la compra dentro de un perímetro que uno mismo ha dibujado. Y de ahí sale la práctica profesional completa, que conviene dejar escrita en dos líneas: se mide lo que se puede medir barato, masa, geometría, latencias, para centrar las distribuciones donde de verdad está el robot, y se aleatoriza lo que no se puede medir, ampliando los rangos a medida que la política mejora, que es la aportación de la aleatorización automática del caso del cubo de Rubik (OpenAI et al., 2019, arXiv:1910.07113). El segundo error, más sutil, es creer que aleatorizar sólo puede mejorar; se desmonta con la observación honesta que el propio cuaderno hace y que conviene no esconder: en ese ejemplo concreto la política robusta no paga peaje en el mundo nominal, pero en general sí lo paga, y presentar la aleatorización como gratis es inexacto."));
children.push(h3("Si la clase no habla"));
children.push(p("Después de dos minutos en parejas la clase habla, y si no habla es porque la consigna era demasiado abstracta. La maniobra de rescate es hacer la pregunta física: se coge una caja de verdad, o el estuche de alguien, y se empuja sobre la mesa del aula, primero sobre la mesa y luego sobre una hoja de papel, preguntando qué ha cambiado. La respuesta es la fricción, la ha visto todo el mundo y la lista arranca sola. La segunda maniobra es la votación por parámetros: el profesor enuncia seis candidatos, fricción, masa, geometría de la caja, latencia, posición inicial, iluminación, y pide levantar la mano en los tres que aleatorizarían; el recuento en la pizarra ya es un orden, y basta preguntar por qué el más votado y por qué el menos. La tercera, para grupos frías, es la inversión: en lugar de preguntar qué aleatorizar, se pregunta qué medirían si tuvieran una tarde de laboratorio; la lista de medidas es fácil y la de aleatorizaciones es lo que queda fuera, que es exactamente la regla que se quiere enseñar."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar cabe en la frase que ya está en el cuaderno y que conviene dictar: mide lo que puedas medir barato y aleatoriza lo que no. Y con la precisión de alcance, que es la que hay que escribir: la aleatorización garantiza rendimiento sobre la familia de mundos que se aleatorizó y no promete nada fuera de ella. El corolario para el proyecto y para el seminario: cuando un artículo presente una transferencia exitosa, la pregunta no es si aleatorizaron, es qué rango aleatorizaron y si el robot real cae dentro. Lo que no conviene decir es que con suficiente aleatorización el problema sim-to-real está resuelto: es la afirmación más extendida y más falsa del área, y desmontarla es el objetivo mismo de la sesión. Tampoco conviene abrir la discusión de la identificación de sistemas ni del ajuste fino sobre el robot real más allá de nombrarlos, aunque alguien pregunte: están mencionados como complementos habituales en el apartado 39.3, se anotan y se remiten, porque los tres minutos que quedan son para anunciar la sesión de imitación y recordar la logística del seminario, que no admite retraso."));

children.push(h2("La discusión de imitación frente a refuerzo en S40 (32–35 min): por qué cada uno domina donde domina"));
children.push(h3("Objetivo"));
children.push(p("El guion la fija en tres minutos, con la respuesta esperada anotada: demostrar manipulación es fácil con teleoperación, demostrar locomoción dinámica es casi imposible, y la recompensa de locomoción es más fácil de especificar. El apartado 40.1 lo dice ya, e incluso señala que es una pregunta excelente para el examen oral del seminario. El objetivo de la discusión no es, por tanto, obtener esa respuesta, que se puede leer, sino que el estudiante la derive de un criterio general y aplicable: dado un problema nuevo, ¿es más barato especificar el éxito o demostrarlo? Con ese criterio se decide en un proyecto real, y sin él la división entre familias parece una casualidad histórica. Hay un segundo objetivo, de calibración de expectativas, que se cobra en el resto de la sesión: la clase tiene que entender que las dos familias no son dos técnicas rivales sino dos formas distintas de introducir el conocimiento humano en el sistema, una por la función objetivo y otra por los datos, porque es lo que permite entender que los modelos fundacionales del apartado 40.3 sean fundamentalmente imitación a escala y no una tercera cosa."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 10 a 35 minutos es el de clonación de comportamiento y sus límites, y la discusión es su punto final: tres minutos, del 32 al 35, con el tramo de políticas de difusión empezando en punto. El reparto: en el minuto 32 se dibuja en la pizarra una tabla de dos columnas, locomoción y manipulación, y dos filas, cuánto cuesta escribir la recompensa, cuánto cuesta demostrar la tarea, se enuncia la pregunta y se callan diez segundos. De 32 a 34, se rellenan las cuatro celdas con la clase. De 34 a 35, la regla de cierre. La tabla de cuatro celdas es lo que hace que esto quepa en tres minutos: sin ella, la pregunta invita a un discurso, y con ella la discusión es rellenar huecos con argumentos. Un aviso de conducción: conviene tener a mano el vídeo de locomoción con el que se abrió el bloque, porque la celda difícil, por qué no se puede demostrar la locomoción, se resuelve en cinco segundos mostrando a un cuadrúpedo corrigiendo un resbalón, y en dos minutos de palabras no se resuelve."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con la tabla dibujada: «Dos tareas: que un cuadrúpedo corra por grava y que un brazo doble una camiseta. Para cada una, dos preguntas: cuánto cuesta escribir la recompensa y cuánto cuesta demostrar la tarea. Rellenadme las cuatro casillas con caro o barato, y justificad las dos que os parezcan menos evidentes.» Pedir caro o barato en lugar de una explicación es lo que fuerza el compromiso y hace visible el patrón en cuanto la tabla está llena, porque la diagonal salta a la vista. Y conviene la segunda pregunta para el minuto 34: «Con esta tabla, ¿qué haríais con una tarea nueva, por ejemplo un robot que tiene que abrir una puerta con manilla?»"));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«La recompensa de la locomoción es fácil: que avance». ", bold: true },
 { text: "Es la respuesta correcta y hay que matizarla con honestidad porque la simplificación es excesiva: la recompensa de una política de locomoción real tiene decenas de términos, velocidad, orientación, consumo, altura del cuerpo, suavidad de los pares, penalización por contacto indebido, y ajustarla es un trabajo considerable. Lo que sí es cierto, y es lo que hay que rescatar, es que todos esos términos son magnitudes medibles con la sensórica que el robot ya lleva, y ahí está la diferencia. La formulación precisa que conviene dejar escrita: la recompensa de locomoción es cara de afinar y fácil de instrumentar; la de doblar una camiseta no se sabe ni instrumentar." },
]));
children.push(pRuns([
 { text: "«La camiseta se demuestra: le enseñas y ya está». ", bold: true },
 { text: "Se acepta y se cuantifica, porque el dato es lo que convence: con teleoperación bimanual de bajo coste y unas decenas de demostraciones se consiguen tareas de precisión como insertar una pila o abrir una tapa (Zhao et al., 2023, arXiv:2304.13705). Unas decenas de demostraciones es una tarde de trabajo, y ése es el orden de magnitud que hay que fijar frente a los millones de transiciones que consume el refuerzo. Conviene añadir de inmediato la contrapartida, que ya se ha visto en el taller de la sesión: demostrar es barato y el clon es frágil, porque hereda todos los problemas de la generalización fuera de la distribución demostrada." },
]));
children.push(pRuns([
 { text: "«¿Y por qué no se puede demostrar la locomoción?». ", bold: true },
 { text: "Es la celda difícil y la pregunta buena. Hay que responderla con el vídeo y con una frase: para demostrar una carrera sobre grava habría que teleoperar doce articulaciones coordinadas a cientos de hercios corrigiendo resbalones que duran milisegundos, y eso no lo hace ninguna persona con ningún mando. La generalización que hay que extraer es de interfaz y no de dificultad: se puede demostrar lo que un humano puede ejecutar a través de una interfaz de teleoperación con el ancho de banda disponible, y la manipulación cabe en ese canal mientras la locomoción dinámica no. Dicho así, el criterio sirve para tareas nuevas, que es lo que se pretende." },
]));
children.push(pRuns([
 { text: "«Para la puerta, las dos cosas». ", bold: true },
 { text: "Es la respuesta madura a la segunda pregunta y hay que celebrarla, porque es la que corresponde a la práctica actual: demostraciones para tener una política razonable de partida y refuerzo para afinarla donde la recompensa sí se puede medir, abrió o no abrió. Conviene nombrar la estructura sin entrar en detalle, porque el detalle no es materia del curso: preentrenar por imitación y ajustar por refuerzo es el patrón dominante, y es la misma división de trabajo que la clase ya ha visto dos veces en el semestre, con el prealimentado y el realimentado del bloque 5 y con el planificador global y el controlador local del bloque 7." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es asociar cada familia a un tipo de robot en lugar de a un tipo de conocimiento disponible: el refuerzo es para patas y la imitación para brazos. Es cómodo, funciona como regla mnemotécnica y falla en el primer caso nuevo. Se desmonta con dos contraejemplos y con el criterio: hay locomoción aprendida por imitación de datos de captura de movimiento y hay manipulación aprendida por refuerzo en tareas donde el éxito es medible, insertar un conector, apretar un tornillo, y lo que decide en cada caso no es la morfología sino cuál de las dos cosas está disponible, la especificación o la demostración. El apoyo empírico está en los dos cuadernos del bloque puestos uno al lado del otro, y conviene señalarlo aunque no haya tiempo de proyectarlo: en 82514_S39_RL_Profundo_SimToReal.ipynb la política se obtiene sin ninguna demostración, sólo con un retorno que se puede calcular en cada episodio; en 82514_S40_Imitacion_VLA.ipynb se obtiene sin ninguna recompensa, sólo con cuarenta trayectorias etiquetadas. Ninguno de los dos cuadernos habla de patas ni de brazos. El segundo error, muy frecuente y con consecuencias en el proyecto, es suponer que la imitación no necesita evaluación porque copia al experto; se desmonta con el resultado del propio taller, donde el clon reproduce las acciones del demostrador hasta el suelo de ruido y sin embargo choca en cuanto recibe un empujón, el error de predicción sobre los datos y el éxito en la tarea son dos cosas distintas y no hay que confundirlas nunca."));
children.push(h3("Si la clase no habla"));
children.push(p("Con la tabla dibujada el silencio es breve, pero si aparece la maniobra de rescate es pedir la celda fácil por nombre: cuánto cuesta demostrar cómo se dobla una camiseta. Es una pregunta que cualquiera contesta y una vez que hay una celda escrita las otras tres se piden por comparación. La segunda maniobra es la votación cruzada, que además es divertida y despierta al grupo a los treinta minutos de clase: quién preferiría pasar una tarde escribiendo la función de recompensa de doblar una camiseta y quién preferiría pasarla teleoperando el robot para doblarla treinta veces. El reparto es siempre abrumador y el reparto es la respuesta. La tercera, para grupos muy callados, es dar la tabla ya rellena con una celda mal puesta y pedir que encuentren el error; encontrar un error en una tabla ajena es una tarea sin riesgo social y produce inmediatamente la justificación de las cuatro celdas."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, en una frase que conviene escribir: la elección entre refuerzo e imitación no la decide el robot, la decide qué es más barato en ese problema, especificar el éxito o demostrarlo. El corolario que ordena la sesión y prepara el apartado de modelos fundacionales: los sistemas de manipulación que se van a ver a continuación son imitación a escala, y por eso arrastran los problemas de la imitación, deriva por errores compuestos y multimodalidad, por muchos parámetros que tengan. Lo que no conviene hacer es cerrar dando una de las dos familias como más avanzada o más prometedora: no lo son, y esa jerarquía es exactamente la que impide entender la sesión siguiente. Tampoco conviene abrir aquí el aprendizaje por refuerzo inverso ni la recompensa aprendida de preferencias, aunque alguien los nombre y sean pertinentes: se anotan como material excelente para el seminario y se sigue, porque el tramo de políticas de difusión necesita sus veinte minutos íntegros y es el que da el argumento técnico del bloque."));

children.push(h2("La discusión de los modelos VLA en S40 (80–90 min): qué cambian y qué no"));
children.push(h3("Objetivo"));
children.push(p("Es la discusión de frontera del bloque y la más delicada de todo el curso, y conviene decir por qué antes de dar cualquier indicación de conducción: es la única en la que el material es tan reciente y tan mediático que la mitad de la clase llega con una posición formada por vídeos y titulares, y en la que el profesor no puede zanjar con una página de libro porque no hay libro. El apartado 40.3 hace el trabajo de fondo, la genealogía de RT-2 a OpenVLA, π0 y GR00T N1, los tres ingredientes comunes y el inventario honesto de limitaciones, y el objetivo de la discusión es exclusivamente uno: que la clase salga sabiendo separar lo demostrado de lo prometido, y sabiendo que esa separación es una competencia profesional y no una actitud. Lo que debe quedar aprendido, en positivo, son dos afirmaciones que sí se pueden sostener: que lo que estos modelos cambian es quién escribe la consigna y cómo se especifica la tarea, el lenguaje pasa a ser la interfaz, y que lo que no cambian es nada de lo que hay por debajo, porque la consigna sigue ejecutándose sobre la cinemática del bloque 4, los lazos del bloque 5, la percepción del bloque 6 y el middleware del bloque 7. La diferencia con la teoría es de hábito: el apartado se puede leer y asentir, y la discusión obliga a etiquetar cada afirmación."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 65 a 90 minutos es el de modelos fundacionales, y la discusión hay que integrarla en su segunda mitad, no añadirla al final: de 65 a 80, la exposición de la genealogía y de los tres ingredientes, con los vídeos que hagan falta para que la conversación tenga objeto. De 80 a 88, ocho minutos de discusión. De 88 a 90, el cierre. Después vienen el gemelo digital y la síntesis del curso, que necesitan quince minutos, y el cuestionario, que no se mueve. Dos avisos de conducción específicos de las discusiones de frontera, y son los que evitan que esto derive en especulación. El primero es anunciar el marco antes de abrir la discusión, en voz alta y sin ironía: en estos ocho minutos vamos a clasificar afirmaciones en tres columnas, demostrado, en curso y esperado, y las tres son legítimas siempre que estén etiquetadas. El segundo es dibujar físicamente esas tres columnas en la pizarra antes de la primera intervención, porque una discusión de frontera sin soporte visual se convierte en un intercambio de entusiasmos en noventa segundos, y con las tres columnas dibujadas cada intervención tiene que ir a alguna parte."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con las tres columnas dibujadas y el último vídeo todavía en pantalla: «Acabamos de ver un robot doblando ropa después de una instrucción hablada, y es real. Ahora quiero que lo desmontemos como ingenieros: decidme una afirmación sobre lo que este sistema puede hacer, y decidme en qué columna la ponemos y por qué. Empiezo yo con una fácil: emite acciones articulares continuas a cincuenta hercios, y eso va en demostrado, porque está medido y publicado (Black et al., 2024, arXiv:2410.24164).» Que el profesor coloque la primera ficha es esencial: define el nivel de precisión exigido y demuestra que la columna de lo demostrado no está vacía, lo que evita que la discusión se lea como un ejercicio de escepticismo."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«Entiende lo que le dices». ", bold: true },
 { text: "Es la primera afirmación y la que más trabajo da, porque mezcla un hecho con una interpretación. El hecho, que va a la columna de lo demostrado, es que estos sistemas ejecutan instrucciones sobre objetos y conceptos que no aparecían en los datos de robot, y que esa generalización semántica la heredan del preentrenamiento con datos de internet, es literalmente la aportación de RT-2 (Brohan et al., 2023, arXiv:2307.15818). La interpretación, que no va a ninguna columna sino a un margen, es la palabra entender. Conviene no abrir el debate filosófico y sustituirlo por una pregunta operativa que sí tiene respuesta y sí es útil: qué generaliza mejor, lo semántico o lo motriz. La respuesta está en el propio apartado y hay que dejarla escrita, porque es de las cosas más útiles que se llevan del bloque: el modelo generaliza mejor los objetos nuevos que las destrezas nuevas." },
]));
children.push(pRuns([
 { text: "«Ya no hace falta programar el robot». ", bold: true },
 { text: "Es la afirmación que va a salir con más convicción y la que hay que trabajar con más cuidado, porque contiene una verdad parcial. Lo que es cierto, y va a lo demostrado, es que la tarea se especifica en lenguaje en lugar de programarse paso a paso, lo cual es un cambio real de interfaz. Lo que es falso es la consecuencia implícita de que debajo no haya nada: la salida del modelo son consignas a entre tres y cincuenta hercios que alguien tiene que convertir en pares y movimientos, y ese alguien son los lazos del bloque 5 corriendo a kilohercios sobre los actuadores del bloque 3. La forma de dejarlo claro sin discutir es pedir el número: a cincuenta hercios, ¿cuántos ciclos de control hay entre dos consignas? Con la respuesta, del orden de veinte o más, la arquitectura se ve sola." },
]));
children.push(pRuns([
 { text: "«Esto ya está en las fábricas». ", bold: true },
 { text: "Va a la columna de en curso y no a la de demostrado, y hay que ser preciso porque la diferencia es la que separa una decisión de inversión de un titular: en 2026 estos sistemas están en pilotos industriales, no en producción masiva. Y hay que dar las tres razones concretas del apartado 40.3, porque son las que un ingeniero necesita para argumentar en su empresa: las tasas de éxito en tareas largas siguen lejos del cien por cien que exige una línea; la latencia y el cómputo dificultan el despliegue a bordo; y no existe todavía una evaluación estandarizada comparable entre laboratorios, porque cada trabajo elige sus tareas. La tercera razón es la más importante y la que menos se nombra, y conviene detenerse en ella: sin evaluación común, comparar dos sistemas por sus cifras publicadas no significa nada." },
]));
children.push(pRuns([
 { text: "«En cinco años esto lo hará todo». ", bold: true },
 { text: "Va a la columna de lo esperado y ahí no se discute: se le pide la condición de falsación, que es la maniobra que convierte una predicción en criterio. La pregunta, dicha sin ironía, es qué habría que ver publicado el año que viene para creérselo, y la lista que la clase construye suele ser buena, tasas de éxito sostenidas en tareas de decenas de pasos, evaluación común entre laboratorios, cómputo embarcado, y datos sobre cuánto cuesta adaptar el modelo a un robot nuevo. Con eso la afirmación se ha convertido en una lista de criterios de evaluación, que es exactamente lo que el seminario pide en enero. Conviene señalar en voz alta que ese giro es la maniobra profesional que hay que hacer con cualquier promesa tecnológica, y que se practicó ya en el bloque 6 con las representaciones neuronales del mapa." },
]));
children.push(h3("Cómo distinguir lo demostrado de lo prometido"));
children.push(p("Merece apartado propio porque es el contenido real de estos ocho minutos y porque es lo que se evalúa en el seminario. La herramienta son cuatro preguntas, y conviene escribirlas en la pizarra la primera vez y dejarlas escritas todo el rato. La primera es qué se midió exactamente: no éxito, sino tasa de éxito sobre cuántos intentos, en cuántas tareas y con qué criterio de éxito, porque en manipulación el criterio de éxito es a menudo la mitad del resultado. La segunda es en qué condiciones: qué robot, qué escena, quién colocaba los objetos, si había reinicios manuales entre intentos y si la escena estaba dentro o fuera de la distribución de entrenamiento, y aquí la pregunta más rentable de todas, que es si se evaluó con objetos nuevos o con los mismos. La tercera es quién lo midió y si es reproducible: pesos públicos y datos públicos como en OpenVLA (Kim et al., 2024, arXiv:2406.09246) no es lo mismo que un informe técnico sin código, y no se trata de desconfiar sino de saber qué se puede verificar. La cuarta es qué se afirma como resultado y qué como perspectiva, distinción que en los propios artículos suele estar razonablemente clara y que se difumina en la divulgación y en las presentaciones de empresa. Aplicadas a esta discusión, las cuatro preguntas producen la posición defendible que hay que dejar en la pizarra con sus etiquetas: la generalización semántica está demostrada; la ejecución de tareas largas con fiabilidad industrial no lo está; el control multiplataforma con una sola política está demostrado en el perímetro de los datos de entrenamiento y en curso fuera de él; y la sustitución del stack clásico no está ni demostrada ni propuesta por los propios autores, que describen sus modelos como generadores de consignas."));
children.push(h3("El estudiante convencido de que los fundamentos ya no hacen falta"));
children.push(p("Aparece todos los años, casi siempre es bueno, y su intervención suele llegar en el minuto 84 formulada como pregunta retórica: si el modelo aprende directamente de píxeles a acciones, para qué hemos hecho cinemática y control. Lo primero que conviene tener claro es que no se le puede contestar por autoridad, porque la respuesta por autoridad es indistinguible de la defensa corporativa del temario y la clase lo percibe al instante; y lo segundo es que no hay que ridiculizarlo ni desactivarlo, porque su pregunta es exactamente la que hay que contestar y porque el coste de silenciarlo lo paga toda la clase. La secuencia que funciona tiene cuatro pasos y ocupa dos minutos. Primero, reformular su posición en su versión más fuerte y pedirle confirmación, sostiene que si el mapa de píxeles a acciones se aprende de punta a punta, las representaciones intermedias son innecesarias, lo que le quita la necesidad de subir el tono y suele ser lo único que buscaba. Segundo, darle la razón en lo que la tiene, y la tiene en algo importante: hay componentes que hasta hace cinco años se diseñaban a mano y hoy se aprenden mejor, y la percepción de apariencia del bloque 6 es el ejemplo más claro. Tercero, pedir el número en lugar de dar el argumento: a qué frecuencia emite consignas el modelo del vídeo y a qué frecuencia hay que cerrar el lazo de par de ese brazo para que no se caiga; la respuesta, cincuenta hercios frente a kilohercios, la da él mismo, y la conclusión de que entre dos consignas hay veinte o más ciclos de control que alguien tiene que ejecutar es suya y no del profesor. Cuarto, devolver la pregunta al grupo con un caso concreto en lugar de cerrarla: qué pasa si la consigna llega tarde una vez, o si el modelo pide una pose que está fuera del espacio de trabajo, o dentro de una singularidad. Ahí aparecen sin ayuda la comprobación de alcanzabilidad del bloque 4 y los límites del bloque 3, y aparecen como necesidades del propio sistema aprendido y no como contenido que hay que defender. Conviene rematar con el dato más honesto y más contundente, que además es el que el propio apartado 40.3 subraya: la seguridad del bloque 2 permanece deliberadamente fuera del modelo, porque la norma exige garantías que una red entrenada no puede ofrecer por sí misma. Y con la frase que cierra el curso teórico, que es la única que se puede sostener con los papers en la mano: el aprendizaje ha cambiado quién escribe la consigna, no quién la ejecuta."));
children.push(h3("Si la clase no habla"));
children.push(p("En esta discusión el silencio tiene una causa particular y hay que reconocerla: nadie quiere opinar en un terreno donde intuye que sabe menos que los titulares que ha leído, y a la vez sospecha que los titulares exageran. La maniobra de rescate no es pedir opiniones sino pedir clasificaciones, que es una tarea acotada: el profesor enuncia cinco afirmaciones, dos verdaderas y demostradas, una en curso y dos exageradas, y pide a mano alzada en qué columna va cada una, contando y escribiendo. Con el recuento en la pizarra se pide razón a la mayoría y a la minoría en las dos que salgan divididas. La segunda maniobra es la del artículo en la mano: se proyecta la sección de resultados de uno de los trabajos y se pide sólo que localicen tres datos, cuántas tareas, cuántos intentos, qué tasa, porque leer un dato en una tabla no compromete a nadie y produce inmediatamente la conversación sobre qué se midió. La tercera, si el grupo está agotado a los ochenta minutos, es reducir la ambición y pedir sólo preguntas: qué le preguntaríais a los autores. Recoger cinco preguntas en la pizarra y no contestar ninguna es un cierre legítimo y además es literalmente el entrenamiento del turno de preguntas del seminario."));
children.push(h3("Cierre"));
children.push(p("Se cierra con las dos afirmaciones que la discusión ha construido y que conviene leer señalando sus columnas. Lo que cambian: el lenguaje se convierte en la interfaz de tarea y el preentrenamiento a escala web aporta una generalización semántica que las demostraciones solas no dan; eso está demostrado y es un cambio de calado. Lo que no cambian: la consigna que emiten sigue ejecutándose sobre la cinemática, los lazos de control, los actuadores y el middleware del resto del curso, y las funciones de seguridad siguen fuera del modelo. Conviene rematar con el inventario de limitaciones dicho sin dramatismo, fiabilidad en tareas largas, latencia y cómputo, evaluación no estandarizada y dependencia crítica de la cobertura de los datos, y con el encuadre de la evaluación, que tranquiliza y ordena: el cuestionario pregunta los tres ingredientes de un VLA y no la arquitectura interna de ninguno. Lo que no conviene hacer, y es la advertencia más importante de esta guía, es tomar partido: ni anunciar que esto lo cambiará todo ni despacharlo como una burbuja. Las dos posiciones son especulación disfrazada de criterio, las dos son indefendibles con las fuentes en la mano, y las dos enseñan lo contrario de lo que se pretendía enseñar. Tampoco conviene entrar en la comparación de familias de modelos ni en detalles de arquitectura, por mucho que alguien insista: no está en la evaluación, se come el gemelo digital y la síntesis del curso, y el sitio para eso es una presentación del seminario, que es donde hay que remitirlo por su nombre."));

children.push(h2("La discusión final dirigida de S40 (100–105 min): qué haría falta para confiar una célula a un VLA"));
children.push(h3("Objetivo"));
children.push(p("El guion la marca como discusión final dirigida y anota la respuesta esperada: monitorización de seguridad clásica e independiente del modelo, con la norma del bloque 2 detrás. La palabra dirigida es la instrucción de conducción y hay que tomarla en serio: aquí no se busca una exploración abierta, se busca que la clase llegue a una conclusión concreta que ya está en el temario, y por eso el formato es más cerrado que el de la discusión anterior. El objetivo es que el argumento de seguridad no quede como una afirmación del profesor al final del curso, sino como una conclusión que la clase deriva de dos premisas que ya conoce: que las funciones de seguridad se implementan con ingeniería certificable e independiente, y que un componente estadístico no puede aportar la garantía que la norma exige. Y hay un objetivo de integración que hace de esta la mejor pregunta de cierre posible del bloque teórico: obliga a usar a la vez el bloque 2, el bloque 6, el bloque 7 y el 8, es decir, es una síntesis del curso disfrazada de pregunta sobre el futuro."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 90 a 105 minutos cubre el gemelo digital y la síntesis, y esta discusión es su punto final: cinco minutos, del 100 al 105, con el cuestionario a las 105 en punto y la logística del seminario al final. El reparto: en el minuto 100, con la diapositiva-manifiesto de la síntesis todavía proyectada, se enuncia la pregunta y se pide una condición por persona, no un discurso. De 100 a 103, se recogen y se escriben en la pizarra en dos columnas, lo que se le pide al modelo y lo que se le pide al sistema alrededor del modelo. De 103 a 105, el cierre con la posición del curso. La división en dos columnas es lo que hace que la discusión llegue a la conclusión buena en cinco minutos: en cuanto la clase ve que casi todas sus condiciones caen en la segunda columna, el argumento está hecho. Un aviso de gestión: el cuestionario no se puede mover, de modo que a las 105 se corta aunque la discusión esté animada; conviene anunciarlo al empezar para que el corte no parezca arbitrario."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente: «Un integrador os ofrece mañana una célula colaborativa gobernada por uno de estos modelos, con un operario trabajando a un metro. Vosotros firmáis la puesta en marcha. Decidme una condición cada uno, sin repetir, y yo la coloco en una de estas dos columnas: cosas que le exijo al modelo y cosas que le exijo al sistema que rodea al modelo.» Poner al estudiante en el papel de quien firma es la clave del formato, porque desplaza la conversación del terreno de la opinión tecnológica al de la responsabilidad profesional, que es donde tiene que estar. Y pedir una condición por persona sin repetir garantiza que hablen ocho o diez personas en tres minutos."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "«Que tenga una tasa de éxito muy alta, del 99,9 %». ", bold: true },
 { text: "Es la primera y va a la columna del modelo, y hay que aceptarla y después demostrar que no basta, que es el paso decisivo de los cinco minutos. La pregunta de vuelta es qué pasa en el uno por mil restante, y la respuesta obliga a distinguir dos cosas que la clase mezcla: un fallo de tarea, la pieza se cae, y un fallo peligroso, el brazo se mueve hacia el operario. Una tasa de éxito agregada no dice nada sobre la segunda, porque no distingue modos de fallo. De ahí sale la formulación que hay que escribir: en seguridad no interesa la tasa media de éxito, interesa la cota del peor caso, y un componente estadístico entrenado con datos no ofrece cotas del peor caso." },
]));
children.push(pRuns([
 { text: "«Que haya un escáner láser y una parada de emergencia». ", bold: true },
 { text: "Va a la segunda columna y es la respuesta que el guion espera; hay que reforzarla con precisión y no dejarla en una intuición. La formulación correcta es la del bloque 2 y conviene recuperarla: las funciones de seguridad, paradas, límites de velocidad y de separación, se implementan con ingeniería certificable, independiente y por debajo de cualquier componente aprendido, porque la norma exige garantías que una red no puede ofrecer por sí misma. Y hay que añadir la precisión que evita el malentendido habitual: independiente significa que la función de seguridad no puede depender de que el modelo funcione, ni de que el modelo la informe; si el vigilante mira lo que el modelo le dice, no es un vigilante." },
]));
children.push(pRuns([
 { text: "«Que se pueda saber por qué ha hecho lo que ha hecho». ", bold: true },
 { text: "Aparece siempre y es una condición legítima que hay que colocar con honestidad: va a la columna del modelo y hoy no se cumple, y decirlo así es mejor que prometer explicabilidad. Lo que sí se puede exigir, y conviene que la clase lo distinga, no es la explicación de la decisión sino la trazabilidad del sistema: registro de las observaciones y de las consignas emitidas con sus sellos de tiempo, versión del modelo desplegada y capacidad de reproducir un episodio. Con eso un incidente se puede investigar aunque el modelo sea opaco, y eso es lo que un responsable de planta necesita. Es también la ocasión de conectar con el gemelo digital que se acaba de explicar: la reproducción de un incidente en el gemelo es hoy la herramienta práctica más realista para eso." },
]));
children.push(pRuns([
 { text: "«Yo no lo firmaría». ", bold: true },
 { text: "Aparece y es una posición defendible que hay que tratar con respeto y sin dejarla como respuesta final, porque no es una condición. La maniobra es pedirle exactamente lo mismo que a los demás: bajo qué condiciones lo firmaría, aunque sean muy exigentes. Casi siempre la lista que produce es la mejor de la clase, modelo confinado a una zona sin personas, o velocidad limitada por hardware a un valor tolerable, o intervención humana en cada ciclo, y conviene señalar que todas esas son decisiones de arquitectura de célula y no de modelo. Es la conclusión que se buscaba, y llega mejor de su boca que de la del profesor." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es creer que la seguridad de un sistema aprendido se consigue mejorando el modelo, y que por tanto es un problema de rendimiento que el progreso resolverá. Es el error de fondo del bloque y hay que desmontarlo con la estructura del argumento y no con una apelación a la prudencia. La forma que funciona es una analogía dentro del propio curso, y por eso conviene reservarla para este momento: en el bloque 5 nadie propone garantizar la seguridad de una máquina afinando mejor el PID, porque un lazo de control bien ajustado sigue siendo un lazo de control y la protección se pone aparte y con otra tecnología. Con los sistemas aprendidos ocurre exactamente lo mismo, y el argumento no depende de que el modelo sea bueno o malo: depende de qué clase de afirmación se puede demostrar sobre él. La segunda vía de desmontaje, más empírica y también del propio curso, es recordar el resultado del taller de la sesión: el clon de comportamiento reproducía las acciones del experto hasta el suelo de ruido del demostrador y se estrellaba en cuanto un empujón lo sacaba de la distribución demostrada. Un sistema que rinde perfectamente dentro de su distribución y falla fuera de ella es precisamente aquello sobre lo que no se pueden dar cotas del peor caso, y eso no es un defecto de esa implementación concreta sino la propiedad estructural del aprendizaje a partir de datos. El segundo error, más práctico, es suponer que basta con poner el modelo detrás de un límite de velocidad configurado por software; se desmonta con una pregunta de una línea: quién garantiza el software que impone el límite, y con qué certificación."));
children.push(h3("Si la clase no habla"));
children.push(p("A los cien minutos de una sesión de dos horas, y justo antes de un cuestionario, la clase está en modo de ahorro. La maniobra de rescate es la más simple y la más eficaz: se pide a mano alzada quién firmaría la puesta en marcha tal como está, se cuenta y se escribe. El recuento es siempre abrumadoramente negativo y entonces la pregunta se convierte en la fácil: qué os falta. La segunda maniobra es la lista cerrada, que además ahorra tiempo: el profesor enuncia seis condiciones y pide clasificarlas en las dos columnas mostrando la mano izquierda o la derecha; es rápido, participa todo el mundo y el resultado visual es el argumento. La tercera, para grupos que necesitan un empujón concreto, es apoyarse en el material del bloque 2 que ya conocen: se recuerdan los cuatro métodos colaborativos y se pregunta cuál de ellos podría aplicarse a una célula gobernada por un modelo, que es una pregunta con respuesta acotada y que produce por sí sola la conclusión de la separación de responsabilidades."));
children.push(h3("Cierre"));
children.push(p("Se cierra con la posición del curso, dicha con precisión y sin adornos: las funciones de seguridad se implementan con ingeniería certificable, independiente y por debajo de cualquier componente aprendido, y eso no es una limitación temporal del estado del arte sino una consecuencia de qué clase de garantías se pueden demostrar sobre un componente estadístico. Y con la lectura de las dos columnas de la pizarra, que es el argumento hecho por la clase: casi todo lo que han exigido está en la segunda columna, es decir, en el sistema alrededor del modelo. El corolario que cierra el bloque y da sentido al curso entero conviene decirlo aquí, porque es el mejor sitio: el ingeniero que sabe montar el sistema alrededor del modelo es el que hace posible que el modelo se use, y ése es el perfil que el curso ha intentado formar. Lo que no conviene decir es que estas tecnologías son inseguras: no lo son ni lo dejan de ser, y esa formulación es tan poco profesional como la contraria. Tampoco conviene cerrar el bloque con una moraleja tranquilizadora sobre la insustituibilidad del ingeniero: suena defensivo, la clase lo detecta y además no hace falta, porque el argumento de las dos columnas ya lo ha demostrado con sus propias respuestas."));

children.push(h2("El mapa colectivo de artículos en S42 (53–58 min): la última pizarra del curso"));
children.push(h3("Objetivo"));
children.push(p("El guion la sitúa en el cierre del seminario y el apartado 42.2 da la plantilla de cinco preguntas con la que cada pareja sitúa su artículo sobre los bloques del curso. Es una puesta en común y no una discusión, y su objetivo es distinto de todo lo anterior: no se trata de decidir nada ni de calibrar ninguna afirmación, se trata de que la síntesis final de la asignatura la construyan los estudiantes en lugar de recibirla. Eso tiene un efecto que ninguna transparencia de recapitulación consigue: cuando seis artículos de frontera, elegidos por ellos y ajenos al temario, acaban colocados sobre los ocho bloques y no queda ninguno huérfano, la tesis del curso deja de ser una afirmación del profesor y pasa a ser una observación empírica. Hay un objetivo secundario, de cierre emocional del semestre, que conviene no despreciar: es la última actividad lectiva antes de las defensas y la pizarra que se construye es el mejor resumen que van a tener para el examen de enero, además de un reconocimiento público del trabajo de las seis parejas."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 48 a 60 minutos cubre la retroalimentación global, el mapa colectivo y el cierre del curso, de modo que el mapa tiene cinco minutos, del 53 al 58. Con seis artículos son cincuenta segundos por pareja y no hay margen, así que el formato tiene que ser mecánico. El reparto: antes de empezar, con la pizarra ya dividida en las ocho zonas de los bloques y la plantilla de cinco preguntas proyectada, se anuncia que cada pareja tiene cuarenta segundos para colocar su artículo y decir una sola cosa. De 53 a 58, las seis intervenciones seguidas, con el profesor escribiendo el título abreviado en la zona que la pareja indique y trazando las flechas que ellos digan. De 58 a 60, el cierre del curso teórico. Dos avisos de gestión. El primero: la plantilla tiene cinco preguntas y en cuarenta segundos no caben; hay que asignar a cada pareja una sola de las cinco, decidida por el profesor según el artículo, y decirlo así. El segundo: conviene tener preparada de antemano la ubicación de los seis artículos, porque la validación de septiembre ya los conoce, de modo que si una pareja se atasca el profesor propone y ellos corrigen, que es más rápido y menos incómodo que dejar el silencio."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con la pizarra dividida: «Última pizarra del curso y la hacéis vosotros. Voy a llamar a las seis parejas por orden y cada una tiene cuarenta segundos para hacer dos cosas: decirme en qué zona de esta pizarra va vuestro artículo, y contestar una sola de las cinco preguntas de la plantilla, la que yo os diga. Empiezo por la pareja uno: ¿qué ejecuta las salidas de vuestro sistema, y a qué frecuencia?» Asignar la pregunta y no dejarla elegir es lo que hace que las seis intervenciones cubran las cinco preguntas de la plantilla entre todas, en lugar de que las seis contesten la más fácil."));
children.push(h3("Resultados que van a salir y qué hacer con cada uno"));
children.push(pRuns([
 { text: "El artículo que se coloca en dos zonas a la vez. ", bold: true },
 { text: "Ocurre siempre y es el mejor resultado posible, no un problema de método: un trabajo de manipulación aprendida usa percepción del bloque 6, ejecuta sobre control del bloque 5 y se comunica con el middleware del bloque 7. Cuando pase hay que aprovecharlo y hacerlo explícito trazando dos flechas en lugar de mover el título, y comentando en una frase que un sistema no vive en un bloque. Es la demostración visual de que los bloques del curso son capas y no compartimentos, que es exactamente lo que la asignatura pretende dejar." },
]));
children.push(pRuns([
 { text: "El artículo que no encaja en ningún bloque. ", bold: true },
 { text: "Aparece uno cada dos o tres años, típicamente de interacción humano-robot, de ética o de una tecnología de sensor que el curso no cubre. No hay que forzarlo dentro de una zona: hay que abrir una zona nueva al margen, escribir el título allí y decir en voz alta que el temario no lo cubre y por qué se ha aceptado igualmente en el seminario. Reconocer los límites del propio programa delante de la clase cuesta diez segundos, da credibilidad a todo lo demás y además es información útil para la revisión de la guía docente, que es literalmente el insumo que se pide en la encuesta de la sesión siguiente." },
]));
children.push(pRuns([
 { text: "«Nuestro artículo no usa nada del curso, es todo aprendido de punta a punta». ", bold: true },
 { text: "Es la afirmación que va a salir de la pareja que ha presentado un modelo fundacional, y es la última oportunidad del semestre de contestarla bien. La respuesta no es un discurso sino la pregunta de la plantilla: qué ejecuta sus salidas y a qué frecuencia. En cuanto la pareja dice que el modelo emite consignas a decenas de hercios, la flecha hacia el bloque 5 la dibujan ellos. Y conviene añadir la segunda pregunta de la plantilla, que remata: qué habría que añadir, independiente del modelo, para ponerlo cerca de personas, con lo que aparece la flecha al bloque 2 y el mapa queda completo." },
]));
children.push(pRuns([
 { text: "Los seis artículos acaban cubriendo casi todos los bloques. ", bold: true },
 { text: "Es el resultado habitual cuando la validación de septiembre ha procurado variedad, y hay que hacerlo notar señalando la pizarra en silencio unos segundos antes de comentarlo, porque el efecto visual es el argumento. La conclusión hay que dejar que la formule alguien de la clase, y si nadie lo hace se enuncia con la frase del apartado 42.2: la literatura de frontera no reemplaza el temario clásico, se apoya en él. Y se cierra con el encargo práctico: la pizarra se fotografía y se sube al campus, porque es el mejor resumen de la asignatura que existe, precisamente por haberlo construido ellos." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante no es de los estudiantes sino del formato, y consiste en que el profesor termine colocando los seis artículos él mismo por falta de tiempo. El resultado es una transparencia de recapitulación con más pasos, y pierde todo el valor: lo que hace funcionar este ejercicio es la autoría. Se evita con la disciplina de las tres reglas ya dichas, una pregunta por pareja, cuarenta segundos, el profesor escribe y no propone, y aceptando que el mapa quede imperfecto, que es un precio pequeño. Del lado del contenido, el error de razonamiento que sí conviene atacar es el que consiste en clasificar los artículos por el tema del que hablan y no por lo que hacen: un artículo de humanoides no va en la zona del bloque 8 por ser de humanoides, va donde esté la pieza que aporta. Se desmonta con la primera pregunta de la plantilla aplicada con rigor, qué aprende el sistema, si aprende algo, y qué no aprende, y basta hacerlo bien con el primer artículo para que los cinco siguientes se coloquen mejor. Es también, dicho de paso, la razón por la que conviene empezar por el artículo cuya ubicación esté más clara y no por el más espectacular."));
children.push(h3("Si la clase no habla"));
children.push(p("En la última clase del semestre, después de tres presentaciones y con las defensas al día siguiente, la clase está fundida y el silencio hay que darlo por descontado. La maniobra de rescate es no pedir voluntarios en ningún momento: se llama a las parejas por orden y por nombre, que ya está publicado, de modo que nadie tiene que decidir si habla. La segunda maniobra, si una pareja se queda en blanco, es que el profesor coloque su artículo en voz alta con una hipótesis y les pida sólo que la confirmen o la corrijan; confirmar o corregir cuesta cinco segundos y mantiene la autoría. La tercera, si el grupo entero está apagado, es cambiar el sujeto de la pregunta: en lugar de dónde va vuestro artículo, se pregunta cuál de los otros cinco artículos se parece más al vuestro y en qué. Comparar es más fácil que clasificar, produce las mismas flechas y además hace que las parejas se citen entre ellas, que es un buen cierre de seminario."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar es la que la pizarra demuestra y no hace falta argumentar: los seis artículos de frontera que ellos han elegido se apoyan en los ocho bloques del curso, y ninguno los sustituye. Conviene rematar con la conexión profesional, que es la que da sentido al seminario más allá de la nota: leer, destilar y defender un artículo en quince minutos es lo que harán en un departamento de investigación y desarrollo o evaluando a un proveedor de tecnología, y las cuatro dimensiones de la rúbrica son una descripción razonable de esa competencia. Y con la logística mínima, dicha en una frase para que el cierre no se deshaga en avisos: qué entra del bloque 8 en la evaluación y la cita de la sesión siguiente. Lo que no conviene hacer es convertir estos últimos minutos en un discurso de despedida: la pizarra es mejor cierre que cualquier discurso y ya está hecha. Tampoco conviene comentar públicamente qué presentación ha sido la mejor, ni siquiera de forma indirecta al comentar el mapa: las calificaciones no se anuncian en el aula, se publican individualmente con su justificación, y el mapa colectivo es el único momento del seminario en que los seis trabajos valen exactamente lo mismo."));

