// ============================================================ Guía de discusiones
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Guía de conducción de las discusiones y puestas en común de este bloque"));

children.push(p("El método general de conducción está desarrollado en los apuntes del bloque 1 y aquí se aplica sin cambios: los diez segundos de silencio después de formular la pregunta, sin reformular y sin contestarse; la distinción entre la pregunta cerrada de recuperación, las de los tramos que abren S26, S29 y S30, que no se discuten, se corrigen en segundos y sirven para forzar recuperación activa, y la pregunta abierta de discusión, que se lanza al grupo y cuyo valor está en el razonamiento; la votación a mano alzada cuando conviene hacer visible un cambio de criterio; el reparto de la palabra con el que monopoliza y con el que no habla nunca; y la exploración de la respuesta errónea antes de corregirla nombrando fuente y página. Lo que cambia es la materia. En este bloque las discusiones no son de opinión ni de juicio: son de criterio técnico, y casi todas nacen de un resultado del taller. Se discute qué significa un error de reproyección de 0,3 píxeles, por qué un núcleo de 13×13 acierta el 98 % donde uno de 1×1 se queda en el 90 %, en qué dirección corrige el filtro cuando la baliza está lejos y qué representación del mapa conviene cuando el mapa es una incógnita más. El árbitro no es el profesor: es la celda que se ejecuta delante de todos y la tabla que produce."));
children.push(p("De ahí tres consecuencias prácticas. La primera es que los cuadernos de la sesión no son material de apoyo, son el material de la discusión, y conviene tenerlos proyectados mientras se discute y no sólo mientras se trabaja: 82514_S25_Formacion_Imagen_Calibracion.ipynb tiene preparado el barrido de vistas que desmonta la interpretación ingenua del error de reproyección; 82514_S26_Procesado_Clasico.ipynb tiene el recuento de píxeles de borde en función de σ y el fallo de Otsu con iluminación desigual; 82514_S27_Percepcion_Aprendida.ipynb es, él solo, el guion de las dos discusiones de esa sesión, porque contiene el ajuste que redescubre Sobel, el barrido de tamaño de núcleo y la curva de capacidad frente a generalización; 82514_S28_Bayes_Kalman_EKF.ipynb, 82514_S29_Localizacion_EKF.ipynb y 82514_S30_Filtro_Particulas_MCL.ipynb producen las creencias que hay que interpretar; y 82514_S31_SLAM.ipynb cierra con el grafo de poses y el cierre de bucle. La segunda consecuencia es que en este bloque hay una regla de higiene que ahorra la mitad de las discusiones estériles: antes de comparar dos números hay que declarar contra qué se mide cada uno. La tercera es que el bloque tiene una discusión de naturaleza distinta a todas las demás, el panorama de reconstrucción neuronal de S31, que no es de criterio sino de frontera y que hay que conducir con las cautelas que se describen en su apartado, es el ensayo general de la discusión de VLA del bloque 8."));
children.push(box("La regla añadida en este bloque", "Ninguna métrica se interpreta sin declarar sobre qué datos se ha calculado. Un error de reproyección se mide sobre las mismas vistas que se usaron para ajustar; un acierto por píxel se mide sobre la escena de entrenamiento o sobre otra; una covarianza es la que el filtro cree, no la que tiene. Casi todos los malentendidos de este bloque son de esta familia, y descubrirlo es parte del contenido, no un tropiezo."));

children.push(h2("La discusión de S25 (85–90 min): qué mata una calibración"));
children.push(h3("Objetivo"));
children.push(p("El apartado 25.3 ya enuncia la respuesta, cambiar el enfoque o el zum, reensamblar la óptica o someter la cámara a ciclos térmicos fuertes altera los intrínsecos y obliga a recalibrar (práctica de laboratorio; sin cita de libro), de modo que si la discusión se conduce como una pregunta de recuperación es tiempo perdido. Lo que la discusión aporta y la exposición no puede aportar es otra cosa: que el estudiante deduzca la lista por sí mismo a partir del significado de los once parámetros que acaba de contar, cinco intrínsecos y seis extrínsecos (Corke, 2023, p. 548). Un parámetro que describe la geometría interna de la cámara deja de valer cuando esa geometría cambia; ese es todo el criterio, y con él se responde a casos que no están en ninguna lista. El segundo aprendizaje es de gestión de proyecto y no aparece en el libro: la calibración no es un paso previo que se hace una vez, es un dato de configuración con fecha de caducidad y con un procedimiento de verificación, y eso hay que decidirlo cuando se diseña la célula, no cuando falla."));
children.push(h3("Formato y tiempos"));
children.push(p("El guion asigna de 70 a 90 minutos a la teoría de calibración y coloca esta discusión en el último punto del tramo, de modo que los cinco minutos que van del 85 al 90 son todo el margen y hay que respetarlo porque el taller necesita sus veinticinco minutos íntegros. El reparto: en el minuto 85 se escribe en la pizarra, en dos columnas, «lo que describe la cámara» y «lo que describe la pose», y se enuncia la pregunta; diez segundos de silencio. De 85 a 88, barrido de respuestas anotando cada caso en la columna que le corresponde. De 88 a 90, el caso que no cae en ninguna de las dos columnas y la síntesis. No conviene abrir esto en parejas: la pregunta es corta, la clase lleva veinte minutos escuchando y lo que hace falta es que hablen, no que escriban."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, y señalando las dos columnas: «Habéis calibrado la cámara el lunes y el jueves los números ya no valen. ¿Qué ha pasado entre el lunes y el jueves? Decidme cosas concretas que puedan ocurrir en un laboratorio o en una planta, y para cada una decidme si afecta a la columna de la izquierda o a la de la derecha.» La formulación importa por dos motivos. Preguntar qué ha pasado, en lugar de qué invalida una calibración, convierte una pregunta de definición en un pequeño problema de diagnóstico, que es mucho más fácil de contestar. Y pedir la columna obliga a razonar con el modelo en la mano en lugar de recitar una lista."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "«Alguien ha tocado el anillo de enfoque» o «han cambiado el zum». ", bold: true },
 { text: "Es la primera y hay que aceptarla rápido, porque es la que da el criterio: enfocar mueve la lente respecto al sensor y por tanto cambia la distancia focal efectiva, es decir, los factores f/ρ_w y f/ρ_h que forman K (Corke, 2023, p. 546). Lo productivo es la pregunta de vuelta: ¿y si la cámara es de foco fijo y nadie ha tocado nada? Ahí aparece el aflojamiento del anillo de montura, que es exactamente el mismo fenómeno sin intervención humana, y es la ocasión de nombrar la práctica industrial de fijar la óptica con laca o con tornillo prisionero." },
]));
children.push(pRuns([
 { text: "«Han movido la cámara». ", bold: true },
 { text: "Sale siempre y es la respuesta más instructiva, porque es la que hay que partir en dos. Mover la cámara invalida los extrínsecos y no toca los intrínsecos, y por tanto exige recalcular la pose pero no rehacer el damero: es una recalibración de veinte segundos con una sola vista de un patrón fijo si se ha tenido la precaución de dejar uno en la célula. Conviene detenerse aquí un minuto entero, porque separar las dos mitades de la matriz C = K·[R|t] (Corke, 2023, pp. 546-547) es la diferencia entre parar la línea media hora y pararla dos días. Y de aquí sale la consecuencia de diseño: la calibración extrínseca se hace referida a algo que exista en la célula, no a un origen imaginario." },
]));
children.push(pRuns([
 { text: "«El robot ha chocado con el soporte» o «la temperatura del armario». ", bold: true },
 { text: "El golpe se acoge en la columna de los extrínsecos y se aprovecha para preguntar cómo se detecta un golpe pequeño que nadie ha visto, que es la pregunta buena: no se detecta mirando la imagen, se detecta con un patrón de verificación y un umbral, y esa es la respuesta que interesa. La deriva térmica es la que casi nunca sale espontáneamente y merece aportarla el profesor si nadie la nombra: afecta a las dos columnas, dilatación del soporte y del propio bloque óptico, y es la razón por la que las células de inspección de precisión se calibran en caliente, después de una hora de funcionamiento, y no al arrancar." },
]));
children.push(pRuns([
 { text: "«Si cambio la resolución de la cámara». ", bold: true },
 { text: "Es la respuesta más valiosa de las cuatro y también la que más equivocaciones produce, y hay que tratarla con cuidado porque la deducción es sutil: la óptica no ha cambiado, pero K está en píxeles, y si el driver entrega la mitad de columnas la focal en píxeles y el punto principal se dividen por dos. No es que la calibración muera, es que expresa otra cosa. El cuaderno 82514_S25_Formacion_Imagen_Calibracion.ipynb deja el aviso escrito en la solución del ejercicio 1: la focal que devuelve la calibración debe cuadrar con la focal física dividida por el tamaño de píxel, y si no cuadra por un factor de dos, casi siempre es que se está calibrando a media resolución. Con una óptica de 6 mm y un píxel de 1,4 µm, la focal esperada son 4286 píxeles; ver 2143 no es un error de ajuste, es un submuestreo." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es creer que una calibración se valida mirando si las imágenes «se ven bien» o si el undistort deja las líneas rectas a la vista. Es un error de método, no de contenido, y no se corrige diciendo que hay que medir: se corrige mostrando el caso en que la vista engaña. La maniobra que funciona ocupa noventa segundos y usa el propio taller: se pide a una pareja que ejecute la calibración con las tres vistas frontales del cuaderno y se proyecta el resultado al lado de la calibración con las doce. El error de reproyección de las tres vistas es más bajo, hay menos datos que explicar, la imagen corregida se ve igual de recta, y la focal recuperada está mucho más lejos de la verdadera. Eso zanja la discusión sin autoridad: si la métrica mejora y la exactitud empeora, la inspección visual no puede ser el criterio. El segundo error, menos frecuente pero más caro, es suponer que una recalibración de extrínsecos exige repetir el procedimiento completo del damero; se desmonta con el recuento de parámetros de la página 548 y con la pregunta de cuántas ecuaciones hacen falta para seis incógnitas."));
children.push(h3("Si la clase no habla"));
children.push(p("El silencio aquí es de falta de experiencia, no de falta de ideas: un estudiante que nunca ha visto una célula de visión no sabe qué cosas pasan en una célula de visión. La maniobra de rescate no es insistir, es cambiar la pregunta abierta por una lista cerrada y pedir clasificación: se enuncian cinco sucesos en voz alta, alguien toca el enfoque, alguien mueve la cámara, se cambia la lente por otra igual, se sube la resolución, pasa un mes, y se pide levantar la mano en los que invaliden la calibración. El recuento se escribe y se pide razón a la mayoría y a la minoría en los dos casos donde el reparto esté más dividido, que serán casi seguro la lente idéntica y el mes transcurrido. Los dos son excelentes: dos lentes del mismo modelo no comparten distorsión, y el paso del tiempo por sí solo no invalida nada, aunque en la práctica sea un buen disparador de verificación."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar es de una frase y conviene escribirla: la calibración describe una cámara concreta en un montaje concreto, y muere cuando cambia cualquiera de los dos; los intrínsecos y los extrínsecos mueren por causas distintas y se recuperan a coste muy distinto. El corolario práctico, que es lo que se llevan al proyecto: en el diseño de la célula hay que decidir el patrón de verificación, el umbral de aviso y quién y cuándo lo pasa, porque una calibración sin procedimiento de verificación es una bomba de relojería silenciosa. Lo que no conviene decir es que en la práctica se recalibra por si acaso cada semana: es falso, es caro y sobre todo enseña ritual en lugar de criterio. Y tampoco conviene prolongar la discusión hacia las cámaras autocalibrantes o la calibración en línea, que existen y son un tema magnífico: se anota en un rincón de la pizarra y se remite al seminario de artículos, porque el taller empieza a las nueve y media en punto."));

children.push(h2("La puesta en común del taller de S25 (106–113 min): qué dice y qué no dice el error de reproyección"));
children.push(h3("Objetivo"));
children.push(p("El guion pide discutir el error de reproyección como métrica de calidad, y la teoría se ha limitado a dar la receta práctica: diez o veinte vistas, damero inclinado y cubriendo las esquinas del encuadre, error final por debajo de unos 0,5 píxeles. Lo que la puesta en común tiene que producir es precisamente la desconfianza hacia ese número, y por eso es de las discusiones más rentables del bloque: el error de reproyección mide el ajuste, no la exactitud, y un valor bajo obtenido con pocas vistas o con vistas poco variadas no significa nada. Es la primera vez en el curso que los estudiantes se encuentran con la distinción entre error de ajuste y error de generalización, y merece la pena nombrarla como tal, porque volverá en S27 con la brecha entre entrenamiento y test y en el bloque 8 con el sobreajuste al simulador. Un aprendizaje colateral que la sesión regala: el diagnóstico útil no es el RMS global sino el error vista a vista, porque la vista que destaca es la que tiene la detección mala o el damero alabeado."));
children.push(h3("Formato y tiempos"));
children.push(p("El taller ocupa de 90 a 115 minutos y el cierre de la sesión de 115 a 120. La puesta en común hay que colocarla cuando la mayoría de parejas tenga ya su K y su error, típicamente en el minuto 106, y no dejarla para el final, porque a las 115 la clase está guardando el portátil. El reparto que funciona: de 106 a 108, recoger a mano alzada los errores de reproyección de las parejas y escribirlos todos en la pizarra en fila, sin comentarlos. De 108 a 111, tres minutos de discusión sobre la dispersión, con la pregunta de apertura. De 111 a 113, ejecutar en el proyector la comparación de doce vistas frente a tres del cuaderno y cerrar. Un detalle de gestión que decide el éxito: hay que recoger los números antes de decir nada sobre ellos, porque en cuanto el profesor insinúa que un número bajo puede ser malo, las parejas dejan de declarar el suyo."));
children.push(h3("Pregunta de apertura"));
children.push(p("Con la fila de números en la pizarra, literalmente: «Tenemos 0,21; 0,28; 0,34; 0,19 y 0,41 píxeles, y una pareja que ha sacado 0,08. Todos por debajo del criterio de medio píxel. ¿Quién ha calibrado mejor?» Y a los diez segundos, si nadie ha desconfiado, la segunda mitad: «¿Con qué imágenes ha calculado cada uno su número?» La pregunta funciona porque parece una pregunta de ranking y no lo es; el 0,08 es la trampa deliberada y en un grupo de treinta siempre aparece alguien que ha usado menos vistas o vistas casi frontales. Si por casualidad no aparece, el profesor pone el 0,08 en la pizarra como si fuera de una pareja anónima."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«El de 0,08 ha calibrado mejor». ", bold: true },
 { text: "Es la respuesta por defecto y no se corrige de frente: se pide a esa pareja cuántas vistas ha usado. La respuesta casi siempre es tres o cuatro, y a veces con el damero puesto de frente sobre la mesa. A partir de ahí la clase concluye sola, y hay que dejar que lo haga: con menos vistas hay menos correspondencias que explicar y el ajuste tiene más libertad, así que el residuo baja. La formulación que conviene dejar escrita es la del cuaderno: el error de reproyección mide el ajuste, no la exactitud." },
]));
children.push(pRuns([
 { text: "«¿Y cómo sabemos entonces si está bien?». ", bold: true },
 { text: "Es la mejor pregunta posible y hay que provocarla si no sale. Tiene tres respuestas y conviene darlas en orden. La primera es la comprobación física que ya pide el guion: la focal estimada en píxeles debe cuadrar con la focal en milímetros dividida por el tamaño de píxel del sensor, y ese contraste no depende del ajuste. La segunda es validar con vistas que no hayan entrado en el ajuste, que es literalmente la solución del ejercicio 3 del cuaderno. La tercera, y la única definitiva en una célula real, es medir una pieza patrón de dimensión conocida y ver el error en milímetros, porque la calibración no se hace para que el residuo sea pequeño, se hace para medir." },
]));
children.push(pRuns([
 { text: "«A mí me sale una vista con el error mucho más alto que las demás». ", bold: true },
 { text: "Aparece en dos o tres parejas y es un regalo: es exactamente lo que el guion quiere que se vea. Se proyecta su gráfico de barras por vista y se pide a la clase que aventure qué le pasa a esa vista. Las causas reales, en orden de frecuencia, son detección de esquinas parcialmente equivocada, damero impreso sobre un soporte que no es plano, y movimiento durante la captura. La conclusión operativa hay que dictarla: la vista mala se elimina y se recalibra, y esa decisión es legítima y no es hacer trampa, porque lo que se está eliminando es un dato malo y no un dato incómodo, la distinción, dicha en voz alta, es una lección de honestidad experimental que sirve para todo el curso." },
]));
children.push(pRuns([
 { text: "«Si añado más parámetros de distorsión, el error baja». ", bold: true },
 { text: "Lo descubre siempre alguien que ha quitado las banderas del cuaderno, y es el caso más avanzado y más valioso. Se acoge con entusiasmo y se lleva hasta el final: el RMS baja porque hay más parámetros libres para absorber el ruido, pero los coeficientes de orden alto se ajustan a valores que se compensan entre sí y K suele empeorar. Es sobreajuste puro y duro, con ese nombre, dicho tres semanas antes de la sesión en que el nombre será materia de examen. La regla de ingeniería para llevarse: no se estiman parámetros que se sabe que valen cero, y no se usan modelos de distorsión de orden alto salvo con ópticas de ojo de pez." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es tratar el 0,5 píxeles como un umbral de aceptación en lugar de como una condición necesaria: si el número está por debajo, la calibración está bien, y si está por encima, se repiten vistas hasta que baje. Ese razonamiento produce calibraciones malas con boletín de notas excelente, y es el que hay que desmontar con datos del propio taller y no con una advertencia genérica. La demostración que lo cierra son treinta segundos de proyector con el cuaderno: se recalibra con tres vistas frontales y se ponen las dos K una al lado de la otra. La de tres vistas tiene el RMS más bajo de la clase y la focal descolocada, porque con el tablero paralelo al sensor la focal y la distancia al tablero son casi indistinguibles, acercar la cámara o alargar la focal producen la misma imagen, que es la ambigüedad fundamental de la proyección perspectiva ya vista en la primera hora (Corke, 2023, p. 548). Inclinar el damero es lo que rompe esa degeneración, y por eso todas las recetas insisten. Con eso, la receta deja de ser un ritual y pasa a tener una razón geométrica, que es exactamente lo que distingue a un ingeniero de un operario de software."));
children.push(h3("Si la clase no habla"));
children.push(p("En medio de un taller el silencio no es timidez, es que están mirando su pantalla. La maniobra de rescate es física antes que retórica: pedir que aparten las manos del teclado y que la pareja con el número más bajo diga en voz alta cuántas vistas ha usado. Convertir la discusión en una entrevista de dos preguntas a una pareja concreta arranca siempre, y en cuanto la segunda pareja contradice a la primera la conversación es de la clase. Si el grupo sigue callado, funciona el recurso de la apuesta: se pide a mano alzada quién cree que calibrar con tres vistas dará un error mayor o menor que con doce, se cuentan las manos, se escriben los dos números y se ejecuta la celda delante de todos. La mayoría vota mayor, el resultado es menor, y el desconcierto de diez segundos que sigue vale más que cualquier explicación."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, dicha en dos frases: el error de reproyección es la única métrica interna que tenemos y es imprescindible, pero mide el ajuste y se puede bajar empeorando la calibración; la exactitud sólo se comprueba contra algo que no haya entrado en el ajuste, una vista reservada, la óptica y el tamaño de píxel, o una pieza patrón. Conviene rematar con la frase del cuaderno, que resume el bloque entero: la geometría no se aprende, se mide. Lo que no conviene hacer es dar por buena la calibración de todo el mundo para no desanimar a nadie antes del proyecto: la mitad de las calibraciones de una clase de máster tienen alguna vista mala, decirlo con naturalidad es normalizar la verificación, y ocultarlo garantiza que el problema reaparezca en diciembre con el robot delante. Tampoco conviene cerrar con que en la práctica esto lo resuelve la librería: es lo contrario de la verdad, porque calibrateCamera hace exactamente lo que se le pide con los datos que se le dan."));

children.push(h2("El repaso a mano alzada que abre S26 (0–5 min): dos preguntas cerradas bien puestas"));
children.push(h3("Objetivo"));
children.push(p("Este tramo no es una discusión y confundirlo con una es el error que lo arruina. Son dos preguntas cerradas de recuperación, cuántos parámetros describen una cámara y cómo se reparten (Corke, 2023, p. 548), y qué información pierde la proyección perspectiva, cuya función no es debatir nada, sino forzar recuperación activa de la memoria cinco días después de la sesión que introdujo el material. La diferencia con la teoría es de mecanismo y no de contenido: recuperar de memoria consolida mucho más que volver a leer, y por eso el guion gasta cinco de sesenta minutos en algo que el profesor podría resumir en treinta segundos. Hay un segundo objetivo, de diagnóstico: la S26 se apoya sin avisar en la calibración de S25, el centroide del blob se convierte en metros con K, y estos cinco minutos son la única oportunidad de detectar que media clase no ha entendido qué es un parámetro intrínseco antes de construir encima."));
children.push(h3("Formato y tiempos"));
children.push(p("Cinco minutos exactos, con el reparto decidido de antemano porque el tramo teórico empieza en el 5 y la sesión es de una sola hora. De 0 a 1, primera pregunta a mano alzada con respuesta corta pedida por nombre a dos estudiantes distintos. De 1 a 2, corrección con la página en pantalla. De 2 a 4, segunda pregunta, que admite algo más de desarrollo. De 4 a 5, la frase de enlace con la sesión del día. Tres advertencias de gestión. La primera es que hay que preguntar por nombre y no al aire: la pregunta cerrada lanzada al grupo la contesta el de siempre y no informa de nada. La segunda es que no hay que aceptar la respuesta a coro, porque enmascara exactamente lo que se quiere medir. La tercera es que estos cinco minutos no se estiran: si se descubre que la clase no se acuerda de nada, la reacción correcta no es dar la teoría de S25 otra vez, sino dejar las once cifras escritas en un rincón de la pizarra y seguir."));
children.push(h3("Preguntas de apertura"));
children.push(p("Las dos, literalmente. La primera: «Sin mirar apuntes: ¿cuántos parámetros hacen falta para describir una cámara, y cómo se reparten?» Se pide el número primero y el reparto después, en ese orden, porque el número es un ancla de memoria y el reparto exige entender. La respuesta correcta es once, cinco intrínsecos y seis extrínsecos (Corke, 2023, p. 548), con el matiz de que la matriz C tiene doce elementos y uno es un factor de escala arbitrario. La segunda: «La proyección perspectiva pierde información. ¿Cuál exactamente, y qué consecuencia tiene eso para un robot que quiere coger una pieza?» La segunda mitad de la pregunta es la que la convierte en útil: sin ella, la respuesta es la palabra profundidad y no se comprueba nada."));
children.push(h3("Respuestas que van a salir y qué hacer con cada una"));
children.push(pRuns([
 { text: "«Once» sin el reparto. ", bold: true },
 { text: "Es la respuesta más frecuente y es media respuesta: el número se memoriza en diez segundos y no demuestra nada. No se acepta y no se penaliza; se pide el desglose a otro estudiante, por nombre. Si el segundo tampoco lo tiene, se escribe la descomposición en la pizarra en quince segundos, focal en dos direcciones, punto principal en dos coordenadas, sesgo; rotación y traslación, y se sigue, con la nota mental de que la clase ha memorizado sin entender y de que la conexión blob-a-metros de hoy habrá que hacerla más despacio." },
]));
children.push(pRuns([
 { text: "«Doce, los de la matriz». ", bold: true },
 { text: "Es el error productivo del tramo y hay que explorarlo, no corregirlo: se pregunta por qué doce y once no coinciden. La respuesta, el factor de escala global es arbitrario, la matriz está definida salvo un factor, es una de las ideas más finas de S25 y quien la reconstruye en voz alta se la queda para siempre. Vale la pena gastar cuarenta segundos aquí aunque cueste el resto del tramo, porque es contenido de examen y porque premia públicamente a quien ha pensado en lugar de memorizar." },
]));
children.push(pRuns([
 { text: "«Se pierde la profundidad». ", bold: true },
 { text: "Correcta e insuficiente, y la pregunta de vuelta está preparada: entonces, si conozco el píxel, ¿qué sé del mundo? La respuesta que hay que arrancar es que se conoce el rayo completo y no el punto, y de ahí sale sola la consecuencia práctica: una pieza sobre una mesa cuya altura se conoce sí se puede localizar, porque el plano corta el rayo en un punto. Ese es el puente exacto con la cadena de hoy, y por eso conviene que lo diga un estudiante y no el profesor." },
]));
children.push(pRuns([
 { text: "«Se pierde el tamaño» o «no se sabe si es grande y lejos o pequeño y cerca». ", bold: true },
 { text: "Es la respuesta buena y hay que reforzarla nombrando la fuente, porque es literalmente la ambigüedad de la proyección perspectiva del libro (Corke, 2023, p. 548). Conviene aprovechar treinta segundos para conectarla con lo que viene: en S26 se va a medir el área de un blob en píxeles, y esa área no es un tamaño hasta que alguien decide a qué distancia está el objeto. Dejar sembrada esa incomodidad hace que la hipótesis de plano de trabajo, que se enunciará en el minuto 40, no suene a truco." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error más frecuente no está en las respuestas, está en la conducción, y merece decírselo un profesor a otro: la tentación de convertir estos cinco minutos en un resumen de S25. Se reconoce cuando el profesor lleva tres minutos hablando y ningún estudiante ha dicho una frase completa; el coste es doble, porque se pierde el efecto de la recuperación activa y porque la clase aprende que las preguntas de apertura las contesta el profesor. La disciplina que lo evita es aritmética: en estos cinco minutos el profesor no puede hablar más de dos, y las respuestas se corrigen señalando la página, no reexplicando. Del lado del contenido, el error de razonamiento recurrente es creer que la distorsión de lente es uno de los cinco intrínsecos; se desmonta con la propia formulación del libro, que la trata como parámetros intrínsecos adicionales (Corke, 2023, p. 552), y se cierra la cuestión en una frase sin abrir debate."));
children.push(h3("Si la clase no habla"));
children.push(p("A las nueve de la mañana de un miércoles, con una sesión de una hora, el silencio es lo normal y no significa desconocimiento. La maniobra de rescate es rebajar el coste de contestar, no rebajar la pregunta: se convierte en votación de tres opciones mostrando los dedos, ocho, once o doce parámetros, y se cuenta. Con el reparto en la pizarra se pide a alguien de la opción mayoritaria que explique por qué, que es mucho más fácil que responder en frío. La segunda maniobra, si tampoco arranca, es el minuto en parejas con una consigna mínima: reconstruid entre los dos la lista de los once. Y hay una tercera, específica de una sesión corta: en lugar de preguntar, se proyecta la matriz C con dos elementos tapados y se pide que digan qué falta. Señalar es siempre más barato que enunciar."));
children.push(h3("Cierre"));
children.push(p("El cierre de estos cinco minutos es una frase de tránsito, no una síntesis, y conviene tenerla preparada literalmente: «Guardad esos once números y quedaos con que de un píxel sabemos un rayo; hoy vamos a sacar de la imagen cosas que se pueden medir, y en el minuto cuarenta vamos a necesitar la matriz K para convertir un centroide en milímetros.» Con eso el tramo de recuperación queda cosido a la sesión y no parece un control sorpresa. Lo que no conviene decir es que esto entrará en el examen, aunque sea verdad: convierte la recuperación en amenaza y, sobre todo, hace que la clase deje de contestar por miedo a equivocarse en algo evaluable. Y tampoco conviene comentar el nivel del grupo en voz alta, ni para bien ni para mal, porque el objetivo de estos cinco minutos es que hablen, y cualquier juicio público sobre el resultado los enmudece durante el resto de la hora."));

children.push(h2("El intercambio sobre latencia y precisión en S27 (31–35 min)"));
children.push(h3("Objetivo"));
children.push(p("El apartado 27.2 ya afirma que la única pasada de YOLO es lo que lo hizo dominante en robótica porque cabe en el presupuesto de latencia de un robot móvil con GPU embarcada (Redmon et al., 2016, arXiv:1506.02640). El objetivo de estos cuatro minutos es que esa frase se convierta en un cálculo. Un estudiante de máster que ha hecho el bloque 5 sabe que un retardo en el lazo desestabiliza, pero no ha conectado nunca ese saber con la elección de un detector; y la conexión es exactamente el contenido: si el robot circula a 1 m/s y el detector tarda 200 ms, el obstáculo se ha desplazado veinte centímetros entre la imagen y la decisión, y ninguna mejora de precisión compensa eso. La diferencia con la teoría es que la exposición presenta el compromiso como una propiedad de las arquitecturas y la discusión lo convierte en una restricción de diseño que se calcula con dos números. Hay un objetivo secundario que se cobra en el bloque 7: quien haya hecho esta cuenta entiende sin más explicación por qué Nav2 separa un planificador global lento de un controlador local rápido."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 20 a 35 minutos es el de detección de objetos y este punto es el último, de modo que quedan cuatro minutos, del 31 al 35. Es poco y por eso hay que renunciar de entrada a cualquier ambición: no se discute qué detector es mejor, se hace una cuenta y se extrae una regla. El reparto: en el minuto 31 se escriben en la pizarra tres números, la velocidad del robot, la latencia del detector y la distancia de frenado, y se enuncia la pregunta; treinta segundos para que hagan la multiplicación en la cabeza o en el papel. De 32 a 34, dos minutos de barrido de respuestas y consecuencias. De 34 a 35, la regla de cierre. No conviene proyectar tablas de mAP y milisegundos de familias de detectores: son datos que caducan cada seis meses y desvían la conversación al ranking, que es justo lo que no interesa."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con los tres números escritos: «Vuestro AMR va a 1 metro por segundo. Tenéis dos detectores: uno acierta el 92 % y tarda 40 milisegundos, y otro acierta el 96 % y tarda 250. ¿Cuál ponéis, y qué número de la pizarra decide?» La formulación tiene dos trampas deliberadas y las dos son productivas. La primera es que el porcentaje de acierto invita a elegir el segundo, y la cuenta lo desmiente. La segunda es que no se dice qué mide el porcentaje, y si alguien lo pregunta hay que celebrarlo en voz alta, porque es la pregunta correcta y enlaza con el criterio de validación que la tabla del apartado 27.4 recogerá catorce minutos más tarde."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«El de 96 %, que acierta más». ", bold: true },
 { text: "Sale primero y no se corrige: se pide la cuenta. A 1 m/s y 250 ms el robot recorre 25 centímetros con información caducada, y si el ciclo completo incluye captura, inferencia, decisión y actuación, la cifra real es mayor. Con el detector rápido son 4 centímetros. Ahí la clase se da cuenta sola de que el 4 % de precisión adicional se paga con veintiún centímetros de ceguera, y esa es la unidad en la que hay que comparar. Conviene dejar escrito el producto velocidad por latencia con nombre propio, porque es la magnitud que gobierna toda la percepción embarcada." },
]));
children.push(pRuns([
 { text: "«Pues bajo la velocidad del robot». ", bold: true },
 { text: "Es la respuesta más inteligente que puede salir y hay que reconocerla como tal antes de complicarla: efectivamente, la latencia del detector fija una velocidad máxima segura, y esa es la forma profesional de escribir la especificación. La complicación que conviene añadir en una frase es de negocio y no de técnica: en logística la velocidad es el tiempo de ciclo y el tiempo de ciclo es dinero, así que rebajarla no es gratis. Con eso el compromiso deja de ser un asunto de dos columnas y se convierte en un problema de tres variables acopladas, que es como son los problemas reales." },
]));
children.push(pRuns([
 { text: "«Los pongo los dos, uno rápido siempre y otro lento cuando haga falta». ", bold: true },
 { text: "Aparece en uno de cada dos grupos y es la respuesta de arquitectura: se acoge con entusiasmo porque es exactamente lo que hacen los sistemas reales, y se le da su nombre, cascada, o detección rápida con verificación lenta. Vale la pena señalar de inmediato la conexión doble: es la misma división de trabajo que en el bloque 7 separa el planificador global lento del controlador local rápido, y la misma que en el bloque 8 reaparecerá dentro de los modelos fundacionales, con un módulo deliberativo lento y un generador de acciones rápido. Ver el mismo patrón tres veces en tres bloques distintos es de las cosas que más ordenan el curso." },
]));
children.push(pRuns([
 { text: "«¿Y no puedo predecir dónde estará el obstáculo?». ", bold: true },
 { text: "Es la mejor pregunta del tramo y hay que darle treinta segundos aunque cueste el cierre, porque anticipa media asignatura: sí, la latencia se compensa prediciendo, y predecir con un modelo de movimiento es exactamente el paso de predicción del filtro de Bayes que empieza en la sesión siguiente (Thrun et al., 2005, p. 27). Conviene decir explícitamente que la respuesta a esta pregunta es el contenido de S28 a S30, y que la compensación de latencia por predicción es una de las razones industriales por las que se filtra. Anotarla en la pizarra como pregunta que se contesta mañana es mejor que contestarla hoy a medias." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es tratar la precisión declarada de un detector como una propiedad del detector, y por tanto comparable entre modelos como se comparan dos motores por su par nominal. Es el mismo error de estatus que en S25 llevaba a aceptar un error de reproyección bajo, y conviene señalar el parentesco en voz alta. Se desmonta con el resultado del propio taller y no con una advertencia: el cuaderno 82514_S27_Percepcion_Aprendida.ipynb tiene el barrido de capacidad donde la red grande acierta el 100 % en entrenamiento y no llega al 90 % en datos nuevos, con el añadido de que en esa tarea, con el ruido que tienen los datos, ningún modelo puede pasar de ese techo por mucha arquitectura que se le ponga. Proyectar esa curva en el minuto 33 es el argumento entero: un porcentaje sin conjunto de evaluación no es un dato, y por eso la primera pregunta a un proveedor que ofrece un 99 % es sobre qué imágenes. El segundo error, más sutil, es confundir la latencia con el inverso de la frecuencia de publicación; se desmonta preguntando qué pasa si el detector publica a 25 Hz pero cada resultado corresponde a una imagen de hace 200 ms, que es el caso habitual con procesamiento por lotes en GPU."));
children.push(h3("Si la clase no habla"));
children.push(p("Con cuatro minutos no hay margen para maniobras largas, así que la de rescate tiene que ser inmediata: se convierte en votación binaria a mano alzada, detector rápido o detector preciso, y se pide una razón a cada bando. Si el reparto sale muy desequilibrado, el profesor defiende en voz alta el bando minoritario durante veinte segundos, que es una técnica que funciona sorprendentemente bien y que además protege a quien votó en minoría. La segunda maniobra es hacer la cuenta a medias en la pizarra: se escribe 1 m/s multiplicado por 0,25 s y se deja el resultado sin escribir, mirando a la clase. Un hueco en una multiplicación es irresistible y alguien lo rellena. Si el grupo está realmente frío, se cambia el sujeto: en lugar de preguntar qué detector, se pregunta a qué velocidad máxima dejarían circular un robot con un detector de 250 ms, que es una pregunta con respuesta numérica y sin riesgo de quedar mal."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar cabe en una frase que conviene dictar: en percepción embarcada la magnitud de diseño no es la precisión, es el producto de la velocidad por la latencia, y la precisión sólo se compara a igualdad de ese producto. El corolario para el proyecto, dicho ahí mismo: cuando en diciembre elijan un detector, la primera cifra que hay que medir en su propio hardware es el tiempo de inferencia, porque el mAP viene en el paper y la latencia depende de su GPU. Lo que no conviene decir es que los detectores modernos ya son suficientemente rápidos y que este compromiso está superado: es falso en cuanto se embarca en un ordenador con presupuesto y desactiva la única cuenta que hay que aprender a hacer. Tampoco conviene entrar en la comparación de versiones de la familia YOLO, por mucho que alguien la pida: es información que caduca, se remite al seminario de artículos y se sigue, porque a las treinta y cinco empieza la segmentación."));

children.push(h2("La discusión de los tres casos en S27 (45–55 min): la más estructurada del bloque"));
children.push(h3("Objetivo"));
children.push(p("Es la discusión de mayor rendimiento del bloque y la única con una herramienta explícita: la tabla de decisión del apartado 27.4, con sus seis criterios y sus dos columnas. Lo que debe quedar aprendido no es la tabla, que está impresa, sino tres cosas que sólo se aprenden usándola. La primera es que la decisión clásico frente a aprendido no se toma por moda ni por tema, sino cruzando requisitos concretos: iluminación, catálogo de objetos, tipo de requisito, datos disponibles, cómputo embarcado y necesidad de trazabilidad. La segunda es que los casos reales no caen limpiamente en una columna, y que la respuesta profesional casi siempre es híbrida, con redes para la apariencia y geometría calibrada para la medida, la frontera que el apartado 27.4 declara no negociable, porque el detector más moderno entrega píxeles y convertirlos en metros sigue pasando por la matriz K. La tercera, y es la que justifica la elección de los tres casos, es que hay un tipo de requisito que no se resuelve con ninguna de las dos columnas: la función de seguridad, que en la célula colaborativa se cubre con sensórica certificada y no con un detector, por bueno que sea (posición del curso, coherente con la S7 del bloque 2; sin cita de libro)."));
children.push(h3("Formato y tiempos"));
children.push(p("El guion asigna los diez minutos que van del 45 al 55, y con tres casos y una tabla de seis filas el reparto tiene que estar decidido de antemano o se come el cierre. De 45 a 46, se reparte o proyecta la tabla y se leen los tres casos en voz alta sin comentarlos: inspección dimensional de una pieza torneada, recogida de objetos variados en logística y detección de personas en una célula colaborativa. De 46 a 48, dos minutos en parejas con una consigna muy concreta y limitada: para vuestro caso, marcad las dos filas de la tabla que deciden y decid con qué columna se queda cada una. Limitar a dos filas es la decisión clave del formato, porque obliga a jerarquizar y evita el recitado completo de la tabla. De 48 a 53, cinco minutos de puesta en común caso por caso, en el orden fácil, medio, difícil. De 53 a 55, el cierre con la regla de la geometría y el anuncio del giro del bloque. Conviene asignar los casos por zonas del aula en lugar de dejar elegir: si se deja elegir, dos tercios de la clase toman el de logística."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con la tabla en la mano: «Tenéis seis criterios y tres encargos. No quiero que me digáis clásico o aprendido; quiero que me digáis qué dos filas de esta tabla deciden vuestro caso y por qué esas dos y no las otras cuatro.» Y para el barrido, la pregunta que se repite en cada caso: «¿Qué fila mandó?» La formulación desplaza deliberadamente el objeto de la discusión: no se discute la conclusión, se discute el criterio, y eso tiene tres ventajas. Nadie puede acertar por intuición, se hace visible el razonamiento que es lo único evaluable, y desaparece la tentación de votar por el bando de la tecnología moderna."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "Inspección dimensional: «iluminación controlada y requisito métrico, así que clásico». ", bold: true },
 { text: "Es la respuesta correcta y llega rápido; el riesgo es que la clase se quede en la fila de la iluminación, que es la más visible y no la decisiva. Hay que empujar a la fila del requisito: se está midiendo una tolerancia, y una tolerancia se mide con geometría calibrada y con subpíxel, no con una caja englobante. La pregunta que lo remata es cuánto vale un píxel en milímetros en su montaje, que devuelve la discusión a S25 y hace visible que el problema no es reconocer la pieza, sino medirla. Si alguien propone usar una red para segmentar el contorno y después medir sobre la máscara, hay que acogerlo porque es exactamente la solución híbrida correcta, y aprovecharlo para preguntar con qué precisión de borde entrega máscaras una red, que es el punto donde la propuesta se sostiene o se cae." },
]));
children.push(pRuns([
 { text: "Logística: «objetos variados y catálogo abierto, así que aprendido». ", bold: true },
 { text: "También correcta y también incompleta, y aquí la fila que hay que rescatar es la de los datos: aprendido no significa entrenar, significa disponer de un dataset o de un modelo fundacional, y en 2026 segmentar una pieza nueva casi nunca empieza por entrenar desde cero, sino por indicar o afinar un modelo preentrenado como SAM (Kirillov et al., 2023, arXiv:2304.02643). La segunda cosa que hay que sacar es que la salida útil no es la caja sino la máscara por instancia, porque lo que necesita un agarre es qué píxeles son esta pieza concreta, que es literalmente lo que aporta Mask R-CNN (He et al., 2017, arXiv:1703.06870). Y la tercera, si hay tiempo: aunque la percepción sea aprendida, el punto de agarre acaba expresado en coordenadas del robot, y para eso vuelve a hacer falta la calibración." },
]));
children.push(pRuns([
 { text: "Célula colaborativa: «personas, así que aprendido, que detecta mejor». ", bold: true },
 { text: "Es la respuesta que va a salir y es la que hay que trabajar despacio, porque el error no está en la primera mitad, una red es, en efecto, mejor detector de personas que cualquier regla, sino en la conclusión. La pregunta de vuelta es qué fila de la tabla se han saltado, y la respuesta es la última: validación y trazabilidad. De ahí se llega en dos pasos a la posición del curso: la función de seguridad exige garantías que hoy se resuelven con sensórica certificada, escáneres, cortinas, y no con la red, que queda como capa adicional y no de seguridad. Conviene formularlo con precisión, porque el matiz es todo: no se prohíbe la red, se le prohíbe ser el elemento del que depende que nadie resulte herido. Es el mismo argumento del bloque 2 y merece decir en voz alta que es el mismo." },
]));
children.push(pRuns([
 { text: "«Entonces lo aprendido es peor». ", bold: true },
 { text: "Aparece como conclusión precipitada del tercer caso y hay que desactivarla en el momento, porque es la lectura contraria a la que interesa. La forma de hacerlo es devolver el primer caso: en la inspección dimensional lo aprendido tampoco es peor, es innecesario, y esas dos cosas no son lo mismo. La regla que conviene dictar es de higiene profesional: ninguna de las dos columnas gana en general, y el ingeniero al que se le puede preguntar cuál usar sin darle los requisitos es el ingeniero al que no hay que preguntar." },
]));
children.push(h3("Cómo usar la tabla sin que se convierta en receta mecánica"));
children.push(p("La tabla tiene un riesgo proporcional a su utilidad: convertirse en un formulario que se rellena para obtener una conclusión, con la sensación de haber decidido cuando lo único que se ha hecho es contar columnas. El síntoma es inconfundible y aparece siempre en algún grupo: cuatro filas favorecen clásico y dos favorecen aprendido, luego clásico. Hay que cortar eso en cuanto asome, y la forma de cortarlo no es un discurso sobre el juicio profesional, son tres reglas concretas que conviene enunciar antes del barrido. La primera es que las filas no valen lo mismo y hay que declarar cuál manda: se pide siempre una fila decisiva y una fila que se sacrifica, y quien no puede nombrar la que sacrifica no ha decidido nada. La segunda es que la tabla no admite empate por diseño, porque una fila con un requisito duro, una tolerancia, una función de seguridad, un presupuesto de cómputo cerrado, gana a cuatro filas de preferencias; en cuanto una fila es una restricción y no una preferencia, el recuento sobra. La tercera es que la conclusión honesta suele ser híbrida y la tabla no tiene columna para eso: la pregunta que lo revela es qué parte del problema resuelve cada columna, y en los tres casos la respuesta reparte apariencia y medida entre las dos. Ayuda una maniobra de dos minutos si el grupo se ha vuelto mecánico: tomar el caso ya resuelto y cambiar un solo dato, la pieza torneada pasa a inspeccionarse en la nave, con luz de ventana, y pedir si cambia la decisión. Si la decisión cambia al mover una fila, la tabla se está usando bien; si no cambia, se está rellenando."));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es el que el propio bloque ha sembrado sin querer al citar a Corke: si las técnicas clásicas de segmentación han sido eclipsadas por las basadas en aprendizaje profundo (Corke, 2023, p. 510), lo razonable es usar siempre lo aprendido. Es un error de alcance, no de contenido: la frase habla de segmentación de apariencia compleja, no de medida geométrica. Se desmonta con dos datos del propio taller y sin apelar a la autoridad de nadie. El primero está en la sección de núcleos aprendidos de 82514_S27_Percepcion_Aprendida.ipynb: unos mínimos cuadrados sobre sesenta y seis mil ejemplos redescubren el operador de Sobel hasta la cuarta cifra, lo que significa que en el caso fácil el aprendizaje llega, con muchos datos, a lo que el ingeniero escribía de memoria en S26, la ganancia está en otra parte. El segundo es la contrapartida, en la misma sección: cuando la tarea es semántica y no derivable, el núcleo de 1×1 se queda en el 90 % de acierto por píxel y el de 13×13 sube al 98 %, sin que nadie haya diseñado ese filtro. Los dos experimentos juntos dicen exactamente dónde está la frontera: el aprendizaje aporta cuando la apariencia no se sabe describir, y no aporta cuando sí. El segundo error, más operativo, es olvidar que la geometría no se aprende; se desmonta pidiendo el número: la red entrega un centroide en píxeles y el robot necesita milímetros, y en medio está la K de la primera sesión del bloque."));
children.push(h3("Si la clase no habla"));
children.push(p("Con la tabla repartida el silencio es improbable, pero cuando ocurre suele ser porque el enunciado de los casos es demasiado abierto y nadie quiere ser el primero en interpretarlo. La maniobra de rescate consiste en cerrar el caso con números en voz alta: la pieza torneada es un eje de veinte milímetros con tolerancia de dos centésimas, la célula de logística recibe cuatrocientas referencias distintas al día, la célula colaborativa comparte espacio con un operario cada noventa segundos. Con datos concretos la tabla se rellena sola. La segunda maniobra es la votación por filas: se lee cada criterio y se pide levantar la mano a quienes crean que ése es el que manda en su caso, contando en voz alta; el reparto visible obliga a que alguien defienda su fila. Y hay una tercera que funciona con grupos muy callados: el profesor toma el caso difícil y da la respuesta equivocada en voz alta, con convicción, invitando a que la desmonten. Refutar una posición ajena es mucho más fácil que construir una propia, y la clase que refuta al profesor ya está discutiendo."));
children.push(h3("Cierre"));
children.push(p("Se cierra con la regla que el guion ya fija y que conviene decir tal cual: la geometría calibrada de S25 no se aprende, incluso el sistema más neuronal necesita saber su matriz K, y el clásico sigue ganando cuando hay control de iluminación, tolerancias métricas y pocos datos. Y con el corolario que la discusión ha demostrado y la tabla no podía demostrar: los tres casos han acabado en soluciones híbridas y ninguna columna ha ganado limpiamente, que es exactamente el estado real de la percepción robótica industrial. Conviene añadir una frase sobre el tercer caso, porque es la que hay que recordar en el proyecto: la seguridad no se decide en esta tabla. Lo que no conviene decir es que con el tiempo el aprendizaje absorberá también la geometría y la seguridad: es especulación, no está en ninguna fuente del bloque y arruina el criterio que se acaba de construir. Tampoco conviene cerrar con que depende de cada caso, sin más, porque es la fórmula que anula diez minutos de trabajo; lo que hay que dejar escrito no es que dependa, sino de qué depende."));

children.push(h2("La discusión de la hipótesis de Markov en S28 (33–40 min)"));
children.push(h3("Objetivo"));
children.push(p("La teoría enuncia la hipótesis y su violación en dos líneas: el estado completo hace el futuro independiente del pasado dado el presente, en la práctica se viola por dinámicas no modeladas, personas que se mueven o errores sistemáticos de los modelos, y parte del oficio consiste en meter en el estado lo suficiente para que la violación sea tolerable (Thrun et al., 2005, p. 33). Leído, eso parece una advertencia menor; discutido, se convierte en la decisión de diseño más importante del bloque. El objetivo de estos siete minutos es que el estudiante deje de ver la hipótesis de Markov como un requisito matemático que el mundo cumple o no cumple, y empiece a verla como una consecuencia de qué variables ha decidido meter en el vector de estado. La diferencia con la teoría es de dirección: la teoría pregunta si el sistema es markoviano y la discusión pregunta qué habría que añadir al estado para que lo fuera, que es la pregunta que se hace en un proyecto. Hay un objetivo secundario que se cobra en el bloque 8: la misma frase, casi literal, reaparecerá en S38 al decir que elegir como estado la última imagen de cámara a menudo no basta."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 10 a 40 minutos cubre la creencia y el filtro de Bayes, con el ejemplo de la puerta y la hipótesis de Markov como puntos finales. La discusión ocupa del 33 al 40, con el aviso computacional del último punto integrado en el cierre. El reparto: en el minuto 33, con el ejemplo de la puerta todavía en la pizarra, la creencia que ha subido a 0,983 tras dos ciclos (Thrun et al., 2005, pp. 28-31), se enuncia la pregunta y se callan diez segundos. De 34 a 38, cuatro minutos de casos, anotando en dos columnas: «viola Markov» y «se arregla ampliando el estado». De 38 a 40, la síntesis y el puente al problema computacional, que es lo que estructura el resto del bloque: el filtro exacto sólo puede implementarse para problemas de estimación muy simples (Thrun et al., 2005, p. 28). Es importante conservar el ejemplo de la puerta en la pizarra: la discusión funciona porque se hace sobre un caso que la clase acaba de calcular a mano, no sobre un robot imaginario."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, señalando el 0,983 de la pizarra: «Este número sale de suponer que, sabiendo si la puerta está abierta ahora, da igual lo que pasara antes. Decidme una situación de este mismo pasillo en la que eso sea falso, y decidme qué habría que meter en el estado para que volviera a ser verdad.» La segunda mitad de la pregunta es la que la hace productiva; sin ella se obtiene una lista de quejas sobre el mundo real, con ella se obtiene diseño. Y pedir un caso del mismo pasillo, en lugar de un caso cualquiera, evita el salto inmediato a la robótica de exteriores y a los coches autónomos, que es el desvío previsible."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«Si hay una persona que abre y cierra la puerta». ", bold: true },
 { text: "Es la primera y es literalmente el ejemplo del libro. Se acepta y se lleva de inmediato a la segunda mitad: qué se mete en el estado. La respuesta razonable, la presencia y la intención de la persona, produce en el aula una reacción muy útil, que es de incredulidad: nadie puede observar una intención. Ahí está el contenido: ampliar el estado es siempre posible en el papel y casi nunca gratis, porque cada variable añadida hay que poder estimarla con algún sensor y aumenta la dimensión del problema. Conviene dejar dicho que la salida profesional en este caso no es ampliar el estado sino admitir la violación y hacerla tolerable, subiendo el ruido de proceso para que el filtro no confíe demasiado." },
]));
children.push(pRuns([
 { text: "«Si la rueda patina siempre en la misma baldosa». ", bold: true },
 { text: "Es la respuesta buena y hay que celebrarla, porque es un error sistemático y no aleatorio, que es la clase de violación que rompe los filtros de verdad. La discusión que sigue es la mejor de las siete minutos: un sesgo constante no lo absorbe un ruido gaussiano de media cero, por mucho que se agrande, y la solución correcta es meter el sesgo en el estado y estimarlo, que es exactamente lo que hacen todas las fusiones inerciales del mundo con la deriva del giróscopo. Es también el momento de nombrar la innovación como detector: si el residuo entre lo medido y lo predicho tiene media distinta de cero, hay un sesgo sin modelar, y eso se ve en la pantalla del taller." },
]));
children.push(pRuns([
 { text: "«Si el sensor tiene retardo». ", bold: true },
 { text: "Aparece si alguien viene de la discusión de latencia de S27 y es un regalo, porque conecta las dos sesiones. Una medida que corresponde a un estado de hace tres ciclos no es función del estado actual, y el filtro que la trata como si lo fuera está violando la hipótesis de observación. Las dos salidas hay que nombrarlas: ampliar el estado con las poses pasadas dentro de la ventana de retardo, que es lo que hacen los estimadores con búfer, o compensar propagando la predicción hasta el instante de la medida. Y conviene señalar que el retardo volverá en el bloque 8 como el parámetro que por sí solo hunde una política entrenada sin él." },
]));
children.push(pRuns([
 { text: "«Entonces la hipótesis de Markov nunca se cumple». ", bold: true },
 { text: "Es la conclusión purista y llega casi siempre en el minuto 37. No se refuta: se le da la razón y se le añade lo que falta. Nunca se cumple exactamente, y sin embargo los filtros de este bloque funcionan y llevan décadas funcionando en aviones y en robots; la razón es que Markov no es una propiedad del mundo, es una propiedad del par formado por el mundo y el vector de estado que uno ha elegido, y el oficio consiste en elegirlo de modo que lo que queda fuera sea pequeño y parezca ruido. Esa frase, dicha en el minuto 37, es la que hay que escribir en la pizarra, porque es la tesis del apartado." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es creer que la hipótesis de Markov se refiere a la memoria del algoritmo y no al contenido del estado: como el filtro sólo guarda la creencia anterior, se concluye que el filtro olvida el pasado y que por eso es peor que un método que guardara toda la historia. Es un malentendido caro porque desemboca en desconfianza hacia el estimador entero. Se desmonta con la definición del propio libro, que es más fuerte de lo que parece: el estado se llama completo cuando es el mejor predictor del futuro, de modo que conocido el estado ningún dato anterior añade información (Thrun et al., 2005, p. 21). El filtro no olvida el pasado: el pasado está resumido en la creencia, y ese resumen es exacto si el estado es completo. La demostración de treinta segundos está en 82514_S28_Bayes_Kalman_EKF.ipynb, en el pasillo de veinte celdas: se ejecuta el filtro de Bayes discreto y se compara la creencia recursiva con la creencia recalculada desde el principio con toda la historia; son la misma. Con eso la discusión deja de ser filosófica. El segundo error, más específico, es intentar arreglar cualquier violación de Markov subiendo el ruido de proceso; se desmonta con el caso de la baldosa resbaladiza, donde un sesgo constante no lo absorbe ninguna gaussiana de media cero, y basta con ejecutar veinte pasos con un error sistemático para ver la estimación irse con la banda de confianza tan estrecha como al principio, el filtro seguro y equivocado, que es el modo de fallo más peligroso de todo el bloque."));
children.push(h3("Si la clase no habla"));
children.push(p("El silencio aquí es de abstracción: la pregunta es conceptual y llega en el minuto 33 de una clase de dos horas. La maniobra de rescate es aterrizar el caso hasta que sea imposible no opinar: se cambia la puerta abstracta por el laboratorio real y se pregunta qué pasa si el brazo del laboratorio empuja la puerta y el muelle la devuelve despacio, de modo que entre dos mediciones la puerta se está cerrando sola. Todo el mundo tiene algo que decir sobre un muelle. La segunda maniobra es la lista cerrada con votación: se enuncian cuatro situaciones y se pide, para cada una, mano arriba si viola Markov; el reparto en la pizarra fuerza el debate en las dos que salgan divididas. La tercera, para grupos muy callados, es invertir la tarea: en lugar de pedir violaciones, se pide que digan qué variables meterían en el estado de un robot que reparte comida en un hospital, y la violación aparece sola cuando alguien nombra a las personas."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, y conviene escribirla porque es la que sostiene S29, S30 y S31: la hipótesis de Markov no es una propiedad del mundo sino del estado que hemos elegido, y el diseño consiste en meter en el estado lo suficiente para que lo que queda fuera se pueda tratar como ruido (Thrun et al., 2005, p. 33). El corolario práctico, que se cobra en el taller de la segunda hora: cuando un filtro se equivoca con la banda de confianza estrecha, la sospecha no es el ajuste del ruido, es que falta una variable en el estado. Y el puente al resto del bloque se hace con el otro punto del guion, que encaja aquí solo: ampliar el estado tiene un precio computacional, el filtro exacto sólo es implementable en casos muy simples (Thrun et al., 2005, p. 28), y de ahí salen las dos familias de aproximaciones que ocupan las tres sesiones siguientes. Lo que no conviene decir es que en la práctica esto no importa porque los filtros funcionan igual: importa, y es la causa de la mitad de los fallos que verán en el proyecto. Tampoco conviene abrir aquí los modelos ocultos de Markov ni las redes con memoria, aunque alguien los nombre: se anotan y se remiten al bloque 8, donde el mismo problema reaparece con las arquitecturas con memoria."));

children.push(h2("La puesta en común del ejercicio de S29 (49–55 min): la pregunta trampa de la baliza lejana"));
children.push(h3("Objetivo"));
children.push(p("El ejercicio en parejas es de papel y tiene enunciado cerrado: robot en (2, 1, 30°) con su covarianza, baliza en (5, 5), calcular la predicción de medida h(μ̄), el jacobiano H y razonar, sin invertir nada, en qué dirección corrige el filtro si el rango medido es mayor que el predicho. La puesta en común no está para corregir la aritmética, que se corrige en treinta segundos, sino para explotar la pregunta trampa que el guion reserva al final: qué pasa con la componente de rumbo si el robot está muy lejos de la baliza. El objetivo es que la clase lea el jacobiano como geometría y no como una tabla de derivadas: la fila del rango apunta del hito al robot y corrige a lo largo de la línea de vista; la fila del rumbo es perpendicular y decae con la distancia, de modo que una baliza lejana casi no informa sobre la orientación. Esa lectura es lo que convierte el EKF en algo que se puede diseñar, dónde coloco las balizas, en lugar de algo que se ejecuta. Y hay un aprendizaje mayor detrás, que es el que se cobra en S31: la observabilidad es una propiedad de la geometría del problema, no del algoritmo, y ningún filtro estima lo que las medidas no contienen."));
children.push(h3("Formato y tiempos"));
children.push(p("El guion asigna de 40 a 55 minutos al ejercicio guiado, con el cierre de 55 a 60. El reparto que funciona: de 40 a 49, nueve minutos de trabajo en parejas con el profesor rotando, que es tiempo suficiente porque las cuentas son cortas y el objetivo es que discutan la dirección de la corrección. De 49 a 51, dos minutos para recoger los números en la pizarra: el rango predicho, el rumbo predicho y el signo de cada componente de la corrección. De 51 a 55, cuatro minutos para la pregunta trampa, que es donde está el valor. Dos avisos de gestión. El primero es que hay que exigir que la dirección de la corrección se razone y se dibuje sobre la figura antes de escribir cualquier número: si se permite calcular primero, la mitad de las parejas invierte una matriz de dos por dos y pierde la intuición, que era todo el objetivo. El segundo es que la pregunta trampa hay que reservarla y no adelantarla; si se enuncia al empezar, las parejas la resuelven mientras trabajan y desaparece el efecto."));
children.push(h3("Pregunta de apertura"));
children.push(p("Para el barrido, con la figura en la pizarra: «El rango predicho es de unos 5 metros y el rumbo de unos 23 grados respecto al morro. El sensor os dice 5,4. Sin invertir nada: ¿hacia dónde se mueve la elipse y por qué?» Y para la trampa, en el minuto 51, literalmente: «Ahora la misma baliza está a cincuenta metros en lugar de a cinco, y medís rango y rumbo con el mismo sensor y el mismo ruido. ¿Qué componente de la pose deja de corregirse, y por qué?» La segunda formulación importa: se pregunta qué componente deja de corregirse, no si el filtro empeora, porque lo que hay que descubrir es que el deterioro no es global sino selectivo, el rango sigue informando perfectamente y la orientación se queda sin observación útil."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«Se mueve alejándose de la baliza». ", bold: true },
 { text: "Es la respuesta correcta y llega en seguida; el trabajo es hacer que la digan bien. Si el rango medido es mayor que el predicho, el robot está más lejos de la baliza de lo que creía, y la media se desplaza a lo largo de la línea que une hito y robot, en el sentido de aumentar la distancia. Conviene pedir que lo señalen con el dedo en la figura y que digan además qué le pasa a la elipse: se estrecha en esa dirección y no en la perpendicular, porque una medida de distancia no informa sobre el desplazamiento lateral. Esa asimetría, dibujada, es la mejor imagen del bloque, y es la que explica por qué con una sola baliza el filtro nunca se cierra." },
]));
children.push(pRuns([
 { text: "«Hemos calculado la corrección y nos sale que también cambia el ángulo». ", bold: true },
 { text: "Sale en dos o tres parejas y no es un error: es correcto y es interesante. Con la covarianza inicial correlacionando posición y orientación, una corrección de posición arrastra la orientación aunque la medida no hable de ella. Hay que acogerlo y nombrarlo, porque es exactamente el mecanismo que en S31 hará que reobservar un hito antiguo corrija todo el mapa a través de los bloques no diagonales de la covarianza (Corke, 2023, p. 229). Ver el fenómeno aquí, en una matriz de tres por tres que cabe en la pizarra, es lo que hace que en S31 no parezca magia." },
]));
children.push(pRuns([
 { text: "«Con la baliza lejana el rumbo ya no corrige». ", bold: true },
 { text: "Es la respuesta que busca la trampa y hay que exigir el por qué, porque el por qué es lo único que se aprende. La fila del rumbo en el jacobiano lleva la distancia en el denominador, de modo que a cincuenta metros un error de orientación de un grado produce en el rumbo medido una señal que el ruido del sensor tapa; el rango, en cambio, sigue midiéndose igual de bien. La consecuencia de diseño hay que sacarla en voz alta y conviene que la formule un estudiante: para observar la orientación hacen falta hitos cercanos, o dos hitos separados en ángulo, y por eso las balizas no se colocan lejos y agrupadas, que es precisamente cómo las coloca todo el mundo la primera vez." },
]));
children.push(pRuns([
 { text: "«Entonces el filtro se entera de que no sabe la orientación». ", bold: true },
 { text: "Es la mejor intervención posible y hay que llevarla hasta el final, porque la respuesta es medio sí y medio no, y ese matiz es el más valioso de la sesión. Sí, la covarianza refleja la mala observabilidad y la componente angular no se reduce: el filtro es honesto en eso. Pero no avisa de nada más, y una asociación de datos equivocada, haber tomado un hito por otro, inyecta una corrección coherentemente errónea que el filtro fusiona con toda confianza (Corke, 2023, p. 223). Distinguir la incertidumbre que el filtro sabe que tiene de la equivocación que el filtro no puede saber que tiene es el aprendizaje que abre S30." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es leer la ganancia de Kalman como una constante de sintonía y no como el resultado de una geometría: se concluye que si el filtro corrige poco la orientación es porque hay que subir la ganancia, o bajar el ruido de medida del rumbo, o retocar los coeficientes hasta que la elipse angular se cierre. Es el error más peligroso del bloque porque produce filtros que aparentan precisión: bajar el ruido declarado del rumbo estrecha la elipse sin añadir un bit de información, y el resultado es un estimador seguro y equivocado. Se desmonta con el propio cuaderno y en un minuto: en 82514_S29_Localizacion_EKF.ipynb se ejecuta el recorrido con la baliza lejana y con el ruido de rumbo declarado a la mitad, y se comparan las dos gráficas de error real frente a banda de confianza; en la segunda la banda se ha estrechado y el error no ha bajado, de modo que la elipse ha dejado de contener la verdad. La conclusión hay que dictarla porque vale para todo el curso: una covarianza no se ajusta para que salga pequeña, se ajusta para que sea verdad, y la comprobación es que el error real caiga dentro de la banda la fracción de veces que la banda promete. El segundo error, más benigno, es intentar resolver el ejercicio invirtiendo matrices; se desmonta a coste cero pidiendo la dirección antes del número, que es lo que ya prescribe el enunciado."));
children.push(h3("Si la clase no habla"));
children.push(p("Después de nueve minutos de trabajo en parejas la clase habla, y si no habla es porque no ha terminado. La maniobra de rescate correcta no es lanzar preguntas al aire, es pedir un dato a una pareja concreta: cuánto os ha salido el rango predicho. Es una pregunta de un solo número, sin riesgo, y una vez que hay un número en la pizarra la discusión sobre la dirección arranca sola. Si el bloqueo es en la pregunta trampa, funciona el gesto: el profesor se coloca en un extremo del aula, señala un punto del techo y camina dos pasos girando ligeramente, preguntando si desde allí se nota el giro mirando ese punto y si se notaría mirando algo a un palmo de la cara. La geometría de la observabilidad se entiende con el cuerpo antes que con el jacobiano, y treinta segundos de teatro ahorran tres minutos de álgebra. La tercera maniobra, si sigue el silencio, es la votación: quién dice que a cincuenta metros la orientación se corrige mejor, igual o peor; el reparto casi siempre está dividido y de ahí ya se puede pedir razones."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar es que el jacobiano es geometría y se lee: cada fila dice en qué dirección del espacio de estados informa esa medida, y la longitud de esa flecha es lo que decide si la componente se corrige o no. El corolario práctico, que se lleva al proyecto y a la vida profesional: la colocación de las balizas o de los reflectores es parte del diseño del estimador, y un mapa de hitos lejanos y agrupados no se arregla con ningún ajuste de software. Conviene rematar con la frase que ya está en el apartado 29.3 y que aquí cae sola: la incertidumbre crece sin límite con dead reckoning y la solución, como descubrieron los fenicios hace cuatro mil años, es usar observaciones de hitos conocidos (Corke, 2023, p. 218), con el añadido que la discusión ha demostrado, que no todos los hitos informan de lo mismo. Lo que no conviene hacer es dar el número de la corrección como respuesta final del ejercicio: el número es lo menos importante y darlo como resultado enseña que el objetivo era calcular. Y no conviene tranquilizar diciendo que en la práctica esto lo resuelve AMCL con el lidar: es cierto que el barrido completo mejora la observabilidad angular, pero decirlo aquí desactiva la lección justo antes de que sea útil, y además en S30 saldrá con su propio argumento."));

children.push(h2("La construcción de la tabla EKF frente a MCL en S30 (52–60 min)"));
children.push(h3("Objetivo"));
children.push(p("El guion es explícito en que la tabla comparativa del apartado 30.3 se construye con la clase y no se dicta, y la instrucción merece respetarse al pie de la letra porque la tabla dictada se copia y la tabla construida se recuerda. Lo que debe quedar aprendido no son las seis filas, que están impresas en estos apuntes, sino la habilidad de derivarlas de una sola diferencia: cómo se representa la creencia. Todo lo demás, si admite multimodalidad, si resuelve la localización global, si se recupera de un secuestro, qué suposiciones hace, cómo escala el coste, es consecuencia de esa elección, y una clase que lo ve así puede completar la tabla de un estimador que no ha estudiado. La diferencia con la teoría es de dirección otra vez: la exposición presenta dos algoritmos y sus propiedades, y la construcción de la tabla obliga a demostrar que las propiedades se siguen de la representación. Hay un objetivo de cierre de bloque además: esta tabla es la que permite plantear la pregunta de S31, y si tampoco tenemos el mapa, sin que suene a tema nuevo."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 52 a 60 son ocho minutos y es el cierre de una sesión de una hora, de modo que la tabla y el anuncio de S31 tienen que caber. El reparto: en el minuto 52 se dibuja la tabla vacía en la pizarra con las dos columnas rotuladas y sólo la primera fila escrita, representación de la creencia; se rellena esa fila con la clase en treinta segundos, porque es pura recuperación. De 53 a 58, cinco minutos para las cinco filas restantes, con la regla de conducción que hace que esto funcione: cada fila la propone un estudiante y la justifica desde la fila primera, y el profesor sólo escribe. De 58 a 59, se relee la tabla completa en voz alta señalando que ninguna fila era información nueva. De 59 a 60, la pregunta que abre S31. Dos avisos. El primero es no rotular las filas de antemano: si el profesor escribe los seis criterios, la clase rellena huecos en lugar de decidir qué importa. El segundo es no dejar que la tabla derive a un ranking; en cuanto alguien pregunta cuál es mejor, hay que devolver la pregunta con un para qué."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con la tabla casi vacía: «Arriba hemos escrito la única diferencia real: el EKF guarda una media y una covarianza, y el MCL guarda mil partículas con pesos. Todo lo demás se deduce de ahí. Decidme una consecuencia de esa diferencia que os importe como ingenieros, y la escribimos como fila.» La formulación pide una consecuencia y no un criterio, que es más fácil de producir, y añade la condición de que importe como ingenieros, que filtra las diferencias irrelevantes. Cuando la tabla lleve tres filas conviene una segunda pregunta, más exigente: «¿Cuál de estas filas es la que decide en el robot del proyecto?»"));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«El MCL puede tener varias hipótesis y el EKF no». ", bold: true },
 { text: "Es la primera y hay que exigir la justificación desde la representación, no aceptarla como dato memorizado: una gaussiana tiene una sola moda por definición, así que la creencia de dos pasillos idénticos no es representable, mientras que una nube de partículas puede tener tantos cúmulos como haga falta (Thrun et al., 2005, p. 97; Corke, 2023, p. 236). Merece la pena pedir el caso concreto, el pasillo con tres puertas de la secuencia gráfica que se acaba de proyectar (Thrun et al., 2005, pp. 250-252), porque la fila de la tabla se recuerda con la imagen, no con la palabra multimodalidad." },
]));
children.push(pRuns([
 { text: "«El MCL cuesta más». ", bold: true },
 { text: "Sale siempre y es la fila que hay que trabajar, porque tal como se enuncia es medio falsa. Hay que pedir en qué crece el coste, y la respuesta correcta tiene dos partes: crece con el número de partículas, que es un parámetro que se elige, y crece con la dimensión del estado, que no. El EKF, en cambio, tiene coste bajo y constante pero cuadrático en el tamaño del estado cuando el estado crece, cosa que en S31 será decisiva. Conviene además introducir aquí el tamaño adaptativo de la nube, que es la respuesta industrial al problema: muchas partículas cuando la creencia está dispersa y pocas cuando está concentrada (Thrun et al., 2005, cap. 8), que es lo que hace el nodo que ejecutarán en el bloque 7." },
]));
children.push(pRuns([
 { text: "«El EKF necesita que le digas dónde está al principio». ", bold: true },
 { text: "Es una fila excelente porque es la que se cobra en el bloque 7: cuando en la demo de Nav2 haya que fijar la pose inicial con el ratón en RViz, ya sabrán por qué. Se acepta y se completa con la taxonomía que se dio en S29: seguimiento de posición, localización global y robot secuestrado, siendo el tercero el más difícil porque el robot cree firmemente estar donde no está (Thrun et al., 2005, p. 194). Y se cierra con el remedio, que es una fila más: la inyección de partículas aleatorias devuelve la capacidad de recuperación, y conviene ligarla a la caída de la verosimilitud media de las medidas en lugar de inyectar un número fijo (Thrun et al., 2005, pp. 257-259)." },
]));
children.push(pRuns([
 { text: "«Entonces el MCL es mejor y el EKF es un algoritmo antiguo». ", bold: true },
 { text: "Llega en el minuto 57 y es la conclusión que hay que desactivar, porque la tabla existe para lo contrario. La respuesta no es un discurso sino una fila más: usos típicos. El EKF es el que se usa para fusión fina y de alta frecuencia con inercial y satélite, donde la creencia es unimodal por construcción y el presupuesto de cómputo es de microsegundos; el MCL es el que se usa para localizar con lidar sobre un mapa de ocupación. Y hay que decir en voz alta que en el robot del proyecto conviven los dos, porque conviven de verdad: uno en la odometría fusionada y otro en la localización. Con eso la tabla deja de ser un ranking." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es creer que más partículas equivale a más precisión, y de ahí que el ajuste del MCL consista en subir el número de partículas hasta donde llegue el ordenador. Es un error con consecuencias inmediatas en el proyecto, porque produce localizadores lentos que se pierden igual. Se desmonta con el experimento que 82514_S30_Filtro_Particulas_MCL.ipynb tiene preparado y que cuesta cuarenta segundos: se ejecuta la localización global con nubes de tamaño creciente y se mira dónde está el fallo. Con pocas partículas el filtro se pierde por falta de cobertura inicial; con muchas no se pierde, pero la precisión final la fija el modelo de medida y el ruido, no el número de muestras, y la curva de error se aplana mucho antes de agotar el cómputo. La lectura que hay que sacar es que las partículas compran cobertura de hipótesis, no resolución, y que el empobrecimiento por remuestreo puede matar la hipótesis correcta con cualquier número de partículas (Thrun et al., 2005, p. 100). El segundo error, muy extendido, es suponer que un filtro de partículas no hace suposiciones porque no supone gaussianidad; se desmonta señalando la fila correspondiente de la tabla: sí hace dos, que se pueda muestrear del modelo de movimiento y que se pueda evaluar la verosimilitud de la medida, y ambas son exigentes cuando el sensor es complicado."));
children.push(h3("Si la clase no habla"));
children.push(p("En el minuto 52 de una sesión de una hora el silencio es cansancio, no ignorancia, y la maniobra de rescate tiene que bajar el esfuerzo a cero. Lo que funciona es pedir comparaciones binarias en lugar de criterios: se enuncia una situación y se pregunta a mano alzada quién elegiría cada estimador. Cuatro situaciones bastan y ya escriben cuatro filas de la tabla: fusionar una unidad inercial a doscientos hercios; encender el robot en un almacén sin saber dónde está; un almacén con dos naves simétricas; un ordenador de a bordo sin margen de cómputo. Cada votación se cuenta, se escribe y se pide una razón al bando mayoritario, y en cinco minutos la tabla está completa sin que nadie haya tenido que proponer un criterio abstracto. La segunda maniobra, si el grupo sigue frío, es dictar dos filas mal, con las columnas cambiadas, y pedir que las corrijan; corregir es siempre más fácil que producir, y una tabla con errores en la pizarra es un imán."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar es que las seis filas son consecuencias de una sola decisión, la representación de la creencia, y que por eso la pregunta profesional no es qué algoritmo es mejor sino qué forma tiene la creencia que hace falta representar. Conviene dejar escrito el corolario que se cobra al día siguiente: si la creencia tiene que poder decir «no sé dónde estoy», ninguna gaussiana sirve, y si tiene que actualizarse en microsegundos, ninguna nube sirve. Y se cierra con la pregunta que el guion reserva y que hay que dejar sin contestar, literalmente: «¿Y si tampoco tenemos el mapa?» Lo que no conviene hacer es rematar declarando un ganador ni sugiriendo que el EKF ha quedado obsoleto: además de falso, desmonta el trabajo de la sesión siguiente, que empieza precisamente con EKF-SLAM como el algoritmo más influyente de la historia del SLAM (Thrun et al., 2005, p. 312). Tampoco conviene ampliar la tabla con más estimadores, filtro de partículas Rao-Blackwellizado, filtro de información, suavizadores, aunque alguien los nombre: se anotan, se prometen para S31 y se respeta el timbre."));

children.push(h2("El panorama de SLAM neuronal en S31 (85–100 min): la discusión de frontera del bloque"));
children.push(h3("Objetivo"));
children.push(p("Este tramo es distinto de todos los anteriores y conducirlo como si fuera uno más es el error que lo estropea. Aquí no hay una decisión de criterio con datos del taller: hay una frontera en movimiento, NeRF, 3D Gaussian Splatting y su entrada en el SLAM denso, que la propia teoría presenta explícitamente como panorama y sin cita de libro, y cuyo material se cita por identificador de arXiv y nada más. El objetivo, por tanto, no es que la clase decida nada, sino que salga capaz de dos cosas. La primera es situar lo nuevo en el esqueleto viejo: reconocer que lo que cambia es la representación del mapa, rejillas, puntos, campos neuronales, gaussianas, y que los modelos probabilísticos de movimiento y observación, la creencia y la optimización siguen siendo los del capítulo 2 de Thrun. La segunda es distinguir lo que estas técnicas han demostrado de lo que se les atribuye, que es el hábito que el seminario de artículos va a evaluar y que en el bloque 8, con los modelos VLA, se convertirá en la competencia central. La diferencia con la teoría es sutil pero real: la exposición puede permitirse enumerar hitos, y la discusión tiene que enseñar a preguntar."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 85 a 100 minutos es de panorama y la discusión hay que integrarla en él, no añadirla: de 85 a 92, la exposición del SLAM visual con ORB-SLAM como sistema completo (Mur-Artal et al., 2015, arXiv:1502.00956) y de las dos representaciones neuronales (Mildenhall et al., 2020, arXiv:2003.08934; Kerbl et al., 2023, arXiv:2308.04079), con los vídeos de síntesis de vistas que hacen falta para que la conversación tenga objeto. De 92 a 98, seis minutos de discusión con la pregunta de apertura. De 98 a 100, el cierre, que es el mensaje del guion sobre lo que cambia y lo que no. Después vienen la síntesis del bloque y el cuestionario, que necesitan sus veinte minutos, de modo que aquí no hay margen para estirar y conviene decirlo al empezar. Un aviso de conducción específico de las discusiones de frontera: hay que anunciar en voz alta el marco antes de abrirla, con una frase del tipo de que en los próximos seis minutos vamos a distinguir lo publicado de lo esperado y que las dos cosas son legítimas si se etiquetan. Sin ese marco, la conversación se vuelve un intercambio de entusiasmos en noventa segundos."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con la reconstrucción proyectada: «Esto que estáis viendo es espectacular y es real: son fotos nuevas de una escena, generadas desde puntos de vista donde nunca hubo cámara. Ahora la pregunta de ingeniero: para que un robot navegue por esa habitación, ¿qué le falta a esa representación que sí tiene la rejilla de ocupación de hace veinte minutos?» La formulación hace tres cosas a la vez, y por eso conviene respetarla. Reconoce el mérito antes de interrogarlo, que evita que la discusión se lea como escepticismo de profesor mayor. Pide una carencia concreta en lugar de una opinión, lo que obliga a usar el vocabulario del bloque. Y compara con un objeto que la clase ha construido, no con una abstracción, de modo que las respuestas se pueden defender con lo que ya saben."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«Le falta saber por dónde se puede pasar». ", bold: true },
 { text: "Es la respuesta que hay que buscar y suele llegar en el primer minuto. Se acepta y se afila: una rejilla de ocupación responde en un acceso a memoria si una celda es transitable, porque para eso se construyó; una representación fotorrealista responde muy bien a qué se vería desde aquí y no responde directamente a qué es libre. Convertir una en otra es posible y se hace, pero es trabajo y tiene coste, y conviene nombrarlo así porque es la pregunta que hay que hacerle a cualquier representación nueva: qué consulta responde barato. Ese criterio, qué consulta es barata, es lo más transferible de los seis minutos y merece quedar escrito en la pizarra." },
]));
children.push(pRuns([
 { text: "«Entonces esto sustituirá al SLAM clásico en dos años». ", bold: true },
 { text: "Aparece siempre y no hay que ridiculizarla ni concederla: hay que pedirle la condición. La pregunta de vuelta, dicha sin ironía, es qué habría que ver publicado para creérselo, y la respuesta que la clase construye suele ser buena: tiempo real en hardware embarcado, robustez a iluminación cambiante y a escenas dinámicas, y consumo de memoria acotado en recorridos largos. Con eso la afirmación se ha convertido en una lista de criterios de evaluación, que es exactamente lo que el seminario pide. Conviene señalar en voz alta que ese giro, de la predicción a la condición de falsación, es la maniobra que hay que hacer con cualquier promesa tecnológica, y que se practicará en enero con los modelos VLA." },
]));
children.push(pRuns([
 { text: "«¿Y esto no necesita saber dónde estaba la cámara?». ", bold: true },
 { text: "Es la mejor pregunta del tramo y hay que provocarla si no sale, porque su respuesta es el argumento central de la sesión. Sí: las reconstrucciones se optimizan a partir de imágenes con sus poses, y esas poses las suele producir un sistema geométrico clásico. De modo que la frontera no está sustituyendo a los cimientos, está construyendo encima de ellos, la proyección perspectiva de S25 sigue siendo el modelo de observación y la optimización por mínimos cuadrados sigue siendo la maquinaria, exactamente como en el pose-graph del apartado 31.3 (Corke, 2023, pp. 230-232). Es también la ocasión de recordar el marco arquitectónico del bloque: ORB-SLAM es un pose-graph cuyo modelo de observación es la proyección perspectiva, y verlo así es el examen conceptual del bloque." },
]));
children.push(pRuns([
 { text: "«¿Y para qué sirve entonces?». ", bold: true },
 { text: "Es la reacción pendular del escéptico y hay que atenderla con casos, porque si no la discusión acaba en desdén, que es tan malo como el entusiasmo. Los usos que ya existen y se pueden nombrar sin especular son la digitalización de entornos para simulación y para teleoperación y su papel como representación de mapa dentro de sistemas de SLAM denso, que es lo que dice el propio apartado 31.5. Y hay una conexión que conviene dejar caer porque se cobra en diciembre: un entorno reconstruido con estas técnicas es materia prima para el gemelo digital y para generar datos sintéticos de entrenamiento, que es el papel que aparecerá en el bloque 8." },
]));
children.push(h3("Cómo distinguir lo demostrado de lo esperado"));
children.push(p("Merece un apartado propio porque es el contenido real de estos seis minutos y porque no está en ninguna otra parte del bloque. La técnica que uso es de tres preguntas, y conviene escribirlas en la pizarra la primera vez que se usan porque después sirven para todo el curso. Primera: qué se ha medido exactamente y sobre qué. En estas líneas de trabajo la métrica suele ser la calidad de síntesis de vistas nuevas sobre conjuntos de escenas estáticas y bien iluminadas, y eso es un resultado sólido y a la vez muy distinto de navegar por un pasillo con gente andando. Segunda: qué condiciones tenía el experimento que no tendrá el robot. Aquí las candidatas son casi siempre las mismas y la clase las encuentra sola si se le pide: escena estática, cobertura completa de cámaras, poses conocidas de antemano, cómputo de sobremesa. Tercera: qué se afirma como resultado y qué se afirma como perspectiva, distinción que en los propios artículos suele estar clara y que se difumina en la divulgación. Aplicadas a esta discusión, las tres preguntas producen una posición defendible y honesta: la calidad de reconstrucción está demostrada, su uso como mapa dentro de un SLAM denso está en curso, y su sustitución de la rejilla de ocupación para navegación no está demostrada. Conviene dejar esa frase escrita con las tres etiquetas, porque es el modelo de lo que se pedirá en las presentaciones del seminario y en el bloque 8."));
children.push(h3("Si la clase no habla"));
children.push(p("En una discusión de frontera el silencio tiene una causa particular: nadie quiere opinar sobre un tema donde intuye que no sabe lo suficiente, y con razón. La maniobra de rescate no es pedir opiniones, es pedir comparaciones con lo que sí conocen. Funciona muy bien la tabla de tres columnas: rejilla de ocupación, nube de puntos con descriptor y representación neuronal, y tres filas que la clase puede rellenar sin saber nada de la frontera, qué consulta responde barato, qué necesita para construirse y qué cuesta guardarla. Rellenar celdas sobre lo conocido produce, sin que nadie lo note, una posición sobre lo desconocido. La segunda maniobra es la pregunta de inversión: en lugar de preguntar qué le falta a lo nuevo, se pregunta qué tenía de malo la rejilla de ocupación, que es una pregunta sobre material propio y con respuestas abundantes, dos dimensiones, resolución fija, nada de apariencia, nada de semántica; de esa lista sale sola la motivación de lo nuevo y la conversación ya está abierta. La tercera, si el grupo está agotado a los cien minutos de clase, es reducir la ambición y pedir sólo una pregunta: qué le preguntaríais a los autores si estuvieran aquí. Recoger cuatro preguntas en la pizarra y no contestar ninguna es un cierre perfectamente legítimo, y además es exactamente lo que se hará en el seminario."));
children.push(h3("Cierre"));
children.push(p("Se cierra con el mensaje que el guion ya fija, dicho tal cual: cambia la representación del mapa, rejilla, puntos, campo neuronal, gaussianas, pero el esqueleto probabilístico, modelos, creencia y optimización, es el de este bloque. Y con el corolario que la discusión ha añadido y la exposición no podía añadir: lo nuevo se apoya en los cimientos viejos, porque estas reconstrucciones necesitan poses de cámara y las poses las produce la geometría de S25 y S31. Conviene rematar reconociendo explícitamente el estado del asunto, que es lo que da credibilidad a todo lo demás: es un campo en movimiento rápido, se presenta como panorama y no como materia cerrada, y de él el cuestionario sólo pedirá saber qué es cada cosa y dónde encaja. Lo que no conviene hacer es tomar partido, ni en el sentido de anunciar que esto lo cambiará todo ni en el de despacharlo como moda pasajera: las dos posiciones son especulación disfrazada de criterio, y la clase distingue perfectamente cuándo un profesor está opinando. Tampoco conviene entrar en detalles de arquitectura de las dos técnicas, por mucho que alguien lo pida: no está en la evaluación, se come la síntesis del bloque y el sitio para eso es una presentación del seminario, que es donde hay que remitirlo por su nombre."));

