// ============================================================ Guía de discusiones
children.push(new Paragraph({ children: [new PageBreak()] }));
children.push(h1("Guía de conducción de las discusiones y puestas en común de este bloque"));

children.push(p("El método general de conducción está desarrollado en los apuntes del bloque 1 y aquí se aplica sin cambios: los diez segundos de silencio después de formular la pregunta, sin reformular y sin contestarse; la distinción entre la pregunta cerrada de recuperación, las de los tramos que abren S33, S35 y S36, y el cuestionario relámpago que cierra S33, que no se discuten sino que se corrigen en segundos porque su función es forzar recuperación activa, y la pregunta abierta de discusión, que se lanza al grupo entero y cuyo valor está en el razonamiento; la votación a mano alzada cuando conviene hacer visible un criterio; el reparto de la palabra; y la exploración de la respuesta errónea antes de corregirla nombrando fuente y sección. Lo que cambia es la materia. En este bloque las discusiones son de criterio técnico y nacen de resultados del taller, igual que en el bloque 6, pero con dos particularidades propias. La primera es que aquí el resultado del que nacen suele ser un fallo y no un número: los topics están y no llega nada, el robot tiembla en RViz, el planificador no encuentra camino con la pinza cargada. La segunda es que gran parte del material se cita sin página, porque para ROS 2, Gazebo, Nav2 y MoveIt 2 no existe edición paginada estable y se cita por nombre de documento y sección (docs.ros.org, docs.nav2.org, moveit.picknik.ai); eso cambia la mecánica del cierre, porque el gesto de zanjar señalando la página se sustituye por el de abrir la página de configuración en el proyector, que funciona igual de bien y además enseña a leer documentación."));
children.push(p("De ahí tres consecuencias prácticas. La primera es que en este bloque el árbitro es la terminal: casi cualquier disputa sobre qué hace el sistema se resuelve ejecutando ros2 topic hz, ros2 topic info o view_frames delante de todos, y conviene tener las terminales abiertas durante las discusiones y no sólo durante el taller. La segunda es que los dos cuadernos del bloque están construidos precisamente para producir el material de estas puestas en común: 82514_S34_Entorno_ROS2_TF2.ipynb contiene la celda de diagnóstico que cada estudiante debe pasar antes del taller y la reimplementación en numpy del árbol de transformadas, con el experimento de la deriva en odom frente a la sierra acotada en map; y 82514_S35_Planificacion.ipynb produce las cifras con las que se construye la tabla comparativa de planificadores, las longitudes de camino, las tasas de éxito y la dispersión entre semillas, sin las cuales esa tabla es una lista de adjetivos. La tercera es que las discusiones más valiosas del bloque no son las de teoría sino las dos de taller: la puesta en común de errores frecuentes de S34, que es la parte más rentable de esa sesión, y la composición del stack completo de S37, que es el andamiaje del proyecto integrador."));
children.push(box("La regla añadida en este bloque", "Ninguna afirmación sobre lo que hace el sistema se acepta sin comprobarla en la terminal. Si alguien dice que el nodo publica, se pide ros2 topic hz; si dice que la transformada existe, se pide tf2_echo; si dice que el planificador falla, se pide el mensaje de error literal. No es desconfianza: es que en un sistema distribuido la intuición sobre lo que está pasando es sistemáticamente peor que la introspección, y aprender ese reflejo es la mitad del bloque."));

children.push(h2("El ejercicio de QoS a mano alzada en S32 (50–55 min)"));
children.push(h3("Objetivo"));
children.push(p("El apartado 32.3 ya da las respuestas: un flujo de sensor de alta frecuencia como /scan se publica best effort porque si se pierde un barrido el siguiente llega en veinticinco milisegundos y retransmitir sólo añadiría latencia, y un mapa que se publica una vez debe ser reliable y transient local para que un visualizador arrancado más tarde lo reciba, combinación que ningún perfil predefinido ofrece, porque «sensor data», «services» y el perfil por defecto son todos volatile y la durabilidad hay que declararla a mano (docs.ros.org, About Quality of Service settings). Si la discusión se conduce como una comprobación de esas tres respuestas, sobra. Lo que aporta y la exposición no puede aportar es que el estudiante descubra que la elección de QoS no es una preferencia sino una consecuencia de dos preguntas sobre el canal: qué pasa si se pierde un mensaje, y a quién le hace falta el último mensaje si llega tarde. Con esas dos preguntas se resuelven canales que no están en ninguna lista, y eso es lo que se necesita en diciembre. El segundo objetivo es preventivo y muy concreto: dejar clavada la regla de compatibilidad antes del taller, porque una pareja reliable contra best effort no da error, simplemente no fluye nada, y ese fallo silencioso es el que más horas consume en los proyectos."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 40 a 55 minutos es el de DDS y QoS, y el ejercicio es su último punto: cinco minutos, del 50 al 55, con el cierre de la sesión de 55 a 60. El reparto: en el minuto 50 se escriben en la pizarra los tres topics en columna y, al lado, las dos preguntas de decisión; se enuncia el ejercicio y se callan diez segundos. De 50 a 53, las tres votaciones a mano alzada, una por topic, con recuento escrito y sin comentar. De 53 a 55, las razones y la regla de compatibilidad. La mecánica de la votación conviene respetarla al detalle porque es lo que hace hablar a un grupo que lleva veinte minutos oyendo hablar de middleware: se enuncia la opción, se pide que voten todos a la vez a una señal, se cuenta en voz alta y se escribe el número sin valorarlo. Y hay una decisión de formato que decide el rendimiento: se vota primero y se razona después, no al contrario, porque quien ya ha comprometido su mano tiene algo que defender."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con los tres topics escritos: «Tres canales de nuestro robot: /scan, que publica el láser a cuarenta hercios; /cmd_vel, que lleva las consignas de velocidad a los motores; y /map, que se publica una sola vez al arrancar. Para cada uno voy a pediros dos manos: fiable o mejor esfuerzo, y si hace falta que un suscriptor que llegue tarde reciba el último mensaje. No quiero justificaciones todavía, quiero manos.» Y después de cada votación, la pregunta que produce el contenido: «¿Qué pasa exactamente si se pierde un mensaje de este canal?» Formular el ejercicio como dos decisiones binarias y no como qué QoS pondríais es lo que lo hace ejecutable en cinco minutos: qué QoS pondríais admite un discurso, y esto admite una mano."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "/scan: mayoría abrumadora por fiable. ", bold: true },
 { text: "Es el resultado que sale casi siempre, típicamente veinticinco manos contra cinco, y es la equivocación productiva del ejercicio: el razonamiento subyacente es que los datos del sensor son importantes, luego hay que garantizarlos. No se corrige de frente; se pregunta qué hace el sistema mientras espera la retransmisión de un barrido perdido. La respuesta, esperar un dato viejo teniendo uno nuevo disponible, la construye la clase sola, y de ahí sale la formulación correcta: en un flujo periódico y redundante, la fiabilidad se paga en latencia y la latencia es peor que la pérdida. Conviene rematar con el número: a cuarenta hercios el siguiente barrido llega en veinticinco milisegundos, y ningún mecanismo de retransmisión es más rápido que eso. Es el mismo argumento que en S27 del bloque 6 hacía preferir un detector rápido a uno preciso." },
]));
children.push(pRuns([
 { text: "/cmd_vel: la clase se divide. ", bold: true },
 { text: "Es la votación más interesante y hay que trabajarla, porque las dos posiciones tienen argumento. Quien vota fiable dice que una consigna perdida es una consigna que el robot no ejecuta; quien vota mejor esfuerzo dice que el controlador publica a diez o veinte hercios y que el siguiente comando corrige. Los dos tienen razón en un caso distinto, y la pregunta que lo aclara es qué significa el mensaje: si /cmd_vel lleva una consigna que se mantiene hasta la siguiente, perder un mensaje es perder actualidad y el flujo se autorrepara; si el diseño fuera de comandos con efecto acumulativo, perder uno sería perder estado y habría que garantizarlo. La lección de ingeniería, que vale para todo el bloque, es que la QoS de un canal se decide leyendo la semántica del mensaje, no el nombre del topic. Y el remate práctico: además de la QoS, este canal necesita un vigilante de plazo, porque lo peligroso no es perder un mensaje sino dejar de recibirlos con el robot en marcha, que es exactamente para lo que existe la política de deadline (docs.ros.org, About Quality of Service settings)." },
]));
children.push(pRuns([
 { text: "/map: nadie ve la durabilidad hasta que se les pregunta. ", bold: true },
 { text: "En la primera votación casi todos aciertan con fiable y casi nadie pide que el suscriptor tardío reciba el mensaje, porque es la política menos intuitiva de las cuatro. La forma de hacerla evidente es un escenario en dos frases: el mapa se publica una vez, en el segundo tres del arranque; abrís RViz en el segundo cuarenta. ¿Veis el mapa? La respuesta es no, y el gesto de incomodidad que produce es el mejor argumento posible para transient local. Conviene añadir que este caso concreto va a ocurrirles en el taller de S36 y que cuando ocurra sabrán qué mirar, lo cual convierte cinco minutos de teoría en una hora de laboratorio ahorrada." },
]));
children.push(pRuns([
 { text: "«¿Y si me equivoco de QoS, qué pasa?». ", bold: true },
 { text: "Es la mejor pregunta del tramo y si no sale hay que provocarla, porque la respuesta es la regla que hay que dejar escrita en la pizarra: un publicador y un suscriptor sólo se conectan si sus políticas son compatibles, y una pareja incompatible no produce ningún error, simplemente no fluye ningún mensaje. Hay que decirlo con las palabras que van a usar ellos, los topics están, ros2 topic list los enseña, y ros2 topic echo no imprime nada, y dar de inmediato el procedimiento de diagnóstico: ros2 topic info con el detalle de perfiles, que muestra los publicadores y suscriptores y sus políticas. Esa secuencia de tres comandos es el contenido más rentable de la sesión entera." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es identificar fiabilidad con importancia: cuanto más importante es el dato, más fiable debe ser el canal. Es un error de categoría y sobrevive a cualquier explicación teórica, porque suena a sentido común. La única forma de desmontarlo es con el experimento, y por suerte cuesta noventa segundos en la clase siguiente y conviene anunciarlo aquí: en el taller de S34, con el TurtleBot simulado, se mide ros2 topic hz /scan con el perfil de datos de sensor y con perfil fiable en una red cargada, y se compara el retardo entre el sello de tiempo del mensaje y el instante de recepción. El resultado, la versión fiable entrega todos los barridos y algunos con retardo acumulado, convierte una discusión de opiniones en una medida. Mientras llega ese momento, el argumento que funciona en el aula es el de la analogía con el bloque 3: nadie retransmite una lectura de un termopar, se toma la siguiente, y nadie duda de que la temperatura sea importante. El segundo error, más específico y muy caro en el proyecto, es creer que la QoS se configura una vez en el sistema; se desmonta señalando que cada publicador y cada suscriptor la declara por separado, y que por tanto la compatibilidad es una propiedad de cada pareja y hay que verificarla pareja a pareja."));
children.push(h3("Si la clase no habla"));
children.push(p("Con votación a mano alzada el silencio es casi imposible, y si aparece es porque la clase no entiende las opciones, no porque no quiera pronunciarse. La maniobra de rescate es traducir las políticas a lenguaje llano antes de votar, escribiendo en la pizarra las cuatro decisiones en forma de preguntas: si se pierde, ¿lo reintento o paso al siguiente? Si alguien llega tarde, ¿le doy el último o que espere? ¿Cuántos guardo en la cola? ¿Cuánto tiempo tolero sin recibir? Con esas cuatro preguntas cualquiera vota. La segunda maniobra, si el grupo sigue mudo, es dar un cuarto canal más fácil como calentamiento, la temperatura de la batería, que se publica cada diez segundos, porque los casos fáciles desbloquean a quien tiene miedo de equivocarse en el difícil. Y una tercera para grupos muy pasivos: el profesor declara en voz alta una configuración deliberadamente absurda, el mapa en best effort con cola de uno, y pide que digan qué va a fallar; refutar es siempre más barato que proponer."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, dicha en una frase y escrita: la QoS es un contrato entre dos extremos que se deduce de la semántica del canal, no de la importancia del dato, y las dos preguntas que lo resuelven son qué cuesta perder un mensaje y quién necesita el último si llega tarde. El corolario operativo, que conviene dictar porque se cobra en el taller: cuando un topic exista y no llegue nada, la primera sospecha es la incompatibilidad de QoS y el primer comando es ros2 topic info con detalle. Lo que no conviene decir es que en la práctica se dejan los valores por defecto y ya funciona: es verdad a medias, los perfiles predefinidos están bien elegidos, y es exactamente la frase que garantiza tres horas perdidas el día que se mezcle un driver de fabricante con un nodo de Nav2. Tampoco conviene entrar en la comparación de proveedores de DDS ni en la configuración de descubrimiento, aunque alguien lo pregunte: se nombra que la capa rmw permite intercambiarlos sin tocar el código de usuario (docs.ros.org, About different ROS 2 DDS/RMW vendors), se anota la pregunta y se sigue, porque el cierre de la sesión tiene que dejar dicho el deber previo al taller."));

children.push(h2("La pregunta sembrada de S34 (103–108 min): quién publicará map a odom"));
children.push(h3("Objetivo"));
children.push(p("El guion la formula como pregunta de conexión para dejar sembrada, y esa etiqueta describe exactamente su función: no es una discusión que deba resolverse hoy, es una incomodidad que debe quedar instalada hasta S36. El apartado 34.3 ya da la respuesta, la convención de REP 105 encadena map a odom y odom a base_link, la odometría publica la segunda arista y el sistema de localización la primera, precisamente para corregir la deriva, pero leerlo produce la sensación de haber entendido una convención administrativa. El objetivo de estos cinco minutos es que la clase deduzca por qué hacen falta dos aristas y no una, es decir, que descubra que ningún sistema de referencia puede ser a la vez exacto y continuo, y que esa imposibilidad es la razón de la arquitectura. Ése es el aprendizaje: no la lista de frames, sino que map es exacta y discontinua y odom es continua e inexacta, y que un controlador reactivo necesita continuidad mientras un planificador necesita exactitud. Con eso, en S36 la separación entre costmap global anclado a map y costmap local anclado a odom no habrá que explicarla."));
children.push(h3("Formato y tiempos"));
children.push(p("La parte 3 del taller ocupa de 85 a 110 minutos y esta pregunta va al final, en los cinco minutos que van del 103 al 108, con el árbol de transformadas del TurtleBot ya generado y proyectado en pantalla, sin el frames.pdf delante la discusión no tiene objeto. El reparto: en el minuto 103 se señala en la pantalla la cadena odom a base_footprint a base_link a base_scan, se pregunta quién publica cada arista y se deja que lo contesten, que es recuperación pura y cuesta un minuto. De 104 a 107 se enuncia la pregunta sembrada y se discute. De 107 a 108 se cierra sin dar la respuesta completa. Un aviso de conducción que es todo el arte de este tramo: la tentación de explicar aquí la localización de Nav2 es muy fuerte y hay que resistirla, porque quema el material de S36 y porque a los ciento ocho minutos de taller la clase no puede absorber una arquitectura nueva. Lo que se busca es dejar una pregunta abierta, no cerrarla."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, señalando la raíz del árbol en la pantalla: «Mirad quién es la raíz de vuestro árbol: odom. No hay ningún frame map. Ahora decidme dos cosas: si le pido a este robot que vaya al muelle de carga, ¿en qué frame doy esa coordenada? Y si la odometría lleva media hora acumulando error, ¿qué le pasa a mi orden?» La formulación pide un caso de uso y no una definición, que es lo que la hace productiva. Y hay una segunda pregunta que conviene reservar para el minuto 106, cuando ya haya quien proponga añadir un frame map: «¿Y por qué no arreglamos directamente odom a base_link, corrigiéndola cada vez que sabemos dónde estamos de verdad?» Ésta es la pregunta que produce el aprendizaje, porque la respuesta es la única que no es evidente."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«La orden la doy en odom, pero se irá desviando». ", bold: true },
 { text: "Es la respuesta correcta y llega en seguida porque acaban de ver la deriva con tf2_echo. Se acepta y se cuantifica, que es lo que la convierte en contenido: con la odometría del ejercicio 2 del cuaderno 82514_S34_Entorno_ROS2_TF2.ipynb acumulando tres décimas de grado por paso, el error crece de forma monótona y sin ninguna cota, y a los pocos minutos de recorrido la coordenada del muelle expresada en odom ya no señala el muelle. Conviene pedir que digan qué gráfica tenía ese error, creciente y sin techo, porque la comparación con la del otro caso es todo el argumento del tramo." },
]));
children.push(pRuns([
 { text: "«Pues hay que añadir un frame que sea el mapa». ", bold: true },
 { text: "Es la propuesta que se busca y hay que acogerla y complicarla de inmediato con la segunda pregunta: por qué no corregir directamente la arista de la odometría. La respuesta que hay que arrancar es que una corrección de localización llega a saltos, y que si esos saltos se meten en odom a base_link, todo lo que consuma esa transformada ve teletransportarse el mundo. En el ejercicio del cuaderno esto se ve con una imagen que conviene nombrar: en map el error es una sierra acotada, que vuelve a cero cada vez que se corrige, y en odom es una rampa sin cota. Ninguno de los dos comportamientos es el bueno para todo, y de ahí que REP 105 obligue a tener las dos aristas." },
]));
children.push(pRuns([
 { text: "«¿Y quién publica esa arista?». ", bold: true },
 { text: "Es la pregunta que cierra el tramo y hay que contestarla sólo a medias, deliberadamente: el sistema de localización, que es un filtro de los que estudiaron en el bloque 6 corriendo sobre el mapa que ellos mismos guardaron, y que veremos con nombre y apellidos en S36. Conviene añadir la frase que hace que la promesa se recuerde: cuando en dos clases arranquemos Nav2 y haya que fijar la pose inicial con el ratón en RViz, lo que estaremos haciendo es darle la primera estimación a ese filtro para que pueda empezar a publicar esta arista. Y ahí se corta." },
]));
children.push(pRuns([
 { text: "«Entonces la pose del robot no la publica nadie». ", bold: true },
 { text: "Es la observación más fina que puede salir y merece medio minuto porque desmonta un malentendido muy extendido: en efecto, el sistema de localización no publica la pose del robot, publica una corrección entre dos sistemas de referencia, y la pose se obtiene componiendo la cadena. La consecuencia práctica hay que decirla porque ahorra depuraciones absurdas: si alguien busca un topic con la pose y no lo encuentra, no es que falte, es que la pose es el resultado de una consulta al árbol. Y la consecuencia de diseño: quien publica una arista es responsable de una relación, no de un dato, que es la diferencia entre un sistema componible y un montón de nodos." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante en este punto del taller es tratar el árbol de transformadas como una lista de nombres que hay que respetar por convención, sin ver que cada arista tiene un dueño y una física distinta. El síntoma aparece en el proyecto en forma de dos nodos publicando la misma arista, que es el error que el apartado 34.3 anticipa: el árbol es árbol y no grafo, cada frame tiene un único padre, y dos fuentes sobre la misma arista producen los saltos erráticos que los estudiantes describen como que el robot tiembla en RViz. Se desmonta con datos del propio taller y no con una advertencia: basta arrancar un segundo publicador de odometría sobre odom a base_link en una terminal y mirar RViz durante quince segundos. El temblor es tan evidente y tan ridículo que la lección se queda. Y conviene aprovechar para dar el diagnóstico, que es lo que de verdad necesitan: view_frames muestra quién publica cada arista y a qué frecuencia, y una arista con dos emisores se detecta ahí en cinco segundos. El segundo error, más conceptual, es esperar que TF2 devuelva una transformada para cualquier instante; se desmonta con la solución del ejercicio 3 del cuaderno, que explica por qué el búfer interpola entre dos muestras y prefiere fallar antes que extrapolar, extrapolar es inventarse datos, y esos datos se van a usar para decidir dónde está un obstáculo."));
children.push(h3("Si la clase no habla"));
children.push(p("A los ciento tres minutos de un taller de dos horas la clase está cansada y con la cabeza en su propia pantalla, de modo que hay que bajar el coste de participar al mínimo. La maniobra de rescate es señalar y preguntar por nombre sobre la pantalla: quién publica esta arista, y esta, y esta. Son tres preguntas de una palabra y reactivan al grupo. La segunda maniobra es la votación binaria con el dibujo delante: quién dice que la corrección de localización debe modificar la arista de la odometría y quién dice que hace falta una arista nueva; con el recuento escrito se pide una razón a cada bando. La tercera, la más eficaz cuando el grupo está agotado, es hacerlo con el cuerpo: el profesor camina en línea recta por el aula contando pasos en voz alta y anunciando su posición estimada, y a mitad del recorrido alguien de la clase le dice dónde está de verdad; el salto que el profesor tiene que dar para reconciliar las dos cosas es literalmente la arista map a odom, y verlo hecho con los pies lo entiende todo el mundo."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, y conviene dejarla escrita en tres líneas en la pizarra, es la tabla de REP 105 con su física: odom a base_link es continua y con deriva, la publica la odometría; map a odom es exacta y con saltos, la publica la localización; base_link a base_scan es fija y calibrada, la publica la descripción del robot. Y el corolario, que es el que se cobra dos clases más tarde: ningún frame es a la vez exacto y continuo, y por eso hacen falta dos. El cierre correcto de este tramo es una promesa y no una respuesta: la arista que falta la publicará en S36 el filtro de partículas del bloque 6, y esa frase basta. Lo que no conviene hacer es explicar aquí la configuración de la localización de Nav2: se queda sin efecto porque falta el contexto y se pierde el efecto de S36. Tampoco conviene decir que estas convenciones son cosa de ROS y que en otro middleware serían otras; es cierto y es irrelevante, y además desactiva la única cosa que hace valiosa una convención, que es que todo el mundo la respete."));

children.push(h2("La puesta en común de errores frecuentes del taller de S34 (110–117 min): la parte más valiosa de la sesión"));
children.push(h3("Objetivo"));
children.push(p("El guion dedica el tramo final a recoger evidencias del taller, y ahí es donde hay que insertar la puesta en común de errores, que es la actividad de mayor rendimiento por minuto de todo el bloque. La razón es sencilla: en un taller de ROS 2 cada pareja tropieza tres o cuatro veces, resuelve sus tropiezos en privado y se lleva a casa la impresión de que a los demás les ha ido mejor. Poner los tropiezos en común hace tres cosas que la teoría no puede hacer. Primero, convierte una anécdota individual en un patrón de sistema: quince parejas con el mismo error significa que el error no es de la pareja, es del modelo mental que la clase tiene del entorno. Segundo, construye un repertorio de diagnóstico, qué síntoma corresponde a qué causa y qué comando lo distingue, que es exactamente la competencia que se evalúa en el proyecto y que ningún apunte transmite. Y tercero, y no es menor, desactiva el sentimiento de incompetencia particular, que en un máster con estudiantes de formación no informática es un problema real y silencioso. La diferencia con la teoría es total: los apuntes ya dicen que hay que hacer source del overlay y que el árbol no admite dos padres, y lo dicen desde S33; la puesta en común es lo que convierte esas frases en reflejos."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 110 a 120 minutos incluye la recogida de evidencias y el anuncio de S35, de modo que la puesta en común tiene siete minutos, del 110 al 117. El reparto que funciona, y es un formato que conviene mantener idéntico todo el curso porque su valor está en la repetición: de 110 a 112, dos minutos de recogida rápida, pidiendo a cada pareja un solo error y en una sola frase, con el profesor escribiendo en la pizarra tres columnas, síntoma, causa, comando que lo distingue, y sin comentar ninguno todavía. De 112 a 116, cuatro minutos para completar la tabla con la clase: para cada síntoma recogido se pregunta a otra pareja qué comando lo diagnostica. De 116 a 117, el cierre. Dos avisos que deciden si esto funciona. El primero es exigir el síntoma antes que la causa: si se pregunta qué error habéis tenido, la respuesta es una explicación ya interpretada y casi siempre equivocada; si se pregunta qué visteis en pantalla, la respuesta es un dato. El segundo es que el profesor no debe resolver: se limita a escribir y a redirigir la pregunta a otra pareja, porque siete minutos de profesor explicando errores no sirven de nada y siete minutos de estudiantes explicándose entre ellos son la mejor clase de la semana."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con las tres columnas ya dibujadas: «Antes de recoger nada quiero un dato de cada pareja. No me contéis qué creíais que pasaba: decidme qué visteis en la pantalla, la primera vez que algo no funcionó, y con qué comando descubristeis por qué. Empezamos por aquí y damos la vuelta al aula.» La formulación tiene tres decisiones deliberadas. Pedir lo que se vio y no lo que se cree separa el síntoma del diagnóstico, que es la distinción que se quiere enseñar. Pedir la primera vez evita que cada pareja cuente su historia entera. Y anunciar que se da la vuelta al aula garantiza que hablen todos y no los cuatro de siempre, con el efecto añadido de que quien sabe que le va a tocar prepara la respuesta."));
children.push(h3("Errores que van a salir y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«ros2 run no encontraba el paquete». ", bold: true },
 { text: "Es el error más repetido, con diferencia, y su causa es siempre la misma familia: la terminal no tiene el overlay en su entorno, o lo tiene de un install obsoleto. Aquí lo importante no es dar la solución, que ya está en el apartado 33.3, sino escribir en la columna del comando lo que distingue una causa de la otra: ros2 pkg prefix con el nombre del paquete dice si el entorno lo ve y desde dónde, y eso separa en dos segundos el olvido del source de la construcción fallida. Conviene pedir a mano alzada cuántas parejas lo han tenido; el bosque de manos es el argumento entero, porque convierte un descuido personal en una propiedad del modelo underlay/overlay que todos tienen que interiorizar." },
]));
children.push(pRuns([
 { text: "«El nodo arrancaba pero no llegaba nada al otro lado». ", bold: true },
 { text: "El segundo más frecuente, y el más instructivo porque tiene tres causas posibles con el mismo síntoma: nombre de topic distinto, muy a menudo por un remapeo o por una barra inicial olvidada, tipo de mensaje distinto, o políticas de QoS incompatibles, que es el fallo silencioso que se anunció en S32. La columna del comando es la que hay que llenar con cuidado, y en este orden: ros2 topic list con tipos para descartar el nombre y el tipo, y ros2 topic info con detalle para ver publicadores, suscriptores y perfiles. Es la ocasión de cobrar la discusión de QoS de la primera sesión del bloque, y hay que decirlo en voz alta: esto es lo que os avisé el miércoles y ha pasado exactamente así." },
]));
children.push(pRuns([
 { text: "«Nos faltaba un paquete que no venía instalado». ", bold: true },
 { text: "Sale cada año y siempre es el mismo: el teleoperador de teclado no viene en el metapaquete de escritorio y hay que instalarlo aparte, tal como recoge la solución del ejercicio 1 del cuaderno 82514_S34_Entorno_ROS2_TF2.ipynb. Conviene tratarlo sin dramatismo y extraer la regla, que es de método y no de ROS: la comprobación previa útil no es contar paquetes, una instalación de escritorio ronda los trescientos o cuatrocientos, sino verificar la lista concreta de los que hace falta, que es lo que hace la celda de diagnóstico del cuaderno. Y de ahí la consigna para el proyecto: la lista de dependencias se declara en package.xml y se verifica con la máquina en la que se va a demostrar, no con la del que programa." },
]));
children.push(pRuns([
 { text: "«El robot temblaba en RViz» o «TF daba error de extrapolación». ", bold: true },
 { text: "Es el error más avanzado de los que van a salir y el que más conviene celebrar, porque lo tiene la pareja que ha llegado más lejos. El temblor es doble publicación sobre la misma arista y se diagnostica con view_frames, que enseña emisores y frecuencias. El error de extrapolación es una consulta a un instante que el búfer no cubre, y hay que aprovecharlo para dejar dicho por qué TF2 prefiere fallar a extrapolar, que es la lección honesta de la sesión: extrapolar es inventarse una posición y esa posición se va a usar para decidir si hay un obstáculo delante. Si aparece este error, es el que conviene poner al final de la tabla y dejar como imagen de cierre." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error de razonamiento que hay que atacar no es ninguno de los de la tabla: es el método de depuración por conjetura y reintento, que consiste en cambiar cosas hasta que funciona sin haber identificado la causa. Es el hábito más caro que traen y el más difícil de corregir, porque a veces funciona. Se reconoce por una frase que dirán textualmente en la puesta en común: no sabemos qué pasaba, hemos reconstruido y ha funcionado. Cuando aparezca, y aparecerá, hay que detenerse quince segundos y hacer la única pregunta que lo desmonta: si mañana vuelve a pasar, ¿sabéis qué mirar? La respuesta es no, y eso es lo que hay que hacer visible, sin reproche, porque es la definición operativa de no haberlo arreglado. Y el argumento no puede ser de autoridad: tiene que apoyarse en la tabla que la propia clase acaba de construir, donde hay tres síntomas idénticos con tres causas distintas y un comando que las separa. La conclusión hay que dictarla porque es transferible a todo el curso: en un sistema distribuido, la conjetura tiene un espacio de búsqueda enorme y la introspección lo reduce a uno, y el coste de aprenderse cuatro comandos es infinitamente menor que el de reconstruir a ciegas. El segundo error de razonamiento, más benigno, es suponer que el problema está en el propio código cuando está en el entorno; se desmonta con la observación estadística de la propia pizarra, donde la mayoría de los síntomas recogidos no eran de código."));
children.push(h3("Si la clase no habla"));
children.push(p("Aquí el silencio tiene una causa concreta y hay que nombrarla para desactivarla: nadie quiere ser el que confiese que perdió veinte minutos por no hacer source de un fichero. La maniobra de rescate es que el profesor empiece confesando el suyo, y conviene tener uno de verdad y contarlo con detalle, el año pasado, media hora buscando por qué no llegaba nada a un nodo que estaba escuchando el topic con la barra delante. Una confesión del profesor abre la puerta a todas las demás y cuesta cuarenta segundos. La segunda maniobra es despersonalizar por escrito: en lugar de preguntar en voz alta, se pide que cada pareja escriba su error en un papelito sin nombre, se recogen y el profesor los lee en voz alta y los agrupa en la pizarra. Es más lento pero funciona con cualquier grupo y produce además una tabla más honesta. La tercera, para cuando no hay tiempo ni para eso, es la votación de la lista: el profesor enuncia los cinco errores clásicos y pide manos en cada uno; el recuento se escribe y ya hay conversación, porque nadie se siente señalado cuando levantan la mano otros dieciocho."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar no es la lista de errores, que se olvida, sino la estructura: en un sistema distribuido, síntoma y causa no se corresponden uno a uno, y la única forma de pasar de uno a otra es la introspección. Conviene decirlo con la frase del apartado 32.2, que aquí cae sola: un ingeniero que domina estas herramientas puede diagnosticar un robot ajeno sin leer una línea de su código. El corolario es la consigna del proyecto: la tabla de la pizarra se fotografía, se sube al campus con las evidencias del taller y se amplía cada vez que aparezca un síntoma nuevo, porque es el documento más útil que van a tener en diciembre. Lo que no conviene hacer es rematar diciendo que estos errores son normales y no hay que preocuparse: la mitad es verdad, son normales, y la otra mitad desactiva la lección, porque lo que hay que aprender es que son diagnosticables. Tampoco conviene señalar a la pareja que más problemas ha tenido, ni siquiera con simpatía, porque el precio de esa broma es que en el siguiente taller nadie declara nada."));

children.push(h2("La tabla comparativa de planificadores en S35 (45–55 min) y su reutilización en la apertura de S36"));
children.push(h3("Objetivo"));
children.push(p("El guion pide un ejercicio en parejas de siete minutos y rellenar entre todos una tabla comparativa con cinco planificadores y cinco preguntas. El apartado 35.1 ya ha dado el vocabulario de propiedades, completo, completo en resolución, probabilísticamente completo, óptimo o satisfactorio, multiconsulta o consulta única, complejidad (Lynch y Park, 2017, pp. 355-356), de modo que la discusión no está para introducirlo, sino para que ese vocabulario se convierta en criterio de elección. Lo que debe quedar aprendido son dos cosas. La primera es que las propiedades no son etiquetas académicas: cada una responde a una pregunta que un ingeniero se hace de verdad, y hay una traducción directa entre ambas que conviene explicitar, completitud es qué me garantizas, optimalidad es cuánto camino de más recorro, multiconsulta es dónde gasto el cómputo, dimensión es si mi robot cabe. La segunda, y es la que sólo se aprende discutiendo, es que la elección casi nunca se decide por la propiedad más prestigiosa sino por la restricción del proyecto: el mapa cambia, la meta cambia, el robot tiene seis grados de libertad o el ordenador tiene un presupuesto cerrado. La misma tabla se reutiliza cinco días después en el arranque de S36 con la pregunta del almacén con carretillas, y esa continuidad hay que anunciarla, porque una tabla que se usa dos veces se estudia y una que se usa una vez se copia."));
children.push(h3("Formato y tiempos"));
children.push(p("El guion asigna de 45 a 55 minutos a campos potenciales y al ejercicio de síntesis, con el cierre de 55 a 60. El reparto que funciona: de 45 a 48, la exposición de los campos potenciales con la figura de los mínimos locales (Lynch y Park, 2017, pp. 386-388), que es el quinto planificador de la tabla y hay que tenerlo antes de rellenarla. En el minuto 48 se dibuja la tabla vacía, cinco filas, cinco columnas, y se reparten las filas por zonas del aula, una por pareja o grupo de parejas. De 48 a 51, tres minutos en parejas para rellenar su fila y sólo su fila. De 51 a 55, cuatro minutos de barrido: cada grupo dicta su fila y el resto puede impugnarla. Dos decisiones de formato que son la diferencia entre una tabla viva y un dictado. La primera es repartir por filas y no pedir la tabla completa a todos: con siete minutos, una pareja no puede razonar veinticinco celdas, y el reparto convierte a cada grupo en responsable de algo. La segunda es habilitar explícitamente la impugnación, quien no esté de acuerdo con una celda lo dice y hay que resolverlo, porque el desacuerdo entre grupos es donde está el contenido y sin permiso para discrepar nadie discrepa."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con la tabla vacía dibujada: «Cada grupo tiene un planificador y cinco preguntas: ¿completo?, ¿óptimo?, ¿dónde está el coste, en planificar o en consultar?, ¿sirve para seis grados de libertad?, ¿sirve con un mapa que cambia? Rellenad sólo vuestra fila, y para cada celda quiero la palabra exacta del vocabulario, no un sí o un no.» Exigir la palabra exacta, completo en resolución, probabilísticamente completo, es lo que impide que la tabla se convierta en una fila de aspas, y además obliga a volver al apartado 35.1. Y para el barrido conviene una segunda pregunta, que es la que produce la conversación: «¿Alguien discute alguna celda de esta fila?»"));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«A* es completo y óptimo». ", bold: true },
 { text: "Aparece siempre así, sin matiz, y el matiz es todo: es completo en resolución y óptimo sobre la rejilla, y sólo devuelve el camino de menor coste si la heurística es admisible, es decir, si no sobreestima (Corke, 2023, p. 175). Hay que exigir las dos precisiones y sostenerlas con el resultado del taller, porque el cuaderno 82514_S35_Planificacion.ipynb lo tiene medido: Dijkstra expande prácticamente todo el espacio libre, A* con heurística euclídea encuentra el mismo camino de 12,66 metros explorando una fracción de los nodos, y A* con la heurística multiplicada por dos expande diez veces menos pero devuelve un camino claramente peor. La conclusión que hay que dejar escrita es la del cuaderno: la heurística no cambia la respuesta, cambia el trabajo, siempre que sea admisible. Y conviene añadir el matiz profesional, porque es el que usarán: el A* ponderado existe y se usa a sabiendas, cuando hay que replanificar muchas veces por segundo y un camino un veinte por ciento peor calculado diez veces más rápido es el buen negocio." },
]));
children.push(pRuns([
 { text: "«PRM es probabilísticamente completo» y nadie sabe qué significa en la práctica. ", bold: true },
 { text: "Es la celda donde el vocabulario se vuelve abstracto y hay que aterrizarlo con los números del taller, que son inmejorables para esto: con treinta muestras, el roadmap encuentra camino en cuatro de ocho intentos, y con ciento veinte muestras en ocho de ocho. Ésa es la definición operativa de probabilísticamente completo, y verla en una tabla de éxitos y fracasos es lo que la hace comprensible. La segunda celda que hay que trabajar en esta fila es la de optimalidad, con la misma munición: 15,7 metros con treinta muestras frente a 12,7 con quinientas, contra los 12,66 de A*. No es óptimo, y se acerca al óptimo pagando muestras. El modo de fallo hay que nombrarlo porque es el que verán en MoveIt 2: los pasajes estrechos, poco probables de muestrear, son su talón de Aquiles, y la figura del libro que contrasta cincuenta vértices mal conectados con trescientos bien conectados es la imagen que hay que proyectar (Corke, 2023, p. 187)." },
]));
children.push(pRuns([
 { text: "«RRT es peor que A*, entonces para qué se usa». ", bold: true },
 { text: "Es la impugnación más frecuente en el barrido y hay que darle la razón antes de contestarla, porque en el plano tiene razón: en el mapa del taller el RRT devuelve caminos de entre 15,1 y 24,5 metros según la semilla, es decir, hasta el doble del óptimo, y esa dispersión entre semillas conviene decirla con esas palabras, el mismo algoritmo, el mismo mapa, respuestas muy distintas. La respuesta a para qué se usa es la columna que casi nadie ha rellenado bien: los métodos de rejilla son impracticables más allá de unos pocos grados de libertad (Lynch y Park, 2017, p. 378), y un brazo de seis ejes no cabe en ninguna rejilla. Con eso la tabla revela su estructura: la columna de la dimensión no es una celda más, es la que decide, y es la razón de que en S37 los planificadores de MoveIt 2 sean todos de muestreo. Conviene además dar la contrapartida honesta que el propio cuaderno señala: el RRT acepta restricciones de movimiento en su planificador local, y por esa puerta entra la cinemática del vehículo, con primitivas de Dubins para el coche no holonómico (Corke, 2023, pp. 196-198)." },
]));
children.push(pRuns([
 { text: "«Los campos potenciales no valen para nada, se quedan atrapados». ", bold: true },
 { text: "Es la conclusión precipitada de la fila más fácil de despachar, y hay que reconducirla porque el planificador reactivo es la mitad de la arquitectura que van a usar mañana. Sí, el robot puede quedar atrapado en un mínimo local aunque exista camino factible, y la figura del libro lo muestra con un mínimo global, un mínimo local y cuatro puntos de silla generados por tres obstáculos (Lynch y Park, 2017, pp. 386-388). Pero la columna del mapa cambiante es la suya: como el gradiente se evalúa en tiempo real, puede manejar obstáculos que se mueven o aparecen inesperadamente (Lynch y Park, 2017, p. 386), y ningún planificador global hace eso a la frecuencia necesaria. La síntesis que hay que arrancar de la clase es la arquitectura: potenciales o cualquier controlador reactivo por debajo, planificador global por encima, que es literalmente la división planner/controller de Nav2 que se ve mañana." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es buscar en la tabla el mejor planificador, es decir, leer las columnas como puntuaciones y sumarlas. Es el mismo vicio que en el bloque 6 amenazaba a la tabla de decisión de percepción y se corrige con la misma disciplina: obligar a nombrar la restricción que manda y la propiedad que se sacrifica. Pero en este bloque hay además un error más específico y más caro, que consiste en creer que la elección del algoritmo es la decisión importante, cuando la decisión importante suele estar antes. La demostración está en el ejercicio 1 del cuaderno 82514_S35_Planificacion.ipynb y merece proyectarse en el minuto 54 aunque cueste un minuto del cierre: con un robot de quince o veintiocho centímetros de radio, el camino cruza por la puerta estrecha y mide unos 13,2 metros; con cuarenta centímetros, la puerta estrecha se cierra, queda sin ninguna celda libre para el centro del robot, y el planificador se ve obligado a dar la vuelta por la puerta ancha, con un camino de unos 14,5 metros y una ruta completamente distinta. Ningún cambio de planificador arregla eso, y ningún planificador es culpable de eso. La lección de ingeniería que hay que dictar es que el radio del robot no es un parámetro del software sino una decisión de diseño mecánico con consecuencias topológicas, y que doce centímetros de más en el chasis pueden eliminar una conexión entre naves de un almacén ya construido. Es también, dicho de paso, la mejor razón para hacer esta comprobación antes de comprar el vehículo."));
children.push(h3("Si la clase no habla"));
children.push(p("Con las filas repartidas la clase habla, porque cada grupo tiene que dictar la suya. El silencio aparece en el barrido, cuando se pide impugnar: nadie quiere contradecir a otro grupo en público. La maniobra de rescate es que el profesor impugne primero, y en concreto que impugne una celda que está bien, para que el grupo tenga que defenderla; defender lo propio es mucho más fácil que atacar lo ajeno y el efecto sobre el resto del aula es inmediato. La segunda maniobra es la votación sobre la celda dudosa, quién cree que esto es óptimo y quién no, con recuento escrito; si el reparto sale dividido, ya no hay que pedir nada. La tercera, para grupos que se han quedado en blanco al rellenar, es cambiar la pregunta abstracta por un caso: en lugar de si sirve con un mapa que cambia, se pregunta qué pasa si un operario deja un palé en medio del pasillo cuando el robot lleva media ruta hecha; con ese caso las cinco filas se rellenan solas, y de paso se prepara la replanificación de D* con su cifra del doce por ciento de vértices reexpandidos (Corke, 2023, p. 184)."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar es que las cinco propiedades son cinco preguntas de proyecto, y que la elección se decide por la restricción más dura y no por la propiedad más prestigiosa: si la meta es estable, la transformada de distancia se amortiza; si el mapa cambia, hay que poder replanificar; si el espacio tiene seis dimensiones, hay que muestrear; y si hay obstáculos imprevistos, hace falta una capa reactiva por debajo. Conviene rematar con la frase del cuaderno, que es la que ordena la sesión: planificar empieza por preparar el mapa, no por elegir el algoritmo. Y con el anuncio que da continuidad a la tabla: mañana la primera pregunta de la clase es exactamente cuál elegiríais para un almacén con carretillas en movimiento, así que la tabla no se borra, se fotografía. Lo que no conviene hacer es declarar un ganador ni sugerir que A* es el planificador que se usa siempre: es el más usado en robótica móvil por buenas razones y no vale para el brazo, y anticipar eso ahora es lo que hace que S37 tenga sentido. Tampoco conviene abrir la discusión de RRT* y los planificadores asintóticamente óptimos más allá de la frase del guion, aunque alguien la pida: se remite a las referencias originales que el propio libro señala (Corke, 2023, p. 202) y al seminario."));

children.push(h2("La pregunta del costmap local en S36 (28–32 min): por qué no puede vivir en map"));
children.push(h3("Objetivo"));
children.push(p("El guion lo formula como una pregunta directa a la clase dentro del tramo de costmaps, y su valor es desproporcionado respecto a lo que ocupa: es el momento en que la convención de frames de S34 se revela como una decisión de arquitectura de control y no como una regla administrativa. El apartado 36.2 lo dice ya, la estimación de localización corrige a saltos y un controlador reactivo que viviera en map vería teletransportarse los obstáculos con cada corrección, mientras que en odom el movimiento es continuo aunque derive, pero dicho por el profesor es una frase más y deducido por la clase es una idea que no se olvida. El objetivo, por tanto, es que la clase reconstruya la consecuencia a partir de lo que ya sabe: que map es exacta y discontinua, que odom es continua e inexacta, y que un lazo reactivo tolera error pero no discontinuidad. Hay un objetivo secundario que se cobra en el proyecto: quien entiende esto no vuelve a mezclar frames en un nodo propio, que es el error de integración más común y el más difícil de diagnosticar, porque el sistema funciona casi siempre."));
children.push(h3("Formato y tiempos"));
children.push(p("El tramo de 20 a 35 minutos es el de costmaps por capas, y la pregunta va al final, en los cuatro minutos que van del 28 al 32, dejando el resto para cerrar la comparación global frente a local. El reparto: en el minuto 28 se dibuja en la pizarra la ventana rodante del costmap local sobre el mapa global, se recuerda en una frase quién publica cada arista, la localización publica map a odom, la odometría publica odom a base_link, y se enuncia la pregunta; diez segundos de silencio. De 29 a 31, la discusión. De 31 a 32, la síntesis y la vuelta al hilo de la sesión. Un aviso de conducción: conviene tener a mano el árbol de transformadas del taller de S34 para proyectarlo si hace falta, porque la mitad de las respuestas fallidas vienen de haber olvidado quién publica qué, y volver a la figura resuelve eso en cinco segundos sin necesidad de explicar nada."));
children.push(h3("Pregunta de apertura"));
children.push(p("Literalmente, con el dibujo hecho: «Nav2 mantiene dos costmaps. El global está anclado a map y el local a odom. La pregunta es por qué no los dos a map, que es el frame exacto: ¿qué le pasaría al controlador local si sus obstáculos estuvieran expresados en map?» Y si en veinte segundos no hay respuesta, la pista mínima y no más: «Recordad qué le pasa a la arista map a odom cada vez que la localización se corrige.» La formulación funciona porque plantea la opción aparentemente mejor, usar el frame exacto para todo, y pide encontrarle el defecto; es mucho más productiva que preguntar por qué el local está en odom, que invita a repetir la convención."));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "«Porque map salta cuando la localización corrige». ", bold: true },
 { text: "Es la respuesta correcta y suele llegar de quien estuvo atento en S34; el trabajo consiste en no aceptarla como palabra y exigir la consecuencia física. La pregunta de vuelta es qué ve el controlador cuando eso pasa, y la respuesta que hay que arrancar es que ve el obstáculo desplazarse de golpe unos centímetros o unas decenas de centímetros sin que nada se haya movido, y que un controlador reactivo responde a eso con un volantazo. Conviene ponerle número usando el propio taller: con la odometría del ejercicio del cuaderno de S34, la corrección periódica producía una sierra cuyos dientes son exactamente el salto que vería el controlador. Ahí la clase entiende que el problema no es teórico." },
]));
children.push(pRuns([
 { text: "«Pero entonces el costmap local tiene los obstáculos mal colocados». ", bold: true },
 { text: "Es la objeción inteligente y la que hace valiosa la discusión; hay que reconocerla como correcta antes de resolverla. Sí, en odom la posición absoluta de los obstáculos deriva, y no importa por dos razones que conviene separar. La primera es que el costmap local es una ventana rodante centrada en el robot y de pocos metros, de modo que lo que necesita es la posición relativa al robot, y ésa la dan los sensores directamente, sin pasar por la localización. La segunda es que la deriva en unos pocos segundos, que es la vida útil de una celda del costmap local, es despreciable. La formulación que resume las dos y conviene dictar: el controlador no necesita saber dónde está en el mundo, necesita saber qué tiene delante." },
]));
children.push(pRuns([
 { text: "«¿Y el planificador global no sufre lo mismo?». ", bold: true },
 { text: "Es la pregunta que cierra el razonamiento y hay que provocarla si no sale. El planificador global sí vive en map y sí ve los saltos, y no pasa nada por dos motivos: replanifica a baja frecuencia, de modo que un salto se absorbe en el siguiente plan, y su producto es un camino completo, no una consigna instantánea de velocidad. Conviene explicitar la simetría, porque es la idea general que se lleva: la frecuencia a la que trabaja un módulo decide qué clase de error tolera, el lazo rápido tolera sesgo y no tolera discontinuidad, el lazo lento tolera discontinuidad y no tolera sesgo. Es la misma lección que en el bloque 5 separaba el prealimentado del realimentado y en el bloque 6 separaba la odometría de la corrección por hitos." },
]));
children.push(pRuns([
 { text: "«Entonces mi nodo, ¿en qué frame trabaja?». ", bold: true },
 { text: "Es la mejor pregunta posible porque es la del proyecto, y hay que contestarla con una regla operativa y no con una teoría: lo que se usa para reaccionar, en odom o en el frame del robot; lo que se usa para saber dónde ir, en map; y nunca se mezclan dos frames en una misma resta sin pasar por el árbol. Conviene añadir el síntoma que produce incumplirla, porque es el que verán: el sistema funciona bien durante minutos y de pronto da un giro absurdo justo después de una corrección de localización, y el diagnóstico es casi imposible si no se sospecha del frame. Decirlo aquí, con nombre y apellidos, ahorra una tarde entera en diciembre." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante es creer que un frame más exacto es siempre preferible, y por tanto que trabajar en map es la buena práctica y trabajar en odom un apaño. Es un error de criterio y se desmonta con el experimento del cuaderno de S34, que es exactamente el que hace falta y conviene reproyectar en el minuto 31: la misma trayectoria con el error medido en los dos frames, la rampa monótona y sin cota en odom y la sierra acotada en map. La lectura hay que dictarla porque no es evidente: map es exacta pero discontinua y odom es continua pero inexacta, y no existe un frame que sea las dos cosas, de ahí que la convención obligue a tener ambos. Y de ahí sale además el criterio de diseño que el propio cuaderno señala y que sirve para el proyecto: la altura de los dientes de sierra es lo que decide la frecuencia con la que hay que localizar, porque si el robot deriva más de lo que el controlador tolera entre dos correcciones, hay que corregir más a menudo o mejorar la odometría. El segundo error, más silencioso, es suponer que la deriva de la odometría se puede corregir sobre la marcha sumándole la corrección de la localización dentro del propio nodo; se desmonta señalando que eso es exactamente reintroducir la discontinuidad en el frame continuo, es decir, deshacer con la mano derecha lo que la arquitectura hacía con la izquierda."));
children.push(h3("Si la clase no habla"));
children.push(p("El silencio aquí suele ser de falta de anclaje: han visto los frames hace cinco días y no los tienen frescos. La maniobra de rescate es proyectar el frames.pdf del taller y preguntar por partes, señalando: quién publica esta arista, con qué frecuencia, y qué le pasa cuando la localización corrige. Tres preguntas de una palabra devuelven el contexto y la pregunta grande se contesta después sola. La segunda maniobra es de teatro y funciona muy bien con este contenido concreto: se pide a un estudiante que camine hacia una silla mirando al suelo mientras el profesor, cada cuatro pasos, le dice que en realidad está medio metro a la izquierda de donde cree. La pregunta, si tuvieras que esquivar la silla, ¿te fías de mi corrección o de lo que ves?, produce la respuesta correcta en tres segundos y sin ninguna álgebra. La tercera, si el grupo está frío, es la votación binaria: quién pondría el costmap local en map y quién en odom, recuento en la pizarra y una razón de cada lado."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar, en una frase que conviene escribir: la elección de frame de cada módulo es una decisión de arquitectura de control, y se toma por la clase de error que ese módulo tolera, no por la exactitud del frame. El corolario que se lleva al proyecto es la regla de las tres líneas que ya se ha dictado, reaccionar en odom, decidir en map, no mezclar sin pasar por el árbol, y la consigna de diagnóstico: cuando el robot haga algo absurdo justo después de una corrección de localización, el sospechoso es el frame. Lo que no conviene hacer es presentar esto como un detalle de implementación de Nav2, porque no lo es: es la razón de ser de la convención de frames y aparece igual en cualquier stack de navegación. Tampoco conviene abrir aquí la fusión de odometría con inercial ni el filtro que la produce, aunque alguien lo pregunte: se anota, se recuerda que el estimador es el del bloque 6 y se sigue, porque el tramo de árboles de comportamiento empieza en el minuto treinta y cinco y es el que aporta la novedad de la sesión."));

children.push(h2("La composición del stack completo y la puesta en común de riesgos en S37 (80–105 min)"));
children.push(h3("Objetivo"));
children.push(p("Es la puesta en común más ambiciosa del bloque y la única cuyo producto se usa fuera de la clase: el diagrama del stack completo es el andamiaje con el que los equipos van a organizar el proyecto integrador y la defensa de S43. El guion la divide en tres movimientos, componer el diagrama entre todos, situar cada proyecto sobre él en equipos, y una puesta en común relámpago de un riesgo técnico por equipo, y los tres tienen objetivos distintos que conviene no confundir. Componer el diagrama es una tarea de síntesis: se trata de que la clase reconstruya, sin apuntes, la cadena que va de los sensores a las ruedas y de la cámara al brazo, y descubra al hacerlo que todas las piezas del semestre tienen sitio. Situar el proyecto es una tarea de proyección: obliga a cada equipo a declarar qué módulos usa, qué interfaces expone y qué parámetros va a tener que justificar. Y la puesta en común de riesgos es la más valiosa de las tres y la que suele salir mal por falta de tiempo: su objetivo es que cada equipo oiga los riesgos de los otros cuatro, porque el fallo que hunde un proyecto en diciembre casi nunca es el que ese equipo había previsto. La diferencia con la teoría es que el apartado 37.4 puede dibujar el diagrama y no puede colocar en él el proyecto de nadie."));
children.push(h3("Formato y tiempos"));
children.push(p("El guion asigna de 80 a 105 minutos, con la síntesis del bloque de 105 a 110 y el cuestionario de 110 a 120. El reparto que funciona: de 80 a 88, ocho minutos para componer el diagrama en la pizarra entre todos, con el profesor dibujando y la clase dictando. De 88 a 100, doce minutos de trabajo por equipos de proyecto sobre su propio caso, con el profesor rotando por las mesas, es tiempo real de tutoría y hay que protegerlo. De 100 a 105, cinco minutos de puesta en común de riesgos, un riesgo y una mitigación por equipo, sesenta segundos cada uno con reloj. Tres avisos de gestión. El primero: el diagrama lo dibuja el profesor y lo dicta la clase, nunca al contrario, porque si el profesor lo dicta se convierte en la última transparencia del bloque y se copia sin pensar. El segundo: los doce minutos de equipos se van en nada, así que hay que dar la consigna por escrito en la pizarra, qué bloques usa, qué interfaz expone cada módulo propio, qué plugins y parámetros hay que justificar, un riesgo, y rotar con reloj, dos minutos por equipo. El tercero: la puesta en común de riesgos tiene que empezar a las cien en punto, aunque los equipos no hayan acabado, porque es la parte que no se puede recuperar y el cuestionario no se puede mover."));
children.push(h3("Preguntas de apertura"));
children.push(p("Para el diagrama, literalmente: «Vamos a dibujar el robot completo del curso, y lo vais a dictar vosotros. Empiezo por la izquierda con una caja que dice sensores. ¿Qué va después, y qué viaja por la flecha?» Insistir en que digan lo que viaja por la flecha, y no sólo el nombre de la caja siguiente, es lo que convierte el ejercicio en síntesis: las flechas son interfaces con tipo y con QoS, y ése es el aprendizaje del bloque. Para los riesgos, en el minuto 100 y con el reloj a la vista: «Un riesgo técnico y una mitigación, en sesenta segundos, y no vale decir que os falta tiempo. Quiero un riesgo que se pueda diagnosticar: qué veríais si ocurriera.»"));
children.push(h3("Respuestas y resultados que van a salir, y qué hacer con cada uno"));
children.push(pRuns([
 { text: "El diagrama se atasca siempre en el mismo punto: entre el mapa y el planificador. ", bold: true },
 { text: "La clase dicta sin problema sensores, percepción, mapa y ruedas, y se queda muda cuando hay que decir quién convierte una meta en velocidades. Es el momento de rescatar el reparto de servidores de S36, planificador global sobre el costmap global, controlador local produciendo /cmd_vel sobre el costmap local, comportamientos de recuperación, y el orquestador por encima recibiendo la acción de navegación (docs.nav2.org, Navigation Concepts), y de pedir que digan dónde encaja la localización. Que ese trozo cueste es buena señal y hay que decirlo: es el único trozo del diagrama que no se ve desde fuera del sistema." },
]));
children.push(pRuns([
 { text: "Nadie dibuja TF2 espontáneamente. ", bold: true },
 { text: "Ocurre todos los años y es el hallazgo pedagógico del ejercicio. La clase dibuja las cajas y las flechas de datos y se olvida de la columna vertebral geométrica, porque TF2 no está en el camino de ningún dato concreto: está debajo de todos. Cuando el diagrama esté acabado hay que preguntar qué falta, dejar que no lo encuentren, y entonces dibujar TF2 como una banda que atraviesa el dibujo entero. La frase que conviene decir ahí es que casi todas las cajas del diagrama piden transformadas y casi ninguna las publica, y que por eso un árbol roto no da error en ningún nodo y estropea el sistema completo." },
]));
children.push(pRuns([
 { text: "«Nuestro riesgo es que no nos dé tiempo». ", bold: true },
 { text: "Es lo que dirá el primer equipo y hay que cortarlo con amabilidad y sin excepciones, porque si se acepta lo repiten los cuatro siguientes y los cinco minutos se pierden. La reformulación que hay que exigir es técnica y diagnosticable: qué módulo concreto es el que puede no llegar, qué síntoma tendría y qué se hace en su lugar. Conviene tener preparados los tres riesgos que el propio guion nombra, para ofrecerlos como plantilla si un equipo no encuentra el suyo: QoS incompatibles entre el driver y el stack de navegación, TF sin sincronizar en la cámara, y el planificador del brazo que no encuentra camino con la pinza cargada." },
]));
children.push(pRuns([
 { text: "«El nuestro es que el brazo no encuentre camino». ", bold: true },
 { text: "Es un riesgo bien formulado y hay que aprovecharlo para cobrar la teoría de la sesión: la mitigación no es cambiar de planificador, es revisar la escena de planificación con la geometría real de la herramienta y de la pieza (moveit.picknik.ai, Concepts: Planning Scene), porque la causa habitual es que la pinza cargada colisiona con algo que el modelo no incluía, y el planificador está haciendo su trabajo. Y hay una segunda mitigación que conviene nombrar porque es la que nadie propone: aceptar el fallo y diseñar qué hace el sistema cuando no hay camino, que es exactamente el papel de las ramas de recuperación de un árbol de comportamiento (docs.nav2.org, Detailed Behavior Tree Walkthrough). Un proyecto que sólo funciona cuando todo va bien no está terminado." },
]));
children.push(h3("El error de razonamiento más frecuente y cómo desmontarlo"));
children.push(p("El error dominante en esta puesta en común es de arquitectura y aparece en cuanto los equipos sitúan su proyecto: confundir el diagrama de módulos con un diagrama de bloques secuencial, en el que cada caja termina su trabajo y entrega el resultado a la siguiente. De esa lectura salen las dos decisiones que arruinan integraciones: implementar como topic con banderas lo que semánticamente es una acción, perdiendo cancelación y resultado, que es el error de diseño más común en los proyectos de años anteriores según el apartado 33.1, y suponer que todo el mundo trabaja a la misma frecuencia y con el mismo sello de tiempo. Se desmonta con el propio diagrama, pidiendo a la clase que anote la frecuencia junto a cada flecha: el láser a cuarenta hercios, el controlador local a diez o veinte, el planificador global cada uno o dos segundos, el árbol de comportamiento a su ritmo, y el lazo de par del bloque 5 a kilohercios. Con las frecuencias escritas, el dibujo deja de parecer una cadena de montaje y se ve lo que es, un conjunto de lazos concurrentes que comparten datos con sellos de tiempo distintos; y de ahí sale sola la razón de existir de TF2 con su búfer temporal (docs.ros.org, tutorial Introducing tf2). El segundo error, muy frecuente en la parte de equipos, es declarar que se usará un módulo sin declarar la interfaz por la que se conecta; se desmonta preguntando el nombre y el tipo del topic, porque un módulo sin interfaz declarada es un módulo que no se ha diseñado."));
children.push(h3("Si la clase no habla"));
children.push(p("En la composición del diagrama el silencio es raro pero cuando aparece es fatal, porque el profesor se queda solo delante de una pizarra vacía. La maniobra de rescate es empezar por el final y no por el principio: se dibuja la caja de los motores a la derecha y se pregunta qué llega hasta ahí y quién lo manda. Ir hacia atrás desde el actuador es mucho más fácil que ir hacia delante desde el sensor, porque cada caja tiene una única respuesta razonable. La segunda maniobra es repartir el dibujo por bloques del curso: se pide al fondo del aula la parte del bloque 6, al centro la del 7 y a la primera fila la del 4 y el 5; con la responsabilidad repartida siempre hay alguien que habla. En la puesta en común de riesgos el problema es el contrario, que hablan de más, y la única herramienta es el reloj visible y el corte a los sesenta segundos, anunciado antes de empezar y aplicado sin excepciones desde el primer equipo, porque la equidad de estos cinco minutos es el tiempo."));
children.push(h3("Cierre"));
children.push(p("La idea que debe quedar es la que el apartado 37.4 formula y que aquí se ha construido en la pizarra: cada flecha del diagrama es una interfaz de ROS 2 con su tipo y su calidad de servicio, y cada caja es un conjunto de nodos con parámetros que hay que justificar, no sólo copiar. Conviene añadir el corolario que la puesta en común de riesgos ha demostrado: los proyectos no fallan por el algoritmo, fallan por las flechas, QoS, frames, sellos de tiempo y semántica de interfaz. Y el encargo operativo: el diagrama se fotografía, cada equipo lo incorpora a su memoria con su propio recorrido marcado, y los cinco riesgos se publican en el campus para todos, porque el riesgo de un equipo es el aviso de otro. Lo que no conviene hacer es cerrar el bloque prometiendo que si el diagrama está claro el proyecto saldrá bien: no es cierto y baja la guardia justo cuando hay que subirla. Tampoco conviene rematar con una lista de recomendaciones de última hora sobre versiones y paquetes: se publica por escrito en el campus, que es donde se puede consultar, y los cinco minutos que quedan se usan para la síntesis del bloque, que es lo que el cuestionario va a preguntar."));

