# -*- coding: utf-8 -*-
"""Notas del orador, decks B1 y B2. Registro de guía docente: recordatorios de contenido y de gestión."""

B1 = [
("82514", "Presentarse y resolver la logística en un par de minutos: campus virtual, horario (miércoles y jueves 1 h, viernes 2 h) y sistema de evaluación. Encuadrar el bloque: origen de la disciplina, método de diseño y panorama profesional actual."),
("Hoja de ruta del bloque", "Recorrer las cuatro sesiones en un minuto. Adelantar dos citas importantes: el seminario de artículos se lanza en S4 y se presenta en diciembre, y el cuestionario del bloque cae al final de S4. Idea que conviene decir ya: este bloque da el vocabulario que usa el resto del curso."),
("¿Qué es la mecatrónica?", "Pregunta de arranque antes de definir nada: qué objetos de casa creen que son mecatrónicos. Anotar la lista en la pizarra y recuperarla al final de la clase con la definición en la mano. Plan: 0-10 presentación de la asignatura; 10-15 pregunta de arranque; 15-35 definición y dominios; 35-50 componentes y ejemplos; 50-60 discusión y cierre."),
("Una definición con dos palabras clave", "Insistir en las dos palabras: sinérgica (los subsistemas se conciben juntos) e integrado (las interacciones dinámicas entran desde la primera fase). Aclarar que electromecánico no implica mecatrónico: es una metodología de diseño, no una lista de piezas. Origen del término: Yaskawa, 1969; conecta con la historia de S3. Cerrar con el ABS de la tarjeta: cuatro dominios físicos en un producto; optimizados por separado dan un freno peor."),
("Componentes de un sistema mecatrónico", "Señalar que la lista de De Silva es literalmente el índice de la asignatura: mecánica y actuadores en B3 y B4, sensores en B3, control en B5, computación embebida en B7. Observación útil: la energía aparece como componente propio porque la potencia enlaza los dominios. Ejemplo anidado: el servomotor es un sistema mecatrónico completo dentro de otro mayor."),
("Dos ejemplos canónicos", "Con el disco duro, hacer la pregunta de la tarjeta: por qué el servo del brazo no puede diseñarse sin conocer la mecánica del brazo (resonancias y masa móvil limitan el ancho de banda; se retoma en B5). Con el servomotor, dar la lectura de conjunto: un robot de seis ejes son seis servomotores coordinados más un esqueleto. Cerrar recuperando la lista de objetos del arranque."),
("El proceso de diseño mecatrónico", "Enlazar con la sesión anterior: definida la disciplina, hoy toca el método. Anticipar la idea central: el diseño por dominios separados falla por razones concretas que se pueden cuantificar. Plan: 0-5 recuperación; 5-20 bucle modelado-diseño; 20-40 diseño acoplado y MDQ; 40-52 caso práctico en parejas (cinta transportadora); 52-60 cierre."),
("Modelado y diseño: un bucle iterativo", "Dibujar el bucle en la pizarra aunque esté proyectado; el gesto de cerrar el ciclo ayuda a fijarlo. Sobre la energía: v·i = ω·τ significa que la potencia eléctrica de entrada iguala la mecánica de salida en el transformador ideal. Aviso de ingeniería: los factores de seguridad excesivos y el diseño por peor caso no dan diseños óptimos. Conectar con el proyecto integrador: es el mismo bucle (modelo en B4, control en B5, percepción en B6 y B7)."),
("Por qué falla el diseño secuencial", "Recorrer los tres problemas con un ejemplo cada uno: el motor de catálogo que ya no rinde su par-velocidad con la inercia real de la transmisión; el acoplamiento perfecto imposible (siempre hay un componente subutilizado o sobrecargado); y las variables que pasan de externas a internas y dejan de poder medirse. Estos tres problemas motivan el MDQ de la siguiente diapositiva."),
("Cociente de Diseño Mecatrónico", "Leer la fórmula con calma: el numerador es lo que consigue el conjunto interconectado y el denominador lo que cada subsistema lograría aislado. Aclarar el nivel de exigencia: las fórmulas se interpretan, no se manipulan en el examen. Sobre los algoritmos genéticos de la derecha: cromosoma igual a diseño completo, función de aptitud igual a MDQ. Cerrar con el caso del transporte guiado: restricciones heredadas de decisiones tempranas."),
("Historia y definición de robot", "Sesión de narrativa: la palabra robot viene del teatro, la primera patente se firmó tras un cóctel y el primer robot industrial acabó sirviendo cerveza en televisión. Objetivo de la hora: una definición de trabajo con tres verbos. Plan: 0-5 recuperación; 5-25 historia; 25-40 definición y sensores; 40-55 telerobots y autonomía con discusión; 55-60 cierre."),
("Tres máquinas que cuentan la historia", "Dejar la diapositiva proyectada durante la narración histórica. Telar de Jacquard: el programa está en las tarjetas perforadas; influyó en Babbage y Ada Lovelace, así que robótica y computación comparten raíz. Unimate: la foto es el servicio de café en el Biltmore (1967), tras su paso por el programa de Carson. El disco duro cierra el círculo con S1: mecatrónica en miniatura."),
("De los autómatas a la fábrica", "Recorrido: Vaucanson (programa fijo en levas), Jacquard (reprogramable), Čapek pone el nombre en 1920 (roboti, servidumbre), Asimov aporta las Tres Leyes y la carga cultural. Después la ingeniería: patente de Devol en el 54, encuentro con Engelberger en un cóctel, Unimation, primer Unimate en la GM de Nueva Jersey en 1961, licencia a Kawasaki en 1968. Anécdota que funciona: el Unimate en el Tonight Show en 1966 sirvió cerveza, metió un putt y dirigió la banda."),
("¿Qué es un robot?", "Dar la definición de Corke como definición literal de examen: máquina orientada a objetivos que percibe, planifica y actúa. Citar a Engelberger (no sé definir un robot, pero lo reconozco cuando lo veo). Decir explícitamente que la tríada organiza el curso: percibir en B3 y B6, planificar en B7, actuar en B3, B4 y B5. Abajo, fijar la pareja propioceptivo (estado propio, base de la odometría) y exteroceptivo (el mundo, corrige la deriva); reaparece en B6."),
("Telerobots y el espectro de autonomía", "Presentar el espectro con sus cuatro niveles y ejemplos: teleoperación (ROV, cirugía), control alternado (piloto automático), compartido (mantener carril), autonomía supervisada (rovers, por la latencia de minutos). Discusión de 10 minutos con los tres casos de la tarjeta; el del brazo industrial incomoda a propósito: ni percibe ni planifica. Cierre: la definición es una vara de medir, no una frontera. Encargar ejemplos de robots de prensa para S4."),
("Panorama 2026 y seminario", "Última sesión del bloque: panorama actual, debate de ética y lanzamiento del seminario. Al final, cuestionario B1. Plan: 0-5 recuperación; 5-25 panorama con vídeos cortos; 25-35 ética en formato debate; 35-45 lanzamiento del seminario; 45-60 cuestionario B1 en Moodle (15 min)."),
("El panorama 2026, en imágenes", "Usar las cuatro fotos como ejercicio rápido: situar cada una en la tríada percibir-planificar-actuar y en el espectro de autonomía de S3. Ingenuity y Perseverance: autonomía supervisada a cientos de millones de kilómetros. Robotaxi: robot de servicio en la calle. Multirrotor: percepción y control embarcados de serie. Atlas 2013: comparar aquel prototipo del DRC con los humanoides industriales actuales."),
("El momento «Physical AI»", "Contexto: desde 2023 los modelos fundacionales llegan al control físico. Nombrar los tres VLA de la diapositiva sin entrar en técnica (eso es B8). Dar el mensaje doble de la tarjeta: los fundamentos no caducan (el VLA emite consignas que ejecutan los lazos de B5 sobre la cinemática de B4) y el perfil que se contrata combina fundamentos, Python, ROS 2 y criterio. Apoyar con dos o tres vídeos cortos."),
("Ética: preguntas sin respuesta fácil", "Formato debate, 10 minutos: proyectar cada afirmación, votación a mano alzada, pedir argumentos de ambos lados. Datos útiles para moderar: los conductores humanos causan más de un millón de muertes al año y aun así el coche autónomo genera más incomodidad; la automatización sostiene industrias enteras. Cerrar con la posición de Corke: estas cuestiones no deben decidirlas solo los roboticistas, pero tampoco pueden ignorarlas."),
("Seminario de artículos científicos", "Recorrer las cuatro tarjetas sin prisa: es evaluación continua. Subrayar tres cosas: la validación del artículo termina el 30 de septiembre y los buenos artículos vuelan; la conexión con el curso es obligatoria; la IA generativa está permitida con declaración y defensa oral individual. Últimos 15 minutos: cuestionario B1 en Moodle (10 preguntas del banco del bloque)."),
]

B2 = [
("82514", "Encuadrar el bloque en una frase: el mapa de la robótica actual. Tres sesiones: taxonomía y configuraciones, robots móviles, y cobots con seguridad y normativa. La parte de normativa es la de más salida profesional."),
("Hoja de ruta del bloque", "Avisar de las dos fechas: el jueves 24 es festivo (La Mercè) y al final de S7 quedan cerrados los equipos del proyecto integrador. El taller de análisis de riesgos de S7 es entregable puntuable. Sugerir que vayan hablando entre ellos para formar equipos."),
("Taxonomía y configuraciones", "Objetivo de la sesión: que cualquier robot que vean lo sepan situar en las dos taxonomías, reconocer su configuración y su grado de autonomía. La foto del Da Vinci sirve de gancho: fijo o móvil, fabricación o servicio, autónomo o teleoperado. Plan: 0-10 repaso del cuestionario B1; 10-35 taxonomías clasificando fotos; 35-65 configuraciones; 65-75 descanso; 75-95 autonomía; 95-115 actividad de fichas; 115-120 preformar equipos."),
("La taxonomía, en imágenes", "Dinámica: proyectar cada foto y pedir a la clase que la sitúe en ambas taxonomías antes de dar la respuesta. ASIMO permite decir que las categorías no son excluyentes (móvil y de servicio). Spot: robot de campo e inspección. Delta: fijo, de fabricación, con cadenas cinemáticas cerradas. El AGV portacontenedores prepara la pregunta de S6 sobre la diferencia con un AMR."),
("Dos taxonomías complementarias", "Presentar las dos taxonomías (movilidad y función) y detenerse en la tarjeta derecha: el industrial clásico vive enjaulado con piezas ordenadas; el cobot sustituye el vallado por sensórica y control; campo y servicio añaden entorno desordenado y personas cerca. Útil la escalera de intimidad física: el de reparto circula entre personas, el coche las lleva dentro, el quirúrgico opera dentro. Explica por qué percepción y seguridad dominan la robótica moderna."),
("Configuraciones de manipuladores", "Dibujar en la pizarra cada configuración con su espacio de trabajo al lado. Señalar que los robots del laboratorio son articulados de 6 ejes y que todo B4 se apoya en esa configuración. Del recuadro inferior, fijar tres conceptos que reaparecen: seis grados de libertad para pose arbitraria, espacio alcanzable frente a diestro, y repetibilidad (la cifra de catálogo) frente a exactitud (peor, y la que importa al programar fuera de línea)."),
("El espectro de autonomía", "Repasar los cuatro niveles con sus ejemplos y avisar de que un mismo sistema cambia de nivel según el modo de operación. Actividad en equipos (20 min): seis fichas por equipo (industrial, cobot, AMR, humanoide, quirúrgico, dron) y para cada una taxonomía, configuración si aplica y posición en el espectro. Puesta en común con votación; las discrepancias son el material interesante. Al cierre, preformar los equipos del proyecto."),
("Robots móviles", "Pregunta técnica que ordena la sesión: por qué la mayoría de los AMR llevan tracción diferencial y no dirección tipo coche. La distinción AGV-AMR separa dos generaciones de la logística. Plan: 0-5 recuperación (dibujar SCARA y articulado); 5-25 ruedas; 25-40 AGV frente a AMR, patas y aire; 40-55 ejercicio de selección de plataforma; 55-60 cierre."),
("Locomoción con ruedas", "Recorrer las cuatro arquitecturas con su criterio de uso. En Ackermann, introducir la palabra no holonómico con la intuición de aparcar en paralelo: no puede desplazarse lateralmente y eso condiciona la planificación en B7. En orugas, avisar de que el giro por deslizamiento castiga la odometría; el dato reaparece en localización (B6)."),
("Robots de servicio, entre personas", "Tres niveles de convivencia: casa (Roomba, con su sensórica de contacto y precipicio), calle (robotaxi, percepción de 360 grados con vidas dentro) y mesa compartida (el brazo del ajedrez, contacto físico potencial). Dejar planteada la pregunta que abre S7: qué hace falta, técnica y normativamente, para que compartir mesa con un brazo industrial sea seguro."),
("AGV frente a AMR", "La distinción clave está en las dos tarjetas: el AGV sigue infraestructura física y el entorno se adapta al vehículo; el AMR navega con un mapa propio (SLAM en B6, Nav2 en B7) y se adapta él al entorno. Frase que conviene dictar: mismo hardware, distinto software. Del recuadro inferior: patas para escaleras y escombros a cambio de equilibrio y consumo, multirrotor frente a ala fija, ROV frente a AUV. Ejercicio de 15 minutos: elegir plataforma para almacén, hospital y viña, justificando locomoción, sensórica y autonomía."),
("Cobots, seguridad y normativa", "Presentar la sesión como la de más salida profesional del bloque. Objetivos: las dos partes de la ISO 10218:2025, los cuatro métodos colaborativos y un primer análisis de riesgos en equipo (entregable puntuable). La foto del UR16e permite anticipar la idea de fuerza limitada con par medido en cada eje. Plan: 0-10 recuperación; 10-40 marco normativo; 40-70 métodos con vídeos; 70-80 descanso; 80-105 taller de riesgos; 105-120 cuestionario B2 en Moodle (15 min) y cierre de equipos."),
("El marco normativo", "La idea principal es la división de responsabilidades: Parte 1 para el fabricante (el robot como componente), Parte 2 para el integrador (la célula completa), y el integrador es el responsable legal de la evaluación de riesgos. Dos aclaraciones: comprar un robot seguro no hace segura la célula, y cobot no es una categoría legal sino una aplicación colaborativa. La revisión de 2025 absorbió la ISO/TS 15066, que sigue siendo la referencia de los límites biomecánicos. Ejemplo provocador: un cobot con una cuchilla no es una aplicación colaborativa segura."),
("Los cuatro métodos de operación colaborativa", "Proyectar un vídeo corto de cada método y pedir que identifiquen cuál es cuál antes de nombrarlos. Al recorrer las tarjetas, subrayar que los métodos se combinan (separación en la aproximación, fuerza limitada en la entrega) y que todos tienen coste de productividad: elegir método es una decisión de diseño, con el espíritu del MDQ de B1."),
("Taller: análisis de riesgos", "Recorrer los cinco pasos de la ISO 12100 insistiendo en dos puntos: los modos degradados (limpieza, mantenimiento, recuperación de fallos) concentran los accidentes reales, y la jerarquía de reducción es estricta: eliminar por diseño, luego proteger, informar solo al final. Encargo de 30 minutos en equipos: tabla de seis filas sobre la célula del ABB con carga y descarga manual. Corrección en común. Recordar que las normas del laboratorio son de obligado cumplimiento. Después: cuestionario B2 en Moodle y cierre de equipos."),
]
